package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * AcmMenuDTO generated by hbm2java
 */
public class AcmMenuDTO implements java.io.Serializable {

	private String coAcmMenu;
	private ProcesoDTO procesoDTO;
	private AcmMenuDTO acmMenuDTO;
	private String nombre;
	private String descripcion;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Byte orden;
	private Boolean boActivo;
	private Set<AcmMenuDTO> acmMenuDTOs = new HashSet<AcmMenuDTO>(0);
	private Set<AcmPerfilMenuDTO> acmPerfilMenuDTOs = new HashSet<AcmPerfilMenuDTO>(
			0);
	private String rowid;

	public AcmMenuDTO() {
	}

	public AcmMenuDTO(String coAcmMenu, String nombre) {
		this.coAcmMenu = coAcmMenu;
		this.nombre = nombre;
	}

	public AcmMenuDTO(String coAcmMenu, ProcesoDTO procesoDTO,
			AcmMenuDTO acmMenuDTO, String nombre, String descripcion,
			Date fhActualizacion, String coUsuarioActualizacion, Byte orden,
			Boolean boActivo, Set<AcmMenuDTO> acmMenuDTOs,
			Set<AcmPerfilMenuDTO> acmPerfilMenuDTOs) {
		this.coAcmMenu = coAcmMenu;
		this.procesoDTO = procesoDTO;
		this.acmMenuDTO = acmMenuDTO;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.orden = orden;
		this.boActivo = boActivo;
		this.acmMenuDTOs = acmMenuDTOs;
		this.acmPerfilMenuDTOs = acmPerfilMenuDTOs;
	}
	
	public String getCodigoDescripcion() {
		return this.coAcmMenu + " - " + this.nombre;
	}
	
	public String getCoAcmMenu() {
		return this.coAcmMenu;
	}

	public void setCoAcmMenu(String coAcmMenu) {
		this.coAcmMenu = coAcmMenu;
	}

	public ProcesoDTO getProcesoDTO() {
		return this.procesoDTO;
	}

	public void setProcesoDTO(ProcesoDTO procesoDTO) {
		this.procesoDTO = procesoDTO;
	}

	public AcmMenuDTO getAcmMenuDTO() {
		return this.acmMenuDTO;
	}

	public void setAcmMenuDTO(AcmMenuDTO acmMenuDTO) {
		this.acmMenuDTO = acmMenuDTO;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Byte getOrden() {
		return this.orden;
	}

	public void setOrden(Byte orden) {
		this.orden = orden;
	}

	public Boolean getBoActivo() {
		return this.boActivo;
	}

	public void setBoActivo(Boolean boActivo) {
		this.boActivo = boActivo;
	}

	public Set<AcmMenuDTO> getAcmMenuDTOs() {
		return this.acmMenuDTOs;
	}

	public void setAcmMenuDTOs(Set<AcmMenuDTO> acmMenuDTOs) {
		this.acmMenuDTOs = acmMenuDTOs;
	}

	public Set<AcmPerfilMenuDTO> getAcmPerfilMenuDTOs() {
		return this.acmPerfilMenuDTOs;
	}

	public void setAcmPerfilMenuDTOs(Set<AcmPerfilMenuDTO> acmPerfilMenuDTOs) {
		this.acmPerfilMenuDTOs = acmPerfilMenuDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}
	
	public boolean equals(Object other) {
		boolean result = false;
		
		try{
			result=coAcmMenu.equals(((AcmMenuDTO)other).getCoAcmMenu());
		}catch(Exception e){
			e.printStackTrace();
		}
		
		return result;
	}

}
