package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * AcmPerfilMenuDTO generated by hbm2java
 */
public class AcmPerfilMenuDTO implements java.io.Serializable {

	private AcmPerfilMenuDTOId id;
	private AcmMenuDTO acmMenuDTO;
	private AcmPerfilDTO acmPerfilDTO;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public AcmPerfilMenuDTO() {
	}

	public AcmPerfilMenuDTO(AcmPerfilMenuDTOId id, AcmMenuDTO acmMenuDTO,
			AcmPerfilDTO acmPerfilDTO) {
		this.id = id;
		this.acmMenuDTO = acmMenuDTO;
		this.acmPerfilDTO = acmPerfilDTO;
	}

	public AcmPerfilMenuDTO(AcmPerfilMenuDTOId id, AcmMenuDTO acmMenuDTO,
			AcmPerfilDTO acmPerfilDTO, Date fhActualizacion,
			String coUsuarioActualizacion) {
		this.id = id;
		this.acmMenuDTO = acmMenuDTO;
		this.acmPerfilDTO = acmPerfilDTO;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public AcmPerfilMenuDTOId getId() {
		return this.id;
	}

	public void setId(AcmPerfilMenuDTOId id) {
		this.id = id;
	}

	public AcmMenuDTO getAcmMenuDTO() {
		return this.acmMenuDTO;
	}

	public void setAcmMenuDTO(AcmMenuDTO acmMenuDTO) {
		this.acmMenuDTO = acmMenuDTO;
	}

	public AcmPerfilDTO getAcmPerfilDTO() {
		return this.acmPerfilDTO;
	}

	public void setAcmPerfilDTO(AcmPerfilDTO acmPerfilDTO) {
		this.acmPerfilDTO = acmPerfilDTO;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
