package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * AcmPerfilMenuDTOId generated by hbm2java
 */
public class AcmPerfilMenuDTOId implements java.io.Serializable {

	private String coAcmPerfil;
	private String coAcmMenu;

	public AcmPerfilMenuDTOId() {
	}

	public AcmPerfilMenuDTOId(String coAcmPerfil, String coAcmMenu) {
		this.coAcmPerfil = coAcmPerfil;
		this.coAcmMenu = coAcmMenu;
	}

	public String getCoAcmPerfil() {
		return this.coAcmPerfil;
	}

	public void setCoAcmPerfil(String coAcmPerfil) {
		this.coAcmPerfil = coAcmPerfil;
	}

	public String getCoAcmMenu() {
		return this.coAcmMenu;
	}

	public void setCoAcmMenu(String coAcmMenu) {
		this.coAcmMenu = coAcmMenu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcmPerfilMenuDTOId))
			return false;
		AcmPerfilMenuDTOId castOther = (AcmPerfilMenuDTOId) other;

		return ((this.getCoAcmPerfil() == castOther.getCoAcmPerfil()) || (this
				.getCoAcmPerfil() != null
				&& castOther.getCoAcmPerfil() != null && this.getCoAcmPerfil()
				.equals(castOther.getCoAcmPerfil())))
				&& ((this.getCoAcmMenu() == castOther.getCoAcmMenu()) || (this
						.getCoAcmMenu() != null
						&& castOther.getCoAcmMenu() != null && this
						.getCoAcmMenu().equals(castOther.getCoAcmMenu())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCoAcmPerfil() == null ? 0 : this.getCoAcmPerfil()
						.hashCode());
		result = 37 * result
				+ (getCoAcmMenu() == null ? 0 : this.getCoAcmMenu().hashCode());
		return result;
	}

}
