package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * AcmProcesoBotonDTO generated by hbm2java
 */
public class AcmProcesoBotonDTO implements java.io.Serializable {

	private AcmProcesoBotonDTOId id;
	private ProcesoDTO procesoDTO;
	private AcmBotonDTO acmBotonDTO;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Boolean boInclusion;
	private String rowid;

	public AcmProcesoBotonDTO() {
	}

	public AcmProcesoBotonDTO(AcmProcesoBotonDTOId id, ProcesoDTO procesoDTO,
			AcmBotonDTO acmBotonDTO) {
		this.id = id;
		this.procesoDTO = procesoDTO;
		this.acmBotonDTO = acmBotonDTO;
	}

	public AcmProcesoBotonDTO(AcmProcesoBotonDTOId id, ProcesoDTO procesoDTO,
			AcmBotonDTO acmBotonDTO, Date fhActualizacion,
			String coUsuarioActualizacion, Boolean boInclusion) {
		this.id = id;
		this.procesoDTO = procesoDTO;
		this.acmBotonDTO = acmBotonDTO;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.boInclusion = boInclusion;
	}

	public AcmProcesoBotonDTOId getId() {
		return this.id;
	}

	public void setId(AcmProcesoBotonDTOId id) {
		this.id = id;
	}

	public ProcesoDTO getProcesoDTO() {
		return this.procesoDTO;
	}

	public void setProcesoDTO(ProcesoDTO procesoDTO) {
		this.procesoDTO = procesoDTO;
	}

	public AcmBotonDTO getAcmBotonDTO() {
		return this.acmBotonDTO;
	}

	public void setAcmBotonDTO(AcmBotonDTO acmBotonDTO) {
		this.acmBotonDTO = acmBotonDTO;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Boolean getBoInclusion() {
		return this.boInclusion;
	}

	public void setBoInclusion(Boolean boInclusion) {
		this.boInclusion = boInclusion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
