package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * AcmUsuarioLogDetalleDTO generated by hbm2java
 */
public class AcmUsuarioLogDetalleDTO implements java.io.Serializable {

	private Long coAcmUsuarioLogDetalle;
	private Long coAcmUsuarioLog;
	private Long coProcesoAccion;
	private String coModelo;
	private String coVersion;
	private String coDocumento;
	private Long coCliente;
	private String refObjetoTributario;
	private String refObjetoTributario2;
	private String refObjetoTributario3;
	private Long coDomicilioTributario;
	private String coProvincia;
	private String coMunicipio;
	private String coConcepto;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public AcmUsuarioLogDetalleDTO() {
	}

	public AcmUsuarioLogDetalleDTO(Long coAcmUsuarioLog, Long coProcesoAccion,
			String coModelo, String coVersion, String coDocumento,
			Long coCliente, String refObjetoTributario,
			String refObjetoTributario2, String refObjetoTributario3,
			Long coDomicilioTributario, String coProvincia, String coMunicipio,
			String coConcepto, Date fhActualizacion,
			String coUsuarioActualizacion) {
		this.coAcmUsuarioLog = coAcmUsuarioLog;
		this.coProcesoAccion = coProcesoAccion;
		this.coModelo = coModelo;
		this.coVersion = coVersion;
		this.coDocumento = coDocumento;
		this.coCliente = coCliente;
		this.refObjetoTributario = refObjetoTributario;
		this.refObjetoTributario2 = refObjetoTributario2;
		this.refObjetoTributario3 = refObjetoTributario3;
		this.coDomicilioTributario = coDomicilioTributario;
		this.coProvincia = coProvincia;
		this.coMunicipio = coMunicipio;
		this.coConcepto = coConcepto;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Long getCoAcmUsuarioLogDetalle() {
		return this.coAcmUsuarioLogDetalle;
	}

	public void setCoAcmUsuarioLogDetalle(Long coAcmUsuarioLogDetalle) {
		this.coAcmUsuarioLogDetalle = coAcmUsuarioLogDetalle;
	}

	public Long getCoAcmUsuarioLog() {
		return this.coAcmUsuarioLog;
	}

	public void setCoAcmUsuarioLog(Long coAcmUsuarioLog) {
		this.coAcmUsuarioLog = coAcmUsuarioLog;
	}

	public Long getCoProcesoAccion() {
		return this.coProcesoAccion;
	}

	public void setCoProcesoAccion(Long coProcesoAccion) {
		this.coProcesoAccion = coProcesoAccion;
	}

	public String getCoModelo() {
		return this.coModelo;
	}

	public void setCoModelo(String coModelo) {
		this.coModelo = coModelo;
	}

	public String getCoVersion() {
		return this.coVersion;
	}

	public void setCoVersion(String coVersion) {
		this.coVersion = coVersion;
	}

	public String getCoDocumento() {
		return this.coDocumento;
	}

	public void setCoDocumento(String coDocumento) {
		this.coDocumento = coDocumento;
	}

	public Long getCoCliente() {
		return this.coCliente;
	}

	public void setCoCliente(Long coCliente) {
		this.coCliente = coCliente;
	}

	public String getRefObjetoTributario() {
		return this.refObjetoTributario;
	}

	public void setRefObjetoTributario(String refObjetoTributario) {
		this.refObjetoTributario = refObjetoTributario;
	}

	public String getRefObjetoTributario2() {
		return this.refObjetoTributario2;
	}

	public void setRefObjetoTributario2(String refObjetoTributario2) {
		this.refObjetoTributario2 = refObjetoTributario2;
	}

	public String getRefObjetoTributario3() {
		return this.refObjetoTributario3;
	}

	public void setRefObjetoTributario3(String refObjetoTributario3) {
		this.refObjetoTributario3 = refObjetoTributario3;
	}

	public Long getCoDomicilioTributario() {
		return this.coDomicilioTributario;
	}

	public void setCoDomicilioTributario(Long coDomicilioTributario) {
		this.coDomicilioTributario = coDomicilioTributario;
	}

	public String getCoProvincia() {
		return this.coProvincia;
	}

	public void setCoProvincia(String coProvincia) {
		this.coProvincia = coProvincia;
	}

	public String getCoMunicipio() {
		return this.coMunicipio;
	}

	public void setCoMunicipio(String coMunicipio) {
		this.coMunicipio = coMunicipio;
	}

	public String getCoConcepto() {
		return this.coConcepto;
	}

	public void setCoConcepto(String coConcepto) {
		this.coConcepto = coConcepto;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
