package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * AcmUsuarioBotonDTOId generated by hbm2java
 */
public class AcmUsuarioBotonDTOId implements java.io.Serializable {

	private String coAcmUsuario;
	private long coAcmBoton;

	public AcmUsuarioBotonDTOId() {
	}

	public AcmUsuarioBotonDTOId(String coAcmUsuario, long coAcmBoton) {
		this.coAcmUsuario = coAcmUsuario;
		this.coAcmBoton = coAcmBoton;
	}

	public String getCoAcmUsuario() {
		return this.coAcmUsuario;
	}

	public void setCoAcmUsuario(String coAcmUsuario) {
		this.coAcmUsuario = coAcmUsuario;
	}

	public long getCoAcmBoton() {
		return this.coAcmBoton;
	}

	public void setCoAcmBoton(long coAcmBoton) {
		this.coAcmBoton = coAcmBoton;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcmUsuarioBotonDTOId))
			return false;
		AcmUsuarioBotonDTOId castOther = (AcmUsuarioBotonDTOId) other;

		return ((this.getCoAcmUsuario() == castOther.getCoAcmUsuario()) || (this
				.getCoAcmUsuario() != null
				&& castOther.getCoAcmUsuario() != null && this
				.getCoAcmUsuario().equals(castOther.getCoAcmUsuario())))
				&& (this.getCoAcmBoton() == castOther.getCoAcmBoton());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCoAcmUsuario() == null ? 0 : this.getCoAcmUsuario()
						.hashCode());
		result = 37 * result + (int) this.getCoAcmBoton();
		return result;
	}

}
