package es.dipucadiz.etir.comun.dto;

// Generated 04-nov-2010 8:41:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * BancoDTO generated by hbm2java
 */
public class BancoDTO implements java.io.Serializable {

	private String coBanco;
	private String nombre;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String procedencia;
	private Set<BancoSucursalDTO> bancoSucursalDTOs = new HashSet<BancoSucursalDTO>(
			0);
	private String rowid;
	private Boolean boEditranF1;
	private String estadoF1;
	private Boolean boEditranF3;
	private String estadoF3;

	public BancoDTO() {
	}

	public BancoDTO(String coBanco) {
		this.coBanco = coBanco;
	}

	public BancoDTO(String coBanco, String nombre, Date fhActualizacion, String coUsuarioActualizacion,
			Set<BancoSucursalDTO> bancoSucursalDTOs) {
		this.coBanco = coBanco;
		this.nombre = nombre;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.bancoSucursalDTOs = bancoSucursalDTOs;
	}

	public String getCodigoDescripcion() {
		return this.getCoBanco() + " - " + this.nombre;
	}
	
	public String getCodigoCompleto() {
		return this.getCoBanco();
	}

	// GETTERS and SETTERS
	
	public String getCoBanco() {
		return this.coBanco;
	}

	public void setCoBanco(String coBanco) {
		this.coBanco = coBanco;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getProcedencia() {
		return this.procedencia;
	}

	public void setProcedencia(String procedencia) {
		this.procedencia = procedencia;
	}
	
	public Set<BancoSucursalDTO> getBancoSucursalDTOs() {
		return this.bancoSucursalDTOs;
	}

	public void setBancoSucursalDTOs(Set<BancoSucursalDTO> bancoSucursalDTOs) {
		this.bancoSucursalDTOs = bancoSucursalDTOs;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public Boolean getBoEditranF1() {
		return boEditranF1;
	}

	public void setBoEditranF1(Boolean boEditranF1) {
		this.boEditranF1 = boEditranF1;
	}

	public String getEstadoF1() {
		return estadoF1;
	}

	public void setEstadoF1(String estadoF1) {
		this.estadoF1 = estadoF1;
	}

	public Boolean getBoEditranF3() {
		return boEditranF3;
	}

	public void setBoEditranF3(Boolean boEditranF3) {
		this.boEditranF3 = boEditranF3;
	}

	public String getEstadoF3() {
		return estadoF3;
	}

	public void setEstadoF3(String estadoF3) {
		this.estadoF3 = estadoF3;
	}

}
