package es.dipucadiz.etir.comun.dto;

// Generated 04-nov-2010 8:41:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.MunicipioConceptoModeloUtil;
import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * BancoSucursalDTO generated by hbm2java
 */
public class BancoSucursalDTO implements java.io.Serializable {

	private BancoSucursalDTOId id;
	private BancoDTO bancoDTO;
	private MunicipioDTO municipioDTO;
	private String dcSucursal;
	private String estado;
	private String tipoOficina;
	private String direccion;
	private String agenciaUrbana;
	private String cp;
	private String telefono;
	private String fax;
	private String telex;
	private String swift;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private String procedencia;
	private String nombreMunicipio;
	private Set<CuentaDTO> cuentaDTOs = new HashSet<CuentaDTO>(0);
	private String rowid;

	public BancoSucursalDTO() {
	}

	public BancoSucursalDTO(BancoSucursalDTOId id, BancoDTO bancoDTO) {
		this.id = id;
		this.bancoDTO = bancoDTO;
	}

	public BancoSucursalDTO(BancoSucursalDTOId id, BancoDTO bancoDTO,
			MunicipioDTO municipioDTO, String dcSucursal, String estado,
			String tipoOficina, String direccion, String agenciaUrbana,
			String cp, String telefono, String fax, String telex, String swift,
			String coUsuarioActualizacion, Date fhActualizacion, String nombreMunicipio,
			Set<CuentaDTO> cuentaDTOs) {
		this.id = id;
		this.bancoDTO = bancoDTO;
		this.municipioDTO = municipioDTO;
		this.dcSucursal = dcSucursal;
		this.estado = estado;
		this.tipoOficina = tipoOficina;
		this.direccion = direccion;
		this.agenciaUrbana = agenciaUrbana;
		this.cp = cp;
		this.telefono = telefono;
		this.fax = fax;
		this.telex = telex;
		this.swift = swift;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.nombreMunicipio = nombreMunicipio;
		this.cuentaDTOs = cuentaDTOs;
	}

	public String getMunicipio() {
		String municipio;
		if(this.getMunicipioDTO()!=null){
			municipio = MunicipioConceptoModeloUtil.getMunicipioDescripcion(this.getMunicipioDTO().getId().getCoProvincia(), this.getMunicipioDTO().getId().getCoMunicipio());
			return this.getMunicipioDTO().getId().getCoProvincia() + this.getMunicipioDTO().getId().getCoMunicipio() + " - " + municipio;
		} else{
			municipio = getNombreMunicipio();
			return this.getCp().substring(0, 2) + "000 - " + municipio;
		}
	}

	// GETTERS and SETTERS
	
	public BancoSucursalDTOId getId() {
		return this.id;
	}

	public void setId(BancoSucursalDTOId id) {
		this.id = id;
	}

	public BancoDTO getBancoDTO() {
		return this.bancoDTO;
	}

	public void setBancoDTO(BancoDTO bancoDTO) {
		this.bancoDTO = bancoDTO;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public String getDcSucursal() {
		return this.dcSucursal;
	}

	public void setDcSucursal(String dcSucursal) {
		this.dcSucursal = dcSucursal;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getTipoOficina() {
		return this.tipoOficina;
	}

	public void setTipoOficina(String tipoOficina) {
		this.tipoOficina = tipoOficina;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getAgenciaUrbana() {
		return this.agenciaUrbana;
	}

	public void setAgenciaUrbana(String agenciaUrbana) {
		this.agenciaUrbana = agenciaUrbana;
	}

	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getTelex() {
		return this.telex;
	}

	public void setTelex(String telex) {
		this.telex = telex;
	}

	public String getSwift() {
		return this.swift;
	}

	public void setSwift(String swift) {
		this.swift = swift;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}
	
	public String getProcedencia() {
		return this.procedencia;
	}

	public void setProcedencia(String procedencia) {
		this.procedencia = procedencia;
	}

	public String getNombreMunicipio() {
		return nombreMunicipio;
	}

	public void setNombreMunicipio(String nombreMunicipio) {
		this.nombreMunicipio = nombreMunicipio;
	}

	public Set<CuentaDTO> getCuentaDTOs() {
		return this.cuentaDTOs;
	}

	public void setCuentaDTOs(Set<CuentaDTO> cuentaDTOs) {
		this.cuentaDTOs = cuentaDTOs;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
