package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.exception.GadirServiceException;
import es.dipucadiz.etir.comun.utilidades.TablaGt;
import es.dipucadiz.etir.comun.utilidades.TablaGtConstants;
import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * BonificacionTipoDTO generated by hbm2java
 */
public class BonificacionTipoDTO implements java.io.Serializable {

	private Long coBonificacionTipo;
	private MunicipioDTO municipioDTO;
	private ConceptoDTO conceptoDTO;
	private Short maxAnos;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private String tipoBonificacion;
	private String detalle;
	private String tipoCrecimiento;
	private BigDecimal porcCrecimiento;
	private boolean boRogada;
	
	private Set<BonificacionTipoPorcDTO> bonificacionTipoPorcDTOs = new HashSet<BonificacionTipoPorcDTO>(
			0);

	public BonificacionTipoDTO() {
	}

	public BonificacionTipoDTO(boolean boRogada) {
		this.boRogada = boRogada;
	}

	public BonificacionTipoDTO(MunicipioDTO municipioDTO,
			ConceptoDTO conceptoDTO, Short maxAnos,
			String coUsuarioActualizacion, Date fhActualizacion,
			String tipoBonificacion, String detalle, String tipoCrecimiento,
			BigDecimal porcCrecimiento, boolean boRogada,
			Set<BonificacionTipoPorcDTO> bonificacionTipoPorcDTOs) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.maxAnos = maxAnos;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.tipoBonificacion = tipoBonificacion;
		this.detalle = detalle;
		this.tipoCrecimiento = tipoCrecimiento;
		this.porcCrecimiento = porcCrecimiento;
		this.boRogada = boRogada;
		this.bonificacionTipoPorcDTOs = bonificacionTipoPorcDTOs;
	}

	public Long getCoBonificacionTipo() {
		return this.coBonificacionTipo;
	}

	public void setCoBonificacionTipo(Long coBonificacionTipo) {
		this.coBonificacionTipo = coBonificacionTipo;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public ConceptoDTO getConceptoDTO() {
		return this.conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public Short getMaxAnos() {
		return this.maxAnos;
	}

	public void setMaxAnos(Short maxAnos) {
		this.maxAnos = maxAnos;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getTipoBonificacion() {
		return this.tipoBonificacion;
	}

	public void setTipoBonificacion(String tipoBonificacion) {
		this.tipoBonificacion = tipoBonificacion;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public String getTipoCrecimiento() {
		if(this.tipoCrecimiento != null)
			return this.tipoCrecimiento;
		else
			return "";
	}

	public void setTipoCrecimiento(String tipoCrecimiento) {
		this.tipoCrecimiento = tipoCrecimiento;
	}

	public BigDecimal getPorcCrecimiento() {
		return this.porcCrecimiento;
	}

	public void setPorcCrecimiento(BigDecimal porcCrecimiento) {
		this.porcCrecimiento = porcCrecimiento;
	}

	public boolean isBoRogada() {
		return this.boRogada;
	}

	public void setBoRogada(boolean boRogada) {
		this.boRogada = boRogada;
	}

	public Set<BonificacionTipoPorcDTO> getBonificacionTipoPorcDTOs() {
		return this.bonificacionTipoPorcDTOs;
	}

	public void setBonificacionTipoPorcDTOs(
			Set<BonificacionTipoPorcDTO> bonificacionTipoPorcDTOs) {
		this.bonificacionTipoPorcDTOs = bonificacionTipoPorcDTOs;
	}

	public String getsRogada() {
		return boRogada ? "Sí" : "No";
	}
	public String getsTipoCrecimiento() {
		if((tipoCrecimiento+"").equals("C"))
			return "Creciente";
		else if((tipoCrecimiento+"").equals("D"))
			return "Decreciente";
		else
			return "";
	}
	public String getsTipoBonificacion() {
		return TablaGt.getValor(TablaGtConstants.TABLA_TIPOS_BONIFICACION, tipoBonificacion, TablaGt.COLUMNA_DESCRIPCION);
	}
	public String getsTipoBonificacionBE() {
		String BE = TablaGt.getValor(TablaGtConstants.TABLA_TIPOS_BONIFICACION, tipoBonificacion, TablaGt.COLUMNA_EXENCION_BONIFICACION);
		if((BE + "").equals("B"))
			return "Bonificación";
		if((BE + "").equals("E"))
			return "Exención";
		else
			return "";
	}
	public String getsTipoBonificacionLO() {
		String LO = TablaGt.getValor(TablaGtConstants.TABLA_TIPOS_BONIFICACION, tipoBonificacion, TablaGt.COLUMNA_POR_LEY_POR_ORDENANZA);
		if((LO + "").equals("L"))
			return "Ley";
		if((LO + "").equals("O"))
			return "Ordenanza";
		else 
			return "";
	}
	public String getsporcCrecimiento() {
		try {
			return  Utilidades.getFormato2Number(porcCrecimiento+"",3.2);
		} catch (GadirServiceException e) {
			return "";
		}
	}
	public String getformattedmaxAnos() { 
		return (maxAnos == 0 ? "" : maxAnos+"");
	} 
	public String getformattedporcCrecimiento() {
		if(tipoCrecimiento == null || tipoCrecimiento.length()==0) 
			return "";
		else {
			try {
				return  Utilidades.getFormato2Number(porcCrecimiento+"",3.2);
			} catch (GadirServiceException e) {
				return "";
			}
		}
	}

		
}
