package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.TablaGt;
import es.dipucadiz.etir.comun.utilidades.TablaGtConstants;
import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * BonificacionDTO generated by hbm2java
 */
public class BonificacionDTO implements java.io.Serializable {

	private Long coBonificacion;
	private MunicipioDTO municipioDTO;
	private ConceptoDTO conceptoDTO;
	private ClienteDTO clienteDTO;
	private String refObjTributario;
	private short anoInicio;
	private short anoFin;
	private String descripcion;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private boolean boActiva;
	private Byte orden;
	private String dondeAplica;
	private String tipoBonificacion;
	private String detalle;
	private String rowid;

	public BonificacionDTO() {
	}

	public BonificacionDTO(MunicipioDTO municipioDTO, ConceptoDTO conceptoDTO,
			ClienteDTO clienteDTO, String refObjTributario, short anoInicio,
			short anoFin, boolean boActiva) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.clienteDTO = clienteDTO;
		this.refObjTributario = refObjTributario;
		this.anoInicio = anoInicio;
		this.anoFin = anoFin;
		this.boActiva = boActiva;
	}

	public BonificacionDTO(MunicipioDTO municipioDTO, ConceptoDTO conceptoDTO,
			ClienteDTO clienteDTO,
			String refObjTributario, short anoInicio, short anoFin,
			String descripcion, Date fhActualizacion,
			String coUsuarioActualizacion, boolean boActiva, Byte orden,
			String dondeAplica, String tipoBonificacion, String detalle) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.clienteDTO = clienteDTO;
		this.refObjTributario = refObjTributario;
		this.anoInicio = anoInicio;
		this.anoFin = anoFin;
		this.descripcion = descripcion;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.boActiva = boActiva;
		this.orden = orden;
		this.dondeAplica = dondeAplica;
		this.tipoBonificacion = tipoBonificacion;
		this.detalle = detalle;
	}

	public Long getCoBonificacion() {
		return this.coBonificacion;
	}

	public void setCoBonificacion(Long coBonificacion) {
		this.coBonificacion = coBonificacion;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public ConceptoDTO getConceptoDTO() {
		return this.conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public ClienteDTO getClienteDTO() {
		return this.clienteDTO;
	}

	public void setClienteDTO(ClienteDTO clienteDTO) {
		this.clienteDTO = clienteDTO;
	}

	public String getRefObjTributario() {
		return this.refObjTributario;
	}

	public void setRefObjTributario(String refObjTributario) {
		this.refObjTributario = refObjTributario;
	}

	public short getAnoInicio() {
		return this.anoInicio;
	}

	public void setAnoInicio(short anoInicio) {
		this.anoInicio = anoInicio;
	}

	public short getAnoFin() {
		return this.anoFin;
	}

	public void setAnoFin(short anoFin) {
		this.anoFin = anoFin;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public boolean isBoActiva() {
		return this.boActiva;
	}

	public void setBoActiva(boolean boActiva) {
		this.boActiva = boActiva;
	}

	public Byte getOrden() {
		return this.orden;
	}

	public void setOrden(Byte orden) {
		this.orden = orden;
	}

	public String getDondeAplica() {
		return this.dondeAplica;
	}

	public void setDondeAplica(String dondeAplica) {
		this.dondeAplica = dondeAplica;
	}

	public String getTipoBonificacion() {
		return this.tipoBonificacion;
	}

	public void setTipoBonificacion(String tipoBonificacion) {
		this.tipoBonificacion = tipoBonificacion;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	////////////////////////
	
	public String getsboActiva() {
		return boActiva ? "Sí" : "No";
	}

	public String getsbosActiva() {
		return boActiva ? "Activa" : "Inactiva";
	}	
	public String getsTipoBonificacionBE() {
		String BE = TablaGt.getValor(TablaGtConstants.TABLA_TIPOS_BONIFICACION, tipoBonificacion, TablaGt.COLUMNA_EXENCION_BONIFICACION);
		if((BE + "").equals("B"))
			return "Bonificación";
		else if((BE + "").equals("E"))
			return "Exención";
		else
			return "";
	}
	public String getsTipoBonificacionLO() {
		String LO = TablaGt.getValor(TablaGtConstants.TABLA_TIPOS_BONIFICACION, tipoBonificacion, TablaGt.COLUMNA_POR_LEY_POR_ORDENANZA);
		if((LO + "").equals("L"))
			return "Ley";
		else if((LO + "").equals("O"))
			return "Por ordenanza";
		else
			return "";
	}
	public String getstipoBonificacion() {
		return TablaGt.getValor(TablaGtConstants.TABLA_TIPOS_BONIFICACION, tipoBonificacion, TablaGt.COLUMNA_DESCRIPCION);
	}
	public String getsdondeAplica() {
		String DA = dondeAplica + "";
		if(DA.equals("I"))
			return "Importe total";
		else if(DA.equals("R"))
			return "Resultado anterior";
		else
			return "";
	}
	
}
