package es.dipucadiz.etir.comun.dto;

// Generated 21-dic-2010 10:46:48 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

import es.dipucadiz.etir.comun.exception.GadirServiceException;
import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * BonificacionTipoPorcDTO generated by hbm2java
 */
public class BonificacionTipoPorcDTO implements java.io.Serializable {

	private Long coBonificacionTipoPorc;
	private BonificacionTipoDTO bonificacionTipoDTO;
	private short ejercicio;
	private BigDecimal porcentaje;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;

	public BonificacionTipoPorcDTO() {
	}

	public BonificacionTipoPorcDTO(BonificacionTipoDTO bonificacionTipoDTO,
			short ejercicio) {
		this.bonificacionTipoDTO = bonificacionTipoDTO;
		this.ejercicio = ejercicio;
	}

	public BonificacionTipoPorcDTO(BonificacionTipoDTO bonificacionTipoDTO,
			short ejercicio, BigDecimal porcentaje,
			String coUsuarioActualizacion, Date fhActualizacion) {
		this.bonificacionTipoDTO = bonificacionTipoDTO;
		this.ejercicio = ejercicio;
		this.porcentaje = porcentaje;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
	}

	public Long getCoBonificacionTipoPorc() {
		return this.coBonificacionTipoPorc;
	}

	public void setCoBonificacionTipoPorc(Long coBonificacionTipoPorc) {
		this.coBonificacionTipoPorc = coBonificacionTipoPorc;
	}

	public BonificacionTipoDTO getBonificacionTipoDTO() {
		return this.bonificacionTipoDTO;
	}

	public void setBonificacionTipoDTO(BonificacionTipoDTO bonificacionTipoDTO) {
		this.bonificacionTipoDTO = bonificacionTipoDTO;
	}

	public short getEjercicio() {
		return this.ejercicio;
	}

	public void setEjercicio(short ejercicio) {
		this.ejercicio = ejercicio;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getsporcentaje() {
		try {
			return  Utilidades.getFormato2Number(porcentaje+"",3.2);
		} catch (GadirServiceException e) {
			return "";
		}		
	}
}
