package es.dipucadiz.etir.comun.dto;

// Generated 04-nov-2010 8:41:23 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ClienteCuentaDTO generated by hbm2java
 */
public class C63BancoDTO implements java.io.Serializable {
	private static final long serialVersionUID = -3735817503176452997L;
	
	private C63BancoDTOId id;
	private ExpedienteDTO expedienteDTO;
	private Date fxEnvioF3;
	private Date fxCalculoF3;
	private Date fxProcesoF4;
	private Date fxRetencion;
	private Long contribEnviados;
	private Long documentosEnviados;
	private BigDecimal imEnviado;
	
	private BigDecimal imRetenido;	
	private Long contribRetenidos;
	
	private BigDecimal imEmbargoTotal;
	private Long contribEmbargoTotal;
	
	private BigDecimal imEmbargoParcial;
	private Long contribEmbargoParcial;
	
	private BigDecimal imEmbargoNegativo;
	private Long contribEmbargoNegativo;
	
	private BigDecimal toImporteLevantado;
	private Long toContribLevantado;
	 
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	
	 private String rowid;

	public C63BancoDTO() {
		super();
	}

	 
	public C63BancoDTO(C63BancoDTOId id, ExpedienteDTO expedienteDTO,
			Date fxEnvioF3, Date fxCalculoF3, Date fxProcesoF4,
			Date fxRetencion, Long contribEnviados, Long documentosEnviados,
			BigDecimal imEnviado, BigDecimal imRetenido, Long contribRetenidos,
			BigDecimal imEmbargoTotal, Long contribEmbargoTotal,
			BigDecimal imEmbargoParcial, Long contribEmbargoParcial,
			BigDecimal imEmbargoNegativo, Long contribEmbargoNegativo,
			String coUsuarioActualizacion, Date fhActualizacion, String rowid) {
		super();
		this.id = id;
		this.expedienteDTO = expedienteDTO;
		this.fxEnvioF3 = fxEnvioF3;
		this.fxCalculoF3 = fxCalculoF3;
		this.fxProcesoF4 = fxProcesoF4;
		this.fxRetencion = fxRetencion;
		this.contribEnviados = contribEnviados;
		this.documentosEnviados = documentosEnviados;
		this.imEnviado = imEnviado;
		this.imRetenido = imRetenido;
		this.contribRetenidos = contribRetenidos;
		this.imEmbargoTotal = imEmbargoTotal;
		this.contribEmbargoTotal = contribEmbargoTotal;
		this.imEmbargoParcial = imEmbargoParcial;
		this.contribEmbargoParcial = contribEmbargoParcial;
		this.imEmbargoNegativo = imEmbargoNegativo;
		this.contribEmbargoNegativo = contribEmbargoNegativo;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.rowid = rowid;
	}


	public Date getFxRetencion() {
		return fxRetencion;
	}


	public void setFxRetencion(Date fxRetencion) {
		this.fxRetencion = fxRetencion;
	}


	public C63BancoDTOId getId() {
		return id;
	}

	public void setId(C63BancoDTOId id) {
		this.id = id;
	}

	public ExpedienteDTO getExpedienteDTO() {
		return expedienteDTO;
	}

	public void setExpedienteDTO(ExpedienteDTO expedienteDTO) {
		this.expedienteDTO = expedienteDTO;
	}

	public Date getFxEnvioF3() {
		return fxEnvioF3;
	}

	public void setFxEnvioF3(Date fxEnvioF3) {
		this.fxEnvioF3 = fxEnvioF3;
	}

	public Date getFxCalculoF3() {
		return fxCalculoF3;
	}

	public void setFxCalculoF3(Date fxCalculoF3) {
		this.fxCalculoF3 = fxCalculoF3;
	}

	public Date getFxProcesoF4() {
		return fxProcesoF4;
	}

	public void setFxProcesoF4(Date fxProcesoF4) {
		this.fxProcesoF4 = fxProcesoF4;
	}

	public Long getContribEnviados() {
		return contribEnviados;
	}

	public void setContribEnviados(Long contribEnviados) {
		this.contribEnviados = contribEnviados;
	}

	public Long getDocumentosEnviados() {
		return documentosEnviados;
	}

	public void setDocumentosEnviados(Long documentosEnviados) {
		this.documentosEnviados = documentosEnviados;
	}

	public BigDecimal getImEnviado() {
		return imEnviado;
	}

	public void setImEnviado(BigDecimal imEnviado) {
		this.imEnviado = imEnviado;
	}

	public BigDecimal getImRetenido() {
		return imRetenido;
	}

	public void setImRetenido(BigDecimal imRetenido) {
		this.imRetenido = imRetenido;
	}

	public Long getContribRetenidos() {
		return contribRetenidos;
	}

	public void setContribRetenidos(Long contribRetenidos) {
		this.contribRetenidos = contribRetenidos;
	}

	public BigDecimal getImEmbargoTotal() {
		return imEmbargoTotal;
	}

	public void setImEmbargoTotal(BigDecimal imEmbargoTotal) {
		this.imEmbargoTotal = imEmbargoTotal;
	}

	public Long getContribEmbargoTotal() {
		return contribEmbargoTotal;
	}

	public void setContribEmbargoTotal(Long contribEmbargoTotal) {
		this.contribEmbargoTotal = contribEmbargoTotal;
	}

	public BigDecimal getImEmbargoParcial() {
		return imEmbargoParcial;
	}

	public void setImEmbargoParcial(BigDecimal imEmbargoParcial) {
		this.imEmbargoParcial = imEmbargoParcial;
	}

	public Long getContribEmbargoParcial() {
		return contribEmbargoParcial;
	}

	public void setContribEmbargoParcial(Long contribEmbargoParcial) {
		this.contribEmbargoParcial = contribEmbargoParcial;
	}

	public BigDecimal getImEmbargoNegativo() {
		return imEmbargoNegativo;
	}

	public void setImEmbargoNegativo(BigDecimal imEmbargoNegativo) {
		this.imEmbargoNegativo = imEmbargoNegativo;
	}

	public Long getContribEmbargoNegativo() {
		return contribEmbargoNegativo;
	}

	public void setContribEmbargoNegativo(Long contribEmbargoNegativo) {
		this.contribEmbargoNegativo = contribEmbargoNegativo;
	}

	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}


	public void setToImporteLevantado(BigDecimal toImporteLevantado) {
		this.toImporteLevantado = toImporteLevantado;
	}


	public BigDecimal getToImporteLevantado() {
		return toImporteLevantado;
	}


	public void setToContribLevantado(Long toContribLevantado) {
		this.toContribLevantado = toContribLevantado;
	}


	public Long getToContribLevantado() {
		return toContribLevantado;
	}

 
}
