package es.dipucadiz.etir.comun.dto;

// Generated 04-nov-2010 8:41:23 by Hibernate Tools 3.2.4.GA

/**
 * ClienteCuentaDTOId generated by hbm2java
 */
public class C63CuentaDTOId implements java.io.Serializable {

	private String iban;
	 private long co63Cliente;
	public String getIban() {
		return iban;
	}
	public void setIban(String iban) {
		this.iban = iban;
	}
 
	public C63CuentaDTOId(String iban, long co63Cliente) {
		super();
		this.iban = iban;
		this.co63Cliente = co63Cliente;
	}
	public long getCo63Cliente() {
		return co63Cliente;
	}
	public void setCo63Cliente(long co63Cliente) {
		this.co63Cliente = co63Cliente;
	}
	public C63CuentaDTOId() {
		super();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcmPerfilBotonDTOId))
			return false;
		C63CuentaDTOId castOther = (C63CuentaDTOId) other;

		return ((this.getIban() == castOther.getIban()) || (this
				.getIban() != null
				&& castOther.getIban() != null && this.getIban()
				.equals(castOther.getIban())))
				&& (this.getCo63Cliente() == castOther.getCo63Cliente());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIban() == null ? 0 : this.getIban()
						.hashCode());
		result = 37 * result + (int) this.getCo63Cliente();
		return result;
	}
}
