package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * CalleSinonimoDTOId generated by hbm2java
 */
public class CalleSinonimoDTOId implements java.io.Serializable {

	private long coCalle;
	private String sigla;
	private String sinonimo;

	public CalleSinonimoDTOId() {
	}

	public CalleSinonimoDTOId(long coCalle, String sigla, String sinonimo) {
		this.coCalle = coCalle;
		this.sigla = sigla;
		this.sinonimo = sinonimo;
	}

	public long getCoCalle() {
		return this.coCalle;
	}

	public void setCoCalle(long coCalle) {
		this.coCalle = coCalle;
	}

	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	public String getSinonimo() {
		return this.sinonimo;
	}

	public void setSinonimo(String sinonimo) {
		this.sinonimo = sinonimo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CalleSinonimoDTOId))
			return false;
		CalleSinonimoDTOId castOther = (CalleSinonimoDTOId) other;

		return (this.getCoCalle() == castOther.getCoCalle())
				&& ((this.getSigla() == castOther.getSigla()) || (this
						.getSigla() != null
						&& castOther.getSigla() != null && this.getSigla()
						.equals(castOther.getSigla())))
				&& ((this.getSinonimo() == castOther.getSinonimo()) || (this
						.getSinonimo() != null
						&& castOther.getSinonimo() != null && this
						.getSinonimo().equals(castOther.getSinonimo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCoCalle();
		result = 37 * result
				+ (getSigla() == null ? 0 : this.getSigla().hashCode());
		result = 37 * result
				+ (getSinonimo() == null ? 0 : this.getSinonimo().hashCode());
		return result;
	}

}
