package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * CalleTramoPostalDTOId generated by hbm2java
 */
public class CalleTramoPostalDTOId implements java.io.Serializable {

	private long coCalle;
	private int desde;

	public CalleTramoPostalDTOId() {
	}

	public CalleTramoPostalDTOId(long coCalle, int desde) {
		this.coCalle = coCalle;
		this.desde = desde;
	}

	public long getCoCalle() {
		return this.coCalle;
	}

	public void setCoCalle(long coCalle) {
		this.coCalle = coCalle;
	}

	public int getDesde() {
		return this.desde;
	}

	public void setDesde(int desde) {
		this.desde = desde;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CalleTramoPostalDTOId))
			return false;
		CalleTramoPostalDTOId castOther = (CalleTramoPostalDTOId) other;

		return (this.getCoCalle() == castOther.getCoCalle())
				&& (this.getDesde() == castOther.getDesde());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCoCalle();
		result = 37 * result + this.getDesde();
		return result;
	}

}
