package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CalleTramoPostalDTO generated by hbm2java
 */
public class CalleTramoPostalDTO implements java.io.Serializable {

	private CalleTramoPostalDTOId id;
	private CalleDTO calleDTO;
	private Integer hasta;
	private String tipo;
	private Integer cp;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public CalleTramoPostalDTO() {
	}

	public CalleTramoPostalDTO(CalleTramoPostalDTOId id, CalleDTO calleDTO) {
		this.id = id;
		this.calleDTO = calleDTO;
	}

	public CalleTramoPostalDTO(CalleTramoPostalDTOId id, CalleDTO calleDTO,
			Integer hasta, String tipo, Integer cp, Date fhActualizacion,
			String coUsuarioActualizacion) {
		this.id = id;
		this.calleDTO = calleDTO;
		this.hasta = hasta;
		this.tipo = tipo;
		this.cp = cp;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public CalleTramoPostalDTOId getId() {
		return this.id;
	}

	public void setId(CalleTramoPostalDTOId id) {
		this.id = id;
	}

	public CalleDTO getCalleDTO() {
		return this.calleDTO;
	}

	public void setCalleDTO(CalleDTO calleDTO) {
		this.calleDTO = calleDTO;
	}

	public Integer getHasta() {
		return this.hasta;
	}

	public void setHasta(Integer hasta) {
		this.hasta = hasta;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Integer getCp() {
		return this.cp;
	}

	public void setCp(Integer cp) {
		this.cp = cp;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
