package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import es.dipucadiz.etir.comun.bo.GenericBO;
import es.dipucadiz.etir.comun.dao.QueryName;
import es.dipucadiz.etir.comun.utilidades.Utilidades;


/**
 * CargaControlRecepcionDTO generated by hbm2java
 */
public class CargaControlRecepcionDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long coCargaControlRecepcion;
	private CargaDTO cargaDTO;
	private MunicipioDTO municipioDTO;
	private EjecucionDTO ejecucionDTO;
	private String estado;
	private Integer totalCargados;
	private Date fhRecepcion;
	private Boolean boNorechazable;
	private String fichero;
	private String coModeloResumen;
	private String coVersionResumen;
	private String coDocumentoResumen;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<DocumentoDTO> documentoDTOs = new HashSet<DocumentoDTO>(0);
	private String rowid;
	private String subtipo;

	public CargaControlRecepcionDTO() {
	}

	public CargaControlRecepcionDTO(CargaDTO cargaDTO, MunicipioDTO municipioDTO) {
		this.cargaDTO = cargaDTO;
		this.municipioDTO = municipioDTO;
	}

	public CargaControlRecepcionDTO(CargaDTO cargaDTO,
			MunicipioDTO municipioDTO, EjecucionDTO ejecucionDTO,
			String estado, Integer totalCargados, Date fhRecepcion,
			Boolean boNorechazable, String fichero, String coModeloResumen,
			String coVersionResumen, String coDocumentoResumen,
			Date fhActualizacion, String coUsuarioActualizacion,
			Set<DocumentoDTO> documentoDTOs) {
		this.cargaDTO = cargaDTO;
		this.municipioDTO = municipioDTO;
		this.ejecucionDTO = ejecucionDTO;
		this.estado = estado;
		this.totalCargados = totalCargados;
		this.fhRecepcion = fhRecepcion;
		this.boNorechazable = boNorechazable;
		this.fichero = fichero;
		this.coModeloResumen = coModeloResumen;
		this.coVersionResumen = coVersionResumen;
		this.coDocumentoResumen = coDocumentoResumen;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.documentoDTOs = documentoDTOs;
	}
	
	
	

	public Long getCoCargaControlRecepcion() {
		return this.coCargaControlRecepcion;
	}

	public void setCoCargaControlRecepcion(Long coCargaControlRecepcion) {
		this.coCargaControlRecepcion = coCargaControlRecepcion;
	}

	public CargaDTO getCargaDTO() {
		return this.cargaDTO;
	}

	public void setCargaDTO(CargaDTO cargaDTO) {
		this.cargaDTO = cargaDTO;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public EjecucionDTO getEjecucionDTO() {
		return this.ejecucionDTO;
	}

	public void setEjecucionDTO(EjecucionDTO ejecucionDTO) {
		this.ejecucionDTO = ejecucionDTO;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Integer getTotalCargados() {
		return this.totalCargados;
	}

	public void setTotalCargados(Integer totalCargados) {
		this.totalCargados = totalCargados;
	}

	public Date getFhRecepcion() {
		return this.fhRecepcion;
	}

	public void setFhRecepcion(Date fhRecepcion) {
		this.fhRecepcion = fhRecepcion;
	}

	public Boolean getBoNorechazable() {
		return this.boNorechazable;
	}

	public void setBoNorechazable(Boolean boNorechazable) {
		this.boNorechazable = boNorechazable;
	}

	public String getFichero() {
		return this.fichero;
	}

	public void setFichero(String fichero) {
		this.fichero = fichero;
	}

	public String getCoModeloResumen() {
		return this.coModeloResumen;
	}

	public void setCoModeloResumen(String coModeloResumen) {
		this.coModeloResumen = coModeloResumen;
	}

	public String getCoVersionResumen() {
		return this.coVersionResumen;
	}

	public void setCoVersionResumen(String coVersionResumen) {
		this.coVersionResumen = coVersionResumen;
	}

	public String getCoDocumentoResumen() {
		return this.coDocumentoResumen;
	}

	public void setCoDocumentoResumen(String coDocumentoResumen) {
		this.coDocumentoResumen = coDocumentoResumen;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<DocumentoDTO> getDocumentoDTOs() {
		return this.documentoDTOs;
	}

	public void setDocumentoDTOs(Set<DocumentoDTO> documentoDTOs) {
		this.documentoDTOs = documentoDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public String getSubtipo() {
		return subtipo;
	}

	public void setSubtipo(String subtipo) {
		this.subtipo = subtipo;
	}

	


}
