package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import es.dipucadiz.etir.comun.bo.GenericBO;
import es.dipucadiz.etir.comun.dao.QueryName;
import es.dipucadiz.etir.comun.utilidades.Utilidades;


/**
 * CargaControlRecepcionDTO generated by hbm2java
 */
public class CargaControlRecepcionTotalizadoDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private CargaControlRecepcionTotalizadoDTOId id;
	private CargaControlRecepcionDTO cargaControlRecepcionDTO;
	private String descripcion;
	private BigDecimal total;
	 
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	 
	 
	

	  
	public CargaControlRecepcionTotalizadoDTOId getId() {
		return id;
	}


	public void setId(CargaControlRecepcionTotalizadoDTOId id) {
		this.id = id;
	}


	public CargaControlRecepcionDTO getCargaControlRecepcionDTO() {
		return cargaControlRecepcionDTO;
	}


	public void setCargaControlRecepcionDTO(
			CargaControlRecepcionDTO cargaControlRecepcionDTO) {
		this.cargaControlRecepcionDTO = cargaControlRecepcionDTO;
	}


	public String getDescripcion() {
		return descripcion;
	}


	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


	public Date getFhActualizacion() {
		return fhActualizacion;
	}


	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}


	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}


	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}


	


	



	public CargaControlRecepcionTotalizadoDTO(
			CargaControlRecepcionTotalizadoDTOId id,
			CargaControlRecepcionDTO cargaControlRecepcionDTO,
			String descripcion, BigDecimal total, Date fhActualizacion,
			String coUsuarioActualizacion) {
		super();
		this.id = id;
		this.cargaControlRecepcionDTO = cargaControlRecepcionDTO;
		this.descripcion = descripcion;
		this.total = total;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}


	public BigDecimal getTotal() {
		return total;
	}


	public void setTotal(BigDecimal total) {
		this.total = total;
	}


	public CargaControlRecepcionTotalizadoDTO() {
		super();
	}


	 


}
