package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA


/**
 * EjecucionDTO generated by hbm2java
 */
public class CargaTGSSDTO implements java.io.Serializable {

	Long id;
	EjecucionDTO ejecucionDTO;
	Long nuInforme;
	ExpedienteDTO expedienteDTO;
	String estado;
	String orden01;
	String orden02;
	Long nuFile;
	
	public CargaTGSSDTO() {
	}

	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public EjecucionDTO getEjecucionDTO() {
		return ejecucionDTO;
	}
	public void setEjecucionDTO(EjecucionDTO ejecucionDTO) {
		this.ejecucionDTO = ejecucionDTO;
	}
	public Long getNuInforme() {
		return nuInforme;
	}
	public void setNuInforme(Long nuInforme) {
		this.nuInforme = nuInforme;
	}
	public ExpedienteDTO getExpedienteDTO() {
		return expedienteDTO;
	}
	public void setExpedienteDTO(ExpedienteDTO expedienteDTO) {
		this.expedienteDTO = expedienteDTO;
	}
	public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getOrden01() {
		return orden01;
	}

	public void setOrden01(String orden01) {
		this.orden01 = orden01;
	}

	public String getOrden02() {
		return orden02;
	}

	public void setOrden02(String orden02) {
		this.orden02 = orden02;
	}

	public Long getNuFile() {
		return nuFile;
	}

	public void setNuFile(Long nuFile) {
		this.nuFile = nuFile;
	}
	
}
