package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CargoSubcargoSeguimientoDTO generated by hbm2java
 */
public class CargoSubcargoSeguimientoDTO implements java.io.Serializable {

	private Long coCargoSubcargoSeguimiento;
	private DocumentoDTO documentoDTO;
	private CargoSubcargoDTO cargoSubcargoDTO;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String coIncidenciaCargo;
	private String coSituacionCargoOrigen;
	private String coSituacionCargoDestino;
	private String observaciones;
	private String coProceso;
	private Long coEjecucion;
	
	private String rowid;

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public CargoSubcargoSeguimientoDTO() {
	}

	public CargoSubcargoSeguimientoDTO(DocumentoDTO documentoDTO,
			CargoSubcargoDTO cargoSubcargoDTO, Date fhActualizacion,
			String coUsuarioActualizacion, String coIncidenciaCargo,
			String coSituacionCargoOrigen, String coSituacionCargoDestino,
			String observaciones, String coProceso, Long coEjecucion) {
		this.documentoDTO = documentoDTO;
		this.cargoSubcargoDTO = cargoSubcargoDTO;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.coIncidenciaCargo = coIncidenciaCargo;
		this.coSituacionCargoOrigen = coSituacionCargoOrigen;
		this.coSituacionCargoDestino = coSituacionCargoDestino;
		this.observaciones = observaciones;
		this.coProceso = coProceso;
		this.coEjecucion = coEjecucion;
	}

	public Long getCoCargoSubcargoSeguimiento() {
		return this.coCargoSubcargoSeguimiento;
	}

	public void setCoCargoSubcargoSeguimiento(Long coCargoSubcargoSeguimiento) {
		this.coCargoSubcargoSeguimiento = coCargoSubcargoSeguimiento;
	}

	public DocumentoDTO getDocumentoDTO() {
		return this.documentoDTO;
	}

	public void setDocumentoDTO(DocumentoDTO documentoDTO) {
		this.documentoDTO = documentoDTO;
	}

	public CargoSubcargoDTO getCargoSubcargoDTO() {
		return this.cargoSubcargoDTO;
	}

	public void setCargoSubcargoDTO(CargoSubcargoDTO cargoSubcargoDTO) {
		this.cargoSubcargoDTO = cargoSubcargoDTO;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getCoIncidenciaCargo() {
		return this.coIncidenciaCargo;
	}

	public void setCoIncidenciaCargo(String coIncidenciaCargo) {
		this.coIncidenciaCargo = coIncidenciaCargo;
	}

	public String getCoSituacionCargoOrigen() {
		return this.coSituacionCargoOrigen;
	}

	public void setCoSituacionCargoOrigen(String coSituacionCargoOrigen) {
		this.coSituacionCargoOrigen = coSituacionCargoOrigen;
	}

	public String getCoSituacionCargoDestino() {
		return this.coSituacionCargoDestino;
	}

	public void setCoSituacionCargoDestino(String coSituacionCargoDestino) {
		this.coSituacionCargoDestino = coSituacionCargoDestino;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getCoProceso() {
		return this.coProceso;
	}

	public void setCoProceso(String coProceso) {
		this.coProceso = coProceso;
	}

	public Long getCoEjecucion() {
		return this.coEjecucion;
	}

	public void setCoEjecucion(Long coEjecucion) {
		this.coEjecucion = coEjecucion;
	}
}
