package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * CargaEstructuraDTOId generated by hbm2java
 */
public class CargaEstructuraDTOId implements java.io.Serializable {

	private long coCarga;
	private String coCargaTipoRegistro;
	private short nuCasilla;

	public CargaEstructuraDTOId() {
	}

	public CargaEstructuraDTOId(long coCarga, String coCargaTipoRegistro,
			short nuCasilla) {
		this.coCarga = coCarga;
		this.coCargaTipoRegistro = coCargaTipoRegistro;
		this.nuCasilla = nuCasilla;
	}

	public long getCoCarga() {
		return this.coCarga;
	}

	public void setCoCarga(long coCarga) {
		this.coCarga = coCarga;
	}

	public String getCoCargaTipoRegistro() {
		return this.coCargaTipoRegistro;
	}

	public void setCoCargaTipoRegistro(String coCargaTipoRegistro) {
		this.coCargaTipoRegistro = coCargaTipoRegistro;
	}

	public short getNuCasilla() {
		return this.nuCasilla;
	}

	public void setNuCasilla(short nuCasilla) {
		this.nuCasilla = nuCasilla;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CargaEstructuraDTOId))
			return false;
		CargaEstructuraDTOId castOther = (CargaEstructuraDTOId) other;

		return (this.getCoCarga() == castOther.getCoCarga())
				&& ((this.getCoCargaTipoRegistro() == castOther
						.getCoCargaTipoRegistro()) || (this
						.getCoCargaTipoRegistro() != null
						&& castOther.getCoCargaTipoRegistro() != null && this
						.getCoCargaTipoRegistro().equals(
								castOther.getCoCargaTipoRegistro())))
				&& (this.getNuCasilla() == castOther.getNuCasilla());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCoCarga();
		result = 37
				* result
				+ (getCoCargaTipoRegistro() == null ? 0 : this
						.getCoCargaTipoRegistro().hashCode());
		result = 37 * result + this.getNuCasilla();
		return result;
	}

}
