package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CargaDTO generated by hbm2java
 */
public class CargaDTO implements java.io.Serializable {

	private Long coCarga;
	private MunicipioDTO municipioDTO;
	private ConceptoDTO conceptoDTO;
	private ModeloVersionDTO modeloVersionDTO;
	private String nombre;
	private String descripcion;
	private Short tamRegistro;
	private Short tipregPosIni;
	private Short tipregPosFin;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	
	private String tipo;
	
	private Set<CargaTipoRegistroDTO> cargaTipoRegistroDTOs = new HashSet<CargaTipoRegistroDTO>(
			0);
	private Set<CargaEstructuraDTO> cargaEstructuraDTOs = new HashSet<CargaEstructuraDTO>(
			0);
	private Set<CargaControlRecepcionDTO> cargaControlRecepcionDTOs = new HashSet<CargaControlRecepcionDTO>(
			0);
	private String rowid;

	public CargaDTO() {
	}

	public CargaDTO(MunicipioDTO municipioDTO, ConceptoDTO conceptoDTO,
			ModeloVersionDTO modeloVersionDTO, String nombre) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.modeloVersionDTO = modeloVersionDTO;
		this.nombre = nombre;
	}

	public CargaDTO(MunicipioDTO municipioDTO, ConceptoDTO conceptoDTO,
			ModeloVersionDTO modeloVersionDTO, String nombre,
			String descripcion, Short tamRegistro, Short tipregPosIni,
			Short tipregPosFin, Date fhActualizacion,
			String coUsuarioActualizacion,
			Set<CargaTipoRegistroDTO> cargaTipoRegistroDTOs,
			Set<CargaEstructuraDTO> cargaEstructuraDTOs,
			Set<CargaControlRecepcionDTO> cargaControlRecepcionDTOs) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.modeloVersionDTO = modeloVersionDTO;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tamRegistro = tamRegistro;
		this.tipregPosIni = tipregPosIni;
		this.tipregPosFin = tipregPosFin;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.cargaTipoRegistroDTOs = cargaTipoRegistroDTOs;
		this.cargaEstructuraDTOs = cargaEstructuraDTOs;
		this.cargaControlRecepcionDTOs = cargaControlRecepcionDTOs;
	}

	public Long getCoCarga() {
		return this.coCarga;
	}

	public void setCoCarga(Long coCarga) {
		this.coCarga = coCarga;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public ConceptoDTO getConceptoDTO() {
		return this.conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public ModeloVersionDTO getModeloVersionDTO() {
		return this.modeloVersionDTO;
	}

	public void setModeloVersionDTO(ModeloVersionDTO modeloVersionDTO) {
		this.modeloVersionDTO = modeloVersionDTO;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Short getTamRegistro() {
		return this.tamRegistro;
	}

	public void setTamRegistro(Short tamRegistro) {
		this.tamRegistro = tamRegistro;
	}

	public Short getTipregPosIni() {
		return this.tipregPosIni;
	}

	public void setTipregPosIni(Short tipregPosIni) {
		this.tipregPosIni = tipregPosIni;
	}

	public Short getTipregPosFin() {
		return this.tipregPosFin;
	}

	public void setTipregPosFin(Short tipregPosFin) {
		this.tipregPosFin = tipregPosFin;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<CargaTipoRegistroDTO> getCargaTipoRegistroDTOs() {
		return this.cargaTipoRegistroDTOs;
	}

	public void setCargaTipoRegistroDTOs(
			Set<CargaTipoRegistroDTO> cargaTipoRegistroDTOs) {
		this.cargaTipoRegistroDTOs = cargaTipoRegistroDTOs;
	}

	public Set<CargaEstructuraDTO> getCargaEstructuraDTOs() {
		return this.cargaEstructuraDTOs;
	}

	public void setCargaEstructuraDTOs(
			Set<CargaEstructuraDTO> cargaEstructuraDTOs) {
		this.cargaEstructuraDTOs = cargaEstructuraDTOs;
	}

	public Set<CargaControlRecepcionDTO> getCargaControlRecepcionDTOs() {
		return this.cargaControlRecepcionDTOs;
	}

	public void setCargaControlRecepcionDTOs(
			Set<CargaControlRecepcionDTO> cargaControlRecepcionDTOs) {
		this.cargaControlRecepcionDTOs = cargaControlRecepcionDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}


	

}
