package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA



/**
 * CargaControlRecepcionDTO generated by hbm2java
 */
public class CargaControlRecepcionTotalizadoDTOId implements java.io.Serializable {

	/**
	 * 
	 */
	private Long coCargaControlRecepcion;
	private String numCasilla;

	
	
	public Long getCoCargaControlRecepcion() {
		return coCargaControlRecepcion;
	}
	public void setCoCargaControlRecepcion(Long coCargaControlRecepcion) {
		this.coCargaControlRecepcion = coCargaControlRecepcion;
	}
	public String getNumCasilla() {
		return numCasilla;
	}
	public void setNumCasilla(String numCasilla) {
		this.numCasilla = numCasilla;
	}
	public CargaControlRecepcionTotalizadoDTOId(Long coCargaControlRecepcion,
			String numCasilla) {
		super();
		this.coCargaControlRecepcion = coCargaControlRecepcion;
		this.numCasilla = numCasilla;
	}
	public CargaControlRecepcionTotalizadoDTOId() {
		super();
	}
 
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CargaControlRecepcionTotalizadoDTOId))
			return false;
		CargaControlRecepcionTotalizadoDTOId castOther = (CargaControlRecepcionTotalizadoDTOId) other;

		return ((this.getCoCargaControlRecepcion().longValue() == castOther.getCoCargaControlRecepcion().longValue())&& 
				(this.getNumCasilla() == castOther.getNumCasilla()) || (this
				.getNumCasilla() != null
				&& castOther.getNumCasilla() != null && this
				.getNumCasilla().equals(castOther.getNumCasilla())));
	}

	public int hashCode() {
		int result = 17;
		
		result = 37 * result + this.getCoCargaControlRecepcion().intValue();
		
		result = 37
				* result
				+ (getNumCasilla() == null ? 0 : this.getNumCasilla()
						.hashCode());
		return result;
	}
}
