package es.dipucadiz.etir.comun.dto;

// Generated 09-mar-2010 14:27:20 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CargoSubcargoDTO generated by hbm2java
 */
public class CargoSubcargoDTO implements java.io.Serializable {

	private Long coCargoSubcargo;
	private ConceptoDTO conceptoDTO;
	private OtrDTO otrDTO;
	private CargoDTO cargoDTO;
	private Date fhSubcargo;
	private Integer totalRecibos;
	private BigDecimal imTotal;
	private String coSituacionCargo;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Short nuSubcargo;
	private Date fxIniVoluntaria;
	private Date fxFinVoluntaria;
	private Set<DocumentoLiquidacionDTO> documentoLiquidacionDTOs = new HashSet<DocumentoLiquidacionDTO>(0);
	private Set<CargoSubcargoSeguimientoDTO> cargoSubcargoSeguimientoDTOs = new HashSet<CargoSubcargoSeguimientoDTO>(0);
	private String rowid;
	
	
	
	
	public CargoSubcargoDTO() {
	}

	public CargoSubcargoDTO(Date fhSubcargo) {
		this.fhSubcargo = fhSubcargo;
	}

	public CargoSubcargoDTO(ConceptoDTO conceptoDTO, OtrDTO otrDTO,
			CargoDTO cargoDTO, IncidSitCargoDTO incidSitCargoDTO,
			Date fhSubcargo, Integer totalRecibos, BigDecimal imTotal,
			String coSituacionCargo, Date fhActualizacion,
			String coUsuarioActualizacion, Short nuSubcargo,
			Date fxIniVoluntaria, Date fxFinVoluntaria,
			Set<DocumentoLiquidacionDTO> documentoLiquidacionDTOs) {
		this.conceptoDTO = conceptoDTO;
		this.otrDTO = otrDTO;
		this.cargoDTO = cargoDTO;
		this.fhSubcargo = fhSubcargo;
		this.totalRecibos = totalRecibos;
		this.imTotal = imTotal;
		this.coSituacionCargo = coSituacionCargo;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.nuSubcargo = nuSubcargo;
		this.fxIniVoluntaria = fxIniVoluntaria;
		this.fxFinVoluntaria = fxFinVoluntaria;
		this.documentoLiquidacionDTOs = documentoLiquidacionDTOs;
	}

	public Long getCoCargoSubcargo() {
		return this.coCargoSubcargo;
	}

	public void setCoCargoSubcargo(Long coCargoSubcargo) {
		this.coCargoSubcargo = coCargoSubcargo;
	}

	public ConceptoDTO getConceptoDTO() {
		return this.conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public OtrDTO getOtrDTO() {
		return this.otrDTO;
	}

	public void setOtrDTO(OtrDTO otrDTO) {
		this.otrDTO = otrDTO;
	}

	public CargoDTO getCargoDTO() {
		return this.cargoDTO;
	}

	public void setCargoDTO(CargoDTO cargoDTO) {
		this.cargoDTO = cargoDTO;
	}

	public Date getFhSubcargo() {
		return this.fhSubcargo;
	}

	public void setFhSubcargo(Date fhSubcargo) {
		this.fhSubcargo = fhSubcargo;
	}

	public Integer getTotalRecibos() {
		return this.totalRecibos;
	}

	public void setTotalRecibos(Integer totalRecibos) {
		this.totalRecibos = totalRecibos;
	}

	public BigDecimal getImTotal() {
		return this.imTotal;
	}

	public void setImTotal(BigDecimal imTotal) {
		this.imTotal = imTotal;
	}
	
	public String getCoSituacionCargo() {
		return this.coSituacionCargo;
	}

	public void setCoSituacionCargo(String coSituacionCargo) {
		this.coSituacionCargo = coSituacionCargo;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Short getNuSubcargo() {
		return this.nuSubcargo;
	}

	public void setNuSubcargo(Short nuSubcargo) {
		this.nuSubcargo = nuSubcargo;
	}

	public Date getFxIniVoluntaria() {
		return this.fxIniVoluntaria;
	}

	public void setFxIniVoluntaria(Date fxIniVoluntaria) {
		this.fxIniVoluntaria = fxIniVoluntaria;
	}

	public Date getFxFinVoluntaria() {
		return this.fxFinVoluntaria;
	}

	public void setFxFinVoluntaria(Date fxFinVoluntaria) {
		this.fxFinVoluntaria = fxFinVoluntaria;
	}


	public Set<DocumentoLiquidacionDTO> getDocumentoLiquidacionDTOs() {
		return this.documentoLiquidacionDTOs;
	}

	public void setDocumentoLiquidacionDTOs(Set<DocumentoLiquidacionDTO> documentoLiquidacionDTOs) {
		this.documentoLiquidacionDTOs = documentoLiquidacionDTOs;
	}
	
	public Set<CargoSubcargoSeguimientoDTO> getCargoSubcargoSeguimientoDTOs() {
		return this.cargoSubcargoSeguimientoDTOs;
	}

	public void setCargoSubcargoSeguimientoDTOs(Set<CargoSubcargoSeguimientoDTO> cargoSubcargoSeguimientoDTOs) {
		this.cargoSubcargoSeguimientoDTOs = cargoSubcargoSeguimientoDTOs;
	}
	
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
