package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CasillaMunicipioDTO generated by hbm2java
 */
public class CasillaMunicipioDTO implements java.io.Serializable {
	private static final long serialVersionUID = -7828591590693541560L;

	private Long coCasillaMunicipio;
	private MunicipioDTO municipioDTO;
	private ConceptoDTO conceptoDTO;
	private CasillaModeloDTO casillaModeloDTO;
	private short orden;
	private Boolean boMantenible;
	private Boolean boNoApremiable;
	private Boolean boRecargoProvincial;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String coCasillaMunicipio2;
	private Set<CasillaMunicipioOperacionDTO> casillaMunicipioOperacionDTOs = new HashSet<CasillaMunicipioOperacionDTO>(
			0);
	private String rowid;

	public CasillaMunicipioDTO() {
	}

	public CasillaMunicipioDTO(MunicipioDTO municipioDTO,
			ConceptoDTO conceptoDTO, CasillaModeloDTO casillaModeloDTO) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.casillaModeloDTO = casillaModeloDTO;
	}

	public CasillaMunicipioDTO(MunicipioDTO municipioDTO,
			ConceptoDTO conceptoDTO, CasillaModeloDTO casillaModeloDTO,
			short orden, Boolean boMantenible, Boolean boRecargoProvincial,
			Date fhActualizacion, String coUsuarioActualizacion,
			Set<CasillaMunicipioOperacionDTO> casillaMunicipioOperacionDTOs) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.casillaModeloDTO = casillaModeloDTO;
		this.orden = orden;
		this.boMantenible = boMantenible;
		this.boRecargoProvincial = boRecargoProvincial;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.casillaMunicipioOperacionDTOs = casillaMunicipioOperacionDTOs;
	}

	public Long getCoCasillaMunicipio() {
		return this.coCasillaMunicipio;
	}
	
	public String getCoCasillaMunicipio2() {
		return this.coCasillaMunicipio2;
	}

	public void setCoCasillaMunicipio(Long coCasillaMunicipio) {
		this.coCasillaMunicipio = coCasillaMunicipio;
	}
	
	public void setCoCasillaMunicipio2(String coCasillaMunicipio2) {
		this.coCasillaMunicipio2 = coCasillaMunicipio2;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public ConceptoDTO getConceptoDTO() {
		return this.conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public CasillaModeloDTO getCasillaModeloDTO() {
		return this.casillaModeloDTO;
	}

	public void setCasillaModeloDTO(CasillaModeloDTO casillaModeloDTO) {
		this.casillaModeloDTO = casillaModeloDTO;
	}

	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	public Boolean getBoMantenible() {
		return this.boMantenible;
	}

	public void setBoMantenible(Boolean boMantenible) {
		this.boMantenible = boMantenible;
	}
	
	public Boolean getBoRecargoProvincial() {
		return this.boRecargoProvincial;
	}
	
	public void setBoRecargoProvincial(Boolean boRecargoProvincial) {
		this.boRecargoProvincial = boRecargoProvincial;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<CasillaMunicipioOperacionDTO> getCasillaMunicipioOperacionDTOs() {
		return this.casillaMunicipioOperacionDTOs;
	}

	public void setCasillaMunicipioOperacionDTOs(
			Set<CasillaMunicipioOperacionDTO> casillaMunicipioOperacionDTOs) {
		this.casillaMunicipioOperacionDTOs = casillaMunicipioOperacionDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public Boolean getBoNoApremiable() {
		return boNoApremiable;
	}

	public void setBoNoApremiable(Boolean boNoApremiable) {
		this.boNoApremiable = boNoApremiable;
	}

}
