package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CasillasLigadasDTO generated by hbm2java
 */
public class CasillasLigadasDTO implements java.io.Serializable {

	private Long coCasillasLigadas;
	private CasillaModeloDTO casillaModeloDTO;
	private Short nuCasillaLigada;
	//private CasillaModeloDTO casillaModeloDTOByCasmodCasillasLigadas;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public CasillasLigadasDTO() {
	}

	public CasillasLigadasDTO(
			CasillaModeloDTO casillaModeloDTO,
			Short nuCasillaLigada) {
		this.casillaModeloDTO = casillaModeloDTO;
		this.nuCasillaLigada = nuCasillaLigada;
	}

	public CasillasLigadasDTO(
			CasillaModeloDTO casillaModeloDTO,
			Short nuCasillaLigada,
			Date fhActualizacion, String coUsuarioActualizacion) {
		this.casillaModeloDTO = casillaModeloDTO;
		this.nuCasillaLigada = nuCasillaLigada;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Long getCoCasillasLigadas() {
		return this.coCasillasLigadas;
	}

	public void setCoCasillasLigadas(Long coCasillasLigadas) {
		this.coCasillasLigadas = coCasillasLigadas;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public CasillaModeloDTO getCasillaModeloDTO() {
		return casillaModeloDTO;
	}

	public void setCasillaModeloDTO(CasillaModeloDTO casillaModeloDTO) {
		this.casillaModeloDTO = casillaModeloDTO;
	}

	public Short getNuCasillaLigada() {
		return nuCasillaLigada;
	}

	public void setNuCasillaLigada(Short nuCasillaLigada) {
		this.nuCasillaLigada = nuCasillaLigada;
	}

	
}
