package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CasillaMunicipioOperacionDTO generated by hbm2java
 */
public class CasillaMunicipioOperacionDTO implements java.io.Serializable {

	private CasillaMunicipioOperacionDTOId id;
	private FuncionArgumentoDTO funcionArgumentoDTO;
	private CasillaMunicipioDTO casillaMunicipioDTO;
	private String atributo;
	private String parametro;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public CasillaMunicipioOperacionDTO() {
	}

	public CasillaMunicipioOperacionDTO(CasillaMunicipioOperacionDTOId id,
			CasillaMunicipioDTO casillaMunicipioDTO) {
		this.id = id;
		this.casillaMunicipioDTO = casillaMunicipioDTO;
	}

	public CasillaMunicipioOperacionDTO(CasillaMunicipioOperacionDTOId id,
			FuncionArgumentoDTO funcionArgumentoDTO,
			CasillaMunicipioDTO casillaMunicipioDTO, String atributo,
			String parametro, Date fhActualizacion,
			String coUsuarioActualizacion) {
		this.id = id;
		this.funcionArgumentoDTO = funcionArgumentoDTO;
		this.casillaMunicipioDTO = casillaMunicipioDTO;
		this.atributo = atributo;
		this.parametro = parametro;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public CasillaMunicipioOperacionDTOId getId() {
		return this.id;
	}

	public void setId(CasillaMunicipioOperacionDTOId id) {
		this.id = id;
	}

	public FuncionArgumentoDTO getFuncionArgumentoDTO() {
		return this.funcionArgumentoDTO;
	}

	public void setFuncionArgumentoDTO(FuncionArgumentoDTO funcionArgumentoDTO) {
		this.funcionArgumentoDTO = funcionArgumentoDTO;
	}

	public CasillaMunicipioDTO getCasillaMunicipioDTO() {
		return this.casillaMunicipioDTO;
	}

	public void setCasillaMunicipioDTO(CasillaMunicipioDTO casillaMunicipioDTO) {
		this.casillaMunicipioDTO = casillaMunicipioDTO;
	}

	public String getAtributo() {
		return this.atributo;
	}

	public void setAtributo(String atributo) {
		this.atributo = atributo;
	}

	public String getParametro() {
		return this.parametro;
	}

	public void setParametro(String parametro) {
		this.parametro = parametro;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
