package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CasillaModeloDTO generated by hbm2java
 */
public class CasillaModeloDTO implements java.io.Serializable, Comparable<CasillaModeloDTO> {

	private CasillaModeloDTOId id;
	private ModeloVersionDTO modeloVersionDTO;
	private String formato;
	private BigDecimal longitud;
	private String nombre;
	private String descripcion;
	private boolean boRepeticion;
	private boolean boDobleDigitacion;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<DocumentoCasillaValorDTO> documentoCasillaValorDTOs = new HashSet<DocumentoCasillaValorDTO>(
			0);
	private Set<CasillasLigadasDTO> casillasLigadasDTOsForCasmodCasillasLigadas = new HashSet<CasillasLigadasDTO>(
			0);
	private Set<BonificacionArt74DTO> bonificacionArt74DTOs = new HashSet<BonificacionArt74DTO>(
			0);
	private Set<ValidacionDTO> validacionDTOs = new HashSet<ValidacionDTO>(0);
	private Set<CasillasLigadasDTO> casillasLigadasDTOsForCasmodCasligCasillasLigadas = new HashSet<CasillasLigadasDTO>(
			0);
	private Set<CasillaMunicipioDTO> casillaMunicipioDTOs = new HashSet<CasillaMunicipioDTO>(
			0);
	private Set<CasillasRelacionadasDTO> casillasRelacionadasDTOs = new HashSet<CasillasRelacionadasDTO>(
			0);
	private Set<SigreSubconceptoDTO> sigreSubconceptoDTOs = new HashSet<SigreSubconceptoDTO>(
			0);
	private String rowid;

	public CasillaModeloDTO() {
	}

	public CasillaModeloDTO(CasillaModeloDTOId id,
			ModeloVersionDTO modeloVersionDTO) {
		this.id = id;
		this.modeloVersionDTO = modeloVersionDTO;
	}

	public CasillaModeloDTO(
			CasillaModeloDTOId id,
			ModeloVersionDTO modeloVersionDTO,
			String formato,
			BigDecimal longitud,
			String nombre,
			String descripcion,
			boolean boRepeticion,
			Boolean boRecProvincial,
			boolean boDobleDigitacion,
			Date fhActualizacion,
			String coUsuarioActualizacion,
			Set<DocumentoCasillaValorDTO> documentoCasillaValorDTOs,
			Set<CasillasLigadasDTO> casillasLigadasDTOsForCasmodCasillasLigadas,
			Set<BonificacionArt74DTO> bonificacionArt74DTOs,
			Set<ValidacionDTO> validacionDTOs,
			Set<CasillasLigadasDTO> casillasLigadasDTOsForCasmodCasligCasillasLigadas,
			Set<CasillaMunicipioDTO> casillaMunicipioDTOs,
			Set<CasillasRelacionadasDTO> casillasRelacionadasDTOs,
			Set<SigreSubconceptoDTO> sigreSubconceptoDTOs) {
		this.id = id;
		this.modeloVersionDTO = modeloVersionDTO;
		this.formato = formato;
		this.longitud = longitud;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.boRepeticion = boRepeticion;
		this.boDobleDigitacion = boDobleDigitacion;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.documentoCasillaValorDTOs = documentoCasillaValorDTOs;
		this.casillasLigadasDTOsForCasmodCasillasLigadas = casillasLigadasDTOsForCasmodCasillasLigadas;
		this.bonificacionArt74DTOs = bonificacionArt74DTOs;
		this.validacionDTOs = validacionDTOs;
		this.casillasLigadasDTOsForCasmodCasligCasillasLigadas = casillasLigadasDTOsForCasmodCasligCasillasLigadas;
		this.casillaMunicipioDTOs = casillaMunicipioDTOs;
		this.casillasRelacionadasDTOs = casillasRelacionadasDTOs;
		this.sigreSubconceptoDTOs = sigreSubconceptoDTOs;
	}

	public String getCodigoDescripcion() {		
		return Short.toString(this.id.getNuCasilla()) + " - " + this.nombre;
	}
	
	public CasillaModeloDTOId getId() {
		return this.id;
	}

	public void setId(CasillaModeloDTOId id) {
		this.id = id;
	}

	public ModeloVersionDTO getModeloVersionDTO() {
		return this.modeloVersionDTO;
	}

	public void setModeloVersionDTO(ModeloVersionDTO modeloVersionDTO) {
		this.modeloVersionDTO = modeloVersionDTO;
	}

	public String getFormato() {
		return this.formato;
	}

	public void setFormato(String formato) {
		this.formato = formato;
	}

	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean getBoRepeticion() {
		return this.boRepeticion;
	}

	public void setBoRepeticion(boolean boRepeticion) {
		this.boRepeticion = boRepeticion;
	}

	public boolean getBoDobleDigitacion() {
		return this.boDobleDigitacion;
	}

	public void setBoDobleDigitacion(boolean boDobleDigitacion) {
		this.boDobleDigitacion = boDobleDigitacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<DocumentoCasillaValorDTO> getDocumentoCasillaValorDTOs() {
		return this.documentoCasillaValorDTOs;
	}

	public void setDocumentoCasillaValorDTOs(
			Set<DocumentoCasillaValorDTO> documentoCasillaValorDTOs) {
		this.documentoCasillaValorDTOs = documentoCasillaValorDTOs;
	}

	public Set<CasillasLigadasDTO> getCasillasLigadasDTOsForCasmodCasillasLigadas() {
		return this.casillasLigadasDTOsForCasmodCasillasLigadas;
	}

	public void setCasillasLigadasDTOsForCasmodCasillasLigadas(
			Set<CasillasLigadasDTO> casillasLigadasDTOsForCasmodCasillasLigadas) {
		this.casillasLigadasDTOsForCasmodCasillasLigadas = casillasLigadasDTOsForCasmodCasillasLigadas;
	}

	public Set<BonificacionArt74DTO> getBonificacionArt74DTOs() {
		return this.bonificacionArt74DTOs;
	}

	public void setBonificacionArt74DTOs(
			Set<BonificacionArt74DTO> bonificacionArt74DTOs) {
		this.bonificacionArt74DTOs = bonificacionArt74DTOs;
	}

	public Set<ValidacionDTO> getValidacionDTOs() {
		return this.validacionDTOs;
	}

	public void setValidacionDTOs(Set<ValidacionDTO> validacionDTOs) {
		this.validacionDTOs = validacionDTOs;
	}

	public Set<CasillasLigadasDTO> getCasillasLigadasDTOsForCasmodCasligCasillasLigadas() {
		return this.casillasLigadasDTOsForCasmodCasligCasillasLigadas;
	}

	public void setCasillasLigadasDTOsForCasmodCasligCasillasLigadas(
			Set<CasillasLigadasDTO> casillasLigadasDTOsForCasmodCasligCasillasLigadas) {
		this.casillasLigadasDTOsForCasmodCasligCasillasLigadas = casillasLigadasDTOsForCasmodCasligCasillasLigadas;
	}

	public Set<CasillaMunicipioDTO> getCasillaMunicipioDTOs() {
		return this.casillaMunicipioDTOs;
	}

	public void setCasillaMunicipioDTOs(
			Set<CasillaMunicipioDTO> casillaMunicipioDTOs) {
		this.casillaMunicipioDTOs = casillaMunicipioDTOs;
	}

	public Set<CasillasRelacionadasDTO> getCasillasRelacionadasDTOs() {
		return this.casillasRelacionadasDTOs;
	}

	public void setCasillasRelacionadasDTOs(
			Set<CasillasRelacionadasDTO> casillasRelacionadasDTOs) {
		this.casillasRelacionadasDTOs = casillasRelacionadasDTOs;
	}

	public Set<SigreSubconceptoDTO> getSigreSubconceptoDTOs() {
		return this.sigreSubconceptoDTOs;
	}

	public void setSigreSubconceptoDTOs(
			Set<SigreSubconceptoDTO> sigreSubconceptoDTOs) {
		this.sigreSubconceptoDTOs = sigreSubconceptoDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public int compareTo(CasillaModeloDTO o) {
		int result;
		if (this.getId().getNuCasilla() > o.getId().getNuCasilla()) {
			result = 1;
		} else if (this.getId().getNuCasilla() < o.getId().getNuCasilla()) {
			result = -1;
		} else {
			result = 0;
		}
		return result;
	}

}
