package es.dipucadiz.etir.comun.dto;
// Generated 07-abr-2010 9:08:07 by Hibernate Tools 3.2.4.GA


import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CircuitoModeloDTO generated by hbm2java
 */
public class CircuitoModeloDTO  implements java.io.Serializable {


     private CircuitoModeloDTOId id;
     private ModeloDTO modeloDTO;
     private CircuitoDTO circuitoDTO;
     private String numCasillaDescripcion;     
     private Date fhActualizacion;
     private String coUsuarioActualizacion;
     private String rowid;

    public CircuitoModeloDTO() {
    }

	
    public CircuitoModeloDTO(CircuitoModeloDTOId id, ModeloDTO modeloDTO, CircuitoDTO circuitoDTO) {
        this.id = id;
        this.modeloDTO = modeloDTO;
        this.circuitoDTO = circuitoDTO;
    }
    public CircuitoModeloDTO(CircuitoModeloDTOId id, ModeloDTO modeloDTO, CircuitoDTO circuitoDTO, Date fhActualizacion, String coUsuarioActualizacion) {
       this.id = id;
       this.modeloDTO = modeloDTO;
       this.circuitoDTO = circuitoDTO;
       this.fhActualizacion = fhActualizacion;
       this.coUsuarioActualizacion = coUsuarioActualizacion;
    }
   
    
    public CircuitoModeloDTO(CircuitoModeloDTOId id, ModeloDTO modeloDTO,
			CircuitoDTO circuitoDTO, String numCasillaDescripcion,
			Date fhActualizacion, String coUsuarioActualizacion, String rowid) {
		super();
		this.id = id;
		this.modeloDTO = modeloDTO;
		this.circuitoDTO = circuitoDTO;
		this.numCasillaDescripcion = numCasillaDescripcion;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.rowid = rowid;
	}


	public CircuitoModeloDTOId getId() {
        return this.id;
    }
    
    public void setId(CircuitoModeloDTOId id) {
        this.id = id;
    }
    public ModeloDTO getModeloDTO() {
        return this.modeloDTO;
    }
    
    public void setModeloDTO(ModeloDTO modeloDTO) {
        this.modeloDTO = modeloDTO;
    }
    public CircuitoDTO getCircuitoDTO() {
        return this.circuitoDTO;
    }
    
    public void setCircuitoDTO(CircuitoDTO circuitoDTO) {
        this.circuitoDTO = circuitoDTO;
    }
    public Date getFhActualizacion() {
        return this.fhActualizacion;
    }
    
    public void setFhActualizacion(Date fhActualizacion) {
        this.fhActualizacion = fhActualizacion;
    }
    public String getCoUsuarioActualizacion() {
        return this.coUsuarioActualizacion;
    }
    
    public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
        this.coUsuarioActualizacion = coUsuarioActualizacion;
    }
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}


	public String getNumCasillaDescripcion() {
		return numCasillaDescripcion;
	}


	public void setNumCasillaDescripcion(String numCasillaDescripcion) {
		this.numCasillaDescripcion = numCasillaDescripcion;
	}




}


