package es.dipucadiz.etir.comun.dto;
// Generated 07-abr-2010 9:08:07 by Hibernate Tools 3.2.4.GA



/**
 * CircuitoRutaDTOId generated by hbm2java
 */
public class CircuitoRutaDTOId  implements java.io.Serializable {


     private String coCircuito;
     private String coProvincia;
     private String coMunicipio;

    public CircuitoRutaDTOId() {
    }

    public CircuitoRutaDTOId(String coCircuito, String coProvincia, String coMunicipio) {
       this.coCircuito = coCircuito;
       this.coProvincia = coProvincia;
       this.coMunicipio = coMunicipio;
    }
   
    public String getCoCircuito() {
        return this.coCircuito;
    }
    
    public void setCoCircuito(String coCircuito) {
        this.coCircuito = coCircuito;
    }
    public String getCoProvincia() {
        return this.coProvincia;
    }
    
    public void setCoProvincia(String coProvincia) {
        this.coProvincia = coProvincia;
    }
    public String getCoMunicipio() {
        return this.coMunicipio;
    }
    
    public void setCoMunicipio(String coMunicipio) {
        this.coMunicipio = coMunicipio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CircuitoRutaDTOId) ) return false;
		 CircuitoRutaDTOId castOther = ( CircuitoRutaDTOId ) other; 
         
		 return ( (this.getCoCircuito()==castOther.getCoCircuito()) || ( this.getCoCircuito()!=null && castOther.getCoCircuito()!=null && this.getCoCircuito().equals(castOther.getCoCircuito()) ) )
 && ( (this.getCoProvincia()==castOther.getCoProvincia()) || ( this.getCoProvincia()!=null && castOther.getCoProvincia()!=null && this.getCoProvincia().equals(castOther.getCoProvincia()) ) )
 && ( (this.getCoMunicipio()==castOther.getCoMunicipio()) || ( this.getCoMunicipio()!=null && castOther.getCoMunicipio()!=null && this.getCoMunicipio().equals(castOther.getCoMunicipio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCoCircuito() == null ? 0 : this.getCoCircuito().hashCode() );
         result = 37 * result + ( getCoProvincia() == null ? 0 : this.getCoProvincia().hashCode() );
         result = 37 * result + ( getCoMunicipio() == null ? 0 : this.getCoMunicipio().hashCode() );
         return result;
   }   


}


