package es.dipucadiz.etir.comun.dto;
// Generated 07-abr-2010 9:08:07 by Hibernate Tools 3.2.4.GA



/**
 * CircuitoAccesoDTOId generated by hbm2java
 */
public class CircuitoAccesoDTOId  implements java.io.Serializable {


     private String coCircuito;
     private String organoPrimerNivel;

    public CircuitoAccesoDTOId() {
    }

    public CircuitoAccesoDTOId(String coCircuito, String organoPrimerNivel) {
       this.coCircuito = coCircuito;
       this.organoPrimerNivel = organoPrimerNivel;
    }
   
    public String getCoCircuito() {
        return this.coCircuito;
    }
    
    public void setCoCircuito(String coCircuito) {
        this.coCircuito = coCircuito;
    }
    public String getOrganoPrimerNivel() {
        return this.organoPrimerNivel;
    }
    
    public void setOrganoPrimerNivel(String organoPrimerNivel) {
        this.organoPrimerNivel = organoPrimerNivel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CircuitoAccesoDTOId) ) return false;
		 CircuitoAccesoDTOId castOther = ( CircuitoAccesoDTOId ) other; 
         
		 return ( (this.getCoCircuito()==castOther.getCoCircuito()) || ( this.getCoCircuito()!=null && castOther.getCoCircuito()!=null && this.getCoCircuito().equals(castOther.getCoCircuito()) ) )
 && ( (this.getOrganoPrimerNivel()==castOther.getOrganoPrimerNivel()) || ( this.getOrganoPrimerNivel()!=null && castOther.getOrganoPrimerNivel()!=null && this.getOrganoPrimerNivel().equals(castOther.getOrganoPrimerNivel()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCoCircuito() == null ? 0 : this.getCoCircuito().hashCode() );
         result = 37 * result + ( getOrganoPrimerNivel() == null ? 0 : this.getOrganoPrimerNivel().hashCode() );
         return result;
   }   


}


