package es.dipucadiz.etir.comun.dto;
// Generated 07-abr-2010 9:08:07 by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CircuitoRutaDTO generated by hbm2java
 */
public class CircuitoRutaDTO  implements java.io.Serializable {


     private CircuitoRutaDTOId id;
     private MunicipioDTO municipioDTO;
     private CircuitoDTO circuitoDTO;
     private Boolean boActivo;
     private Date fhActualizacion;
     private String coUsuarioActualizacion;
     private Boolean boIndividual;
     private Date fxValidez;
     private Set<TramiteDTO> tramiteDTOs = new HashSet<TramiteDTO>(0);
     private Set<ExpedienteDTO> expedienteDTOs = new HashSet<ExpedienteDTO>(0);
     private String rowid;

     public CircuitoRutaDTO() {
 	}

 	public CircuitoRutaDTO(CircuitoRutaDTOId id, MunicipioDTO municipioDTO,
 			CircuitoDTO circuitoDTO) {
 		this.id = id;
 		this.municipioDTO = municipioDTO;
 		this.circuitoDTO = circuitoDTO;
 	}

 	public CircuitoRutaDTO(CircuitoRutaDTOId id, MunicipioDTO municipioDTO,
 			CircuitoDTO circuitoDTO, Boolean boActivo, Date fhActualizacion,
 			String coUsuarioActualizacion, Boolean boIndividual,
 			Date fxValidez, Set<TramiteDTO> tramiteDTOs,
 			Set<ExpedienteDTO> expedienteDTOs) {
 		this.id = id;
 		this.municipioDTO = municipioDTO;
 		this.circuitoDTO = circuitoDTO;
 		this.boActivo = boActivo;
 		this.fhActualizacion = fhActualizacion;
 		this.coUsuarioActualizacion = coUsuarioActualizacion;
 		this.boIndividual = boIndividual;
 		this.fxValidez = fxValidez;
 		this.tramiteDTOs = tramiteDTOs;
 		this.expedienteDTOs = expedienteDTOs;
 	}

 	public CircuitoRutaDTOId getId() {
 		return this.id;
 	}

 	public void setId(CircuitoRutaDTOId id) {
 		this.id = id;
 	}

 	public MunicipioDTO getMunicipioDTO() {
 		return this.municipioDTO;
 	}

 	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
 		this.municipioDTO = municipioDTO;
 	}

 	public CircuitoDTO getCircuitoDTO() {
 		return this.circuitoDTO;
 	}

 	public void setCircuitoDTO(CircuitoDTO circuitoDTO) {
 		this.circuitoDTO = circuitoDTO;
 	}

 	public Boolean getBoActivo() {
 		return this.boActivo;
 	}

 	public void setBoActivo(Boolean boActivo) {
 		this.boActivo = boActivo;
 	}

 	public Date getFhActualizacion() {
 		return this.fhActualizacion;
 	}

 	public void setFhActualizacion(Date fhActualizacion) {
 		this.fhActualizacion = fhActualizacion;
 	}

 	public String getCoUsuarioActualizacion() {
 		return this.coUsuarioActualizacion;
 	}

 	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
 		this.coUsuarioActualizacion = coUsuarioActualizacion;
 	}

 	public Boolean getBoIndividual() {
 		return this.boIndividual;
 	}

 	public void setBoIndividual(Boolean boIndividual) {
 		this.boIndividual = boIndividual;
 	}

 	public Date getFxValidez() {
 		return this.fxValidez;
 	}

 	public void setFxValidez(Date fxValidez) {
 		this.fxValidez = fxValidez;
 	}

 	public Set<TramiteDTO> getTramiteDTOs() {
 		return this.tramiteDTOs;
 	}

 	public void setTramiteDTOs(Set<TramiteDTO> tramiteDTOs) {
 		this.tramiteDTOs = tramiteDTOs;
 	}

 	public Set<ExpedienteDTO> getExpedienteDTOs() {
 		return this.expedienteDTOs;
 	}

 	public void setExpedienteDTOs(Set<ExpedienteDTO> expedienteDTOs) {
 		this.expedienteDTOs = expedienteDTOs;
 	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}




}


