package es.dipucadiz.etir.comun.dto;
// Generated 07-abr-2010 9:08:07 by Hibernate Tools 3.2.4.GA


import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CircuitoCompatibleDTO generated by hbm2java
 */
public class CircuitoCompatibleDTO  implements java.io.Serializable {


     private CircuitoCompatibleDTOId id;
     private CircuitoDTO circuitoDTOByCoCircuito;
     private CircuitoDTO circuitoDTOByCoCircuitoCompatible;
     private Date fhActualizacion;
     private String coUsuarioActualizacion;
     private String tipo;
     
     private String rowid;

    public CircuitoCompatibleDTO() {
    }

	
    public CircuitoCompatibleDTO(CircuitoCompatibleDTOId id, CircuitoDTO circuitoDTOByCoCircuito, CircuitoDTO circuitoDTOByCoCircuitoCompatible) {
        this.id = id;
        this.circuitoDTOByCoCircuito = circuitoDTOByCoCircuito;
        this.circuitoDTOByCoCircuitoCompatible = circuitoDTOByCoCircuitoCompatible;
    }
    public CircuitoCompatibleDTO(CircuitoCompatibleDTOId id, CircuitoDTO circuitoDTOByCoCircuito, CircuitoDTO circuitoDTOByCoCircuitoCompatible, Date fhActualizacion, String coUsuarioActualizacion) {
       this.id = id;
       this.circuitoDTOByCoCircuito = circuitoDTOByCoCircuito;
       this.circuitoDTOByCoCircuitoCompatible = circuitoDTOByCoCircuitoCompatible;
       this.fhActualizacion = fhActualizacion;
       this.coUsuarioActualizacion = coUsuarioActualizacion;
    }
   
    public CircuitoCompatibleDTOId getId() {
        return this.id;
    }
    
    public void setId(CircuitoCompatibleDTOId id) {
        this.id = id;
    }
    public CircuitoDTO getCircuitoDTOByCoCircuito() {
        return this.circuitoDTOByCoCircuito;
    }
    
    public void setCircuitoDTOByCoCircuito(CircuitoDTO circuitoDTOByCoCircuito) {
        this.circuitoDTOByCoCircuito = circuitoDTOByCoCircuito;
    }
    public CircuitoDTO getCircuitoDTOByCoCircuitoCompatible() {
        return this.circuitoDTOByCoCircuitoCompatible;
    }
    
    public void setCircuitoDTOByCoCircuitoCompatible(CircuitoDTO circuitoDTOByCoCircuitoCompatible) {
        this.circuitoDTOByCoCircuitoCompatible = circuitoDTOByCoCircuitoCompatible;
    }
    public Date getFhActualizacion() {
        return this.fhActualizacion;
    }
    
    public void setFhActualizacion(Date fhActualizacion) {
        this.fhActualizacion = fhActualizacion;
    }
    public String getCoUsuarioActualizacion() {
        return this.coUsuarioActualizacion;
    }
    
    public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
        this.coUsuarioActualizacion = coUsuarioActualizacion;
    }
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}


	public String getTipo() {
		return tipo;
	}


	public void setTipo(String tipo) {
		this.tipo = tipo;
	}




}


