package es.dipucadiz.etir.comun.dto;

// Generated 17-may-2012 9:28:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ClienteRepresentanteDTO generated by hbm2java
 */
public class ClienteRepresentanteDTO implements java.io.Serializable {

	private Long coClienteRepresentante;
	private ClienteDTO clienteDTO;
	private ClienteDTO representanteDTO;
	private CircuitoDTO circuitoDTO;
	private Date fxDesde;
	private Date fxHasta;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public ClienteRepresentanteDTO() {}

	public ClienteRepresentanteDTO(ClienteDTO clienteDTO, ClienteDTO representanteDTO, CircuitoDTO circuitoDTO, Date fxDesde, Date fxHasta, Date fhActualizacion, String coUsuarioActualizacion) {
		this.clienteDTO = clienteDTO;
		this.representanteDTO = representanteDTO;
		this.circuitoDTO = circuitoDTO;
		this.fxDesde = fxDesde;
		this.fxHasta = fxHasta;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getCodigoDescripcionRepresentante() {
		String res = "";
		try {
			res += getRepresentanteDTO().getNifNombre();
			res += " (" + getCircuitoDTO().getNombre() + ")";
		} catch (Exception e) {}

		return res;
	}

	public String getCodigoDescripcionCliente() {
		String res = "";
		try {
			res += getClienteDTO().getNifNombre();
			res += " (" + getCircuitoDTO().getNombre() + ")";
		} catch (Exception e) {}

		return res;
	}

	public Long getCoClienteRepresentante() {
		return this.coClienteRepresentante;
	}

	public void setCoClienteRepresentante(Long coClienteRepresentante) {
		this.coClienteRepresentante = coClienteRepresentante;
	}

	public ClienteDTO getClienteDTO() {
		return this.clienteDTO;
	}

	public void setClienteDTO(ClienteDTO clienteDTO) {
		this.clienteDTO = clienteDTO;
	}

	public ClienteDTO getRepresentanteDTO() {
		return this.representanteDTO;
	}

	public void setRepresentanteDTO(ClienteDTO representanteDTO) {
		this.representanteDTO = representanteDTO;
	}

	public CircuitoDTO getCircuitoDTO() {
		return this.circuitoDTO;
	}

	public void setCircuitoDTO(CircuitoDTO circuitoDTO) {
		this.circuitoDTO = circuitoDTO;
	}

	public Date getFxDesde() {
		return this.fxDesde;
	}

	public void setFxDesde(Date fxDesde) {
		this.fxDesde = fxDesde;
	}

	public Date getFxHasta() {
		return this.fxHasta;
	}

	public void setFxHasta(Date fxHasta) {
		this.fxHasta = fxHasta;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

}
