package es.dipucadiz.etir.comun.dto;

// Generated 04-nov-2010 8:41:23 by Hibernate Tools 3.2.4.GA

/**
 * ClienteCuentaDTOId generated by hbm2java
 */
public class ClienteCuentaDTOId implements java.io.Serializable {

	private String coBanco;
	private String coBancoSucursal;
	private String dc;
	private String cuenta;
	private long coCliente;

	public ClienteCuentaDTOId() {
	}

	public ClienteCuentaDTOId(String coBanco, String coBancoSucursal,
			String dc, String cuenta, long coCliente) {
		this.coBanco = coBanco;
		this.coBancoSucursal = coBancoSucursal;
		this.dc = dc;
		this.cuenta = cuenta;
		this.coCliente = coCliente;
	}

	public String getCoBanco() {
		return this.coBanco;
	}

	public void setCoBanco(String coBanco) {
		this.coBanco = coBanco;
	}

	public String getCoBancoSucursal() {
		return this.coBancoSucursal;
	}

	public void setCoBancoSucursal(String coBancoSucursal) {
		this.coBancoSucursal = coBancoSucursal;
	}

	public String getDc() {
		return this.dc;
	}

	public void setDc(String dc) {
		this.dc = dc;
	}

	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	public long getCoCliente() {
		return this.coCliente;
	}

	public void setCoCliente(long coCliente) {
		this.coCliente = coCliente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClienteCuentaDTOId))
			return false;
		ClienteCuentaDTOId castOther = (ClienteCuentaDTOId) other;

		return ((this.getCoBanco() == castOther.getCoBanco()) || (this
				.getCoBanco() != null
				&& castOther.getCoBanco() != null && this.getCoBanco().equals(
				castOther.getCoBanco())))
				&& ((this.getCoBancoSucursal() == castOther
						.getCoBancoSucursal()) || (this.getCoBancoSucursal() != null
						&& castOther.getCoBancoSucursal() != null && this
						.getCoBancoSucursal().equals(
								castOther.getCoBancoSucursal())))
				&& ((this.getDc() == castOther.getDc()) || (this.getDc() != null
						&& castOther.getDc() != null && this.getDc().equals(
						castOther.getDc())))
				&& ((this.getCuenta() == castOther.getCuenta()) || (this
						.getCuenta() != null
						&& castOther.getCuenta() != null && this.getCuenta()
						.equals(castOther.getCuenta())))
				&& (this.getCoCliente() == castOther.getCoCliente());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCoBanco() == null ? 0 : this.getCoBanco().hashCode());
		result = 37
				* result
				+ (getCoBancoSucursal() == null ? 0 : this.getCoBancoSucursal()
						.hashCode());
		result = 37 * result + (getDc() == null ? 0 : this.getDc().hashCode());
		result = 37 * result
				+ (getCuenta() == null ? 0 : this.getCuenta().hashCode());
		result = 37 * result + (int) this.getCoCliente();
		return result;
	}

}
