package es.dipucadiz.etir.comun.dto;

// Generated 04-nov-2010 8:41:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CodigoTerritorialCompatDTO generated by hbm2java
 */
public class CodigoTerritorialCompatDTO implements java.io.Serializable {

	private Long coCodigoTerritorialCompat;
	private String o1nUsuario;
	private String o1nDocumento;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private boolean boCoincide2;
	private boolean boCoincide3;
	private boolean boCoincide3usu2doc;
	private String modo;
	private String rowid;

	public CodigoTerritorialCompatDTO() {
	}

	public CodigoTerritorialCompatDTO(String o1nUsuario, String o1nDocumento,
			boolean boCoincide2, boolean boCoincide3,
			boolean boCoincide3usu2doc, String modo) {
		this.o1nUsuario = o1nUsuario;
		this.o1nDocumento = o1nDocumento;
		this.boCoincide2 = boCoincide2;
		this.boCoincide3 = boCoincide3;
		this.boCoincide3usu2doc = boCoincide3usu2doc;
		this.modo = modo;
	}

	public CodigoTerritorialCompatDTO(String o1nUsuario, String o1nDocumento,
			String coUsuarioActualizacion, Date fhActualizacion,
			boolean boCoincide2, boolean boCoincide3,
			boolean boCoincide3usu2doc, String modo) {
		this.o1nUsuario = o1nUsuario;
		this.o1nDocumento = o1nDocumento;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.boCoincide2 = boCoincide2;
		this.boCoincide3 = boCoincide3;
		this.boCoincide3usu2doc = boCoincide3usu2doc;
		this.modo = modo;
	}

	public Long getCoCodigoTerritorialCompat() {
		return this.coCodigoTerritorialCompat;
	}

	public void setCoCodigoTerritorialCompat(Long coCodigoTerritorialCompat) {
		this.coCodigoTerritorialCompat = coCodigoTerritorialCompat;
	}

	public String getO1nUsuario() {
		return this.o1nUsuario;
	}

	public void setO1nUsuario(String o1nUsuario) {
		this.o1nUsuario = o1nUsuario;
	}

	public String getO1nDocumento() {
		return this.o1nDocumento;
	}

	public void setO1nDocumento(String o1nDocumento) {
		this.o1nDocumento = o1nDocumento;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public boolean isBoCoincide2() {
		return this.boCoincide2;
	}

	public void setBoCoincide2(boolean boCoincide2) {
		this.boCoincide2 = boCoincide2;
	}

	public boolean isBoCoincide3() {
		return this.boCoincide3;
	}

	public void setBoCoincide3(boolean boCoincide3) {
		this.boCoincide3 = boCoincide3;
	}

	public boolean isBoCoincide3usu2doc() {
		return this.boCoincide3usu2doc;
	}

	public void setBoCoincide3usu2doc(boolean boCoincide3usu2doc) {
		this.boCoincide3usu2doc = boCoincide3usu2doc;
	}

	public String getModo() {
		return this.modo;
	}

	public void setModo(String modo) {
		this.modo = modo;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
