package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * CodterrUniadmDTOId generated by hbm2java
 */
public class CodterrUniadmDTOId implements java.io.Serializable {

	private String coCodigoTerritorial;
	private String coUnidadAdministrativa;

	public CodterrUniadmDTOId() {
	}

	public CodterrUniadmDTOId(String coCodigoTerritorial,
			String coUnidadAdministrativa) {
		this.coCodigoTerritorial = coCodigoTerritorial;
		this.coUnidadAdministrativa = coUnidadAdministrativa;
	}

	public String getCoCodigoTerritorial() {
		return this.coCodigoTerritorial;
	}

	public void setCoCodigoTerritorial(String coCodigoTerritorial) {
		this.coCodigoTerritorial = coCodigoTerritorial;
	}

	public String getCoUnidadAdministrativa() {
		return this.coUnidadAdministrativa;
	}

	public void setCoUnidadAdministrativa(String coUnidadAdministrativa) {
		this.coUnidadAdministrativa = coUnidadAdministrativa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CodterrUniadmDTOId))
			return false;
		CodterrUniadmDTOId castOther = (CodterrUniadmDTOId) other;

		return ((this.getCoCodigoTerritorial() == castOther
				.getCoCodigoTerritorial()) || (this.getCoCodigoTerritorial() != null
				&& castOther.getCoCodigoTerritorial() != null && this
				.getCoCodigoTerritorial().equals(
						castOther.getCoCodigoTerritorial())))
				&& ((this.getCoUnidadAdministrativa() == castOther
						.getCoUnidadAdministrativa()) || (this
						.getCoUnidadAdministrativa() != null
						&& castOther.getCoUnidadAdministrativa() != null && this
						.getCoUnidadAdministrativa().equals(
								castOther.getCoUnidadAdministrativa())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCoCodigoTerritorial() == null ? 0 : this
						.getCoCodigoTerritorial().hashCode());
		result = 37
				* result
				+ (getCoUnidadAdministrativa() == null ? 0 : this
						.getCoUnidadAdministrativa().hashCode());
		return result;
	}

}
