package es.dipucadiz.etir.comun.dto;

import java.util.Date;

// Generated 11-mar-2011 9:08:07 by Hibernate Tools 3.2.4.GA


/**
 * CompensacionDocumentoDTO generated by hbm2java
 */
public class CompensacionDocumentoDTO  implements java.io.Serializable {

	private CompensacionDocumentoDTOId id;
	private CompensacionDTO compensacionDTO;
	private DocumentoDTO documentoDTO;
	private Date fhActualizacion;
    private String coUsuarioActualizacion;
    private String rowid;

    public CompensacionDocumentoDTO() {
    }

    public CompensacionDocumentoDTO(CompensacionDocumentoDTOId id, CompensacionDTO compensacionDTO, DocumentoDTO documentoDTO, Date fhActualizacion, String coUsuarioActualizacion) {
       this.id = id;
       this.compensacionDTO = compensacionDTO;
       this.documentoDTO = documentoDTO;
       this.fhActualizacion = fhActualizacion;
       this.coUsuarioActualizacion = coUsuarioActualizacion;      
    }

	public CompensacionDocumentoDTOId getId() {
		return id;
	}

	public void setId(CompensacionDocumentoDTOId id) {
		this.id = id;
	}

	public CompensacionDTO getCompensacionDTO() {
		return compensacionDTO;
	}

	public void setCompensacionDTO(CompensacionDTO compensacionDTO) {
		this.compensacionDTO = compensacionDTO;
	}

	public DocumentoDTO getDocumentoDTO() {
		return documentoDTO;
	}

	public void setDocumentoDTO(DocumentoDTO documentoDTO) {
		this.documentoDTO = documentoDTO;
	}

	public Date getFhActualizacion() {
		return fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	
    


}