package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * DatosDTO generated by hbm2java
 */
public class CondEmbargoAeatDTO implements java.io.Serializable {
	private static final long serialVersionUID = -7321968357782601700L;
	
	private Long coCondEmbargoAeat;
	private Date fxVigenciaIni;
	private Date fxVigenciaFin;
	private BigDecimal imMinTipo1;
	private BigDecimal imMinTipo2;
	private BigDecimal imMinTipo3;
	private BigDecimal imMax;
	private BigDecimal maxRegistros;
	private DiputacionCuentaDTO diputacionCuentaDTO;
	private Short diaDesdeEnvio;
	private Short diaHastaEnvio;
	private Short diaDesdeTratamiento;
	private Short diaHastaTratamiento;
	private String nombrePersonaRelacionada;
	private BigDecimal telefonoContacto;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private String rowid;

	public CondEmbargoAeatDTO() {
	}

	
	public Long getCoCondEmbargoAeat() {
		return coCondEmbargoAeat;
	}

	public void setCoCondEmbargoAeat(Long coCondEmbargoAeat) {
		this.coCondEmbargoAeat = coCondEmbargoAeat;
	}

	public Date getFxVigenciaIni() {
		return fxVigenciaIni;
	}

	public void setFxVigenciaIni(Date fxVigenciaIni) {
		this.fxVigenciaIni = fxVigenciaIni;
	}

	public Date getFxVigenciaFin() {
		return fxVigenciaFin;
	}

	public void setFxVigenciaFin(Date fxVigenciaFin) {
		this.fxVigenciaFin = fxVigenciaFin;
	}

	public BigDecimal getImMinTipo1() {
		return imMinTipo1;
	}

	public void setImMinTipo1(BigDecimal imMinTipo1) {
		this.imMinTipo1 = imMinTipo1;
	}

	public BigDecimal getImMinTipo2() {
		return imMinTipo2;
	}

	public void setImMinTipo2(BigDecimal imMinTipo2) {
		this.imMinTipo2 = imMinTipo2;
	}

	public BigDecimal getImMinTipo3() {
		return imMinTipo3;
	}

	public void setImMinTipo3(BigDecimal imMinTipo3) {
		this.imMinTipo3 = imMinTipo3;
	}

	public BigDecimal getImMax() {
		return imMax;
	}

	public void setImMax(BigDecimal imMax) {
		this.imMax = imMax;
	}

	public BigDecimal getMaxRegistros() {
		return maxRegistros;
	}

	public void setMaxRegistros(BigDecimal maxRegistros) {
		this.maxRegistros = maxRegistros;
	}

	public DiputacionCuentaDTO getDiputacionCuentaDTO() {
		return diputacionCuentaDTO;
	}

	public void setDiputacionCuentaDTO(DiputacionCuentaDTO diputacionCuentaDTO) {
		this.diputacionCuentaDTO = diputacionCuentaDTO;
	}

	public Short getDiaDesdeEnvio() {
		return diaDesdeEnvio;
	}

	public void setDiaDesdeEnvio(Short diaDesdeEnvio) {
		this.diaDesdeEnvio = diaDesdeEnvio;
	}

	public Short getDiaHastaEnvio() {
		return diaHastaEnvio;
	}

	public void setDiaHastaEnvio(Short diaHastaEnvio) {
		this.diaHastaEnvio = diaHastaEnvio;
	}

	public Short getDiaDesdeTratamiento() {
		return diaDesdeTratamiento;
	}

	public void setDiaDesdeTratamiento(Short diaDesdeTratamiento) {
		this.diaDesdeTratamiento = diaDesdeTratamiento;
	}

	public Short getDiaHastaTratamiento() {
		return diaHastaTratamiento;
	}

	public void setDiaHastaTratamiento(Short diaHastaTratamiento) {
		this.diaHastaTratamiento = diaHastaTratamiento;
	}

	public String getNombrePersonaRelacionada() {
		return nombrePersonaRelacionada;
	}

	public void setNombrePersonaRelacionada(String nombrePersonaRelacionada) {
		this.nombrePersonaRelacionada = nombrePersonaRelacionada;
	}

	public BigDecimal getTelefonoContacto() {
		return telefonoContacto;
	}

	public void setTelefonoContacto(BigDecimal telefonoContacto) {
		this.telefonoContacto = telefonoContacto;
	}

	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = rowid;
	}


} 
