package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * DatosDTO generated by hbm2java
 */
public class CondEmbargoC63DTO implements java.io.Serializable {
	private static final long serialVersionUID = 6820699138329585799L;

	private Long coCondEmbargoC63;
	private String coFase;
	private Date fxVigenciaIni;
	private Date fxVigenciaFin;
	private BigDecimal maxRegistros;
	private Boolean boProvidenciado;
	private Boolean boNotificado;
	private Short minMesesVigencia;
	private Short nuMesesReenvio;
	private CircuitoDTO circuitoAsociadoDTO;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private String rowid;
	
	public CondEmbargoC63DTO() {
	}

	public Long getCoCondEmbargoC63() {
		return coCondEmbargoC63;
	}

	public void setCoCondEmbargoC63(Long coCondEmbargoC63) {
		this.coCondEmbargoC63 = coCondEmbargoC63;
	}

	public String getCoFase() {
		return coFase;
	}

	public void setCoFase(String coFase) {
		this.coFase = coFase;
	}

	public Date getFxVigenciaIni() {
		return fxVigenciaIni;
	}

	public void setFxVigenciaIni(Date fxVigenciaIni) {
		this.fxVigenciaIni = fxVigenciaIni;
	}

	public Date getFxVigenciaFin() {
		return fxVigenciaFin;
	}

	public void setFxVigenciaFin(Date fxVigenciaFin) {
		this.fxVigenciaFin = fxVigenciaFin;
	}

	public BigDecimal getMaxRegistros() {
		return maxRegistros;
	}

	public void setMaxRegistros(BigDecimal maxRegistros) {
		this.maxRegistros = maxRegistros;
	}

	public Boolean getBoProvidenciado() {
		return boProvidenciado;
	}

	public void setBoProvidenciado(Boolean boProvidenciado) {
		this.boProvidenciado = boProvidenciado;
	}

	public Boolean getBoNotificado() {
		return boNotificado;
	}

	public void setBoNotificado(Boolean boNotificado) {
		this.boNotificado = boNotificado;
	}

	public Short getMinMesesVigencia() {
		return minMesesVigencia;
	}

	public void setMinMesesVigencia(Short minMesesVigencia) {
		this.minMesesVigencia = minMesesVigencia;
	}

	public Short getNuMesesReenvio() {
		return nuMesesReenvio;
	}

	public void setNuMesesReenvio(Short nuMesesReenvio) {
		this.nuMesesReenvio = nuMesesReenvio;
	}

	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	public CircuitoDTO getCircuitoAsociadoDTO() {
		return circuitoAsociadoDTO;
	}

	public void setCircuitoAsociadoDTO(CircuitoDTO circuitoAsociadoDTO) {
		this.circuitoAsociadoDTO = circuitoAsociadoDTO;
	}

	


} 
