package es.dipucadiz.etir.comun.dto;

// Generated 22-mar-2013 13:49:06 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * ContadorRefObjDTO generated by hbm2java
 */
public class ContadorRefObjDTO implements java.io.Serializable {
	private static final long serialVersionUID = 576123455450227800L;
	
	private Long coContadorRefObj;
	private MunicipioDTO municipioDTO;
	private ConceptoDTO conceptoDTO;
	private ModeloDTO modeloDTO;
	private Short ejercicio;
	private String prefijo;
	private long contador;
	private Byte longitud;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;

	public ContadorRefObjDTO() {
	}

	public ContadorRefObjDTO(long contador) {
		this.contador = contador;
	}

	public ContadorRefObjDTO(MunicipioDTO municipioDTO,
			ConceptoDTO conceptoDTO, ModeloDTO modeloDTO, Short ejercicio,
			String prefijo, long contador, Byte longitud,
			Date fhActualizacion, String coUsuarioActualizacion) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.modeloDTO = modeloDTO;
		this.ejercicio = ejercicio;
		this.prefijo = prefijo;
		this.contador = contador;
		this.longitud = longitud;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Long getCoContadorRefObj() {
		return this.coContadorRefObj;
	}

	public void setCoContadorRefObj(Long coContadorRefObj) {
		this.coContadorRefObj = coContadorRefObj;
	}

	public Short getEjercicio() {
		return this.ejercicio;
	}

	public void setEjercicio(Short ejercicio) {
		this.ejercicio = ejercicio;
	}

	public String getPrefijo() {
		return this.prefijo;
	}

	public void setPrefijo(String prefijo) {
		this.prefijo = prefijo;
	}

	public long getContador() {
		return this.contador;
	}

	public void setContador(long contador) {
		this.contador = contador;
	}

	public Byte getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Byte longitud) {
		this.longitud = longitud;
	}

	public Serializable getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public MunicipioDTO getMunicipioDTO() {
		return municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public ConceptoDTO getConceptoDTO() {
		return conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public ModeloDTO getModeloDTO() {
		return modeloDTO;
	}

	public void setModeloDTO(ModeloDTO modeloDTO) {
		this.modeloDTO = modeloDTO;
	}

}
