package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * ContadorDTOId generated by hbm2java
 */
public class ContadorDTOId implements java.io.Serializable {

	private String tipo;
	private String coProvincia;
	private String coMunicipio;
	private short ejercicio;

	public ContadorDTOId() {
	}

	public ContadorDTOId(String tipo, String coProvincia, String coMunicipio,
			short ejercicio) {
		this.tipo = tipo;
		this.coProvincia = coProvincia;
		this.coMunicipio = coMunicipio;
		this.ejercicio = ejercicio;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getCoProvincia() {
		return this.coProvincia;
	}

	public void setCoProvincia(String coProvincia) {
		this.coProvincia = coProvincia;
	}

	public String getCoMunicipio() {
		return this.coMunicipio;
	}

	public void setCoMunicipio(String coMunicipio) {
		this.coMunicipio = coMunicipio;
	}

	public short getEjercicio() {
		return this.ejercicio;
	}

	public void setEjercicio(short ejercicio) {
		this.ejercicio = ejercicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContadorDTOId))
			return false;
		ContadorDTOId castOther = (ContadorDTOId) other;

		return ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null
				&& castOther.getTipo() != null && this.getTipo().equals(
				castOther.getTipo())))
				&& ((this.getCoProvincia() == castOther.getCoProvincia()) || (this
						.getCoProvincia() != null
						&& castOther.getCoProvincia() != null && this
						.getCoProvincia().equals(castOther.getCoProvincia())))
				&& ((this.getCoMunicipio() == castOther.getCoMunicipio()) || (this
						.getCoMunicipio() != null
						&& castOther.getCoMunicipio() != null && this
						.getCoMunicipio().equals(castOther.getCoMunicipio())))
				&& (this.getEjercicio() == castOther.getEjercicio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37
				* result
				+ (getCoProvincia() == null ? 0 : this.getCoProvincia()
						.hashCode());
		result = 37
				* result
				+ (getCoMunicipio() == null ? 0 : this.getCoMunicipio()
						.hashCode());
		result = 37 * result + this.getEjercicio();
		return result;
	}

}
