package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ConveniosConceptoDTO generated by hbm2java
 */
public class ConveniosConceptoDTO implements java.io.Serializable {

	private ConveniosConceptoDTOId id;
	private ConveniosDTO conveniosDTO;
	private ConceptoDTO conceptoDTO;
	private OtrDTO otrDTO;
	private boolean boExclusionPpp;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private BigDecimal porcIncrementoPpp;
	private Set<ConveniosModeloDTO> conveniosModeloDTOs = new HashSet<ConveniosModeloDTO>(
			0);
	
	private String rowid;

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public ConveniosConceptoDTO() {
	}

	public ConveniosConceptoDTO(ConveniosConceptoDTOId id,
			ConveniosDTO conveniosDTO, ConceptoDTO conceptoDTO,
			boolean boExclusionPpp) {
		this.id = id;
		this.conveniosDTO = conveniosDTO;
		this.conceptoDTO = conceptoDTO;
		this.boExclusionPpp = boExclusionPpp;
	}

	public ConveniosConceptoDTO(ConveniosConceptoDTOId id,
			ConveniosDTO conveniosDTO, ConceptoDTO conceptoDTO, OtrDTO otrDTO,
			boolean boExclusionPpp, String coUsuarioActualizacion,
			Date fhActualizacion, Set<ConveniosModeloDTO> conveniosModeloDTOs) {
		this.id = id;
		this.conveniosDTO = conveniosDTO;
		this.conceptoDTO = conceptoDTO;
		this.otrDTO = otrDTO;
		this.boExclusionPpp = boExclusionPpp;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.conveniosModeloDTOs = conveniosModeloDTOs;
	}

	public ConveniosConceptoDTOId getId() {
		return this.id;
	}

	public void setId(ConveniosConceptoDTOId id) {
		this.id = id;
	}

	public ConveniosDTO getConveniosDTO() {
		return this.conveniosDTO;
	}

	public void setConveniosDTO(ConveniosDTO conveniosDTO) {
		this.conveniosDTO = conveniosDTO;
	}

	public ConceptoDTO getConceptoDTO() {
		return this.conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public OtrDTO getOtrDTO() {
		return this.otrDTO;
	}

	public void setOtrDTO(OtrDTO otrDTO) {
		this.otrDTO = otrDTO;
	}

	public boolean isBoExclusionPpp() {
		return this.boExclusionPpp;
	}

	public void setBoExclusionPpp(boolean boExclusionPpp) {
		this.boExclusionPpp = boExclusionPpp;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public BigDecimal getPorcIncrementoPpp() {
		return this.porcIncrementoPpp;
	}

	public void setPorcIncrementoPpp(BigDecimal porcIncrementoPpp) {
		this.porcIncrementoPpp = porcIncrementoPpp;
	}

	public Set<ConveniosModeloDTO> getConveniosModeloDTOs() {
		return this.conveniosModeloDTOs;
	}

	public void setConveniosModeloDTOs(
			Set<ConveniosModeloDTO> conveniosModeloDTOs) {
		this.conveniosModeloDTOs = conveniosModeloDTOs;
	}

}
