package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CorrespondenciaArgumentoDTO generated by hbm2java
 */
public class CorrespondenciaArgumentoDTO implements java.io.Serializable {

	private CorrespondenciaArgumentoDTOId id;
	private FuncionArgumentoDTO funcionArgumentoDTO;
	private CorrespondenciaDTO correspondenciaDTO;
	private String tipo;
	private String valor;
	private Short posDesde;
	private Short posHasta;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public CorrespondenciaArgumentoDTO() {
	}

	public CorrespondenciaArgumentoDTO(CorrespondenciaArgumentoDTOId id,
			FuncionArgumentoDTO funcionArgumentoDTO,
			CorrespondenciaDTO correspondenciaDTO) {
		this.id = id;
		this.funcionArgumentoDTO = funcionArgumentoDTO;
		this.correspondenciaDTO = correspondenciaDTO;
	}

	public CorrespondenciaArgumentoDTO(CorrespondenciaArgumentoDTOId id,
			FuncionArgumentoDTO funcionArgumentoDTO,
			CorrespondenciaDTO correspondenciaDTO, String tipo, String valor,
			Short posDesde, Short posHasta, Date fhActualizacion,
			String coUsuarioActualizacion) {
		this.id = id;
		this.funcionArgumentoDTO = funcionArgumentoDTO;
		this.correspondenciaDTO = correspondenciaDTO;
		this.tipo = tipo;
		this.valor = valor;
		this.posDesde = posDesde;
		this.posHasta = posHasta;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public CorrespondenciaArgumentoDTOId getId() {
		return this.id;
	}

	public void setId(CorrespondenciaArgumentoDTOId id) {
		this.id = id;
	}

	public FuncionArgumentoDTO getFuncionArgumentoDTO() {
		return this.funcionArgumentoDTO;
	}

	public void setFuncionArgumentoDTO(FuncionArgumentoDTO funcionArgumentoDTO) {
		this.funcionArgumentoDTO = funcionArgumentoDTO;
	}

	public CorrespondenciaDTO getCorrespondenciaDTO() {
		return this.correspondenciaDTO;
	}

	public void setCorrespondenciaDTO(CorrespondenciaDTO correspondenciaDTO) {
		this.correspondenciaDTO = correspondenciaDTO;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public Short getPosDesde() {
		return this.posDesde;
	}

	public void setPosDesde(Short posDesde) {
		this.posDesde = posDesde;
	}

	public Short getPosHasta() {
		return this.posHasta;
	}

	public void setPosHasta(Short posHasta) {
		this.posHasta = posHasta;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
