package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CorrespondenciaDTO generated by hbm2java
 */
public class CorrespondenciaDTO implements java.io.Serializable {

	private Long coCorrespondencia;
	private MunicipioDTO municipioDTO;
	private ConceptoDTO conceptoDTO;
	private FuncionDTO funcionDTO;
	private ModeloVersionDTO modeloVersionDTO;
	private short orden;
	private String descripcion;
	private Boolean boActiva;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<CorrespondenciaArgumentoDTO> correspondenciaArgumentoDTOs = new HashSet<CorrespondenciaArgumentoDTO>(
			0);
	private String rowid;

	public CorrespondenciaDTO() {
	}

	public CorrespondenciaDTO(MunicipioDTO municipioDTO,
			ConceptoDTO conceptoDTO, FuncionDTO funcionDTO,
			ModeloVersionDTO modeloVersionDTO, short orden) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.funcionDTO = funcionDTO;
		this.modeloVersionDTO = modeloVersionDTO;
		this.orden = orden;
	}

	public CorrespondenciaDTO(MunicipioDTO municipioDTO,
			ConceptoDTO conceptoDTO, FuncionDTO funcionDTO,
			ModeloVersionDTO modeloVersionDTO, short orden, String descripcion,
			Boolean boActiva, Date fhActualizacion,
			String coUsuarioActualizacion,
			Set<CorrespondenciaArgumentoDTO> correspondenciaArgumentoDTOs) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.funcionDTO = funcionDTO;
		this.modeloVersionDTO = modeloVersionDTO;
		this.orden = orden;
		this.descripcion = descripcion;
		this.boActiva = boActiva;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.correspondenciaArgumentoDTOs = correspondenciaArgumentoDTOs;
	}

	public Long getCoCorrespondencia() {
		return this.coCorrespondencia;
	}

	public void setCoCorrespondencia(Long coCorrespondencia) {
		this.coCorrespondencia = coCorrespondencia;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public ConceptoDTO getConceptoDTO() {
		return this.conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public FuncionDTO getFuncionDTO() {
		return this.funcionDTO;
	}

	public void setFuncionDTO(FuncionDTO funcionDTO) {
		this.funcionDTO = funcionDTO;
	}

	public ModeloVersionDTO getModeloVersionDTO() {
		return this.modeloVersionDTO;
	}

	public void setModeloVersionDTO(ModeloVersionDTO modeloVersionDTO) {
		this.modeloVersionDTO = modeloVersionDTO;
	}

	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getBoActiva() {
		return this.boActiva;
	}

	public void setBoActiva(Boolean boActiva) {
		this.boActiva = boActiva;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<CorrespondenciaArgumentoDTO> getCorrespondenciaArgumentoDTOs() {
		return this.correspondenciaArgumentoDTOs;
	}

	public void setCorrespondenciaArgumentoDTOs(
			Set<CorrespondenciaArgumentoDTO> correspondenciaArgumentoDTOs) {
		this.correspondenciaArgumentoDTOs = correspondenciaArgumentoDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
