package es.dipucadiz.etir.comun.dto;

// Generated 09-mar-2010 14:09:36 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CruceGrupoDTO generated by hbm2java
 */
public class CruceGrupoDTO implements java.io.Serializable {

	private Long coCruceGrupo;
	private CodigoTerritorialDTO codigoTerritorialDTO;
	private MunicipioDTO municipioDTO;
	private UnidadAdministrativaDTO unidadAdministrativaDTO;
	private String nombre;
	private String descripcion;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<CruceDTO> cruceDTOs = new HashSet<CruceDTO>(0);
	private String rowid;

	public CruceGrupoDTO() {
	}

	public CruceGrupoDTO(MunicipioDTO municipioDTO, String nombre) {
		this.municipioDTO = municipioDTO;
		this.nombre = nombre;
	}

	public CruceGrupoDTO(CodigoTerritorialDTO codigoTerritorialDTO,
			MunicipioDTO municipioDTO,
			UnidadAdministrativaDTO unidadAdministrativaDTO, String nombre,
			String descripcion, Date fhActualizacion,
			String coUsuarioActualizacion, Set<CruceDTO> cruceDTOs) {
		this.codigoTerritorialDTO = codigoTerritorialDTO;
		this.municipioDTO = municipioDTO;
		this.unidadAdministrativaDTO = unidadAdministrativaDTO;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.cruceDTOs = cruceDTOs;
	}

	public Long getCoCruceGrupo() {
		return this.coCruceGrupo;
	}

	public void setCoCruceGrupo(Long coCruceGrupo) {
		this.coCruceGrupo = coCruceGrupo;
	}

	public CodigoTerritorialDTO getCodigoTerritorialDTO() {
		return this.codigoTerritorialDTO;
	}

	public void setCodigoTerritorialDTO(
			CodigoTerritorialDTO codigoTerritorialDTO) {
		this.codigoTerritorialDTO = codigoTerritorialDTO;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public UnidadAdministrativaDTO getUnidadAdministrativaDTO() {
		return this.unidadAdministrativaDTO;
	}

	public void setUnidadAdministrativaDTO(
			UnidadAdministrativaDTO unidadAdministrativaDTO) {
		this.unidadAdministrativaDTO = unidadAdministrativaDTO;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<CruceDTO> getCruceDTOs() {
		return this.cruceDTOs;
	}

	public void setCruceDTOs(Set<CruceDTO> cruceDTOs) {
		this.cruceDTOs = cruceDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
