package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CruceCondicionDTO generated by hbm2java
 */
public class CruceCondicionDTO implements java.io.Serializable {
	private static final long serialVersionUID = 7302523449243463059L;
	
	private CruceCondicionDTOId id;
	private CruceDTO cruceDTO;
	private String tipoOrigen;
	private String valorOrigen;
	private String tipoCruce;
	private String valorCruce;
	private String conector;
	private String operador;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String valorAdicionalOrigen;
	private String valorAdicionalCruce;
	private boolean boOrigenIzquierda;
	private String rowid;

	public CruceCondicionDTO() {
	}

	public CruceCondicionDTO(CruceCondicionDTOId id, CruceDTO cruceDTO) {
		this.id = id;
		this.cruceDTO = cruceDTO;
	}

	public CruceCondicionDTO(CruceCondicionDTOId id, CruceDTO cruceDTO,
			String tipoOrigen, String valorOrigen, String tipoCruce,
			String valorCruce, String conector, String operador,
			Date fhActualizacion, String coUsuarioActualizacion,
			String valorAdicionalOrigen, String valorAdicionalCruce) {
		this.id = id;
		this.cruceDTO = cruceDTO;
		this.tipoOrigen = tipoOrigen;
		this.valorOrigen = valorOrigen;
		this.tipoCruce = tipoCruce;
		this.valorCruce = valorCruce;
		this.conector = conector;
		this.operador = operador;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.valorAdicionalOrigen = valorAdicionalOrigen;
		this.valorAdicionalCruce = valorAdicionalCruce;
	}

	public CruceCondicionDTOId getId() {
		return this.id;
	}

	public void setId(CruceCondicionDTOId id) {
		this.id = id;
	}

	public CruceDTO getCruceDTO() {
		return this.cruceDTO;
	}

	public void setCruceDTO(CruceDTO cruceDTO) {
		this.cruceDTO = cruceDTO;
	}

	public String getTipoOrigen() {
		return this.tipoOrigen;
	}

	public void setTipoOrigen(String tipoOrigen) {
		this.tipoOrigen = tipoOrigen;
	}

	public String getValorOrigen() {
		return this.valorOrigen;
	}

	public void setValorOrigen(String valorOrigen) {
		this.valorOrigen = valorOrigen;
	}

	public String getTipoCruce() {
		return this.tipoCruce;
	}

	public void setTipoCruce(String tipoCruce) {
		this.tipoCruce = tipoCruce;
	}

	public String getValorCruce() {
		return this.valorCruce;
	}

	public void setValorCruce(String valorCruce) {
		this.valorCruce = valorCruce;
	}

	public String getConector() {
		return this.conector;
	}

	public void setConector(String conector) {
		this.conector = conector;
	}

	public String getOperador() {
		return this.operador;
	}

	public void setOperador(String operador) {
		this.operador = operador;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getValorAdicionalOrigen() {
		return this.valorAdicionalOrigen;
	}

	public void setValorAdicionalOrigen(String valorAdicionalOrigen) {
		this.valorAdicionalOrigen = valorAdicionalOrigen;
	}

	public String getValorAdicionalCruce() {
		return this.valorAdicionalCruce;
	}

	public void setValorAdicionalCruce(String valorAdicionalCruce) {
		this.valorAdicionalCruce = valorAdicionalCruce;
	}
	
	public boolean isBoOrigenIzquierda() {
		return boOrigenIzquierda;
	}

	public void setBoOrigenIzquierda(boolean boOrigenIzquierda) {
		this.boOrigenIzquierda = boOrigenIzquierda;
	}

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public boolean equals(Object obj) {
		if (obj instanceof CruceCondicionDTO){
			CruceCondicionDTO otroDTO = (CruceCondicionDTO) obj;
			return (
					Utilidades.nvl(this.getConector(),"").equals(Utilidades.nvl(otroDTO.getConector(),"")) &&
					this.getId().getCoArgumento() == otroDTO.getId().getCoArgumento() &&
					this.getId().getCoCondicion() == otroDTO.getId().getCoCondicion() &&
					this.getId().getCoCruceGrupo() == otroDTO.getId().getCoCruceGrupo() &&
					Utilidades.nvl(this.getOperador(),"").equals(Utilidades.nvl(otroDTO.getOperador(),"")) &&
					Utilidades.nvl(this.getTipoCruce(),"").equals(Utilidades.nvl(otroDTO.getTipoCruce(),"")) &&
					Utilidades.nvl(this.getTipoOrigen(),"").equals(Utilidades.nvl(otroDTO.getTipoOrigen(),"")) &&
					Utilidades.nvl(this.getValorAdicionalCruce(),"").equals(Utilidades.nvl(otroDTO.getValorAdicionalCruce(),"")) &&
					Utilidades.nvl(this.getValorAdicionalOrigen(),"").equals(Utilidades.nvl(otroDTO.getValorAdicionalOrigen(),"")) &&
					Utilidades.nvl(this.getValorCruce(),"").equals(Utilidades.nvl(otroDTO.getValorCruce(),"")) &&
					Utilidades.nvl(this.getValorOrigen(),"").equals(Utilidades.nvl(otroDTO.getValorOrigen(),"")) &&
					this.boOrigenIzquierda == otroDTO.boOrigenIzquierda
			);
		}else{
			return super.equals(obj);
		}
	}
	public int hashCode() {
		assert false : "hashCode not designed";
		return 42; // any arbitrary constant will do
	}

}
