package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CruceResultadoDTO generated by hbm2java
 */
public class CruceResultadoDTO implements java.io.Serializable {

	private CruceResultadoDTOId id;
	private CruceDTO cruceDTO;
	private String nombre;
	private String descripcion;
	private String tipo;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<CruceResultadoCampoDTO> cruceResultadoCampoDTOs = new HashSet<CruceResultadoCampoDTO>(
			0);
	private String rowid;

	public CruceResultadoDTO() {
	}

	public CruceResultadoDTO(CruceResultadoDTOId id, CruceDTO cruceDTO) {
		this.id = id;
		this.cruceDTO = cruceDTO;
	}

	public CruceResultadoDTO(CruceResultadoDTOId id, CruceDTO cruceDTO,
			String nombre, String descripcion, String tipo,
			Date fhActualizacion, String coUsuarioActualizacion,
			Set<CruceResultadoCampoDTO> cruceResultadoCampoDTOs) {
		this.id = id;
		this.cruceDTO = cruceDTO;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.cruceResultadoCampoDTOs = cruceResultadoCampoDTOs;
	}

	public CruceResultadoDTOId getId() {
		return this.id;
	}

	public void setId(CruceResultadoDTOId id) {
		this.id = id;
	}

	public CruceDTO getCruceDTO() {
		return this.cruceDTO;
	}

	public void setCruceDTO(CruceDTO cruceDTO) {
		this.cruceDTO = cruceDTO;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<CruceResultadoCampoDTO> getCruceResultadoCampoDTOs() {
		return this.cruceResultadoCampoDTOs;
	}

	public void setCruceResultadoCampoDTOs(
			Set<CruceResultadoCampoDTO> cruceResultadoCampoDTOs) {
		this.cruceResultadoCampoDTOs = cruceResultadoCampoDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
