package es.dipucadiz.etir.comun.dto;

// Generated 04-nov-2010 8:41:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * CuentaDTO generated by hbm2java
 */
public class CuentaDTO implements java.io.Serializable {

	private CuentaDTOId id;
	private BancoSucursalDTO bancoSucursalDTO;
	private String coModelo;
	private String coVersion;
	private String coDocumento;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private Set<ClienteCuentaDTO> clienteCuentaDTOs = new HashSet<ClienteCuentaDTO>(0);
	private String rowid;
	private String prefijoIBAN;
	private String sufijoExtranjero;
	public CuentaDTO() {
	}

	public CuentaDTO(CuentaDTOId id, BancoSucursalDTO bancoSucursalDTO) {
		this.id = id;
		this.bancoSucursalDTO = bancoSucursalDTO;
	}

	public CuentaDTO(CuentaDTOId id, BancoSucursalDTO bancoSucursalDTO,
			String coModelo, String coVersion, String coDocumento,
			String coUsuarioActualizacion, Date fhActualizacion,
			Set<ClienteCuentaDTO> clienteCuentaDTOs) {
		this.id = id;
		this.bancoSucursalDTO = bancoSucursalDTO;
		this.coModelo = coModelo;
		this.coVersion = coVersion;
		this.coDocumento = coDocumento;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.clienteCuentaDTOs = clienteCuentaDTOs;
	}

	public CuentaDTOId getId() {
		return this.id;
	}

	public void setId(CuentaDTOId id) {
		this.id = id;
	}

	public BancoSucursalDTO getBancoSucursalDTO() {
		return this.bancoSucursalDTO;
	}

	public void setBancoSucursalDTO(BancoSucursalDTO bancoSucursalDTO) {
		this.bancoSucursalDTO = bancoSucursalDTO;
	}

	public String getCoModelo() {
		return this.coModelo;
	}

	public void setCoModelo(String coModelo) {
		this.coModelo = coModelo;
	}

	public String getCoVersion() {
		return this.coVersion;
	}

	public void setCoVersion(String coVersion) {
		this.coVersion = coVersion;
	}

	public String getCoDocumento() {
		return this.coDocumento;
	}

	public void setCoDocumento(String coDocumento) {
		this.coDocumento = coDocumento;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public Set<ClienteCuentaDTO> getClienteCuentaDTOs() {
		return this.clienteCuentaDTOs;
	}

	public void setClienteCuentaDTOs(Set<ClienteCuentaDTO> clienteCuentaDTOs) {
		this.clienteCuentaDTOs = clienteCuentaDTOs;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}
	
	public String getNumeroCompleto() {
		return this.id.getCoBanco() + " " + this.id.getCoBancoSucursal() + " " + this.id.getDc() + " " + this.id.getCuenta();
	}

	public String getPrefijoIBAN() {
		if(prefijoIBAN==null)
			return "0000";
		else
		return prefijoIBAN;
	}

	public void setPrefijoIBAN(String prefijoIBAN) {
		this.prefijoIBAN = prefijoIBAN;
	}

	public String getSufijoExtranjero() {
		return sufijoExtranjero;
	}

	public void setSufijoExtranjero(String sufijoExtranjero) {
		this.sufijoExtranjero = sufijoExtranjero;
	}


	public String getIBANNumeroCompletoFormatoPantalla(){
		
 	String cabeceraDatosCuenta = "";
 	String datosCuenta= "";
 	
//		if(getPrefijoIBAN()!=null){ 
//			cabeceraDatosCuenta=cabeceraDatosCuenta+getPrefijoIBAN()+ " ";		
//		}else{
//			cabeceraDatosCuenta=cabeceraDatosCuenta+"0000"+ " ";		
//		}
//		String 	datosCuenta = getId().getCoBanco() + getId().getCoBancoSucursal() +  getId().getDc() +  getId().getCuenta(); 
//
//		return cabeceraDatosCuenta=cabeceraDatosCuenta+datosCuenta.substring(0, 4)+" "+datosCuenta.substring(4, 8)+" "+datosCuenta.substring(8, 12)+" "+datosCuenta.substring(12, 16)+" "+datosCuenta.substring(16, 20);	

	if(getPrefijoIBAN()==null || "".equals(getPrefijoIBAN())){
		prefijoIBAN="0000";
	}else{
	prefijoIBAN =  getPrefijoIBAN();
	}
		cabeceraDatosCuenta = prefijoIBAN+ " ";
		
		datosCuenta =  getId().getCoBanco() +  getId().getCoBancoSucursal() +   getId().getDc() +   getId().getCuenta(); 
	 
		return cabeceraDatosCuenta=cabeceraDatosCuenta+datosCuenta.substring(0, 4)+" "+datosCuenta.substring(4, 8)+" "+datosCuenta.substring(8, 12)+" "+datosCuenta.substring(12, 16)+" "+datosCuenta.substring(16, 20);

	}
	
	//Develve el numero de cuenta sin el prefijo si esta a null o vacio
	public String getIBANNumeroCompleto(){
		if(getPrefijoIBAN() != null || "".equals(getPrefijoIBAN()))
			return getPrefijoIBAN() + " " + getNumeroCompleto();
		else
			return getNumeroCompleto();
	}
}
