package es.dipucadiz.etir.comun.dto;

// Generated 10-may-2012 8:24:35 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * DecretoFirmaDTO generated by hbm2java
 */
public class DecretoFirmaDTO implements java.io.Serializable {

	private DecretoFirmaDTOId id;
	private DecretoDTO decretoDTO;
	private String nif;
	private String nombre;
	private String cargo;
	private String coUsuarioActualizacion;
	private Serializable fhActualizacion;

	public DecretoFirmaDTO() {
	}

	public DecretoFirmaDTO(DecretoFirmaDTOId id, DecretoDTO decretoDTO) {
		this.id = id;
		this.decretoDTO = decretoDTO;
	}

	public DecretoFirmaDTO(DecretoFirmaDTOId id, DecretoDTO decretoDTO,
			String nif, String nombre, String cargo,
			String coUsuarioActualizacion, Serializable fhActualizacion) {
		this.id = id;
		this.decretoDTO = decretoDTO;
		this.nif = nif;
		this.nombre = nombre;
		this.cargo = cargo;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
	}

	public DecretoFirmaDTOId getId() {
		return this.id;
	}

	public void setId(DecretoFirmaDTOId id) {
		this.id = id;
	}

	public DecretoDTO getDecretoDTO() {
		return this.decretoDTO;
	}

	public void setDecretoDTO(DecretoDTO decretoDTO) {
		this.decretoDTO = decretoDTO;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Serializable getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Serializable fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

}
