package es.dipucadiz.etir.comun.dto;

// Generated 10-may-2012 8:24:35 by Hibernate Tools 3.4.0.CR1

/**
 * DecretoFirmaDTOId generated by hbm2java
 */
public class DecretoFirmaDTOId implements java.io.Serializable {

	private long coDecreto;
	private int orden;

	public DecretoFirmaDTOId() {
	}

	public DecretoFirmaDTOId(long coDecreto, int orden) {
		this.coDecreto = coDecreto;
		this.orden = orden;
	}

	public long getCoDecreto() {
		return this.coDecreto;
	}

	public void setCoDecreto(long coDecreto) {
		this.coDecreto = coDecreto;
	}

	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DecretoFirmaDTOId))
			return false;
		DecretoFirmaDTOId castOther = (DecretoFirmaDTOId) other;

		return (this.getCoDecreto() == castOther.getCoDecreto())
				&& (this.getOrden() == castOther.getOrden());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCoDecreto();
		result = 37 * result + this.getOrden();
		return result;
	}

}
