package es.dipucadiz.etir.comun.dto;

// Generated 10-may-2012 8:24:35 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * DecretoAdjuntoDTO generated by hbm2java
 */
public class DecretoAdjuntoDTO implements java.io.Serializable {

	private DecretoAdjuntoDTOId id;
	private DecretoDTO decretoDTO;
	private Long coCliente;
	private Short idServicio;
	private String estado;
	private Serializable fhEstado;
	private Serializable fhFirma;
	private String motivoDevolucion;
	private Long refDoc;
	private String coUsuarioActualizacion;
	private Serializable fhActualizacion;

	public DecretoAdjuntoDTO() {
	}

	public DecretoAdjuntoDTO(DecretoAdjuntoDTOId id, DecretoDTO decretoDTO) {
		this.id = id;
		this.decretoDTO = decretoDTO;
	}

	public DecretoAdjuntoDTO(DecretoAdjuntoDTOId id, DecretoDTO decretoDTO,
			Long coCliente, Short idServicio, String estado,
			Serializable fhEstado, Serializable fhFirma,
			String motivoDevolucion, Long refDoc,
			String coUsuarioActualizacion, Serializable fhActualizacion) {
		this.id = id;
		this.decretoDTO = decretoDTO;
		this.coCliente = coCliente;
		this.idServicio = idServicio;
		this.estado = estado;
		this.fhEstado = fhEstado;
		this.fhFirma = fhFirma;
		this.motivoDevolucion = motivoDevolucion;
		this.refDoc = refDoc;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
	}

	public DecretoAdjuntoDTOId getId() {
		return this.id;
	}

	public void setId(DecretoAdjuntoDTOId id) {
		this.id = id;
	}

	public DecretoDTO getDecretoDTO() {
		return this.decretoDTO;
	}

	public void setDecretoDTO(DecretoDTO decretoDTO) {
		this.decretoDTO = decretoDTO;
	}

	public Long getCoCliente() {
		return this.coCliente;
	}

	public void setCoCliente(Long coCliente) {
		this.coCliente = coCliente;
	}

	public Short getIdServicio() {
		return this.idServicio;
	}

	public void setIdServicio(Short idServicio) {
		this.idServicio = idServicio;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Serializable getFhEstado() {
		return this.fhEstado;
	}

	public void setFhEstado(Serializable fhEstado) {
		this.fhEstado = fhEstado;
	}

	public Serializable getFhFirma() {
		return this.fhFirma;
	}

	public void setFhFirma(Serializable fhFirma) {
		this.fhFirma = fhFirma;
	}

	public String getMotivoDevolucion() {
		return this.motivoDevolucion;
	}

	public void setMotivoDevolucion(String motivoDevolucion) {
		this.motivoDevolucion = motivoDevolucion;
	}

	public Long getRefDoc() {
		return this.refDoc;
	}

	public void setRefDoc(Long refDoc) {
		this.refDoc = refDoc;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Serializable getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Serializable fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

}
