package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * DocumentoContadorDTO generated by hbm2java
 */
public class DocumentoContadorDTO implements java.io.Serializable {

	private DocumentoContadorDTOId id;
	private ModeloVersionDTO modeloVersionDTO;
	private int nuDocumento;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public DocumentoContadorDTO() {
	}

	public DocumentoContadorDTO(ModeloVersionDTO modeloVersionDTO,
			int nuDocumento) {
		this.modeloVersionDTO = modeloVersionDTO;
		this.nuDocumento = nuDocumento;
	}

	public DocumentoContadorDTO(ModeloVersionDTO modeloVersionDTO,
			int nuDocumento, Date fhActualizacion, String coUsuarioActualizacion) {
		this.modeloVersionDTO = modeloVersionDTO;
		this.nuDocumento = nuDocumento;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public DocumentoContadorDTOId getId() {
		return this.id;
	}

	public void setId(DocumentoContadorDTOId id) {
		this.id = id;
	}

	public ModeloVersionDTO getModeloVersionDTO() {
		return this.modeloVersionDTO;
	}

	public void setModeloVersionDTO(ModeloVersionDTO modeloVersionDTO) {
		this.modeloVersionDTO = modeloVersionDTO;
	}

	public int getNuDocumento() {
		return this.nuDocumento;
	}

	public void setNuDocumento(int nuDocumento) {
		this.nuDocumento = nuDocumento;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
