package es.dipucadiz.etir.comun.dto;

// Generated 01-jun-2010 13:02:55 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * DocumentoNotDgcDTO generated by hbm2java
 */
public class DocumentoNotDgcDTO implements java.io.Serializable {

	private Long coDocumentoNotDgc;
	private DocumentoDTO documentoDTO;
	private String expedienteDgc;
	private Short anoExpediente;
	private Integer documentoExpediente;
	private boolean boLiquidable;
	private Date fxEnvioBop;
	private String resultadoNotificacion;
	private Date fxNotificacion;
	private boolean boLiquidado;
	private boolean boEnviadoSigre;
	private String tipo;
	private boolean boResolucionPapel;
	private String estado;
	private boolean boNotificacionBop;
	private Byte coDgc;
	private Date fhEnvioSigre;
	private Date fhImpresion;
	private Date fxDevolucionDgc;
	private Short ejerEfectoIbi;
	private Short ejerEntradaPadron;
	private String tipoAlteracion;
	private Long grupoAnulacion;
	private Date fhAnulacion;
	private Date fxEnvioNotificado;
	private Date fxPublicacionBop;
	private Long grupoBop;
	private String tipoProcedimiento;
	private String nifTitular;
	private String nombreTitular;
	private String nifDestinatario;
	private String nombreDestinatario;
	private String coProvinciaDestinatario;
	private String coMunicipioDestinatario;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public DocumentoNotDgcDTO() {
	}

	public DocumentoNotDgcDTO(DocumentoDTO documentoDTO, String expedienteDgc,
			Short anoExpediente) {
		this.documentoDTO = documentoDTO;
		this.expedienteDgc = expedienteDgc;
		this.anoExpediente = anoExpediente;
	}

	public DocumentoNotDgcDTO(DocumentoDTO documentoDTO, String expedienteDgc,
			Short anoExpediente, Integer documentoExpediente,
			boolean boLiquidable, Date fxEnvioBop,
			String resultadoNotificacion, Date fxNotificacion,
			boolean boLiquidado, boolean boEnviadoSigre, String tipo,
			boolean boResolucionPapel, String estado,
			boolean boNotificacionBop, Byte coDgc, Date fhEnvioSigre,
			Date fhImpresion, Date fxDevolucionDgc, Short ejerEfectoIbi,
			Short ejerEntradaPadron, String tipoAlteracion,
			Long grupoAnulacion, Date fhAnulacion, Date fxEnvioNotificado,
			Date fxPublicacionBop, Long grupoBop, String tipoProcedimiento,
			Date fhActualizacion, String coUsuarioActualizacion) {
		this.documentoDTO = documentoDTO;
		this.expedienteDgc = expedienteDgc;
		this.anoExpediente = anoExpediente;
		this.documentoExpediente = documentoExpediente;
		this.boLiquidable = boLiquidable;
		this.fxEnvioBop = fxEnvioBop;
		this.resultadoNotificacion = resultadoNotificacion;
		this.fxNotificacion = fxNotificacion;
		this.boLiquidado = boLiquidado;
		this.boEnviadoSigre = boEnviadoSigre;
		this.tipo = tipo;
		this.boResolucionPapel = boResolucionPapel;
		this.estado = estado;
		this.boNotificacionBop = boNotificacionBop;
		this.coDgc = coDgc;
		this.fhEnvioSigre = fhEnvioSigre;
		this.fhImpresion = fhImpresion;
		this.fxDevolucionDgc = fxDevolucionDgc;
		this.ejerEfectoIbi = ejerEfectoIbi;
		this.ejerEntradaPadron = ejerEntradaPadron;
		this.tipoAlteracion = tipoAlteracion;
		this.grupoAnulacion = grupoAnulacion;
		this.fhAnulacion = fhAnulacion;
		this.fxEnvioNotificado = fxEnvioNotificado;
		this.fxPublicacionBop = fxPublicacionBop;
		this.grupoBop = grupoBop;
		this.tipoProcedimiento = tipoProcedimiento;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Long getCoDocumentoNotDgc() {
		return this.coDocumentoNotDgc;
	}

	public void setCoDocumentoNotDgc(Long coDocumentoNotDgc) {
		this.coDocumentoNotDgc = coDocumentoNotDgc;
	}

	public DocumentoDTO getDocumentoDTO() {
		return this.documentoDTO;
	}

	public void setDocumentoDTO(DocumentoDTO documentoDTO) {
		this.documentoDTO = documentoDTO;
	}

	public String getExpedienteDgc() {
		return this.expedienteDgc;
	}

	public void setExpedienteDgc(String expedienteDgc) {
		this.expedienteDgc = expedienteDgc;
	}

	public Short getAnoExpediente() {
		return this.anoExpediente;
	}

	public void setAnoExpediente(Short anoExpediente) {
		this.anoExpediente = anoExpediente;
	}

	public Integer getDocumentoExpediente() {
		return this.documentoExpediente;
	}

	public void setDocumentoExpediente(Integer documentoExpediente) {
		this.documentoExpediente = documentoExpediente;
	}

	public boolean getBoLiquidable() {
		return this.boLiquidable;
	}

	public void setBoLiquidable(boolean boLiquidable) {
		this.boLiquidable = boLiquidable;
	}

	public Date getFxEnvioBop() {
		return this.fxEnvioBop;
	}

	public void setFxEnvioBop(Date fxEnvioBop) {
		this.fxEnvioBop = fxEnvioBop;
	}

	public String getResultadoNotificacion() {
		return this.resultadoNotificacion;
	}

	public void setResultadoNotificacion(String resultadoNotificacion) {
		this.resultadoNotificacion = resultadoNotificacion;
	}

	public Date getFxNotificacion() {
		return this.fxNotificacion;
	}

	public void setFxNotificacion(Date fxNotificacion) {
		this.fxNotificacion = fxNotificacion;
	}

	public boolean getBoLiquidado() {
		return this.boLiquidado;
	}

	public void setBoLiquidado(boolean boLiquidado) {
		this.boLiquidado = boLiquidado;
	}

	public boolean getBoEnviadoSigre() {
		return this.boEnviadoSigre;
	}

	public void setBoEnviadoSigre(boolean boEnviadoSigre) {
		this.boEnviadoSigre = boEnviadoSigre;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public boolean getBoResolucionPapel() {
		return this.boResolucionPapel;
	}

	public void setBoResolucionPapel(boolean boResolucionPapel) {
		this.boResolucionPapel = boResolucionPapel;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public boolean getBoNotificacionBop() {
		return this.boNotificacionBop;
	}

	public void setBoNotificacionBop(boolean boNotificacionBop) {
		this.boNotificacionBop = boNotificacionBop;
	}

	public Byte getCoDgc() {
		return this.coDgc;
	}

	public void setCoDgc(Byte coDgc) {
		this.coDgc = coDgc;
	}

	public Date getFhEnvioSigre() {
		return this.fhEnvioSigre;
	}

	public void setFhEnvioSigre(Date fhEnvioSigre) {
		this.fhEnvioSigre = fhEnvioSigre;
	}

	public Date getFhImpresion() {
		return this.fhImpresion;
	}

	public void setFhImpresion(Date fhImpresion) {
		this.fhImpresion = fhImpresion;
	}

	public Date getFxDevolucionDgc() {
		return this.fxDevolucionDgc;
	}

	public void setFxDevolucionDgc(Date fxDevolucionDgc) {
		this.fxDevolucionDgc = fxDevolucionDgc;
	}

	public Short getEjerEfectoIbi() {
		return this.ejerEfectoIbi;
	}

	public void setEjerEfectoIbi(Short ejerEfectoIbi) {
		this.ejerEfectoIbi = ejerEfectoIbi;
	}

	public Short getEjerEntradaPadron() {
		return this.ejerEntradaPadron;
	}

	public void setEjerEntradaPadron(Short ejerEntradaPadron) {
		this.ejerEntradaPadron = ejerEntradaPadron;
	}

	public String getTipoAlteracion() {
		return this.tipoAlteracion;
	}

	public void setTipoAlteracion(String tipoAlteracion) {
		this.tipoAlteracion = tipoAlteracion;
	}

	public Long getGrupoAnulacion() {
		return this.grupoAnulacion;
	}

	public void setGrupoAnulacion(Long grupoAnulacion) {
		this.grupoAnulacion = grupoAnulacion;
	}

	public Date getFhAnulacion() {
		return this.fhAnulacion;
	}

	public void setFhAnulacion(Date fhAnulacion) {
		this.fhAnulacion = fhAnulacion;
	}

	public Date getFxEnvioNotificado() {
		return this.fxEnvioNotificado;
	}

	public void setFxEnvioNotificado(Date fxEnvioNotificado) {
		this.fxEnvioNotificado = fxEnvioNotificado;
	}

	public Date getFxPublicacionBop() {
		return this.fxPublicacionBop;
	}

	public void setFxPublicacionBop(Date fxPublicacionBop) {
		this.fxPublicacionBop = fxPublicacionBop;
	}

	public Long getGrupoBop() {
		return this.grupoBop;
	}

	public void setGrupoBop(Long grupoBop) {
		this.grupoBop = grupoBop;
	}

	public String getTipoProcedimiento() {
		return this.tipoProcedimiento;
	}

	public void setTipoProcedimiento(String tipoProcedimiento) {
		this.tipoProcedimiento = tipoProcedimiento;
	}

	public String getNifTitular() {
		return nifTitular;
	}

	public void setNifTitular(String nifTitular) {
		this.nifTitular = nifTitular;
	}

	public String getNombreTitular() {
		return nombreTitular;
	}

	public void setNombreTitular(String nombreTitular) {
		this.nombreTitular = nombreTitular;
	}

	public String getNifDestinatario() {
		return nifDestinatario;
	}

	public void setNifDestinatario(String nifDestinatario) {
		this.nifDestinatario = nifDestinatario;
	}

	public String getNombreDestinatario() {
		return nombreDestinatario;
	}

	public void setNombreDestinatario(String nombreDestinatario) {
		this.nombreDestinatario = nombreDestinatario;
	}

	public String getCoProvinciaDestinatario() {
		return coProvinciaDestinatario;
	}

	public void setCoProvinciaDestinatario(String coProvinciaDestinatario) {
		this.coProvinciaDestinatario = coProvinciaDestinatario;
	}

	public String getCoMunicipioDestinatario() {
		return coMunicipioDestinatario;
	}

	public void setCoMunicipioDestinatario(String coMunicipioDestinatario) {
		this.coMunicipioDestinatario = coMunicipioDestinatario;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
