package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * DocumentoCasillaValorDTOId generated by hbm2java
 */
public class DocumentoCasillaValorDTOId implements java.io.Serializable {

	private String coModelo;
	private String coVersion;
	private String coDocumento;
	private short nuCasilla;
	private short hoja;

	public DocumentoCasillaValorDTOId() {
	}

	public DocumentoCasillaValorDTOId(String coModelo, String coVersion,
			String coDocumento, short nuCasilla, short hoja) {
		this.coModelo = coModelo;
		this.coVersion = coVersion;
		this.coDocumento = coDocumento;
		this.nuCasilla = nuCasilla;
		this.hoja = hoja;
	}

	public String getCoModelo() {
		return this.coModelo;
	}

	public void setCoModelo(String coModelo) {
		this.coModelo = coModelo;
	}

	public String getCoVersion() {
		return this.coVersion;
	}

	public void setCoVersion(String coVersion) {
		this.coVersion = coVersion;
	}

	public String getCoDocumento() {
		return this.coDocumento;
	}

	public void setCoDocumento(String coDocumento) {
		this.coDocumento = coDocumento;
	}

	public short getNuCasilla() {
		return this.nuCasilla;
	}

	public void setNuCasilla(short nuCasilla) {
		this.nuCasilla = nuCasilla;
	}

	public short getHoja() {
		return this.hoja;
	}

	public void setHoja(short hoja) {
		this.hoja = hoja;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentoCasillaValorDTOId))
			return false;
		DocumentoCasillaValorDTOId castOther = (DocumentoCasillaValorDTOId) other;

		return ((this.getCoModelo() == castOther.getCoModelo()) || (this
				.getCoModelo() != null
				&& castOther.getCoModelo() != null && this.getCoModelo()
				.equals(castOther.getCoModelo())))
				&& ((this.getCoVersion() == castOther.getCoVersion()) || (this
						.getCoVersion() != null
						&& castOther.getCoVersion() != null && this
						.getCoVersion().equals(castOther.getCoVersion())))
				&& ((this.getCoDocumento() == castOther.getCoDocumento()) || (this
						.getCoDocumento() != null
						&& castOther.getCoDocumento() != null && this
						.getCoDocumento().equals(castOther.getCoDocumento())))
				&& (this.getNuCasilla() == castOther.getNuCasilla())
				&& (this.getHoja() == castOther.getHoja());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCoModelo() == null ? 0 : this.getCoModelo().hashCode());
		result = 37 * result
				+ (getCoVersion() == null ? 0 : this.getCoVersion().hashCode());
		result = 37
				* result
				+ (getCoDocumento() == null ? 0 : this.getCoDocumento()
						.hashCode());
		result = 37 * result + this.getNuCasilla();
		result = 37 * result + this.getHoja();
		return result;
	}

}
