package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * DocumentoCensoDTO generated by hbm2java
 */
public class DocumentoCensoDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DocumentoCensoDTOId id;
	private DocumentoDTO documentoDTO;
	private Date fxAlta;
	private Date fxBaja;
	private Boolean boActivo;
	private String tipoMovimiento;
	private Short ejercicioPadron;
	private String periodoPadron;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Date fxTramite;
	private String rowid;

	public DocumentoCensoDTO() {
	}

	public DocumentoCensoDTO(DocumentoDTO documentoDTO) {
		this.documentoDTO = documentoDTO;
	}

	public DocumentoCensoDTO(DocumentoDTO documentoDTO, Date fxAlta,
			Date fxBaja, Boolean boActivo, String tipoMovimiento,
			Short ejercicioPadron, String periodoPadron, Date fhActualizacion,
			String coUsuarioActualizacion, Date fxTramite) {
		this.documentoDTO = documentoDTO;
		this.fxAlta = fxAlta;
		this.fxBaja = fxBaja;
		this.boActivo = boActivo;
		this.tipoMovimiento = tipoMovimiento;
		this.ejercicioPadron = ejercicioPadron;
		this.periodoPadron = periodoPadron;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fxTramite = fxTramite;		
	}

	public DocumentoCensoDTOId getId() {
		return this.id;
	}

	public void setId(DocumentoCensoDTOId id) {
		this.id = id;
	}

	public DocumentoDTO getDocumentoDTO() {
		return this.documentoDTO;
	}

	public void setDocumentoDTO(DocumentoDTO documentoDTO) {
		this.documentoDTO = documentoDTO;
	}

	public Date getFxAlta() {
		return this.fxAlta;
	}

	public void setFxAlta(Date fxAlta) {
		this.fxAlta = fxAlta;
	}

	public Date getFxBaja() {
		return this.fxBaja;
	}

	public void setFxBaja(Date fxBaja) {
		this.fxBaja = fxBaja;
	}

	public Boolean getBoActivo() {
		return this.boActivo;
	}

	public void setBoActivo(Boolean boActivo) {
		this.boActivo = boActivo;
	}

	public String getTipoMovimiento() {
		return this.tipoMovimiento;
	}

	public void setTipoMovimiento(String tipoMovimiento) {
		this.tipoMovimiento = tipoMovimiento;
	}

	public Short getEjercicioPadron() {
		return this.ejercicioPadron;
	}

	public void setEjercicioPadron(Short ejercicioPadron) {
		this.ejercicioPadron = ejercicioPadron;
	}

	public String getPeriodoPadron() {
		return this.periodoPadron;
	}

	public void setPeriodoPadron(String periodoPadron) {
		this.periodoPadron = periodoPadron;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFxTramite() {
		return this.fxTramite;
	}

	public void setFxTramite(Date fxTramite) {
		this.fxTramite = fxTramite;
	}

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
