package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * DocumentoContadorDTOId generated by hbm2java
 */
public class DocumentoContadorDTOId implements java.io.Serializable {

	private String coModelo;
	private String coVersion;

	public DocumentoContadorDTOId() {
	}

	public DocumentoContadorDTOId(String coModelo, String coVersion) {
		this.coModelo = coModelo;
		this.coVersion = coVersion;
	}

	public String getCoModelo() {
		return this.coModelo;
	}

	public void setCoModelo(String coModelo) {
		this.coModelo = coModelo;
	}

	public String getCoVersion() {
		return this.coVersion;
	}

	public void setCoVersion(String coVersion) {
		this.coVersion = coVersion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentoContadorDTOId))
			return false;
		DocumentoContadorDTOId castOther = (DocumentoContadorDTOId) other;

		return ((this.getCoModelo() == castOther.getCoModelo()) || (this
				.getCoModelo() != null
				&& castOther.getCoModelo() != null && this.getCoModelo()
				.equals(castOther.getCoModelo())))
				&& ((this.getCoVersion() == castOther.getCoVersion()) || (this
						.getCoVersion() != null
						&& castOther.getCoVersion() != null && this
						.getCoVersion().equals(castOther.getCoVersion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCoModelo() == null ? 0 : this.getCoModelo().hashCode());
		result = 37 * result
				+ (getCoVersion() == null ? 0 : this.getCoVersion().hashCode());
		return result;
	}

}
