package es.dipucadiz.etir.comun.dto;

// Generated 03-dic-2010 12:05:13 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * DomiciliacionBonifRuegoDTO generated by hbm2java
 */
public class DomiciliacionBonifRuegoDTO implements java.io.Serializable {

	private Long coDomiciliacionBonifRuego;
	private DomiciliacionDTO domiciliacionDTO;
	private Date fhConcesion;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;

	public DomiciliacionBonifRuegoDTO() {
	}

	public DomiciliacionBonifRuegoDTO(DomiciliacionDTO domiciliacionDTO) {
		this.domiciliacionDTO = domiciliacionDTO;
	}

	public DomiciliacionBonifRuegoDTO(DomiciliacionDTO domiciliacionDTO,
			Date fhConcesion, Date fhActualizacion,
			String coUsuarioActualizacion) {
		this.domiciliacionDTO = domiciliacionDTO;
		this.fhConcesion = fhConcesion;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Long getCoDomiciliacionBonifRuego() {
		return this.coDomiciliacionBonifRuego;
	}

	public void setCoDomiciliacionBonifRuego(Long coDomiciliacionBonifRuego) {
		this.coDomiciliacionBonifRuego = coDomiciliacionBonifRuego;
	}

	public DomiciliacionDTO getDomiciliacionDTO() {
		return this.domiciliacionDTO;
	}

	public void setDomiciliacionDTO(DomiciliacionDTO domiciliacionDTO) {
		this.domiciliacionDTO = domiciliacionDTO;
	}

	public Date getFhConcesion() {
		return this.fhConcesion;
	}

	public void setFhConcesion(Date fhConcesion) {
		this.fhConcesion = fhConcesion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

}
