package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * DomiciliacionDTO generated by hbm2java
 */
public class DomiciliacionDTO implements java.io.Serializable {

	private Integer coDomiciliacion;
	private MunicipioDTO municipioDTO;
	private ConceptoDTO conceptoDTO;
	private ClienteCuentaDTO clienteCuentaDTO;
	private DocumentoDTO documentoDTO;
	private ClienteDTO clienteDTO;
	private String tipo;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String refObjTributario;
	private String refDomiciliacion;
	private Date fxInicio;
	private Date fxFinal;
	private String procedencia;
	private String motivo;
	private Set<FraccionamientoDTO> fraccionamientoDTOs = new HashSet<FraccionamientoDTO>(
			0);
	private Set<DocumentoDTO> documentoDTOs = new HashSet<DocumentoDTO>(0);
	private Set<PppDTO> pppDTOs = new HashSet<PppDTO>(0);
	private String rowid;

	public DomiciliacionDTO() {
	}

	public DomiciliacionDTO(MunicipioDTO municipioDTO, ConceptoDTO conceptoDTO,
			ClienteCuentaDTO clienteCuentaDTO, DocumentoDTO documentoDTO,
			String tipo, Date fhActualizacion, String coUsuarioActualizacion,
			String refObjTributario, String refDomiciliacion, Date fxInicio,
			Date fxFinal, Set<DocumentoDTO> documentoDTOs) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.clienteCuentaDTO = clienteCuentaDTO;
		this.documentoDTO = documentoDTO;
		this.tipo = tipo;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.refObjTributario = refObjTributario;
		this.refDomiciliacion = refDomiciliacion;
		this.fxInicio = fxInicio;
		this.fxFinal = fxFinal;
		this.documentoDTOs = documentoDTOs;
	}

	public Integer getCoDomiciliacion() {
		return this.coDomiciliacion;
	}

	public void setCoDomiciliacion(Integer coDomiciliacion) {
		this.coDomiciliacion = coDomiciliacion;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public ConceptoDTO getConceptoDTO() {
		return this.conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public ClienteCuentaDTO getClienteCuentaDTO() {
		return this.clienteCuentaDTO;
	}

	public void setClienteCuentaDTO(ClienteCuentaDTO clienteCuentaDTO) {
		this.clienteCuentaDTO = clienteCuentaDTO;
	}

	public DocumentoDTO getDocumentoDTO() {
		return this.documentoDTO;
	}

	public void setDocumentoDTO(DocumentoDTO documentoDTO) {
		this.documentoDTO = documentoDTO;
	}
	
	public ClienteDTO getClienteDTO() {
		return this.clienteDTO;
	}

	public void setClienteDTO(ClienteDTO clienteDTO) {
		this.clienteDTO = clienteDTO;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getRefObjTributario() {
		return this.refObjTributario;
	}

	public void setRefObjTributario(String refObjTributario) {
		this.refObjTributario = refObjTributario;
	}

	public String getRefDomiciliacion() {
		return this.refDomiciliacion;
	}

	public void setRefDomiciliacion(String refDomiciliacion) {
		this.refDomiciliacion = refDomiciliacion;
	}

	public Date getFxInicio() {
		return this.fxInicio;
	}

	public void setFxInicio(Date fxInicio) {
		this.fxInicio = fxInicio;
	}

	public Date getFxFinal() {
		return this.fxFinal;
	}

	public void setFxFinal(Date fxFinal) {
		this.fxFinal = fxFinal;
	}
	
	public String getProcedencia() {
		return this.procedencia;
	}

	public void setProcedencia(String procedencia) {
		this.procedencia = procedencia;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}
	
	public Set<FraccionamientoDTO> getFraccionamientoDTOs() {
		return this.fraccionamientoDTOs;
	}

	public void setFraccionamientoDTOs(
			Set<FraccionamientoDTO> fraccionamientoDTOs) {
		this.fraccionamientoDTOs = fraccionamientoDTOs;
	}

	public Set<DocumentoDTO> getDocumentoDTOs() {
		return this.documentoDTOs;
	}

	public void setDocumentoDTOs(Set<DocumentoDTO> documentoDTOs) {
		this.documentoDTOs = documentoDTOs;
	}
	
	public Set<PppDTO> getPppDTOs() {
		return this.pppDTOs;
	}

	public void setPppDTOs(Set<PppDTO> pppDTOs) {
		this.pppDTOs = pppDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
