package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * DomicilioNotificacionDTO generated by hbm2java
 */
public class DomicilioNotificacionDTO implements java.io.Serializable, Comparable<DomicilioNotificacionDTO> {
	private static final long serialVersionUID = 5999896223613277805L;

	private Long coDomicilioNotificacion;
	private String coModeloCenso;
	private String coVersionCenso;
	private String coDocumentoCenso;
	private ConceptoDTO conceptoDTO;
	private ModeloVersionDTO modeloVersionDTO;
	private DomicilioDTO domicilioDTO;
	private ClienteDTO clienteDTO;
	private MunicipioDTO municipioDTO;
	private Date fxVigenciaDesde;
	private Date fxVigenciaHasta;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public DomicilioNotificacionDTO() {
	}

	public DomicilioNotificacionDTO(String coModeloCenso, String coVersionCenso, 
			String coDocumentoCenso, ConceptoDTO conceptoDTO, ModeloVersionDTO modeloVersionDTO,
			DomicilioDTO domicilioDTO, ClienteDTO clienteDTO) {
		this.coModeloCenso = coModeloCenso;
		this.coVersionCenso = coVersionCenso;
		this.coDocumentoCenso = coDocumentoCenso;
		this.conceptoDTO = conceptoDTO;
		this.modeloVersionDTO = modeloVersionDTO;
		this.domicilioDTO = domicilioDTO;
		this.clienteDTO = clienteDTO;
	}

	public DomicilioNotificacionDTO(String coModeloCenso, String coVersionCenso, 
			String coDocumentoCenso, ConceptoDTO conceptoDTO, ModeloVersionDTO modeloVersionDTO,
			DomicilioDTO domicilioDTO, ClienteDTO clienteDTO,
			Date fxVigenciaDesde, Date fxVigenciaHasta, Date fhActualizacion,
			String coUsuarioActualizacion) {
		this.coModeloCenso = coModeloCenso;
		this.coVersionCenso = coVersionCenso;
		this.coDocumentoCenso = coDocumentoCenso;
		this.conceptoDTO = conceptoDTO;
		this.modeloVersionDTO = modeloVersionDTO;
		this.domicilioDTO = domicilioDTO;
		this.clienteDTO = clienteDTO;
		this.fxVigenciaDesde = fxVigenciaDesde;
		this.fxVigenciaHasta = fxVigenciaHasta;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Long getCoDomicilioNotificacion() {
		return this.coDomicilioNotificacion;
	}

	public void setCoDomicilioNotificacion(Long coDomicilioNotificacion) {
		this.coDomicilioNotificacion = coDomicilioNotificacion;
	}

	public ConceptoDTO getConceptoDTO() {
		return this.conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public ModeloVersionDTO getModeloVersionDTO() {
		return this.modeloVersionDTO;
	}

	public void setModeloVersionDTO(ModeloVersionDTO modeloVersionDTO) {
		this.modeloVersionDTO = modeloVersionDTO;
	}

	public DomicilioDTO getDomicilioDTO() {
		return this.domicilioDTO;
	}

	public void setDomicilioDTO(DomicilioDTO domicilioDTO) {
		this.domicilioDTO = domicilioDTO;
	}

	public ClienteDTO getClienteDTO() {
		return this.clienteDTO;
	}

	public void setClienteDTO(ClienteDTO clienteDTO) {
		this.clienteDTO = clienteDTO;
	}

	public MunicipioDTO getMunicipioDTO() {
		return municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public Date getFxVigenciaDesde() {
		return this.fxVigenciaDesde;
	}

	public void setFxVigenciaDesde(Date fxVigenciaDesde) {
		this.fxVigenciaDesde = fxVigenciaDesde;
	}

	public Date getFxVigenciaHasta() {
		return this.fxVigenciaHasta;
	}

	public void setFxVigenciaHasta(Date fxVigenciaHasta) {
		this.fxVigenciaHasta = fxVigenciaHasta;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public String getCoModeloCenso() {
		return coModeloCenso;
	}

	public void setCoModeloCenso(String coModeloCenso) {
		this.coModeloCenso = coModeloCenso;
	}

	public String getCoVersionCenso() {
		return coVersionCenso;
	}

	public void setCoVersionCenso(String coVersionCenso) {
		this.coVersionCenso = coVersionCenso;
	}

	public String getCoDocumentoCenso() {
		return coDocumentoCenso;
	}

	public void setCoDocumentoCenso(String coDocumentoCenso) {
		this.coDocumentoCenso = coDocumentoCenso;
	}
	
	public int compareTo(DomicilioNotificacionDTO o) {
		int result;
		result = this.getMunicipioDTO().getId().getCoProvincia().compareTo(o.getMunicipioDTO().getId().getCoProvincia()); 
		if (result == 0) { //misma provincia
			result = this.getMunicipioDTO().getId().getCoMunicipio().compareTo(o.getMunicipioDTO().getId().getCoMunicipio()); 
			if (result == 0) { //mismo municipio
				result = this.getConceptoDTO().getCoConcepto().compareTo(o.getConceptoDTO().getCoConcepto());
				if (result == 0) { //mismo concepto
					result = this.getCoModeloCenso().compareTo(o.getCoModeloCenso());
					if (result == 0) { //mismo modelo
						result = this.getCoDocumentoCenso().compareTo(o.getCoDocumentoCenso());
					}
				}
			}
		} 
		
		return result;
	}
}
