package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * DomicilioDTO generated by hbm2java
 */
public class DomicilioDTO implements java.io.Serializable {

	private Long coDomicilio;
	private UnidadUrbanaDTO unidadUrbanaDTO;
	private ClienteDTO clienteDTO;
	private Date fxAlta;
	private Boolean boFiscalAeat;
	private Boolean boFiscalMunicipal;
	private Boolean boNotificacion;
	private boolean boTributario;
	private String procedencia;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<DocumentoDTO> documentoDTOsForCoDomicilioFiscal = new HashSet<DocumentoDTO>(
			0);
	private Set<DomicilioNotificacionDTO> domicilioNotificacionDTOs = new HashSet<DomicilioNotificacionDTO>(
			0);
	private Set<DocumentoDTO> documentoDTOsForCoDomicilio = new HashSet<DocumentoDTO>(
			0);
	private String rowid;

	public DomicilioDTO() {
	}

	public DomicilioDTO(UnidadUrbanaDTO unidadUrbanaDTO, ClienteDTO clienteDTO) {
		this.unidadUrbanaDTO = unidadUrbanaDTO;
		this.clienteDTO = clienteDTO;
	}

	public DomicilioDTO(UnidadUrbanaDTO unidadUrbanaDTO, ClienteDTO clienteDTO,
			Date fxAlta, Boolean boFiscalAeat, Boolean boFiscalMunicipal,
			Boolean boNotificacion, String procedencia, Date fhActualizacion,
			String coUsuarioActualizacion,
			Set<DocumentoDTO> documentoDTOsForCoDomicilioFiscal,
			Set<DomicilioNotificacionDTO> domicilioNotificacionDTOs,
			Set<DocumentoDTO> documentoDTOsForCoDomicilio) {
		this.unidadUrbanaDTO = unidadUrbanaDTO;
		this.clienteDTO = clienteDTO;
		this.fxAlta = fxAlta;
		this.boFiscalAeat = boFiscalAeat;
		this.boFiscalMunicipal = boFiscalMunicipal;
		this.boNotificacion = boNotificacion;
		this.procedencia = procedencia;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.documentoDTOsForCoDomicilioFiscal = documentoDTOsForCoDomicilioFiscal;
		this.domicilioNotificacionDTOs = domicilioNotificacionDTOs;
		this.documentoDTOsForCoDomicilio = documentoDTOsForCoDomicilio;
	}

	public Long getCoDomicilio() {
		return this.coDomicilio;
	}

	public void setCoDomicilio(Long coDomicilio) {
		this.coDomicilio = coDomicilio;
	}

	public UnidadUrbanaDTO getUnidadUrbanaDTO() {
		return this.unidadUrbanaDTO;
	}

	public void setUnidadUrbanaDTO(UnidadUrbanaDTO unidadUrbanaDTO) {
		this.unidadUrbanaDTO = unidadUrbanaDTO;
	}

	public ClienteDTO getClienteDTO() {
		return this.clienteDTO;
	}

	public void setClienteDTO(ClienteDTO clienteDTO) {
		this.clienteDTO = clienteDTO;
	}

	public Date getFxAlta() {
		return this.fxAlta;
	}

	public void setFxAlta(Date fxAlta) {
		this.fxAlta = fxAlta;
	}

	public Boolean getBoFiscalAeat() {
		return this.boFiscalAeat;
	}

	public void setBoFiscalAeat(Boolean boFiscalAeat) {
		this.boFiscalAeat = boFiscalAeat;
	}

	public Boolean getBoFiscalMunicipal() {
		return this.boFiscalMunicipal;
	}

	public void setBoFiscalMunicipal(Boolean boFiscalMunicipal) {
		this.boFiscalMunicipal = boFiscalMunicipal;
	}

	public Boolean getBoNotificacion() {
		return this.boNotificacion;
	}

	public void setBoNotificacion(Boolean boNotificacion) {
		this.boNotificacion = boNotificacion;
	}

	public String getProcedencia() {
		return this.procedencia;
	}

	public void setProcedencia(String procedencia) {
		this.procedencia = procedencia;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<DocumentoDTO> getDocumentoDTOsForCoDomicilioFiscal() {
		return this.documentoDTOsForCoDomicilioFiscal;
	}

	public void setDocumentoDTOsForCoDomicilioFiscal(
			Set<DocumentoDTO> documentoDTOsForCoDomicilioFiscal) {
		this.documentoDTOsForCoDomicilioFiscal = documentoDTOsForCoDomicilioFiscal;
	}

	public Set<DomicilioNotificacionDTO> getDomicilioNotificacionDTOs() {
		return this.domicilioNotificacionDTOs;
	}

	public void setDomicilioNotificacionDTOs(
			Set<DomicilioNotificacionDTO> domicilioNotificacionDTOs) {
		this.domicilioNotificacionDTOs = domicilioNotificacionDTOs;
	}

	public Set<DocumentoDTO> getDocumentoDTOsForCoDomicilio() {
		return this.documentoDTOsForCoDomicilio;
	}

	public void setDocumentoDTOsForCoDomicilio(
			Set<DocumentoDTO> documentoDTOsForCoDomicilio) {
		this.documentoDTOsForCoDomicilio = documentoDTOsForCoDomicilio;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}
	
	public boolean isBoTributario() {
		return this.boTributario;
	}

	public void setBoTributario(boolean boTributario) {
		this.boTributario = boTributario;
	}

}
