package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * EjecucionParametroDTOId generated by hbm2java
 */
public class EjecucionParametroDTOId implements java.io.Serializable {

	private long coEjecucion;
	private short nuParametro;

	public EjecucionParametroDTOId() {
	}

	public EjecucionParametroDTOId(long coEjecucion, short nuParametro) {
		this.coEjecucion = coEjecucion;
		this.nuParametro = nuParametro;
	}

	public long getCoEjecucion() {
		return this.coEjecucion;
	}

	public void setCoEjecucion(long coEjecucion) {
		this.coEjecucion = coEjecucion;
	}

	public short getNuParametro() {
		return this.nuParametro;
	}

	public void setNuParametro(short nuParametro) {
		this.nuParametro = nuParametro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EjecucionParametroDTOId))
			return false;
		EjecucionParametroDTOId castOther = (EjecucionParametroDTOId) other;

		return (this.getCoEjecucion() == castOther.getCoEjecucion())
				&& (this.getNuParametro() == castOther.getNuParametro());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCoEjecucion();
		result = 37 * result + this.getNuParametro();
		return result;
	}

}
