package es.dipucadiz.etir.comun.dto;
// Generated 07-abr-2010 9:08:07 by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;
import es.dipucadiz.etir.comun.utilidades.UtilidadesFormato;

/**
 * ExpedienteDTO generated by hbm2java
 */
public class ExpedienteDTO  implements java.io.Serializable {
	private static final long serialVersionUID = 7287840864703013007L;
	
	private Long coExpediente;
     private CodigoTerritorialDTO codigoTerritorialDTO;
     private ExpedienteDTO expedienteOrigenDTO;
     private TramiteDTO tramiteOrigenDTO;
     private CircuitoRutaDTO circuitoRutaDTO;
     private MunicipioDTO municipioDTO;
     private ConceptoDTO conceptoDTO;
     private DocumentoDTO documentoResumenDTO;
     private Long nuExpediente;
     private Short ejercicio;
     private String estado;
     private String observaciones;
     private Integer maxSubExpediente;
     private Date fhActualizacion;
     private String coUsuarioActualizacion;
     private Set<ExpedienteDTO> expedienteDTOs = new HashSet<ExpedienteDTO>(0);
     private String rowid;

    public ExpedienteDTO() {
    }

    public ExpedienteDTO(CodigoTerritorialDTO codigoTerritorialDTO, ExpedienteDTO expedienteOrigenDTO, TramiteDTO tramiteOrigenDTO, CircuitoRutaDTO circuitoRutaDTO, Long nuExpediente, Short ejercicio, String estado, String observaciones, Date fhActualizacion, String coUsuarioActualizacion, Set<ExpedienteDTO> expedienteDTOs) {
       this.codigoTerritorialDTO = codigoTerritorialDTO;
       this.expedienteOrigenDTO = expedienteOrigenDTO;
       this.tramiteOrigenDTO = tramiteOrigenDTO;
       this.circuitoRutaDTO = circuitoRutaDTO;
       this.nuExpediente = nuExpediente;
       this.ejercicio = ejercicio;
       this.estado = estado;
       this.observaciones = observaciones;
       this.fhActualizacion = fhActualizacion;
       this.coUsuarioActualizacion = coUsuarioActualizacion;
       this.expedienteDTOs = expedienteDTOs;
    }
   
    public String getCodigoDescripcion() {
    	return circuitoRutaDTO.getId().getCoCircuito() + " " + 
    			municipioDTO.getId().getCoProvincia() + municipioDTO.getId().getCoMunicipio() + " " +
    			ejercicio.toString() + " " +
    			UtilidadesFormato.padLeft(nuExpediente.toString(), 10, '0');
    }
    
    public Long getCoExpediente() {
        return this.coExpediente;
    }
    
    public void setCoExpediente(Long coExpediente) {
        this.coExpediente = coExpediente;
    }
    public CodigoTerritorialDTO getCodigoTerritorialDTO() {
        return this.codigoTerritorialDTO;
    }
    
    public void setCodigoTerritorialDTO(CodigoTerritorialDTO codigoTerritorialDTO) {
        this.codigoTerritorialDTO = codigoTerritorialDTO;
    }
    public ExpedienteDTO getExpedienteOrigenDTO() {
        return this.expedienteOrigenDTO;
    }
    
    public void setExpedienteOrigenDTO(ExpedienteDTO expedienteOrigenDTO) {
        this.expedienteOrigenDTO = expedienteOrigenDTO;
    }
    public TramiteDTO getTramiteOrigenDTO() {
        return this.tramiteOrigenDTO;
    }
    
    public void setTramiteOrigenDTO(TramiteDTO tramiteOrigenDTO) {
        this.tramiteOrigenDTO = tramiteOrigenDTO;
    }
    public CircuitoRutaDTO getCircuitoRutaDTO() {
        return this.circuitoRutaDTO;
    }
    
    public void setCircuitoRutaDTO(CircuitoRutaDTO circuitoRutaDTO) {
        this.circuitoRutaDTO = circuitoRutaDTO;
    }
    public Long getNuExpediente() {
        return this.nuExpediente;
    }
    
    public void setNuExpediente(Long nuExpediente) {
        this.nuExpediente = nuExpediente;
    }
    public Short getEjercicio() {
        return this.ejercicio;
    }
    
    public void setEjercicio(Short ejercicio) {
        this.ejercicio = ejercicio;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Date getFhActualizacion() {
        return this.fhActualizacion;
    }
    
    public void setFhActualizacion(Date fhActualizacion) {
        this.fhActualizacion = fhActualizacion;
    }
    public String getCoUsuarioActualizacion() {
        return this.coUsuarioActualizacion;
    }
    
    public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
        this.coUsuarioActualizacion = coUsuarioActualizacion;
    }
    public Set<ExpedienteDTO> getExpedienteDTOs() {
        return this.expedienteDTOs;
    }
    
    public void setExpedienteDTOs(Set<ExpedienteDTO> expedienteDTOs) {
        this.expedienteDTOs = expedienteDTOs;
    }
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public MunicipioDTO getMunicipioDTO() {
		return municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public DocumentoDTO getDocumentoResumenDTO() {
		return documentoResumenDTO;
	}

	public void setDocumentoResumenDTO(DocumentoDTO documentoResumenDTO) {
		this.documentoResumenDTO = documentoResumenDTO;
	}

	public ConceptoDTO getConceptoDTO() {
		return conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public Integer getMaxSubExpediente() {
		return maxSubExpediente;
	}

	public void setMaxSubExpediente(Integer maxSubExpediente) {
		this.maxSubExpediente = maxSubExpediente;
	}




}


