package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ExtraccionInformeDTO generated by hbm2java
 */
public class ExtraccionInformeDTO implements java.io.Serializable {

	private ExtraccionInformeDTOId id;
	private ExtraccionDTO extraccionDTO;
	private String nombre;
	private String descripcion;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<ExtraccionInformeEstructDTO> extraccionInformeEstructDTOs = new HashSet<ExtraccionInformeEstructDTO>(
			0);
	private String rowid;

	public ExtraccionInformeDTO() {
	}

	public ExtraccionInformeDTO(ExtraccionInformeDTOId id,
			ExtraccionDTO extraccionDTO) {
		this.id = id;
		this.extraccionDTO = extraccionDTO;
	}

	public ExtraccionInformeDTO(ExtraccionInformeDTOId id,
			ExtraccionDTO extraccionDTO, String nombre, String descripcion,
			Date fhActualizacion, String coUsuarioActualizacion,
			Set<ExtraccionInformeEstructDTO> extraccionInformeEstructDTOs) {
		this.id = id;
		this.extraccionDTO = extraccionDTO;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.extraccionInformeEstructDTOs = extraccionInformeEstructDTOs;
	}

	public ExtraccionInformeDTOId getId() {
		return this.id;
	}

	public void setId(ExtraccionInformeDTOId id) {
		this.id = id;
	}

	public ExtraccionDTO getExtraccionDTO() {
		return this.extraccionDTO;
	}

	public void setExtraccionDTO(ExtraccionDTO extraccionDTO) {
		this.extraccionDTO = extraccionDTO;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<ExtraccionInformeEstructDTO> getExtraccionInformeEstructDTOs() {
		return this.extraccionInformeEstructDTOs;
	}

	public void setExtraccionInformeEstructDTOs(
			Set<ExtraccionInformeEstructDTO> extraccionInformeEstructDTOs) {
		this.extraccionInformeEstructDTOs = extraccionInformeEstructDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
