package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * ExtraccionEstructuraDTOId generated by hbm2java
 */
public class ExtraccionEstructuraDTOId implements java.io.Serializable {

	private String coExtraccion;
	private String coExtraccionTipoRegistro;
	private short ordenExtraccionEstructura;

	public ExtraccionEstructuraDTOId() {
	}

	public ExtraccionEstructuraDTOId(String coExtraccion,
			String coExtraccionTipoRegistro, short ordenExtraccionEstructura) {
		this.coExtraccion = coExtraccion;
		this.coExtraccionTipoRegistro = coExtraccionTipoRegistro;
		this.ordenExtraccionEstructura = ordenExtraccionEstructura;
	}

	public String getCoExtraccion() {
		return this.coExtraccion;
	}

	public void setCoExtraccion(String coExtraccion) {
		this.coExtraccion = coExtraccion;
	}

	public String getCoExtraccionTipoRegistro() {
		return this.coExtraccionTipoRegistro;
	}

	public void setCoExtraccionTipoRegistro(String coExtraccionTipoRegistro) {
		this.coExtraccionTipoRegistro = coExtraccionTipoRegistro;
	}

	public short getOrdenExtraccionEstructura() {
		return this.ordenExtraccionEstructura;
	}

	public void setOrdenExtraccionEstructura(short ordenExtraccionEstructura) {
		this.ordenExtraccionEstructura = ordenExtraccionEstructura;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExtraccionEstructuraDTOId))
			return false;
		ExtraccionEstructuraDTOId castOther = (ExtraccionEstructuraDTOId) other;

		return ((this.getCoExtraccion() == castOther.getCoExtraccion()) || (this
				.getCoExtraccion() != null
				&& castOther.getCoExtraccion() != null && this
				.getCoExtraccion().equals(castOther.getCoExtraccion())))
				&& ((this.getCoExtraccionTipoRegistro() == castOther
						.getCoExtraccionTipoRegistro()) || (this
						.getCoExtraccionTipoRegistro() != null
						&& castOther.getCoExtraccionTipoRegistro() != null && this
						.getCoExtraccionTipoRegistro().equals(
								castOther.getCoExtraccionTipoRegistro())))
				&& (this.getOrdenExtraccionEstructura() == castOther
						.getOrdenExtraccionEstructura());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCoExtraccion() == null ? 0 : this.getCoExtraccion()
						.hashCode());
		result = 37
				* result
				+ (getCoExtraccionTipoRegistro() == null ? 0 : this
						.getCoExtraccionTipoRegistro().hashCode());
		result = 37 * result + this.getOrdenExtraccionEstructura();
		return result;
	}

}
