package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ExtraccionOrdenDTO generated by hbm2java
 */
public class ExtraccionOrdenDTO implements java.io.Serializable {

	private ExtraccionOrdenDTOId id;
	private ExtraccionTipoRegistroDTO extraccionTipoRegistroDTO;
	private String nombre;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<ExtraccionOrdenCampoDTO> extraccionOrdenCampoDTOs = new HashSet<ExtraccionOrdenCampoDTO>(
			0);
	private String rowid;

	public ExtraccionOrdenDTO() {
	}

	public ExtraccionOrdenDTO(ExtraccionOrdenDTOId id,
			ExtraccionTipoRegistroDTO extraccionTipoRegistroDTO) {
		this.id = id;
		this.extraccionTipoRegistroDTO = extraccionTipoRegistroDTO;
	}

	public ExtraccionOrdenDTO(ExtraccionOrdenDTOId id,
			ExtraccionTipoRegistroDTO extraccionTipoRegistroDTO, String nombre,
			Date fhActualizacion, String coUsuarioActualizacion,
			Set<ExtraccionOrdenCampoDTO> extraccionOrdenCampoDTOs) {
		this.id = id;
		this.extraccionTipoRegistroDTO = extraccionTipoRegistroDTO;
		this.nombre = nombre;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.extraccionOrdenCampoDTOs = extraccionOrdenCampoDTOs;
	}

	public ExtraccionOrdenDTOId getId() {
		return this.id;
	}

	public void setId(ExtraccionOrdenDTOId id) {
		this.id = id;
	}

	public ExtraccionTipoRegistroDTO getExtraccionTipoRegistroDTO() {
		return this.extraccionTipoRegistroDTO;
	}

	public void setExtraccionTipoRegistroDTO(
			ExtraccionTipoRegistroDTO extraccionTipoRegistroDTO) {
		this.extraccionTipoRegistroDTO = extraccionTipoRegistroDTO;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<ExtraccionOrdenCampoDTO> getExtraccionOrdenCampoDTOs() {
		return this.extraccionOrdenCampoDTOs;
	}

	public void setExtraccionOrdenCampoDTOs(
			Set<ExtraccionOrdenCampoDTO> extraccionOrdenCampoDTOs) {
		this.extraccionOrdenCampoDTOs = extraccionOrdenCampoDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
