package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ExtraccionCriterioCondDTO generated by hbm2java
 */
public class ExtraccionCriterioCondDTO implements java.io.Serializable {

	private ExtraccionCriterioCondDTOId id;
	private ExtraccionCriterioDTO extraccionCriterioDTO;
	private String tipoCondicion;
	private String valorCondicion;
	private String operador;
	private String conector;
	private String valorCompara;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String tipoCompara;
	private String rowid;

	public ExtraccionCriterioCondDTO() {
	}

	public ExtraccionCriterioCondDTO(ExtraccionCriterioCondDTOId id,
			ExtraccionCriterioDTO extraccionCriterioDTO) {
		this.id = id;
		this.extraccionCriterioDTO = extraccionCriterioDTO;
	}

	public ExtraccionCriterioCondDTO(ExtraccionCriterioCondDTOId id,
			ExtraccionCriterioDTO extraccionCriterioDTO, String tipoCondicion,
			String valorCondicion, String operador, String conector,
			String valorCompara, Date fhActualizacion,
			String coUsuarioActualizacion, String tipoCompara) {
		this.id = id;
		this.extraccionCriterioDTO = extraccionCriterioDTO;
		this.tipoCondicion = tipoCondicion;
		this.valorCondicion = valorCondicion;
		this.operador = operador;
		this.conector = conector;
		this.valorCompara = valorCompara;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.tipoCompara = tipoCompara;
	}

	public ExtraccionCriterioCondDTOId getId() {
		return this.id;
	}

	public void setId(ExtraccionCriterioCondDTOId id) {
		this.id = id;
	}

	public ExtraccionCriterioDTO getExtraccionCriterioDTO() {
		return this.extraccionCriterioDTO;
	}

	public void setExtraccionCriterioDTO(
			ExtraccionCriterioDTO extraccionCriterioDTO) {
		this.extraccionCriterioDTO = extraccionCriterioDTO;
	}

	public String getTipoCondicion() {
		return this.tipoCondicion;
	}

	public void setTipoCondicion(String tipoCondicion) {
		this.tipoCondicion = tipoCondicion;
	}

	public String getValorCondicion() {
		return this.valorCondicion;
	}

	public void setValorCondicion(String valorCondicion) {
		this.valorCondicion = valorCondicion;
	}

	public String getOperador() {
		return this.operador;
	}

	public void setOperador(String operador) {
		this.operador = operador;
	}

	public String getConector() {
		return this.conector;
	}

	public void setConector(String conector) {
		this.conector = conector;
	}

	public String getValorCompara() {
		return this.valorCompara;
	}

	public void setValorCompara(String valorCompara) {
		this.valorCompara = valorCompara;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getTipoCompara() {
		return this.tipoCompara;
	}

	public void setTipoCompara(String tipoCompara) {
		this.tipoCompara = tipoCompara;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
