package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ExtraccionOrdenCampoDTO generated by hbm2java
 */
public class ExtraccionOrdenCampoDTO implements java.io.Serializable {

	private ExtraccionOrdenCampoDTOId id;
	private ExtraccionOrdenDTO extraccionOrdenDTO;
	private Boolean boAscendente;
	private String tipoOrdenacion;
	private String valorOrdenacion;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public ExtraccionOrdenCampoDTO() {
	}

	public ExtraccionOrdenCampoDTO(ExtraccionOrdenCampoDTOId id,
			ExtraccionOrdenDTO extraccionOrdenDTO) {
		this.id = id;
		this.extraccionOrdenDTO = extraccionOrdenDTO;
	}

	public ExtraccionOrdenCampoDTO(ExtraccionOrdenCampoDTOId id,
			ExtraccionOrdenDTO extraccionOrdenDTO, Boolean boAscendente,
			String tipoOrdenacion, String valorOrdenacion,
			Date fhActualizacion, String coUsuarioActualizacion) {
		this.id = id;
		this.extraccionOrdenDTO = extraccionOrdenDTO;
		this.boAscendente = boAscendente;
		this.tipoOrdenacion = tipoOrdenacion;
		this.valorOrdenacion = valorOrdenacion;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public ExtraccionOrdenCampoDTOId getId() {
		return this.id;
	}

	public void setId(ExtraccionOrdenCampoDTOId id) {
		this.id = id;
	}

	public ExtraccionOrdenDTO getExtraccionOrdenDTO() {
		return this.extraccionOrdenDTO;
	}

	public void setExtraccionOrdenDTO(ExtraccionOrdenDTO extraccionOrdenDTO) {
		this.extraccionOrdenDTO = extraccionOrdenDTO;
	}

	public Boolean getBoAscendente() {
		return this.boAscendente;
	}

	public void setBoAscendente(Boolean boAscendente) {
		this.boAscendente = boAscendente;
	}

	public String getTipoOrdenacion() {
		return this.tipoOrdenacion;
	}

	public void setTipoOrdenacion(String tipoOrdenacion) {
		this.tipoOrdenacion = tipoOrdenacion;
	}

	public String getValorOrdenacion() {
		return this.valorOrdenacion;
	}

	public void setValorOrdenacion(String valorOrdenacion) {
		this.valorOrdenacion = valorOrdenacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
