package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * FormulaDTO generated by hbm2java
 */
public class FormulaDTO implements java.io.Serializable {

	private String coFormula;
	private String nombre;
	private String descripcion;
	private String tipo;
	private Boolean boCorrecto;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<FormulaPasoDTO> formulaPasoDTOs = new HashSet<FormulaPasoDTO>(0);
	private String rowid;

	public FormulaDTO() {
	}

	public FormulaDTO(String nombre) {
		this.nombre = nombre;
	}

	public FormulaDTO(String coFormula, String nombre, String descripcion, String tipo,
			Boolean boCorrecto, Date fhActualizacion,
			String coUsuarioActualizacion, Set<FormulaPasoDTO> formulaPasoDTOs) {
		this.coFormula = coFormula;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.boCorrecto = boCorrecto;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.formulaPasoDTOs = formulaPasoDTOs;
	}

	public String getCoFormula() {
		return this.coFormula;
	}

	public void setCoFormula(String coFormula) {
		this.coFormula = coFormula;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Boolean getBoCorrecto() {
		return this.boCorrecto;
	}

	public void setBoCorrecto(Boolean boCorrecto) {
		this.boCorrecto = boCorrecto;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<FormulaPasoDTO> getFormulaPasoDTOs() {
		return this.formulaPasoDTOs;
	}

	public void setFormulaPasoDTOs(Set<FormulaPasoDTO> formulaPasoDTOs) {
		this.formulaPasoDTOs = formulaPasoDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public String getCodigoDescripcion() {
		return this.coFormula + " - " + this.nombre;
	}
	
}
