package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * FraccionamientoDTO generated by hbm2java
 */
public class FraccionamientoDTO implements java.io.Serializable {

	private Long coFraccionamiento;
	private MunicipioDTO municipioDTO;
	private DocumentoDTO documentoDTO;
	private DomiciliacionDTO domiciliacionDTO;
	private ClienteDTO clienteDTO;
	private BigDecimal importe;
	private Short nuPlazos;
	private Date fxSolicitud;
	private Date fxConcesion;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private String coSituacionCargo;
	private BigDecimal imCobrado;
	private Short mesInicio;
	private Short anoInicio;
	private Short mesFin;
	private Short anoFin;
	private Short mesesPeriodicidad;
	private String ordenanza;
	private Boolean boProrrateado; 
	private Boolean boMantenible;
	private String procedencia;
	
	private BigDecimal imSinIntereses;
	private BigDecimal imInteresFraccionamiento;
	private BigDecimal imInteresDemora;
	private BigDecimal imInteresExtemporaneo;
	private BigDecimal imRecargoExtemporaneo;
 
	private BigDecimal imCostas;
	private BigDecimal imRecargo;

	private BigDecimal imPlazoSolicitud;

	   private BDDocumentalGrupoDTO bdDocumentalGrupoDTO;
    
	private Set<FraccionamientoSeguimientoDTO> fraccionamientoSeguimientoDTOs = new HashSet<FraccionamientoSeguimientoDTO>(
			0);
	private Set<FraccionamientoReciboDTO> fraccionamientoReciboDTOs = new HashSet<FraccionamientoReciboDTO>(
			0);
	private Set<DocumentoLiquidacionDTO> documentoLiquidacionDTOs = new HashSet<DocumentoLiquidacionDTO>(
			0);
	private Set<FraccGarantiaAportadaDTO> fraccGarantiaAportadaDTOs = new HashSet<FraccGarantiaAportadaDTO>(
			0);
	private Set<FraccionamientoPlazoDTO> fraccionamientoPlazoDTOs = new HashSet<FraccionamientoPlazoDTO>(
			0);
	private String tipo;
			
	private String rowid;

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public FraccionamientoDTO() {
	}

	public FraccionamientoDTO(DocumentoDTO documentoDTO,
			DomiciliacionDTO domiciliacionDTO, ClienteDTO clienteDTO,
			BigDecimal importe, Short nuPlazos, Date fxSolicitud,
			Date fxConcesion, String coUsuarioActualizacion,
			Date fhActualizacion, String coSituacionCargo,
			BigDecimal imCobrado, Short mesInicio, Short anoInicio, Short mesFin,
			Short anoFin, Short mesesPeriodicidad, String ordenanza,
			Set<FraccionamientoSeguimientoDTO> fraccionamientoSeguimientoDTOs,
			Set<FraccionamientoReciboDTO> fraccionamientoReciboDTOs,
			Set<DocumentoLiquidacionDTO> documentoLiquidacionDTOs,
			Set<FraccGarantiaAportadaDTO> fraccGarantiaAportadaDTOs,
			Set<FraccionamientoPlazoDTO> fraccionamientoPlazoDTOs) {
		this.documentoDTO = documentoDTO;
		this.domiciliacionDTO = domiciliacionDTO;
		this.clienteDTO = clienteDTO;
		this.importe = importe;
		this.nuPlazos = nuPlazos;
		this.fxSolicitud = fxSolicitud;
		this.fxConcesion = fxConcesion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.coSituacionCargo = coSituacionCargo;
		this.imCobrado = imCobrado;
		this.mesInicio = mesInicio;
		this.anoInicio = anoInicio;
		this.mesFin = mesFin;
		this.anoFin = anoFin;
		this.mesesPeriodicidad = mesesPeriodicidad;
		this.ordenanza = ordenanza;
		this.fraccionamientoSeguimientoDTOs = fraccionamientoSeguimientoDTOs;
		this.fraccionamientoReciboDTOs = fraccionamientoReciboDTOs;
		this.documentoLiquidacionDTOs = documentoLiquidacionDTOs;
		this.fraccGarantiaAportadaDTOs = fraccGarantiaAportadaDTOs;
		this.fraccionamientoPlazoDTOs = fraccionamientoPlazoDTOs;
	}

	public Long getCoFraccionamiento() {
		return this.coFraccionamiento;
	}

	public void setCoFraccionamiento(Long coFraccionamiento) {
		this.coFraccionamiento = coFraccionamiento;
	}

	public DocumentoDTO getDocumentoDTO() {
		return this.documentoDTO;
	}

	public void setDocumentoDTO(DocumentoDTO documentoDTO) {
		this.documentoDTO = documentoDTO;
	}

	public DomiciliacionDTO getDomiciliacionDTO() {
		return this.domiciliacionDTO;
	}

	public void setDomiciliacionDTO(DomiciliacionDTO domiciliacionDTO) {
		this.domiciliacionDTO = domiciliacionDTO;
	}

	public ClienteDTO getClienteDTO() {
		return this.clienteDTO;
	}

	public void setClienteDTO(ClienteDTO clienteDTO) {
		this.clienteDTO = clienteDTO;
	}

	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	public Short getNuPlazos() {
		return this.nuPlazos;
	}

	public void setNuPlazos(Short nuPlazos) {
		this.nuPlazos = nuPlazos;
	}

	public Date getFxSolicitud() {
		return this.fxSolicitud;
	}

	public void setFxSolicitud(Date fxSolicitud) {
		this.fxSolicitud = fxSolicitud;
	}

	public Date getFxConcesion() {
		return this.fxConcesion;
	}

	public void setFxConcesion(Date fxConcesion) {
		this.fxConcesion = fxConcesion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoSituacionCargo() {
		return this.coSituacionCargo;
	}

	public void setCoSituacionCargo(String coSituacionCargo) {
		this.coSituacionCargo = coSituacionCargo;
	}

	public BigDecimal getImCobrado() {
		return this.imCobrado;
	}

	public void setImCobrado(BigDecimal imCobrado) {
		this.imCobrado = imCobrado;
	}

	public Short getMesInicio() {
		return this.mesInicio;
	}

	public void setMesInicio(Short mesInicio) {
		this.mesInicio = mesInicio;
	}

	public Short getAnoInicio() {
		return this.anoInicio;
	}

	public void setAnoInicio(Short anoInicio) {
		this.anoInicio = anoInicio;
	}

	public Short getMesFin() {
		return this.mesFin;
	}

	public void setMesFin(Short mesFin) {
		this.mesFin = mesFin;
	}

	public Short getAnoFin() {
		return this.anoFin;
	}

	public void setAnoFin(Short anoFin) {
		this.anoFin = anoFin;
	}

	public Short getMesesPeriodicidad() {
		return this.mesesPeriodicidad;
	}

	public void setMesesPeriodicidad(Short mesesPeriodicidad) {
		this.mesesPeriodicidad = mesesPeriodicidad;
	}

	public String getOrdenanza() {
		return this.ordenanza;
	}

	public void setOrdenanza(String ordenanza) {
		this.ordenanza = ordenanza;
	}

	public Set<FraccionamientoSeguimientoDTO> getFraccionamientoSeguimientoDTOs() {
		return this.fraccionamientoSeguimientoDTOs;
	}

	public void setFraccionamientoSeguimientoDTOs(
			Set<FraccionamientoSeguimientoDTO> fraccionamientoSeguimientoDTOs) {
		this.fraccionamientoSeguimientoDTOs = fraccionamientoSeguimientoDTOs;
	}

	public Set<FraccionamientoReciboDTO> getFraccionamientoReciboDTOs() {
		return this.fraccionamientoReciboDTOs;
	}

	public void setFraccionamientoReciboDTOs(
			Set<FraccionamientoReciboDTO> fraccionamientoReciboDTOs) {
		this.fraccionamientoReciboDTOs = fraccionamientoReciboDTOs;
	}

	public Set<DocumentoLiquidacionDTO> getDocumentoLiquidacionDTOs() {
		return this.documentoLiquidacionDTOs;
	}

	public void setDocumentoLiquidacionDTOs(
			Set<DocumentoLiquidacionDTO> documentoLiquidacionDTOs) {
		this.documentoLiquidacionDTOs = documentoLiquidacionDTOs;
	}

	public Set<FraccGarantiaAportadaDTO> getFraccGarantiaAportadaDTOs() {
		return this.fraccGarantiaAportadaDTOs;
	}

	public void setFraccGarantiaAportadaDTOs(
			Set<FraccGarantiaAportadaDTO> fraccGarantiaAportadaDTOs) {
		this.fraccGarantiaAportadaDTOs = fraccGarantiaAportadaDTOs;
	}

	public Set<FraccionamientoPlazoDTO> getFraccionamientoPlazoDTOs() {
		return this.fraccionamientoPlazoDTOs;
	}

	public void setFraccionamientoPlazoDTOs(
			Set<FraccionamientoPlazoDTO> fraccionamientoPlazoDTOs) {
		this.fraccionamientoPlazoDTOs = fraccionamientoPlazoDTOs;
	}

	public MunicipioDTO getMunicipioDTO() {
		return municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getTipo() {
		return tipo;
	}

	public BigDecimal getImSinIntereses() {
		return imSinIntereses;
	}

	public void setImSinIntereses(BigDecimal imSinIntereses) {
		this.imSinIntereses = imSinIntereses;
	}

	public BigDecimal getImInteresFraccionamiento() {
		return imInteresFraccionamiento;
	}

	public void setImInteresFraccionamiento(BigDecimal imInteresFraccionamiento) {
		this.imInteresFraccionamiento = imInteresFraccionamiento;
	}

	public BigDecimal getImInteresDemora() {
		return imInteresDemora;
	}

	public void setImInteresDemora(BigDecimal imInteresDemora) {
		this.imInteresDemora = imInteresDemora;
	}

	public BigDecimal getImInteresExtemporaneo() {
		return imInteresExtemporaneo;
	}

	public void setImInteresExtemporaneo(BigDecimal imInteresExtemporaneo) {
		this.imInteresExtemporaneo = imInteresExtemporaneo;
	}

	public BigDecimal getImRecargoExtemporaneo() {
		return imRecargoExtemporaneo;
	}

	public void setImRecargoExtemporaneo(BigDecimal imRecargoExtemporaneo) {
		this.imRecargoExtemporaneo = imRecargoExtemporaneo;
	}

	public BigDecimal getImCostas() {
		return imCostas;
	}

	public void setImCostas(BigDecimal imCostas) {
		this.imCostas = imCostas;
	}

	public BigDecimal getImRecargo() {
		return imRecargo;
	}

	public void setImRecargo(BigDecimal imRecargo) {
		this.imRecargo = imRecargo;
	}

	public Boolean getBoProrrateado() {
		return boProrrateado;
	}

	public void setBoProrrateado(Boolean boProrrateado) {
		this.boProrrateado = boProrrateado;
	}

	public BigDecimal getImPlazoSolicitud() {
		return imPlazoSolicitud;
	}

	public void setImPlazoSolicitud(BigDecimal imPlazoSolicitud) {
		this.imPlazoSolicitud = imPlazoSolicitud;
	}

	public BDDocumentalGrupoDTO getBdDocumentalGrupoDTO() {
		return bdDocumentalGrupoDTO;
	}

	public void setBdDocumentalGrupoDTO(BDDocumentalGrupoDTO bdDocumentalGrupoDTO) {
		this.bdDocumentalGrupoDTO = bdDocumentalGrupoDTO;
	}

	public Boolean getBoMantenible() {
		return boMantenible;
	}

	public void setBoMantenible(Boolean boMantenible) {
		this.boMantenible = boMantenible;
	}

	public String getProcedencia() {
		return procedencia;
	}

	public void setProcedencia(String procedencia) {
		this.procedencia = procedencia;
	}
	
	
	
}
