package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

/**
 * FraccionamientoPlazoDTOId generated by hbm2java
 */
public class FraccionamientoPlazoDTOId implements java.io.Serializable {

	private long coFraccionamiento;
	private short nuPlazo;

	public FraccionamientoPlazoDTOId() {
	}

	public FraccionamientoPlazoDTOId(long coFraccionamiento, short nuPlazo) {
		this.coFraccionamiento = coFraccionamiento;
		this.nuPlazo = nuPlazo;
	}

	public long getCoFraccionamiento() {
		return this.coFraccionamiento;
	}

	public void setCoFraccionamiento(long coFraccionamiento) {
		this.coFraccionamiento = coFraccionamiento;
	}

	public short getNuPlazo() {
		return this.nuPlazo;
	}

	public void setNuPlazo(short nuPlazo) {
		this.nuPlazo = nuPlazo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FraccionamientoPlazoDTOId))
			return false;
		FraccionamientoPlazoDTOId castOther = (FraccionamientoPlazoDTOId) other;

		return (this.getCoFraccionamiento() == castOther.getCoFraccionamiento())
				&& (this.getNuPlazo() == castOther.getNuPlazo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCoFraccionamiento();
		result = 37 * result + this.getNuPlazo();
		return result;
	}

}
