package es.dipucadiz.etir.comun.dto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.exception.GadirServiceException;
import es.dipucadiz.etir.comun.utilidades.Utilidades;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

/**
 * FraccionamientoPlazoDTO generated by hbm2java
 */
public class FraccionamientoPlazoDTO implements java.io.Serializable {

	private FraccionamientoPlazoDTOId id;
	private DocumentoLiquidacionDTO documentoLiquidacionDTO;
	private FraccionamientoDTO fraccionamientoDTO;
	private FraccGarantiaAportadaDTO fraccGarantiaAportadaDTO;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private short ano;
	private short mes;
 
	 
	private BigDecimal imInteres;
	private BigDecimal imInteresPonderado;
	private CuentaDTO cuentaDTO;
	private Long nuIntervencion;
	private String coDevolucion;
	private Date fxDevolucion;
	private Set<FraccPlazoReciboDTO> fraccPlazoReciboDTOs = new HashSet<FraccPlazoReciboDTO>(0);
	
	private Date fxEnvio;
	private Date fxCobro;
	private Date fxPaseEjecutiva;
	
	private BigDecimal imInteresFraccionamiento;
	private BigDecimal imInteresDemora;
	private BigDecimal imInteresExtemporaneo;
	private BigDecimal imRecargoExtemporaneo;
	private BigDecimal imRecargo;
	private Date fxPlazoJunta;
	private Date fxPlazo;
	private BigDecimal imCostas;
	private BigDecimal imPrincipal;	
	 
 
	public BigDecimal getImporteTotal(){
		//faltaria .add(getImCostas())
		//return getImPrincipal().add(getImRecargo()).add(getImCostas()).add(getImInteresDemora()).add(getImInteresPonderado()).add(getImInteresFraccionamiento());
		BigDecimal suma = BigDecimal.ZERO;
		
		if(getImPrincipal()!=null)
			suma=suma.add(getImPrincipal());
			
		if(getImRecargo()!=null)
			suma=suma.add(getImRecargo());
		
		if(getImCostas()!=null)
			suma=suma.add(getImCostas()); 
//		if(getImInteresDemora() !=null)
//			suma=suma.add(getImInteresDemora()); 
		
		
		if(getImInteresPonderado()!=null)
			suma=suma.add(getImInteresPonderado()); 
 
		return suma;
	}
	
	
	public String getImporteTotalStr() throws GadirServiceException {
		return Utilidades.getFormato2Number(getImporteTotal(), 15.2);
	}

	public BigDecimal getInteresFraccionamiento(){
		//faltaria .add(getImCostas())
		return getImInteres().subtract(getImInteresDemora());
	}
	
	
	public String getInteresFraccionamientoStr() throws GadirServiceException {
		return Utilidades.getFormato2Number(getInteresFraccionamiento(), 15.2);
	}

	
	private String rowid;

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public FraccionamientoPlazoDTO() {
	}

	public FraccionamientoPlazoDTO(FraccionamientoPlazoDTOId id,
			DocumentoLiquidacionDTO documentoLiquidacionDTO,
			FraccionamientoDTO fraccionamientoDTO, short ano, short mes) {
		this.id = id;
		this.documentoLiquidacionDTO = documentoLiquidacionDTO;
		this.fraccionamientoDTO = fraccionamientoDTO;
		this.ano = ano;
		this.mes = mes;
	}

	public FraccionamientoPlazoDTO(FraccionamientoPlazoDTOId id,
			DocumentoLiquidacionDTO documentoLiquidacionDTO,
			FraccionamientoDTO fraccionamientoDTO,
			FraccGarantiaAportadaDTO fraccGarantiaAportadaDTO,
			String coUsuarioActualizacion, Date fhActualizacion, short ano,
			short mes, BigDecimal imInteres,
			BigDecimal imInteresPonderado,
			Set<FraccPlazoReciboDTO> fraccPlazoReciboDTOs) {
		this.id = id;
		this.documentoLiquidacionDTO = documentoLiquidacionDTO;
		this.fraccionamientoDTO = fraccionamientoDTO;
		this.fraccGarantiaAportadaDTO = fraccGarantiaAportadaDTO;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.ano = ano;
		this.mes = mes;
		this.imInteres = imInteres;
		this.imInteresPonderado = imInteresPonderado;
		this.fraccPlazoReciboDTOs = fraccPlazoReciboDTOs;
	}

	public FraccionamientoPlazoDTOId getId() {
		return this.id;
	}

	public void setId(FraccionamientoPlazoDTOId id) {
		this.id = id;
	}

	public DocumentoLiquidacionDTO getDocumentoLiquidacionDTO() {
		return this.documentoLiquidacionDTO;
	}

	public void setDocumentoLiquidacionDTO(
			DocumentoLiquidacionDTO documentoLiquidacionDTO) {
		this.documentoLiquidacionDTO = documentoLiquidacionDTO;
	}

	public FraccionamientoDTO getFraccionamientoDTO() {
		return this.fraccionamientoDTO;
	}

	public void setFraccionamientoDTO(FraccionamientoDTO fraccionamientoDTO) {
		this.fraccionamientoDTO = fraccionamientoDTO;
	}

	public FraccGarantiaAportadaDTO getFraccGarantiaAportadaDTO() {
		return this.fraccGarantiaAportadaDTO;
	}

	public void setFraccGarantiaAportadaDTO(
			FraccGarantiaAportadaDTO fraccGarantiaAportadaDTO) {
		this.fraccGarantiaAportadaDTO = fraccGarantiaAportadaDTO;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public short getAno() {
		return this.ano;
	}

	public void setAno(short ano) {
		this.ano = ano;
	}

	public short getMes() {
		return this.mes;
	}

	public void setMes(short mes) {
		this.mes = mes;
	}

	public BigDecimal getImInteres() {
		return this.imInteres;
	}

	public void setImInteres(BigDecimal imInteres) {
		this.imInteres = imInteres;
	}

	public BigDecimal getImInteresPonderado() {
		return this.imInteresPonderado;
	}

	public void setImInteresPonderado(BigDecimal imInteresPonderado) {
		this.imInteresPonderado = imInteresPonderado;
	}

	public Set<FraccPlazoReciboDTO> getFraccPlazoReciboDTOs() {
		return this.fraccPlazoReciboDTOs;
	}

	public void setFraccPlazoReciboDTOs(
			Set<FraccPlazoReciboDTO> fraccPlazoReciboDTOs) {
		this.fraccPlazoReciboDTOs = fraccPlazoReciboDTOs;
	}

	public CuentaDTO getCuentaDTO() {
		return cuentaDTO;
	}

	public void setCuentaDTO(CuentaDTO cuentaDTO) {
		this.cuentaDTO = cuentaDTO;
	}

	public void setNuIntervencion(Long nuIntervencion) {
		this.nuIntervencion = nuIntervencion;
	}

	public Long getNuIntervencion() {
		return nuIntervencion;
	}

	 

	public void setCoDevolucion(String coDevolucion) {
		this.coDevolucion = coDevolucion;
	}

	public String getCoDevolucion() {
		return coDevolucion;
	}

	public void setFxDevolucion(Date fxDevolucion) {
		this.fxDevolucion = fxDevolucion;
	}

	public Date getFxDevolucion() {
		return fxDevolucion;
	}

	 

	public Date getFxEnvio() {
		return fxEnvio;
	}

	public void setFxEnvio(Date fxEnvio) {
		this.fxEnvio = fxEnvio;
	}

	public Date getFxCobro() {
		return fxCobro;
	}

	public void setFxCobro(Date fxCobro) {
		this.fxCobro = fxCobro;
	}

	public Date getFxPaseEjecutiva() {
		return fxPaseEjecutiva;
	}

	public void setFxPaseEjecutiva(Date fxPaseEjecutiva) {
		this.fxPaseEjecutiva = fxPaseEjecutiva;
	}

 

	public BigDecimal getImInteresFraccionamiento() {
		return imInteresFraccionamiento;
	}

	public void setImInteresFraccionamiento(BigDecimal imInteresFraccionamiento) {
		this.imInteresFraccionamiento = imInteresFraccionamiento;
	}

	public BigDecimal getImInteresDemora() {
		return imInteresDemora;
	}

	public void setImInteresDemora(BigDecimal imInteresDemora) {
		this.imInteresDemora = imInteresDemora;
	}

	public BigDecimal getImInteresExtemporaneo() {
		return imInteresExtemporaneo;
	}

	public void setImInteresExtemporaneo(BigDecimal imInteresExtemporaneo) {
		this.imInteresExtemporaneo = imInteresExtemporaneo;
	}

	public BigDecimal getImRecargoExtemporaneo() {
		return imRecargoExtemporaneo;
	}

	public void setImRecargoExtemporaneo(BigDecimal imRecargoExtemporaneo) {
		this.imRecargoExtemporaneo = imRecargoExtemporaneo;
	}

	public BigDecimal getImRecargo() {
		return imRecargo;
	}

	public void setImRecargo(BigDecimal imRecargo) {
		this.imRecargo = imRecargo;
	}

	public Date getFxPlazo() {
		return fxPlazo;
	}

	public void setFxPlazo(Date fxPlazo) {
		this.fxPlazo = fxPlazo;
	}

	public BigDecimal getImPrincipal() {
		return imPrincipal;
	}

	public void setImPrincipal(BigDecimal imPrincipal) {
		this.imPrincipal = imPrincipal;
	}


	public BigDecimal getImCostas() {
		return imCostas;
	}


	public void setImCostas(BigDecimal imCostas) {
		this.imCostas = imCostas;
	}


	public Date getFxPlazoJunta() {
		return fxPlazoJunta;
	}


	public void setFxPlazoJunta(Date fxPlazoJunta) {
		this.fxPlazoJunta = fxPlazoJunta;
	}


	
}
