package es.dipucadiz.etir.comun.dto;

// Generated 02-dic-2010 10:42:18 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * FraccionamientoSeguimientoDTO generated by hbm2java
 */
public class FraccionamientoSeguimientoDTO implements java.io.Serializable {

	private Long coFraccionamientoSeguimiento;
	private FraccionamientoDTO fraccionamientoDTO;
	private DocumentoDTO documentoDTO;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String coIncidenciaCargo;
	private String coSituacionCargoOrigen;
	private String coSituacionCargoDestino;
	private String observaciones;
	private String coProceso;
	private Long coEjecucion;
	
	private String rowid;

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public FraccionamientoSeguimientoDTO() {
	}

	public FraccionamientoSeguimientoDTO(FraccionamientoDTO fraccionamientoDTO,
			Date fhActualizacion, String coUsuarioActualizacion,
			String coIncidenciaCargo, String coSituacionCargoOrigen,
			String coSituacionCargoDestino, String observaciones,
			String coProceso, Long coEjecucion) {
		this.fraccionamientoDTO = fraccionamientoDTO;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.coIncidenciaCargo = coIncidenciaCargo;
		this.coSituacionCargoOrigen = coSituacionCargoOrigen;
		this.coSituacionCargoDestino = coSituacionCargoDestino;
		this.observaciones = observaciones;
		this.coProceso = coProceso;
		this.coEjecucion = coEjecucion;
	}

	public Long getCoFraccionamientoSeguimiento() {
		return this.coFraccionamientoSeguimiento;
	}

	public void setCoFraccionamientoSeguimiento(
			Long coFraccionamientoSeguimiento) {
		this.coFraccionamientoSeguimiento = coFraccionamientoSeguimiento;
	}

	public FraccionamientoDTO getFraccionamientoDTO() {
		return this.fraccionamientoDTO;
	}

	public void setFraccionamientoDTO(FraccionamientoDTO fraccionamientoDTO) {
		this.fraccionamientoDTO = fraccionamientoDTO;
	}
	
	public DocumentoDTO getDocumentoDTO() {
		return this.documentoDTO;
	}

	public void setDocumentoDTO(DocumentoDTO documentoDTO) {
		this.documentoDTO = documentoDTO;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getCoIncidenciaCargo() {
		return this.coIncidenciaCargo;
	}

	public void setCoIncidenciaCargo(String coIncidenciaCargo) {
		this.coIncidenciaCargo = coIncidenciaCargo;
	}

	public String getCoSituacionCargoOrigen() {
		return this.coSituacionCargoOrigen;
	}

	public void setCoSituacionCargoOrigen(String coSituacionCargoOrigen) {
		this.coSituacionCargoOrigen = coSituacionCargoOrigen;
	}

	public String getCoSituacionCargoDestino() {
		return this.coSituacionCargoDestino;
	}

	public void setCoSituacionCargoDestino(String coSituacionCargoDestino) {
		this.coSituacionCargoDestino = coSituacionCargoDestino;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getCoProceso() {
		return this.coProceso;
	}

	public void setCoProceso(String coProceso) {
		this.coProceso = coProceso;
	}

	public Long getCoEjecucion() {
		return this.coEjecucion;
	}

	public void setCoEjecucion(Long coEjecucion) {
		this.coEjecucion = coEjecucion;
	}

}
