package es.dipucadiz.etir.comun.dto;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * FuncionDTO generated by hbm2java
 */
public class FuncionDTO implements java.io.Serializable {

	private String coFuncion;
	private String tipo;
	private String nombre;
	private String descripcion;
	private String clase;
	private String metodo;
	private String coPlsql;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<CorrespondenciaDTO> correspondenciaDTOs = new HashSet<CorrespondenciaDTO>(
			0);
	private Set<FormulaPasoDTO> formulaPasoDTOs = new HashSet<FormulaPasoDTO>(0);
	private Set<ValidacionDTO> validacionDTOs = new HashSet<ValidacionDTO>(0);
	private Set<FuncionArgumentoDTO> funcionArgumentoDTOs = new HashSet<FuncionArgumentoDTO>(
			0);
	private String rowid;

	public FuncionDTO() {
	}

	public FuncionDTO(String coFuncion, String tipo, String nombre) {
		this.coFuncion = coFuncion;
		this.tipo = tipo;
		this.nombre = nombre;
	}

	public FuncionDTO(String coFuncion, String tipo, String nombre,
			String descripcion, String clase, String metodo, String coPlsql,
			Date fhActualizacion, String coUsuarioActualizacion,
			Set<CorrespondenciaDTO> correspondenciaDTOs,
			Set<FormulaPasoDTO> formulaPasoDTOs,
			Set<ValidacionDTO> validacionDTOs,
			Set<FuncionArgumentoDTO> funcionArgumentoDTOs) {
		this.coFuncion = coFuncion;
		this.tipo = tipo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.clase = clase;
		this.metodo = metodo;
		this.coPlsql = coPlsql;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.correspondenciaDTOs = correspondenciaDTOs;
		this.formulaPasoDTOs = formulaPasoDTOs;
		this.validacionDTOs = validacionDTOs;
		this.funcionArgumentoDTOs = funcionArgumentoDTOs;
	}

	public String getCoFuncion() {
		return this.coFuncion;
	}

	public void setCoFuncion(String coFuncion) {
		this.coFuncion = coFuncion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getClase() {
		return this.clase;
	}

	public void setClase(String clase) {
		this.clase = clase;
	}

	public String getMetodo() {
		return this.metodo;
	}

	public void setMetodo(String metodo) {
		this.metodo = metodo;
	}

	public String getCoPlsql() {
		return this.coPlsql;
	}

	public void setCoPlsql(String coPlsql) {
		this.coPlsql = coPlsql;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<CorrespondenciaDTO> getCorrespondenciaDTOs() {
		return this.correspondenciaDTOs;
	}

	public void setCorrespondenciaDTOs(
			Set<CorrespondenciaDTO> correspondenciaDTOs) {
		this.correspondenciaDTOs = correspondenciaDTOs;
	}

	public Set<FormulaPasoDTO> getFormulaPasoDTOs() {
		return this.formulaPasoDTOs;
	}

	public void setFormulaPasoDTOs(Set<FormulaPasoDTO> formulaPasoDTOs) {
		this.formulaPasoDTOs = formulaPasoDTOs;
	}

	public Set<ValidacionDTO> getValidacionDTOs() {
		return this.validacionDTOs;
	}

	public void setValidacionDTOs(Set<ValidacionDTO> validacionDTOs) {
		this.validacionDTOs = validacionDTOs;
	}

	public Set<FuncionArgumentoDTO> getFuncionArgumentoDTOs() {
		return this.funcionArgumentoDTOs;
	}

	public void setFuncionArgumentoDTOs(
			Set<FuncionArgumentoDTO> funcionArgumentoDTOs) {
		this.funcionArgumentoDTOs = funcionArgumentoDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}
	
	public String getCodigoDescripcion() {
		return this.nombre + " (" + this.coFuncion + ")";
	}

}
