package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * FuncionArgumentoDTO generated by hbm2java
 */
public class FuncionArgumentoDTO implements java.io.Serializable {

	private FuncionArgumentoDTOId id;
	private FuncionDTO funcionDTO;
	private String nombre;
	private String formato;
	private BigDecimal longitud;
	private Boolean boEntrada;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Boolean boObligatorio;
	private Set<CorrespondenciaArgumentoDTO> correspondenciaArgumentoDTOs = new HashSet<CorrespondenciaArgumentoDTO>(
			0);
	private Set<ValidacionArgumentoDTO> validacionArgumentoDTOs = new HashSet<ValidacionArgumentoDTO>(
			0);
	private Set<CasillaMunicipioOperacionDTO> casillaMunicipioOperacionDTOs = new HashSet<CasillaMunicipioOperacionDTO>(
			0);
	private String rowid;

	public FuncionArgumentoDTO() {
	}

	public FuncionArgumentoDTO(FuncionArgumentoDTOId id, FuncionDTO funcionDTO) {
		this.id = id;
		this.funcionDTO = funcionDTO;
	}

	public FuncionArgumentoDTO(FuncionArgumentoDTOId id, FuncionDTO funcionDTO,
			String nombre, String formato, BigDecimal longitud,
			Boolean boEntrada, Date fhActualizacion,
			String coUsuarioActualizacion,
			Set<CorrespondenciaArgumentoDTO> correspondenciaArgumentoDTOs,
			Set<ValidacionArgumentoDTO> validacionArgumentoDTOs,
			Set<CasillaMunicipioOperacionDTO> casillaMunicipioOperacionDTOs) {
		this.id = id;
		this.funcionDTO = funcionDTO;
		this.nombre = nombre;
		this.formato = formato;
		this.longitud = longitud;
		this.boEntrada = boEntrada;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.correspondenciaArgumentoDTOs = correspondenciaArgumentoDTOs;
		this.validacionArgumentoDTOs = validacionArgumentoDTOs;
		this.casillaMunicipioOperacionDTOs = casillaMunicipioOperacionDTOs;
	}

	public FuncionArgumentoDTOId getId() {
		return this.id;
	}

	public void setId(FuncionArgumentoDTOId id) {
		this.id = id;
	}

	public FuncionDTO getFuncionDTO() {
		return this.funcionDTO;
	}

	public void setFuncionDTO(FuncionDTO funcionDTO) {
		this.funcionDTO = funcionDTO;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getFormato() {
		return this.formato;
	}

	public void setFormato(String formato) {
		this.formato = formato;
	}

	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	public Boolean getBoEntrada() {
		return this.boEntrada;
	}

	public void setBoEntrada(Boolean boEntrada) {
		this.boEntrada = boEntrada;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public Boolean getBoObligatorio() {
		return this.boObligatorio;
	}

	public void setBoObligatorio(Boolean boObligatorio) {
		this.boObligatorio = boObligatorio;
	}

	public Set<CorrespondenciaArgumentoDTO> getCorrespondenciaArgumentoDTOs() {
		return this.correspondenciaArgumentoDTOs;
	}

	public void setCorrespondenciaArgumentoDTOs(
			Set<CorrespondenciaArgumentoDTO> correspondenciaArgumentoDTOs) {
		this.correspondenciaArgumentoDTOs = correspondenciaArgumentoDTOs;
	}

	public Set<ValidacionArgumentoDTO> getValidacionArgumentoDTOs() {
		return this.validacionArgumentoDTOs;
	}

	public void setValidacionArgumentoDTOs(
			Set<ValidacionArgumentoDTO> validacionArgumentoDTOs) {
		this.validacionArgumentoDTOs = validacionArgumentoDTOs;
	}

	public Set<CasillaMunicipioOperacionDTO> getCasillaMunicipioOperacionDTOs() {
		return this.casillaMunicipioOperacionDTOs;
	}

	public void setCasillaMunicipioOperacionDTOs(
			Set<CasillaMunicipioOperacionDTO> casillaMunicipioOperacionDTOs) {
		this.casillaMunicipioOperacionDTOs = casillaMunicipioOperacionDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public String getCodigoDescripcion() {
		StringBuffer dc = new StringBuffer();
		dc.append(getId().getCoArgumentoFuncion());
		dc.append(" - ");
		dc.append(getNombre());
		dc.append(" (").append(getId().getCoFuncion()).append(")");
		return dc.toString();
	}

}
