package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * GarantiaDTO generated by hbm2java
 */
public class GarantiaDTO implements java.io.Serializable {

	private Long coGarantia;
	private String texto;
	private String tipo;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private Set<FraccionamientoGarDocDTO> fraccionamientoGarDocDTOs = new HashSet<FraccionamientoGarDocDTO>(
			0);
	private Set<FraccionamientoGarantiaDTO> fraccionamientoGarantiaDTOs = new HashSet<FraccionamientoGarantiaDTO>(
			0);
	
	private String rowid;

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public GarantiaDTO() {
	}

	public GarantiaDTO(String texto, String tipo,
			String coUsuarioActualizacion, Date fhActualizacion,
			Set<FraccionamientoGarDocDTO> fraccionamientoGarDocDTOs,
			Set<FraccionamientoGarantiaDTO> fraccionamientoGarantiaDTOs) {
		this.texto = texto;
		this.tipo = tipo;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.fraccionamientoGarDocDTOs = fraccionamientoGarDocDTOs;
		this.fraccionamientoGarantiaDTOs = fraccionamientoGarantiaDTOs;
	}

	public Long getCoGarantia() {
		return this.coGarantia;
	}

	public void setCoGarantia(Long coGarantia) {
		this.coGarantia = coGarantia;
	}

	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public Set<FraccionamientoGarDocDTO> getFraccionamientoGarDocDTOs() {
		return this.fraccionamientoGarDocDTOs;
	}

	public void setFraccionamientoGarDocDTOs(
			Set<FraccionamientoGarDocDTO> fraccionamientoGarDocDTOs) {
		this.fraccionamientoGarDocDTOs = fraccionamientoGarDocDTOs;
	}

	public Set<FraccionamientoGarantiaDTO> getFraccionamientoGarantiaDTOs() {
		return this.fraccionamientoGarantiaDTOs;
	}

	public void setFraccionamientoGarantiaDTOs(
			Set<FraccionamientoGarantiaDTO> fraccionamientoGarantiaDTOs) {
		this.fraccionamientoGarantiaDTOs = fraccionamientoGarantiaDTOs;
	}

}
