package es.dipucadiz.etir.comun.dto;

import java.io.IOException;
import java.io.InputStream;
import java.io.StringWriter;
import java.sql.Clob;
import java.sql.SQLException;
import java.util.Date;

import org.apache.commons.io.IOUtils;

import es.dipucadiz.etir.comun.bo.EjecucionBO;
import es.dipucadiz.etir.comun.bo.ProcesoBO;
import es.dipucadiz.etir.comun.config.GadirConfig;
import es.dipucadiz.etir.comun.exception.GadirServiceException;
import es.dipucadiz.etir.comun.utilidades.ControlTerritorial;
import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ConveniosDTO generated by hbm2java
 */
public class GestorTareasSeguimientoDTO implements java.io.Serializable {
	private static final long serialVersionUID = -4734740956600301542L;

	private GestorTareasSeguimientoDTOId id;
	private GestorTareasDTO gestorTareasDTO;
	private Date fhAlta;
	private Clob observaciones;
	private EjecucionDTO ejecucionDTO;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	
	public GestorTareasSeguimientoDTO() {
	}
	
	public GestorTareasSeguimientoDTO(GestorTareasSeguimientoDTOId id) {
		this.id = id;
	}

	public GestorTareasSeguimientoDTOId getId() {
		return id;
	}

	public void setId(GestorTareasSeguimientoDTOId id) {
		this.id = id;
	}

	public Date getFhAlta() {
		return fhAlta;
	}

	public void setFhAlta(Date fhAlta) {
		this.fhAlta = fhAlta;
	}

	public Clob getObservaciones() {
		return observaciones;
	}

	public void setObservaciones(Clob observaciones) {
		this.observaciones = observaciones;
	}

	public EjecucionDTO getEjecucionDTO() {
		return ejecucionDTO;
	}

	public void setEjecucionDTO(EjecucionDTO ejecucionDTO) {
		this.ejecucionDTO = ejecucionDTO;
	}

	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public GestorTareasDTO getGestorTareasDTO() {
		return gestorTareasDTO;
	}

	public void setGestorTareasDTO(GestorTareasDTO gestorTareasDTO) {
		this.gestorTareasDTO = gestorTareasDTO;
	}
	
	public String getObservacionesString(){
		if(this.observaciones != null){
				StringWriter w = new StringWriter();
				try {
					InputStream in = observaciones.getAsciiStream();
					IOUtils.copy(in, w);
				} catch (IOException e) {
					return "";
				} catch (SQLException e) {
					return "";
				}
				return w.toString();
			}
			return "";
	}	
	
	public String getDescripcionProceso(){
		String descripcion = "";
		try {
			if(ejecucionDTO != null){
				EjecucionBO ejBO =(EjecucionBO) GadirConfig.getBean("ejecucionBO");
				EjecucionDTO ejecucionDTOAux = ejBO.findById(ejecucionDTO.getCoEjecucion());
				if(ejecucionDTOAux.getProcesoDTO() != null) {
					ProcesoBO prBO =(ProcesoBO) GadirConfig.getBean("procesoBO");
					ProcesoDTO procesoDTOAux = prBO.findById(ejecucionDTOAux.getProcesoDTO().getCoProceso());
					descripcion = procesoDTOAux.getDescripcion();
				}
			}
		} catch (GadirServiceException e) {
			descripcion = "";
		}
		return descripcion;
	}	
}