package es.dipucadiz.etir.comun.dto;

import java.util.Date;

/**
 * ConveniosDTO generated by hbm2java
 */
public class GestorTareasRelacionDTO implements java.io.Serializable {
	private static final long serialVersionUID = 24287200543277350L;

	private GestorTareasRelacionDTOId id;
	private GestorTareasDTO gestorTareasDTO;
	private GestorTareasDTO gestorTareasRelacionadaDTO;
	private String tipoRelacion;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	
	public GestorTareasRelacionDTO() {
	}
	
	public GestorTareasRelacionDTO(GestorTareasRelacionDTOId id) {
		this.id = id;
	}

	public GestorTareasRelacionDTOId getId() {
		return id;
	}

	public void setId(GestorTareasRelacionDTOId id) {
		this.id = id;
	}

	public GestorTareasDTO getGestorTareasDTO() {
		return gestorTareasDTO;
	}

	public void setGestorTareasDTO(GestorTareasDTO gestorTareasDTO) {
		this.gestorTareasDTO = gestorTareasDTO;
	}

	public GestorTareasDTO getGestorTareasRelacionadaDTO() {
		return gestorTareasRelacionadaDTO;
	}

	public void setGestorTareasRelacionadaDTO(
			GestorTareasDTO gestorTareasRelacionadaDTO) {
		this.gestorTareasRelacionadaDTO = gestorTareasRelacionadaDTO;
	}

	public String getTipoRelacion() {
		return tipoRelacion;
	}

	public void setTipoRelacion(String tipoRelacion) {
		this.tipoRelacion = tipoRelacion;
	}

	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}
	
}