package es.dipucadiz.etir.comun.dto;

// Generated 14-ene-2011 12:09:45 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * HAcmUsuarioNotificacionDTO generated by hbm2java
 */
public class HAcmUsuarioNotificacionDTO implements java.io.Serializable {

	private Long id;
	private Long coAcmUsuarioNotificacion;
	private String coAcmUsuario;
	private String mensaje;
	private Short importancia;
	private String tipo;
	private Long coEjecucion;
	private Date fxInicio;
	private Date fxFin;
	private String coAcmUsuarioRemitente;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String HTipoMovimiento;

	private Integer totalUsuarios;
	private String razonSocial;
	private String fhActualizacionTime;
	
	private Date fhActualizacionConfirmado;
	
	private Integer totalConfirmados;
	
	public HAcmUsuarioNotificacionDTO() {
	}

	public HAcmUsuarioNotificacionDTO(Long coAcmUsuarioNotificacion,
			String coAcmUsuario, String mensaje, Short importancia,
			String tipo, Long coEjecucion, Date fxInicio, Date fxFin,
			String coAcmUsuarioRemitente, Date fhActualizacion,
			String coUsuarioActualizacion, String HTipoMovimiento) {
		this.coAcmUsuarioNotificacion = coAcmUsuarioNotificacion;
		this.coAcmUsuario = coAcmUsuario;
		this.mensaje = mensaje;
		this.importancia = importancia;
		this.tipo = tipo;
		this.coEjecucion = coEjecucion;
		this.fxInicio = fxInicio;
		this.fxFin = fxFin;
		this.coAcmUsuarioRemitente = coAcmUsuarioRemitente;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.HTipoMovimiento = HTipoMovimiento;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCoAcmUsuarioNotificacion() {
		return this.coAcmUsuarioNotificacion;
	}

	public void setCoAcmUsuarioNotificacion(Long coAcmUsuarioNotificacion) {
		this.coAcmUsuarioNotificacion = coAcmUsuarioNotificacion;
	}

	public String getCoAcmUsuario() {
		return this.coAcmUsuario;
	}

	public void setCoAcmUsuario(String coAcmUsuario) {
		this.coAcmUsuario = coAcmUsuario;
	}

	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Long getCoEjecucion() {
		return this.coEjecucion;
	}

	public void setCoEjecucion(Long coEjecucion) {
		this.coEjecucion = coEjecucion;
	}

	public Date getFxInicio() {
		return this.fxInicio;
	}

	public void setFxInicio(Date fxInicio) {
		this.fxInicio = fxInicio;
	}

	public Date getFxFin() {
		return this.fxFin;
	}

	public void setFxFin(Date fxFin) {
		this.fxFin = fxFin;
	}

	public String getCoAcmUsuarioRemitente() {
		return this.coAcmUsuarioRemitente;
	}

	public void setCoAcmUsuarioRemitente(String coAcmUsuarioRemitente) {
		this.coAcmUsuarioRemitente = coAcmUsuarioRemitente;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getFhActualizacionTime() {
		String fxActualizacion = "";
		if(!Utilidades.isEmpty(this.fhActualizacion))
			fxActualizacion = this.fhActualizacion.getTime()+"";
		return fxActualizacion;
	}

	public void setFhActualizacionTime(Date fhActualizacionTime) {
		this.fhActualizacionTime = fhActualizacionTime.getTime()+"";
	}
	
	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getHTipoMovimiento() {
		return this.HTipoMovimiento;
	}

	public void setHTipoMovimiento(String HTipoMovimiento) {
		this.HTipoMovimiento = HTipoMovimiento;
	}

	public Short getImportancia() {
		return importancia;
	}

	public void setImportancia(Short importancia) {
		this.importancia = importancia;
	}

	//////
	
	public String getCodigoDescripcion(){
		return coAcmUsuario + " - " + razonSocial; 
	}
	
	
	public String getStringFecha() {
		return Utilidades.dateToYYYYMMDDHHMMSSformateado(this.fhActualizacion);
	}

	public String getStringFechaONo() {
		String fecha = Utilidades.dateToYYYYMMDDHHMMSSformateado(this.fhActualizacion);
		return Utilidades.isEmpty(fecha) ? "No" : fecha;
	}
	
	public String getStringImportancia() {
		switch(importancia) {
			case 1:
				return "Area de notificaciones";
			case 2:
				return "Barra inferior";
			case 3:
				return "Ventana emergente";
			default:
				return importancia+"";
		}
	}
	
	public String getStringTipo() {
		if(tipo.equalsIgnoreCase("M"))
			return "";
		else if(tipo.equalsIgnoreCase("Q"))
			return "Se permite cerrar";
		else if(tipo.equalsIgnoreCase("L"))
			return "Solo en login";
		else if(tipo.equalsIgnoreCase("T"))
			return "No sólo en login";
		else if(tipo.equalsIgnoreCase("B"))
			return "";
		else 
			return tipo+"";
	}

	public String getStringOrigen() {
		if(tipo != null)
			return tipo.equalsIgnoreCase("B") ? "Batch" : "Online";
		else
			return "";
	}
	
	public Integer getTotalUsuarios() {
		return totalUsuarios;
	}

	public void setTotalUsuarios(Integer totalUsuarios) {
		this.totalUsuarios = totalUsuarios;
	}

	public String getRazonSocial() {
		return razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}
	
	public Date getFhActualizacionConfirmado() {
		return this.fhActualizacionConfirmado;
	}
	
	public void setFhActualizacionConfirmado(Date fhActualizacionConfirmado) {
		this.fhActualizacionConfirmado = fhActualizacionConfirmado;
	}

	public String getStringFechaONoConfirmado() {
		String fecha = Utilidades.dateToYYYYMMDDHHMMSSformateado(this.fhActualizacionConfirmado);
		return Utilidades.isEmpty(fecha) ? "No" : fecha;
	}

	public Integer getTotalConfirmados() {
		return totalConfirmados;
	}

	public void setTotalConfirmados(Integer totalConfirmados) {
		this.totalConfirmados = totalConfirmados;
	}
	
	
	
	
}
