package es.dipucadiz.etir.comun.dto;

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

// Generated 11-feb-2010 12:29:03 by Hibernate Tools 3.2.4.GA

/**
 * HCargoDTO generated by hbm2java
 */
public class HCalleDTO implements java.io.Serializable {

	private Long id;
	private Long coCalle;
	private String coProvincia;
	private String coMunicipio;
	private String sigla;
	private String nombreCalle;
	private String procedencia;
	private Integer coMunicipal;
	private Integer coDgc;
	private Long coCalleUbicacion;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String HTipoMovimiento;
	private String coProceso;
	private Long coEjecucion;
	private String rowid;
	
	

	public HCalleDTO() {
	}



	public HCalleDTO(Long id, Long coCalle, String coProvincia,
			String coMunicipio, String sigla, String nombreCalle,
			String procedencia, Integer coMunicipal, Integer coDgc,
			Long coCalleUbicacion, Date fhActualizacion,
			String coUsuarioActualizacion, String tipoMovimiento,
			String coProceso, Long coEjecucion, String rowid) {
		super();
		this.id = id;
		this.coCalle = coCalle;
		this.coProvincia = coProvincia;
		this.coMunicipio = coMunicipio;
		this.sigla = sigla;
		this.nombreCalle = nombreCalle;
		this.procedencia = procedencia;
		this.coMunicipal = coMunicipal;
		this.coDgc = coDgc;
		this.coCalleUbicacion = coCalleUbicacion;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		HTipoMovimiento = tipoMovimiento;
		this.coProceso = coProceso;
		this.coEjecucion = coEjecucion;
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}



	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}



	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}



	/**
	 * @return the sigla
	 */
	public String getSigla() {
		return sigla;
	}



	/**
	 * @param sigla the sigla to set
	 */
	public void setSigla(String sigla) {
		this.sigla = sigla;
	}



	/**
	 * @return the coCalle
	 */
	public Long getCoCalle() {
		return coCalle;
	}



	/**
	 * @param coCalle the coCalle to set
	 */
	public void setCoCalle(Long coCalle) {
		this.coCalle = coCalle;
	}



	/**
	 * @return the coProvincia
	 */
	public String getCoProvincia() {
		return coProvincia;
	}



	/**
	 * @param coProvincia the coProvincia to set
	 */
	public void setCoProvincia(String coProvincia) {
		this.coProvincia = coProvincia;
	}



	/**
	 * @return the coMunicipio
	 */
	public String getCoMunicipio() {
		return coMunicipio;
	}



	/**
	 * @param coMunicipio the coMunicipio to set
	 */
	public void setCoMunicipio(String coMunicipio) {
		this.coMunicipio = coMunicipio;
	}



	/**
	 * @return the nombreCalle
	 */
	public String getNombreCalle() {
		return nombreCalle;
	}



	/**
	 * @param nombreCalle the nombreCalle to set
	 */
	public void setNombreCalle(String nombreCalle) {
		this.nombreCalle = nombreCalle;
	}



	/**
	 * @return the procedencia
	 */
	public String getProcedencia() {
		return procedencia;
	}



	/**
	 * @param procedencia the procedencia to set
	 */
	public void setProcedencia(String procedencia) {
		this.procedencia = procedencia;
	}



	/**
	 * @return the coMunicipal
	 */
	public Integer getCoMunicipal() {
		return coMunicipal;
	}



	/**
	 * @param coMunicipal the coMunicipal to set
	 */
	public void setCoMunicipal(Integer coMunicipal) {
		this.coMunicipal = coMunicipal;
	}



	/**
	 * @return the coDgc
	 */
	public Integer getCoDgc() {
		return coDgc;
	}



	/**
	 * @param coDgc the coDgc to set
	 */
	public void setCoDgc(Integer coDgc) {
		this.coDgc = coDgc;
	}



	/**
	 * @return the coCalleUbicacion
	 */
	public Long getCoCalleUbicacion() {
		return coCalleUbicacion;
	}



	/**
	 * @param coCalleUbicacion the coCalleUbicacion to set
	 */
	public void setCoCalleUbicacion(Long coCalleUbicacion) {
		this.coCalleUbicacion = coCalleUbicacion;
	}



	/**
	 * @return the fhActualizacion
	 */
	public Date getFhActualizacion() {
		return fhActualizacion;
	}



	/**
	 * @param fhActualizacion the fhActualizacion to set
	 */
	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}



	/**
	 * @return the coUsuarioActualizacion
	 */
	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}



	/**
	 * @param coUsuarioActualizacion the coUsuarioActualizacion to set
	 */
	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}



	/**
	 * @return the hTipoMovimiento
	 */
	public String getHTipoMovimiento() {
		return HTipoMovimiento;
	}



	/**
	 * @param tipoMovimiento the hTipoMovimiento to set
	 */
	public void setHTipoMovimiento(String tipoMovimiento) {
		HTipoMovimiento = tipoMovimiento;
	}



	/**
	 * @return the coProceso
	 */
	public String getCoProceso() {
		return coProceso;
	}



	/**
	 * @param coProceso the coProceso to set
	 */
	public void setCoProceso(String coProceso) {
		this.coProceso = coProceso;
	}



	/**
	 * @return the coEjecucion
	 */
	public Long getCoEjecucion() {
		return coEjecucion;
	}



	/**
	 * @param coEjecucion the coEjecucion to set
	 */
	public void setCoEjecucion(Long coEjecucion) {
		this.coEjecucion = coEjecucion;
	}

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
