package es.dipucadiz.etir.comun.dto;

// Generated 23-jun-2010 11:22:57 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * HCasillaMunicipioOperaciDTO generated by hbm2java
 */
public class HCasillaMunicipioOperaciDTO implements java.io.Serializable {

	private Long id;
	private Long coCasillaMunicipio;
	private String coOperacion;
	private String atributo;
	private String coFuncion;
	private Integer coArgumentoFuncion;
	private String parametro;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String HTipoMovimiento;
	private String rowid;

	public HCasillaMunicipioOperaciDTO() {
	}

	public HCasillaMunicipioOperaciDTO(Long coCasillaMunicipio,
			String coOperacion, String atributo, String coFuncion,
			Integer coArgumentoFuncion, String parametro, Date fhActualizacion,
			String coUsuarioActualizacion, String HTipoMovimiento) {
		this.coCasillaMunicipio = coCasillaMunicipio;
		this.coOperacion = coOperacion;
		this.atributo = atributo;
		this.coFuncion = coFuncion;
		this.coArgumentoFuncion = coArgumentoFuncion;
		this.parametro = parametro;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.HTipoMovimiento = HTipoMovimiento;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCoCasillaMunicipio() {
		return this.coCasillaMunicipio;
	}

	public void setCoCasillaMunicipio(Long coCasillaMunicipio) {
		this.coCasillaMunicipio = coCasillaMunicipio;
	}

	public String getCoOperacion() {
		return this.coOperacion;
	}

	public void setCoOperacion(String coOperacion) {
		this.coOperacion = coOperacion;
	}

	public String getAtributo() {
		return this.atributo;
	}

	public void setAtributo(String atributo) {
		this.atributo = atributo;
	}

	public String getCoFuncion() {
		return this.coFuncion;
	}

	public void setCoFuncion(String coFuncion) {
		this.coFuncion = coFuncion;
	}

	public Integer getCoArgumentoFuncion() {
		return this.coArgumentoFuncion;
	}

	public void setCoArgumentoFuncion(Integer coArgumentoFuncion) {
		this.coArgumentoFuncion = coArgumentoFuncion;
	}

	public String getParametro() {
		return this.parametro;
	}

	public void setParametro(String parametro) {
		this.parametro = parametro;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getHTipoMovimiento() {
		return this.HTipoMovimiento;
	}

	public void setHTipoMovimiento(String HTipoMovimiento) {
		this.HTipoMovimiento = HTipoMovimiento;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
