package es.dipucadiz.etir.comun.dto;

// Generated 09-mar-2010 14:27:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * HClienteDTO generated by hbm2java
 */
public class HClienteDTO implements java.io.Serializable {

	private long id;
	private Long coCliente;
	private String identificador;
	private String razonSocial;
	private String anagrama;
	private String etiqueta;
	private String procedencia;
	private Date fxAlta;
	private Date fxBaja;
	private Boolean boActivo;
	private Date fxNacimiento;
	private Date fxFallecimiento;
	private String email;
	private String motivoBaja;
	private Integer telefono;
	private Integer fax;
	private Long coClienteRepresentante;
	private Long coClienteAsociado;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Boolean boSms;
	private Integer movil;
	private String HTipoMovimiento;
	private String coProceso;
	private Long coEjecucion;
	private String rowid;

	public HClienteDTO() {
	}

	public HClienteDTO(long id, String identificador, String razonSocial) {
		this.id = id;
		this.identificador = identificador;
		this.razonSocial = razonSocial;
	}

	public HClienteDTO(long id, Long coCliente, String identificador,
			String razonSocial, String anagrama, String etiqueta,
			String procedencia, Date fxAlta, Date fxBaja, Boolean boActivo,
			Date fxNacimiento, Date fxFallecimiento, String email,
			String motivoBaja, Integer telefono, Integer fax,
			Long coClienteRepresentante, Long coClienteAsociado,
			Date fhActualizacion, String coUsuarioActualizacion,
			String HTipoMovimiento, String coProceso, Long coEjecucion) {
		this.id = id;
		this.coCliente = coCliente;
		this.identificador = identificador;
		this.razonSocial = razonSocial;
		this.anagrama = anagrama;
		this.etiqueta = etiqueta;
		this.procedencia = procedencia;
		this.fxAlta = fxAlta;
		this.fxBaja = fxBaja;
		this.boActivo = boActivo;
		this.fxNacimiento = fxNacimiento;
		this.fxFallecimiento = fxFallecimiento;
		this.email = email;
		this.motivoBaja = motivoBaja;
		this.telefono = telefono;
		this.fax = fax;
		this.coClienteRepresentante = coClienteRepresentante;
		this.coClienteAsociado = coClienteAsociado;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.HTipoMovimiento = HTipoMovimiento;
		this.coProceso = coProceso;
		this.coEjecucion = coEjecucion;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Long getCoCliente() {
		return this.coCliente;
	}

	public void setCoCliente(Long coCliente) {
		this.coCliente = coCliente;
	}

	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getAnagrama() {
		return this.anagrama;
	}

	public void setAnagrama(String anagrama) {
		this.anagrama = anagrama;
	}

	public String getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(String etiqueta) {
		this.etiqueta = etiqueta;
	}

	public String getProcedencia() {
		return this.procedencia;
	}

	public void setProcedencia(String procedencia) {
		this.procedencia = procedencia;
	}

	public Date getFxAlta() {
		return this.fxAlta;
	}

	public void setFxAlta(Date fxAlta) {
		this.fxAlta = fxAlta;
	}

	public Date getFxBaja() {
		return this.fxBaja;
	}

	public void setFxBaja(Date fxBaja) {
		this.fxBaja = fxBaja;
	}

	public Boolean getBoActivo() {
		return this.boActivo;
	}

	public void setBoActivo(Boolean boActivo) {
		this.boActivo = boActivo;
	}

	public Date getFxNacimiento() {
		return this.fxNacimiento;
	}

	public void setFxNacimiento(Date fxNacimiento) {
		this.fxNacimiento = fxNacimiento;
	}

	public Date getFxFallecimiento() {
		return this.fxFallecimiento;
	}

	public void setFxFallecimiento(Date fxFallecimiento) {
		this.fxFallecimiento = fxFallecimiento;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMotivoBaja() {
		return this.motivoBaja;
	}

	public void setMotivoBaja(String motivoBaja) {
		this.motivoBaja = motivoBaja;
	}

	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public Integer getFax() {
		return this.fax;
	}

	public void setFax(Integer fax) {
		this.fax = fax;
	}

	/**
	 * @deprecated Usar ClienteRepresentanteDTO
	 */
	@Deprecated
	public Long getCoClienteRepresentante() {
		return this.coClienteRepresentante;
	}

	/**
	 * @deprecated Usar ClienteRepresentanteDTO
	 */
	@Deprecated
	public void setCoClienteRepresentante(Long coClienteRepresentante) {
		this.coClienteRepresentante = coClienteRepresentante;
	}

	public Long getCoClienteAsociado() {
		return this.coClienteAsociado;
	}

	public void setCoClienteAsociado(Long coClienteAsociado) {
		this.coClienteAsociado = coClienteAsociado;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public Boolean getBoSms() {
		return this.boSms;
	}

	public void setBoSms(Boolean boSms) {
		this.boSms = boSms;
	}
	
	public Integer getMovil() {
		return this.movil;
	}

	public void setMovil(Integer movil) {
		this.movil = movil;
	}

	public String getHTipoMovimiento() {
		return this.HTipoMovimiento;
	}

	public void setHTipoMovimiento(String HTipoMovimiento) {
		this.HTipoMovimiento = HTipoMovimiento;
	}

	public String getCoProceso() {
		return this.coProceso;
	}

	public void setCoProceso(String coProceso) {
		this.coProceso = coProceso;
	}

	public Long getCoEjecucion() {
		return this.coEjecucion;
	}

	public void setCoEjecucion(Long coEjecucion) {
		this.coEjecucion = coEjecucion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
