package es.dipucadiz.etir.comun.dto;

// Generated 09-mar-2010 14:27:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * HDocumentoDTO generated by hbm2java
 */
public class HDocumentoDTO implements java.io.Serializable {

	private Long id;
	private String coModelo;
	private String coVersion;
	private String coDocumento;
	private Long coCliente;
	private Long coDomicilio;
	private String coProvincia;
	private String coMunicipio;
	private String coConcepto;
	private Short ejercicio;
	private String periodo;
	private String refObjTributario1;
	private String refObjTributario2;
	private String refObjTributario3;
	private String coUnidadAdministrativa;
	private String coCodigoTerritorial;
	private Date fxPresentacion;
	private Date fxDevengo;
	private String estado;
	private String procedencia;
	private Long coCargaControlRecepcion;
	private String coDocumentoOrigen;
	private String coModeloOrigen;
	private String coVersionOrigen;
	private String coDocumentoResumen;
	private String coModeloResumen;
	private String coVersionResumen;
	private String coSituacion;
	private Boolean boIndividual;
	private String refCatastral;
	private Integer coDomiciliacion;
	private String refDomiciliacion;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Long coDomicilioFiscal;
	private String HTipoMovimiento;
	private String coProceso;
	private Long coEjecucion;
	private Long coIncidenciaSituacion;
	private String rowid;

	public HDocumentoDTO() {
	}

	public HDocumentoDTO(String coProvincia, String coMunicipio) {
		this.coProvincia = coProvincia;
		this.coMunicipio = coMunicipio;
	}

	public HDocumentoDTO(String coModelo, String coVersion, String coDocumento,
			Long coCliente, Long coDomicilio, String coProvincia,
			String coMunicipio, String coConcepto, Short ejercicio,
			String periodo, String refObjTributario3, String refObjTributario1,
			String refObjTributario2, String coUnidadAdministrativa,
			String coCodigoTerritorial, Date fxPresentacion, Date fxDevengo,
			String estado, String procedencia, Long coCargaControlRecepcion,
			String coDocumentoOrigen, String coModeloOrigen,
			String coVersionOrigen, String coDocumentoResumen,
			String coModeloResumen, String coVersionResumen,
			String coSituacion, Boolean boIndividual, String refCatastral,
			Integer coDomiciliacion, String refDomiciliacion, 
			Date fhActualizacion,
			String coUsuarioActualizacion, Long coDomicilioFiscal,
			String HTipoMovimiento, String coProceso, Long coEjecucion,
			Long coIncidenciaSituacion) {
		this.coModelo = coModelo;
		this.coVersion = coVersion;
		this.coDocumento = coDocumento;
		this.coCliente = coCliente;
		this.coDomicilio = coDomicilio;
		this.coProvincia = coProvincia;
		this.coMunicipio = coMunicipio;
		this.coConcepto = coConcepto;
		this.ejercicio = ejercicio;
		this.periodo = periodo;
		this.refObjTributario3 = refObjTributario3;
		this.refObjTributario1 = refObjTributario1;
		this.refObjTributario2 = refObjTributario2;
		this.coUnidadAdministrativa = coUnidadAdministrativa;
		this.coCodigoTerritorial = coCodigoTerritorial;
		this.fxPresentacion = fxPresentacion;
		this.fxDevengo = fxDevengo;
		this.estado = estado;
		this.procedencia = procedencia;
		this.coCargaControlRecepcion = coCargaControlRecepcion;
		this.coDocumentoOrigen = coDocumentoOrigen;
		this.coModeloOrigen = coModeloOrigen;
		this.coVersionOrigen = coVersionOrigen;
		this.coDocumentoResumen = coDocumentoResumen;
		this.coModeloResumen = coModeloResumen;
		this.coVersionResumen = coVersionResumen;
		this.coSituacion = coSituacion;
		this.boIndividual = boIndividual;
		this.refCatastral = refCatastral;
		this.coDomiciliacion = coDomiciliacion;
		this.refDomiciliacion = refDomiciliacion;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.coDomicilioFiscal = coDomicilioFiscal;
		this.HTipoMovimiento = HTipoMovimiento;
		this.coProceso = coProceso;
		this.coEjecucion = coEjecucion;
		this.coIncidenciaSituacion = coIncidenciaSituacion;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCoModelo() {
		return this.coModelo;
	}

	public void setCoModelo(String coModelo) {
		this.coModelo = coModelo;
	}

	public String getCoVersion() {
		return this.coVersion;
	}

	public void setCoVersion(String coVersion) {
		this.coVersion = coVersion;
	}

	public String getCoDocumento() {
		return this.coDocumento;
	}

	public void setCoDocumento(String coDocumento) {
		this.coDocumento = coDocumento;
	}

	public Long getCoCliente() {
		return this.coCliente;
	}

	public void setCoCliente(Long coCliente) {
		this.coCliente = coCliente;
	}

	public Long getCoDomicilio() {
		return this.coDomicilio;
	}

	public void setCoDomicilio(Long coDomicilio) {
		this.coDomicilio = coDomicilio;
	}

	public String getCoProvincia() {
		return this.coProvincia;
	}

	public void setCoProvincia(String coProvincia) {
		this.coProvincia = coProvincia;
	}

	public String getCoMunicipio() {
		return this.coMunicipio;
	}

	public void setCoMunicipio(String coMunicipio) {
		this.coMunicipio = coMunicipio;
	}

	public String getCoConcepto() {
		return this.coConcepto;
	}

	public void setCoConcepto(String coConcepto) {
		this.coConcepto = coConcepto;
	}

	public Short getEjercicio() {
		return this.ejercicio;
	}

	public void setEjercicio(Short ejercicio) {
		this.ejercicio = ejercicio;
	}

	public String getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(String periodo) {
		this.periodo = periodo;
	}

	public String getRefObjTributario1() {
		return this.refObjTributario1;
	}

	public void setRefObjTributario1(String refObjTributario1) {
		this.refObjTributario1 = refObjTributario1;
	}

	public String getRefObjTributario2() {
		return this.refObjTributario2;
	}

	public void setRefObjTributario2(String refObjTributario2) {
		this.refObjTributario2 = refObjTributario2;
	}

	public String getRefObjTributario3() {
		return this.refObjTributario3;
	}

	public void setRefObjTributario3(String refObjTributario3) {
		this.refObjTributario3 = refObjTributario3;
	}

	public String getCoUnidadAdministrativa() {
		return this.coUnidadAdministrativa;
	}

	public void setCoUnidadAdministrativa(String coUnidadAdministrativa) {
		this.coUnidadAdministrativa = coUnidadAdministrativa;
	}

	public String getCoCodigoTerritorial() {
		return this.coCodigoTerritorial;
	}

	public void setCoCodigoTerritorial(String coCodigoTerritorial) {
		this.coCodigoTerritorial = coCodigoTerritorial;
	}

	public Date getFxPresentacion() {
		return this.fxPresentacion;
	}

	public void setFxPresentacion(Date fxPresentacion) {
		this.fxPresentacion = fxPresentacion;
	}

	public Date getFxDevengo() {
		return this.fxDevengo;
	}

	public void setFxDevengo(Date fxDevengo) {
		this.fxDevengo = fxDevengo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getProcedencia() {
		return this.procedencia;
	}

	public void setProcedencia(String procedencia) {
		this.procedencia = procedencia;
	}

	public Long getCoCargaControlRecepcion() {
		return this.coCargaControlRecepcion;
	}

	public void setCoCargaControlRecepcion(Long coCargaControlRecepcion) {
		this.coCargaControlRecepcion = coCargaControlRecepcion;
	}

	public String getCoDocumentoOrigen() {
		return this.coDocumentoOrigen;
	}

	public void setCoDocumentoOrigen(String coDocumentoOrigen) {
		this.coDocumentoOrigen = coDocumentoOrigen;
	}

	public String getCoModeloOrigen() {
		return this.coModeloOrigen;
	}

	public void setCoModeloOrigen(String coModeloOrigen) {
		this.coModeloOrigen = coModeloOrigen;
	}

	public String getCoVersionOrigen() {
		return this.coVersionOrigen;
	}

	public void setCoVersionOrigen(String coVersionOrigen) {
		this.coVersionOrigen = coVersionOrigen;
	}

	public String getCoDocumentoResumen() {
		return this.coDocumentoResumen;
	}

	public void setCoDocumentoResumen(String coDocumentoResumen) {
		this.coDocumentoResumen = coDocumentoResumen;
	}

	public String getCoModeloResumen() {
		return this.coModeloResumen;
	}

	public void setCoModeloResumen(String coModeloResumen) {
		this.coModeloResumen = coModeloResumen;
	}

	public String getCoVersionResumen() {
		return this.coVersionResumen;
	}

	public void setCoVersionResumen(String coVersionResumen) {
		this.coVersionResumen = coVersionResumen;
	}

	public String getCoSituacion() {
		return this.coSituacion;
	}

	public void setCoSituacion(String coSituacion) {
		this.coSituacion = coSituacion;
	}

	public Boolean getBoIndividual() {
		return this.boIndividual;
	}

	public void setBoIndividual(Boolean boIndividual) {
		this.boIndividual = boIndividual;
	}

	public String getRefCatastral() {
		return this.refCatastral;
	}

	public void setRefCatastral(String refCatastral) {
		this.refCatastral = refCatastral;
	}

	public Integer getCoDomiciliacion() {
		return this.coDomiciliacion;
	}

	public void setCoDomiciliacion(Integer coDomiciliacion) {
		this.coDomiciliacion = coDomiciliacion;
	}

	public String getRefDomiciliacion() {
		return this.refDomiciliacion;
	}

	public void setRefDomiciliacion(String refDomiciliacion) {
		this.refDomiciliacion = refDomiciliacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Long getCoDomicilioFiscal() {
		return this.coDomicilioFiscal;
	}

	public void setCoDomicilioFiscal(Long coDomicilioFiscal) {
		this.coDomicilioFiscal = coDomicilioFiscal;
	}

	public String getHTipoMovimiento() {
		return this.HTipoMovimiento;
	}

	public void setHTipoMovimiento(String HTipoMovimiento) {
		this.HTipoMovimiento = HTipoMovimiento;
	}

	public String getCoProceso() {
		return this.coProceso;
	}

	public void setCoProceso(String coProceso) {
		this.coProceso = coProceso;
	}

	public Long getCoEjecucion() {
		return this.coEjecucion;
	}

	public void setCoEjecucion(Long coEjecucion) {
		this.coEjecucion = coEjecucion;
	}
	
	public Long getCoIncidenciaSituacion() {
		return this.coIncidenciaSituacion;
	}

	public void setCoIncidenciaSituacion(Long coIncidenciaSituacion) {
		this.coIncidenciaSituacion = coIncidenciaSituacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
