package es.dipucadiz.etir.comun.dto;

// Generated 09-mar-2010 14:27:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * HDocumentoCensoDTO generated by hbm2java
 */
public class HDocumentoCensoDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String coModelo;
	private String coVersion;
	private String coDocumento;
	private Date fxAlta;
	private Date fxBaja;
	private Boolean boActivo;
	private String tipoMovimiento;
	private Short ejercicioPadron;
	private String periodoPadron;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String HTipoMovimiento;
	private String coProceso;
	private Long coEjecucion;
	private String observaciones;
	private Date fxTramite;
	private String rowid;

	public HDocumentoCensoDTO() {
	}

	public HDocumentoCensoDTO(String coModelo, String coVersion,
			String coDocumento, Date fxAlta, Date fxBaja, Boolean boActivo,
			String tipoMovimiento, Short ejercicioPadron, String periodoPadron,
			Date fhActualizacion, String coUsuarioActualizacion,
			String HTipoMovimiento, String coProceso, Long coEjecucion,
			String observaciones, Date fxTramite) {
		this.coModelo = coModelo;
		this.coVersion = coVersion;
		this.coDocumento = coDocumento;
		this.fxAlta = fxAlta;
		this.fxBaja = fxBaja;
		this.boActivo = boActivo;
		this.tipoMovimiento = tipoMovimiento;
		this.ejercicioPadron = ejercicioPadron;
		this.periodoPadron = periodoPadron;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.HTipoMovimiento = HTipoMovimiento;
		this.coProceso = coProceso;
		this.coEjecucion = coEjecucion;
		this.observaciones = observaciones;
		this.fxTramite = fxTramite;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCoModelo() {
		return this.coModelo;
	}

	public void setCoModelo(String coModelo) {
		this.coModelo = coModelo;
	}

	public String getCoVersion() {
		return this.coVersion;
	}

	public void setCoVersion(String coVersion) {
		this.coVersion = coVersion;
	}

	public String getCoDocumento() {
		return this.coDocumento;
	}

	public void setCoDocumento(String coDocumento) {
		this.coDocumento = coDocumento;
	}

	public Date getFxAlta() {
		return this.fxAlta;
	}

	public void setFxAlta(Date fxAlta) {
		this.fxAlta = fxAlta;
	}

	public Date getFxBaja() {
		return this.fxBaja;
	}

	public void setFxBaja(Date fxBaja) {
		this.fxBaja = fxBaja;
	}

	public Boolean getBoActivo() {
		return this.boActivo;
	}

	public void setBoActivo(Boolean boActivo) {
		this.boActivo = boActivo;
	}

	public String getTipoMovimiento() {
		return this.tipoMovimiento;
	}

	public void setTipoMovimiento(String tipoMovimiento) {
		this.tipoMovimiento = tipoMovimiento;
	}

	public Short getEjercicioPadron() {
		return this.ejercicioPadron;
	}

	public void setEjercicioPadron(Short ejercicioPadron) {
		this.ejercicioPadron = ejercicioPadron;
	}

	public String getPeriodoPadron() {
		return this.periodoPadron;
	}

	public void setPeriodoPadron(String periodoPadron) {
		this.periodoPadron = periodoPadron;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getHTipoMovimiento() {
		return this.HTipoMovimiento;
	}

	public void setHTipoMovimiento(String HTipoMovimiento) {
		this.HTipoMovimiento = HTipoMovimiento;
	}

	public String getCoProceso() {
		return this.coProceso;
	}

	public void setCoProceso(String coProceso) {
		this.coProceso = coProceso;
	}

	public Long getCoEjecucion() {
		return this.coEjecucion;
	}

	public void setCoEjecucion(Long coEjecucion) {
		this.coEjecucion = coEjecucion;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Date getFxTramite() {
		return this.fxTramite;
	}

	public void setFxTramite(Date fxTramite) {
		this.fxTramite = fxTramite;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
