package es.dipucadiz.etir.comun.dto;

// Generated 09-mar-2010 14:27:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;
import java.sql.Clob;
import java.util.Date;
/**
 * HDocumentoDTO generated by hbm2java
 */
public class HGestorTareasDTO implements java.io.Serializable {

		private static final long serialVersionUID = 4264788357633096915L;
		
		private Long id;
		private String HTipoMovimiento;
		private Long nuTarea;
		private String titulo;
		private String aplicacion;
		private String coTipo;
		private String coSubtipo;
		private Date fxEntrada;
		private Date fxPrevistoInicio;
		private Date fxInicio;
		private Date fxPrevistoFin;
		private Date fxFin;
		private String coUsuarioAlta;
		private String coUsuarioReceptor;
		private String coUsuarioEmisor;
		private String nombreEmisor;
		private String coTipoSoporte;
		private String coUsuarioAsignado;
		private String estado;
		private Short poRealizado;
		private String prioridad;
		private Clob observaciones;
		private BDDocumentalGrupoDTO bddocGrupoDocumentacionDTO; 
		private BDDocumentalGrupoDTO bddocGrupoFicheroDTO; 
		private String organoPrimerNivel;
		private UnidadAdministrativaDTO unidadAdministrativaDTO;
		private MunicipioDTO municipioAfectadoDTO;
		private String coUsuarioActualizacion;
		private Date fhActualizacion;
		
		public HGestorTareasDTO() {
		}
		
		public Long getNuTarea() {
			return nuTarea;
		}

		public void setNuTarea(Long nuTarea) {
			this.nuTarea = nuTarea;
		}

		public String getCoTipo() {
			return coTipo;
		}

		public void setCoTipo(String coTipo) {
			this.coTipo = coTipo;
		}

		public String getCoSubtipo() {
			return coSubtipo;
		}

		public void setCoSubtipo(String coSubtipo) {
			this.coSubtipo = coSubtipo;
		}

		public Date getFxEntrada() {
			return fxEntrada;
		}

		public void setFxEntrada(Date fxEntrada) {
			this.fxEntrada = fxEntrada;
		}

		public Date getFxPrevistoInicio() {
			return fxPrevistoInicio;
		}

		public void setFxPrevistoInicio(Date fxPrevistoInicio) {
			this.fxPrevistoInicio = fxPrevistoInicio;
		}

		public Date getFxInicio() {
			return fxInicio;
		}

		public void setFxInicio(Date fxInicio) {
			this.fxInicio = fxInicio;
		}

		public Date getFxPrevistoFin() {
			return fxPrevistoFin;
		}

		public void setFxPrevistoFin(Date fxPrevistoFin) {
			this.fxPrevistoFin = fxPrevistoFin;
		}

		public Date getFxFin() {
			return fxFin;
		}

		public void setFxFin(Date fxFin) {
			this.fxFin = fxFin;
		}

		public String getCoUsuarioAlta() {
			return coUsuarioAlta;
		}

		public void setCoUsuarioAlta(String coUsuarioAlta) {
			this.coUsuarioAlta = coUsuarioAlta;
		}

		public String getCoUsuarioReceptor() {
			return coUsuarioReceptor;
		}

		public void setCoUsuarioReceptor(String coUsuarioReceptor) {
			this.coUsuarioReceptor = coUsuarioReceptor;
		}

		public String getCoUsuarioEmisor() {
			return coUsuarioEmisor;
		}

		public void setCoUsuarioEmisor(String coUsuarioEmisor) {
			this.coUsuarioEmisor = coUsuarioEmisor;
		}

		public String getNombreEmisor() {
			return nombreEmisor;
		}

		public void setNombreEmisor(String nombreEmisor) {
			this.nombreEmisor = nombreEmisor;
		}

		public String getCoTipoSoporte() {
			return coTipoSoporte;
		}

		public void setCoTipoSoporte(String coTipoSoporte) {
			this.coTipoSoporte = coTipoSoporte;
		}

		public String getCoUsuarioAsignado() {
			return coUsuarioAsignado;
		}

		public void setCoUsuarioAsignado(String coUsuarioAsignado) {
			this.coUsuarioAsignado = coUsuarioAsignado;
		}

		public String getEstado() {
			return estado;
		}

		public void setEstado(String estado) {
			this.estado = estado;
		}

		public Short getPoRealizado() {
			return poRealizado;
		}

		public void setPoRealizado(Short poRealizado) {
			this.poRealizado = poRealizado;
		}

		public String getPrioridad() {
			return prioridad;
		}

		public void setPrioridad(String prioridad) {
			this.prioridad = prioridad;
		}

		public Clob getObservaciones() {
			return observaciones;
		}

		public void setObservaciones(Clob observaciones) {
			this.observaciones = observaciones;
		}

		public BDDocumentalGrupoDTO getBddocGrupoDocumentacionDTO() {
			return bddocGrupoDocumentacionDTO;
		}

		public void setBddocGrupoDocumentacionDTO(
				BDDocumentalGrupoDTO bddocGrupoDocumentacionDTO) {
			this.bddocGrupoDocumentacionDTO = bddocGrupoDocumentacionDTO;
		}

		public BDDocumentalGrupoDTO getBddocGrupoFicheroDTO() {
			return bddocGrupoFicheroDTO;
		}

		public void setBddocGrupoFicheroDTO(BDDocumentalGrupoDTO bddocGrupoFicheroDTO) {
			this.bddocGrupoFicheroDTO = bddocGrupoFicheroDTO;
		}

		public String getOrganoPrimerNivel() {
			return organoPrimerNivel;
		}

		public void setOrganoPrimerNivel(String organoPrimerNivel) {
			this.organoPrimerNivel = organoPrimerNivel;
		}

		public UnidadAdministrativaDTO getUnidadAdministrativaDTO() {
			return unidadAdministrativaDTO;
		}

		public void setUnidadAdministrativaDTO(
				UnidadAdministrativaDTO unidadAdministrativaDTO) {
			this.unidadAdministrativaDTO = unidadAdministrativaDTO;
		}

		public MunicipioDTO getMunicipioAfectadoDTO() {
			return municipioAfectadoDTO;
		}

		public void setMunicipioAfectadoDTO(MunicipioDTO municipioAfectadoDTO) {
			this.municipioAfectadoDTO = municipioAfectadoDTO;
		}

		public String getCoUsuarioActualizacion() {
			return coUsuarioActualizacion;
		}

		public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
			this.coUsuarioActualizacion = coUsuarioActualizacion;
		}

		public Date getFhActualizacion() {
			return fhActualizacion;
		}

		public void setFhActualizacion(Date fhActualizacion) {
			this.fhActualizacion = fhActualizacion;
		}

		public String getTitulo() {
			return titulo;
		}

		public void setTitulo(String titulo) {
			this.titulo = titulo;
		}

		public String getAplicacion() {
			return aplicacion;
		}

		public void setAplicacion(String aplicacion) {
			this.aplicacion = aplicacion;
		}

		public Long getId() {
			return id;
		}

		public void setId(Long id) {
			this.id = id;
		}

		public String getHTipoMovimiento() {
			return HTipoMovimiento;
		}

		public void setHTipoMovimiento(String hTipoMovimiento) {
			HTipoMovimiento = hTipoMovimiento;
		}

		
	}


