package es.dipucadiz.etir.comun.dto;

// Generated 26-may-2010 13:41:37 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * HNotificacionDGCDTO generated by hbm2java
 */
public class HNotificacionDGCDTO implements java.io.Serializable {

	private Long id;
	private Long coNotificacionDgc;
	private String coModelo;
	private String coVersion;
	private String coDocumento;
	private String expedienteDgc;
	private short anoExpediente;
	private String coProvincia;
	private String coMunicipio;
	private Long coClienteTitular;
	private Long coClienteDestinatario;
	private Integer documentoExpediente;
	private Boolean boLiquidable;
	private Date fxEnvioBop;
	private String resultadoNotificacion;
	private Date fxNotificacion;
	private Boolean boLiquidado;
	private Boolean boEnviadoSigre;
	private String tipo;
	private Boolean boResolucionPapel;
	private String estado;
	private Boolean boNotificacionBop;
	private Byte coDgc;
	private Date fhEnvioSigre;
	private Date fhImpresion;
	private Date fxDevolucionDgc;
	private Short ejerEfectoIbi;
	private Short ejerEntradaPadron;
	private String tipoAlteracion;
	private Long grupoAnulacion;
	private Date fhAnulacion;
	private Date fxEnvioNotificado;
	private Date fxPublicacionBop;
	private Long grupoBop;
	private String tipoProcedimiento;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String HTipoMovimiento;
	private String rowid;

	public HNotificacionDGCDTO() {
	}

	public HNotificacionDGCDTO(long id, String coModelo, String coVersion,
			String coDocumento, String expedienteDgc, short anoExpediente) {
		this.id = id;
		this.coModelo = coModelo;
		this.coVersion = coVersion;
		this.coDocumento = coDocumento;
		this.expedienteDgc = expedienteDgc;
		this.anoExpediente = anoExpediente;
	}



	public HNotificacionDGCDTO(Long id, Long coNotificacionDgc,
			String coModelo, String coVersion, String coDocumento,
			String expedienteDgc, short anoExpediente, String coProvincia,
			String coMunicipio, Long coClienteTitular,
			Long coClienteDestinatario, Integer documentoExpediente,
			Boolean boLiquidable, Date fxEnvioBop,
			String resultadoNotificacion, Date fxNotificacion,
			Boolean boLiquidado, Boolean boEnviadoSigre, String tipo,
			Boolean boResolucionPapel, String estado,
			Boolean boNotificacionBop, Byte coDgc, Date fhEnvioSigre,
			Date fhImpresion, Date fxDevolucionDgc, Short ejerEfectoIbi,
			Short ejerEntradaPadron, String tipoAlteracion,
			Long grupoAnulacion, Date fhAnulacion, Date fxEnvioNotificado,
			Date fxPublicacionBop, Long grupoBop, String tipoProcedimiento,
			Date fhActualizacion, String coUsuarioActualizacion,
			String tipoMovimiento, String rowid) {
		super();
		this.id = id;
		this.coNotificacionDgc = coNotificacionDgc;
		this.coModelo = coModelo;
		this.coVersion = coVersion;
		this.coDocumento = coDocumento;
		this.expedienteDgc = expedienteDgc;
		this.anoExpediente = anoExpediente;
		this.coProvincia = coProvincia;
		this.coMunicipio = coMunicipio;
		this.coClienteTitular = coClienteTitular;
		this.coClienteDestinatario = coClienteDestinatario;
		this.documentoExpediente = documentoExpediente;
		this.boLiquidable = boLiquidable;
		this.fxEnvioBop = fxEnvioBop;
		this.resultadoNotificacion = resultadoNotificacion;
		this.fxNotificacion = fxNotificacion;
		this.boLiquidado = boLiquidado;
		this.boEnviadoSigre = boEnviadoSigre;
		this.tipo = tipo;
		this.boResolucionPapel = boResolucionPapel;
		this.estado = estado;
		this.boNotificacionBop = boNotificacionBop;
		this.coDgc = coDgc;
		this.fhEnvioSigre = fhEnvioSigre;
		this.fhImpresion = fhImpresion;
		this.fxDevolucionDgc = fxDevolucionDgc;
		this.ejerEfectoIbi = ejerEfectoIbi;
		this.ejerEntradaPadron = ejerEntradaPadron;
		this.tipoAlteracion = tipoAlteracion;
		this.grupoAnulacion = grupoAnulacion;
		this.fhAnulacion = fhAnulacion;
		this.fxEnvioNotificado = fxEnvioNotificado;
		this.fxPublicacionBop = fxPublicacionBop;
		this.grupoBop = grupoBop;
		this.tipoProcedimiento = tipoProcedimiento;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		HTipoMovimiento = tipoMovimiento;
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public Long getId() {
		return this.id;
	}

	
	/**
	 * @return the rowid
	 */
	public String getRowid() {
		return rowid;
	}

	/**
	 * @param rowid the rowid to set
	 */
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCoNotificacionDgc() {
		return this.coNotificacionDgc;
	}

	public void setCoNotificacionDgc(Long coNotificacionDgc) {
		this.coNotificacionDgc = coNotificacionDgc;
	}

	public String getCoModelo() {
		return this.coModelo;
	}

	public void setCoModelo(String coModelo) {
		this.coModelo = coModelo;
	}

	public String getCoVersion() {
		return this.coVersion;
	}

	public void setCoVersion(String coVersion) {
		this.coVersion = coVersion;
	}

	public String getCoDocumento() {
		return this.coDocumento;
	}

	public void setCoDocumento(String coDocumento) {
		this.coDocumento = coDocumento;
	}

	public String getExpedienteDgc() {
		return this.expedienteDgc;
	}

	public void setExpedienteDgc(String expedienteDgc) {
		this.expedienteDgc = expedienteDgc;
	}

	public short getAnoExpediente() {
		return this.anoExpediente;
	}

	public void setAnoExpediente(short anoExpediente) {
		this.anoExpediente = anoExpediente;
	}

	public String getCoProvincia() {
		return this.coProvincia;
	}

	public void setCoProvincia(String coProvincia) {
		this.coProvincia = coProvincia;
	}

	public String getCoMunicipio() {
		return this.coMunicipio;
	}

	public void setCoMunicipio(String coMunicipio) {
		this.coMunicipio = coMunicipio;
	}

	public Long getCoClienteTitular() {
		return this.coClienteTitular;
	}

	public void setCoClienteTitular(Long coClienteTitular) {
		this.coClienteTitular = coClienteTitular;
	}

	public Long getCoClienteDestinatario() {
		return this.coClienteDestinatario;
	}

	public void setCoClienteDestinatario(Long coClienteDestinatario) {
		this.coClienteDestinatario = coClienteDestinatario;
	}

	public Integer getDocumentoExpediente() {
		return this.documentoExpediente;
	}

	public void setDocumentoExpediente(Integer documentoExpediente) {
		this.documentoExpediente = documentoExpediente;
	}

	public Boolean getBoLiquidable() {
		return this.boLiquidable;
	}

	public void setBoLiquidable(Boolean boLiquidable) {
		this.boLiquidable = boLiquidable;
	}

	public Date getFxEnvioBop() {
		return this.fxEnvioBop;
	}

	public void setFxEnvioBop(Date fxEnvioBop) {
		this.fxEnvioBop = fxEnvioBop;
	}

	public String getResultadoNotificacion() {
		return this.resultadoNotificacion;
	}

	public void setResultadoNotificacion(String resultadoNotificacion) {
		this.resultadoNotificacion = resultadoNotificacion;
	}

	public Date getFxNotificacion() {
		return this.fxNotificacion;
	}

	public void setFxNotificacion(Date fxNotificacion) {
		this.fxNotificacion = fxNotificacion;
	}

	public Boolean getBoLiquidado() {
		return this.boLiquidado;
	}

	public void setBoLiquidado(Boolean boLiquidado) {
		this.boLiquidado = boLiquidado;
	}

	public Boolean getBoEnviadoSigre() {
		return this.boEnviadoSigre;
	}

	public void setBoEnviadoSigre(Boolean boEnviadoSigre) {
		this.boEnviadoSigre = boEnviadoSigre;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Boolean getBoResolucionPapel() {
		return this.boResolucionPapel;
	}

	public void setBoResolucionPapel(Boolean boResolucionPapel) {
		this.boResolucionPapel = boResolucionPapel;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Boolean getBoNotificacionBop() {
		return this.boNotificacionBop;
	}

	public void setBoNotificacionBop(Boolean boNotificacionBop) {
		this.boNotificacionBop = boNotificacionBop;
	}

	public Byte getCoDgc() {
		return this.coDgc;
	}

	public void setCoDgc(Byte coDgc) {
		this.coDgc = coDgc;
	}

	public Date getFhEnvioSigre() {
		return this.fhEnvioSigre;
	}

	public void setFhEnvioSigre(Date fhEnvioSigre) {
		this.fhEnvioSigre = fhEnvioSigre;
	}

	public Date getFhImpresion() {
		return this.fhImpresion;
	}

	public void setFhImpresion(Date fhImpresion) {
		this.fhImpresion = fhImpresion;
	}

	public Date getFxDevolucionDgc() {
		return this.fxDevolucionDgc;
	}

	public void setFxDevolucionDgc(Date fxDevolucionDgc) {
		this.fxDevolucionDgc = fxDevolucionDgc;
	}

	public Short getEjerEfectoIbi() {
		return this.ejerEfectoIbi;
	}

	public void setEjerEfectoIbi(Short ejerEfectoIbi) {
		this.ejerEfectoIbi = ejerEfectoIbi;
	}

	public Short getEjerEntradaPadron() {
		return this.ejerEntradaPadron;
	}

	public void setEjerEntradaPadron(Short ejerEntradaPadron) {
		this.ejerEntradaPadron = ejerEntradaPadron;
	}

	public String getTipoAlteracion() {
		return this.tipoAlteracion;
	}

	public void setTipoAlteracion(String tipoAlteracion) {
		this.tipoAlteracion = tipoAlteracion;
	}

	public Long getGrupoAnulacion() {
		return this.grupoAnulacion;
	}

	public void setGrupoAnulacion(Long grupoAnulacion) {
		this.grupoAnulacion = grupoAnulacion;
	}

	public Date getFhAnulacion() {
		return this.fhAnulacion;
	}

	public void setFhAnulacion(Date fhAnulacion) {
		this.fhAnulacion = fhAnulacion;
	}

	public Date getFxEnvioNotificado() {
		return this.fxEnvioNotificado;
	}

	public void setFxEnvioNotificado(Date fxEnvioNotificado) {
		this.fxEnvioNotificado = fxEnvioNotificado;
	}

	public Date getFxPublicacionBop() {
		return this.fxPublicacionBop;
	}

	public void setFxPublicacionBop(Date fxPublicacionBop) {
		this.fxPublicacionBop = fxPublicacionBop;
	}

	public Long getGrupoBop() {
		return this.grupoBop;
	}

	public void setGrupoBop(Long grupoBop) {
		this.grupoBop = grupoBop;
	}

	public String getTipoProcedimiento() {
		return this.tipoProcedimiento;
	}

	public void setTipoProcedimiento(String tipoProcedimiento) {
		this.tipoProcedimiento = tipoProcedimiento;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getHTipoMovimiento() {
		return this.HTipoMovimiento;
	}

	public void setHTipoMovimiento(String HTipoMovimiento) {
		this.HTipoMovimiento = HTipoMovimiento;
	}

}
