package es.dipucadiz.etir.comun.dto;

import java.util.Date;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA


/**
 * ProcesoDTO generated by hbm2java
 */
public class ImpresoraDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 34832092194268842L;
	private String coImpresora;
	private String nombre;
	private String descripcion;
	private String ubicacion;
	private String ip;
	private String tipo;
	private UnidadAdministrativaDTO unidadAdministrativaDTO;
	private String situacion;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	
	
	public ImpresoraDTO() {
	}

	public ImpresoraDTO(String coImpresora) {
		this.coImpresora = coImpresora;
	}
	
	public String getCodigoDescripcion() {
		return coImpresora + " - " + nombre;
	}
	
	public String getCoImpresora() {
		return coImpresora;
	}
	public void setCoImpresora(String coImpresora) {
		this.coImpresora = coImpresora;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getDescripcion() {
		return descripcion;
	}
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	public String getUbicacion() {
		return ubicacion;
	}
	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}
	public String getIp() {
		return ip;
	}
	public void setIp(String ip) {
		this.ip = ip;
	}
	public String getTipo() {
		return tipo;
	}
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	public UnidadAdministrativaDTO getUnidadAdministrativaDTO() {
		return unidadAdministrativaDTO;
	}
	public void setUnidadAdministrativaDTO(UnidadAdministrativaDTO unidadAdministrativaDTO) {
		this.unidadAdministrativaDTO = unidadAdministrativaDTO;
	}
	public String getSituacion() {
		return situacion;
	}
	public void setSituacion(String situacion) {
		this.situacion = situacion;
	}
	public Date getFhActualizacion() {
		return fhActualizacion;
	}
	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}
	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}
	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

}
