package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * IncidenciaSituacionDTO generated by hbm2java
 */
public class IncidenciaSituacionDTO implements java.io.Serializable {

	private Long coIncidenciaSituacion;
	private ModoCobroDTO modoCobroDTOByCoModoCobroOrigen;
	private SituacionDTO situacionDTOByCoSituacionOrigen;
	private MunicipioDTO municipioDTO;
	private IncidenciaDTO incidenciaDTO;
	private SituacionDTO situacionDTOByCoSituacionDestino;
	private ModoCobroDTO modoCobroDTOByCoModoCobroDestino;
	private ModeloVersionDTO modeloVersionDTO;
	private EstadoSituacionDTO estadoSituacionDTOByCoEstadoSituacionDestino;
	private ProcesoDTO procesoDTO;
	private EstadoSituacionDTO estadoSituacionDTOByCoEstadoSituacionOrigen;
	private String actuacion;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String movimientoContable;
	private boolean boSeleccionable;
	private boolean boEconomica;
	private boolean boActualizaUltimaInsit;
	private Set<TramiteDTO> tramiteDTOs = new HashSet<TramiteDTO>(0);
	private Set<IncidenciaSituacionPerDTO> incidenciaSituacionPerDTOs = new HashSet<IncidenciaSituacionPerDTO>(
			0);
	private Set<IncidSitCargoDTO> incidSitCargoDTOs = new HashSet<IncidSitCargoDTO>(
			0);
	private String rowid;

	public String getCodigoDescripcion(){
		String res="";
		if (situacionDTOByCoSituacionOrigen!=null){
			res += situacionDTOByCoSituacionOrigen.getCoSituacion();
			if (estadoSituacionDTOByCoEstadoSituacionOrigen!=null){
				res += " ";
				res += estadoSituacionDTOByCoEstadoSituacionOrigen.getCoEstadoSituacion();
			}
			if (modoCobroDTOByCoModoCobroOrigen!=null){
				res += " ";
				res += modoCobroDTOByCoModoCobroOrigen.getCoModoCobro();
			}
		}
		
		if (incidenciaDTO!=null){
			res += " - ";
			res += incidenciaDTO.getCoIncidencia();
		}
		if (situacionDTOByCoSituacionDestino!=null){
			
			res += " - ";
			res += situacionDTOByCoSituacionDestino.getCoSituacion();
			if (estadoSituacionDTOByCoEstadoSituacionDestino!=null){
				res += " ";
				res += estadoSituacionDTOByCoEstadoSituacionDestino.getCoEstadoSituacion();
			}
			if (modoCobroDTOByCoModoCobroDestino!=null){
				res += " ";
				res += modoCobroDTOByCoModoCobroDestino.getCoModoCobro();
			}
		}
		
		return res;
	}
	
	public IncidenciaSituacionDTO() {
	}

	public IncidenciaSituacionDTO(MunicipioDTO municipioDTO,
			IncidenciaDTO incidenciaDTO, ModeloVersionDTO modeloVersionDTO,
			boolean boSeleccionable, boolean boEconomica,
			boolean boActualizaUltimaInsit) {
		this.municipioDTO = municipioDTO;
		this.incidenciaDTO = incidenciaDTO;
		this.modeloVersionDTO = modeloVersionDTO;
		this.boSeleccionable = boSeleccionable;
		this.boEconomica = boEconomica;
		this.boActualizaUltimaInsit = boActualizaUltimaInsit;
	}

	public IncidenciaSituacionDTO(ModoCobroDTO modoCobroDTOByCoModoCobroOrigen,
			SituacionDTO situacionDTOByCoSituacionOrigen,
			MunicipioDTO municipioDTO, IncidenciaDTO incidenciaDTO,
			SituacionDTO situacionDTOByCoSituacionDestino,
			ModoCobroDTO modoCobroDTOByCoModoCobroDestino,
			ModeloVersionDTO modeloVersionDTO,
			EstadoSituacionDTO estadoSituacionDTOByCoEstadoSituacionDestino,
			ProcesoDTO procesoDTO,
			EstadoSituacionDTO estadoSituacionDTOByCoEstadoSituacionOrigen,
			String actuacion, Date fhActualizacion,
			String coUsuarioActualizacion, String movimientoContable,
			boolean boSeleccionable, boolean boEconomica,
			boolean boActualizaUltimaInsit, Set<TramiteDTO> tramiteDTOs,
			Set<IncidenciaSituacionPerDTO> incidenciaSituacionPerDTOs,
			Set<IncidSitCargoDTO> incidSitCargoDTOs) {
		this.modoCobroDTOByCoModoCobroOrigen = modoCobroDTOByCoModoCobroOrigen;
		this.situacionDTOByCoSituacionOrigen = situacionDTOByCoSituacionOrigen;
		this.municipioDTO = municipioDTO;
		this.incidenciaDTO = incidenciaDTO;
		this.situacionDTOByCoSituacionDestino = situacionDTOByCoSituacionDestino;
		this.modoCobroDTOByCoModoCobroDestino = modoCobroDTOByCoModoCobroDestino;
		this.modeloVersionDTO = modeloVersionDTO;
		this.estadoSituacionDTOByCoEstadoSituacionDestino = estadoSituacionDTOByCoEstadoSituacionDestino;
		this.procesoDTO = procesoDTO;
		this.estadoSituacionDTOByCoEstadoSituacionOrigen = estadoSituacionDTOByCoEstadoSituacionOrigen;
		this.actuacion = actuacion;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.movimientoContable = movimientoContable;
		this.boSeleccionable = boSeleccionable;
		this.boEconomica = boEconomica;
		this.boActualizaUltimaInsit = boActualizaUltimaInsit;
		this.tramiteDTOs = tramiteDTOs;
		this.incidenciaSituacionPerDTOs = incidenciaSituacionPerDTOs;
		this.incidSitCargoDTOs = incidSitCargoDTOs;
	}

	public Long getCoIncidenciaSituacion() {
		return this.coIncidenciaSituacion;
	}

	public void setCoIncidenciaSituacion(Long coIncidenciaSituacion) {
		this.coIncidenciaSituacion = coIncidenciaSituacion;
	}

	public ModoCobroDTO getModoCobroDTOByCoModoCobroOrigen() {
		return this.modoCobroDTOByCoModoCobroOrigen;
	}

	public void setModoCobroDTOByCoModoCobroOrigen(
			ModoCobroDTO modoCobroDTOByCoModoCobroOrigen) {
		this.modoCobroDTOByCoModoCobroOrigen = modoCobroDTOByCoModoCobroOrigen;
	}

	public SituacionDTO getSituacionDTOByCoSituacionOrigen() {
		return this.situacionDTOByCoSituacionOrigen;
	}

	public void setSituacionDTOByCoSituacionOrigen(
			SituacionDTO situacionDTOByCoSituacionOrigen) {
		this.situacionDTOByCoSituacionOrigen = situacionDTOByCoSituacionOrigen;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public IncidenciaDTO getIncidenciaDTO() {
		return this.incidenciaDTO;
	}

	public void setIncidenciaDTO(IncidenciaDTO incidenciaDTO) {
		this.incidenciaDTO = incidenciaDTO;
	}

	public SituacionDTO getSituacionDTOByCoSituacionDestino() {
		return this.situacionDTOByCoSituacionDestino;
	}

	public void setSituacionDTOByCoSituacionDestino(
			SituacionDTO situacionDTOByCoSituacionDestino) {
		this.situacionDTOByCoSituacionDestino = situacionDTOByCoSituacionDestino;
	}

	public ModoCobroDTO getModoCobroDTOByCoModoCobroDestino() {
		return this.modoCobroDTOByCoModoCobroDestino;
	}

	public void setModoCobroDTOByCoModoCobroDestino(
			ModoCobroDTO modoCobroDTOByCoModoCobroDestino) {
		this.modoCobroDTOByCoModoCobroDestino = modoCobroDTOByCoModoCobroDestino;
	}

	public ModeloVersionDTO getModeloVersionDTO() {
		return this.modeloVersionDTO;
	}

	public void setModeloVersionDTO(ModeloVersionDTO modeloVersionDTO) {
		this.modeloVersionDTO = modeloVersionDTO;
	}

	public EstadoSituacionDTO getEstadoSituacionDTOByCoEstadoSituacionDestino() {
		return this.estadoSituacionDTOByCoEstadoSituacionDestino;
	}

	public void setEstadoSituacionDTOByCoEstadoSituacionDestino(
			EstadoSituacionDTO estadoSituacionDTOByCoEstadoSituacionDestino) {
		this.estadoSituacionDTOByCoEstadoSituacionDestino = estadoSituacionDTOByCoEstadoSituacionDestino;
	}

	public ProcesoDTO getProcesoDTO() {
		return this.procesoDTO;
	}

	public void setProcesoDTO(ProcesoDTO procesoDTO) {
		this.procesoDTO = procesoDTO;
	}

	public EstadoSituacionDTO getEstadoSituacionDTOByCoEstadoSituacionOrigen() {
		return this.estadoSituacionDTOByCoEstadoSituacionOrigen;
	}

	public void setEstadoSituacionDTOByCoEstadoSituacionOrigen(
			EstadoSituacionDTO estadoSituacionDTOByCoEstadoSituacionOrigen) {
		this.estadoSituacionDTOByCoEstadoSituacionOrigen = estadoSituacionDTOByCoEstadoSituacionOrigen;
	}

	public String getActuacion() {
		return this.actuacion;
	}

	public void setActuacion(String actuacion) {
		this.actuacion = actuacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getMovimientoContable() {
		return this.movimientoContable;
	}

	public void setMovimientoContable(String movimientoContable) {
		this.movimientoContable = movimientoContable;
	}

	public boolean isBoSeleccionable() {
		return this.boSeleccionable;
	}

	public void setBoSeleccionable(boolean boSeleccionable) {
		this.boSeleccionable = boSeleccionable;
	}

	public boolean isBoEconomica() {
		return this.boEconomica;
	}

	public void setBoEconomica(boolean boEconomica) {
		this.boEconomica = boEconomica;
	}

	public boolean isBoActualizaUltimaInsit() {
		return this.boActualizaUltimaInsit;
	}

	public void setBoActualizaUltimaInsit(boolean boActualizaUltimaInsit) {
		this.boActualizaUltimaInsit = boActualizaUltimaInsit;
	}

	public Set<TramiteDTO> getTramiteDTOs() {
		return this.tramiteDTOs;
	}

	public void setTramiteDTOs(Set<TramiteDTO> tramiteDTOs) {
		this.tramiteDTOs = tramiteDTOs;
	}

	public Set<IncidenciaSituacionPerDTO> getIncidenciaSituacionPerDTOs() {
		return this.incidenciaSituacionPerDTOs;
	}

	public void setIncidenciaSituacionPerDTOs(
			Set<IncidenciaSituacionPerDTO> incidenciaSituacionPerDTOs) {
		this.incidenciaSituacionPerDTOs = incidenciaSituacionPerDTOs;
	}

	public Set<IncidSitCargoDTO> getIncidSitCargoDTOs() {
		return this.incidSitCargoDTOs;
	}

	public void setIncidSitCargoDTOs(Set<IncidSitCargoDTO> incidSitCargoDTOs) {
		this.incidSitCargoDTOs = incidSitCargoDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
