package es.dipucadiz.etir.comun.dto;

// Generated 15-nov-2010 8:36:49 by Hibernate Tools 3.2.4.GA

/**
 * IncidenciaCargoDTOId generated by hbm2java
 */
public class IncidenciaCargoDTOId implements java.io.Serializable {

	private String coIncidenciaCargo;
	private String tipo;

	public IncidenciaCargoDTOId() {
	}

	public IncidenciaCargoDTOId(String coIncidenciaCargo, String tipo) {
		this.coIncidenciaCargo = coIncidenciaCargo;
		this.tipo = tipo;
	}

	public String getCoIncidenciaCargo() {
		return this.coIncidenciaCargo;
	}

	public void setCoIncidenciaCargo(String coIncidenciaCargo) {
		this.coIncidenciaCargo = coIncidenciaCargo;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IncidenciaCargoDTOId))
			return false;
		IncidenciaCargoDTOId castOther = (IncidenciaCargoDTOId) other;

		return ((this.getCoIncidenciaCargo() == castOther
				.getCoIncidenciaCargo()) || (this.getCoIncidenciaCargo() != null
				&& castOther.getCoIncidenciaCargo() != null && this
				.getCoIncidenciaCargo()
				.equals(castOther.getCoIncidenciaCargo())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null
						&& castOther.getTipo() != null && this.getTipo()
						.equals(castOther.getTipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCoIncidenciaCargo() == null ? 0 : this
						.getCoIncidenciaCargo().hashCode());
		result = 37 * result
				+ (getTipo() == null ? 0 : this.getTipo().hashCode());
		return result;
	}

}
