package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * IncidSitCargoDTO generated by hbm2java
 */
public class IncidSitCargoDTO implements java.io.Serializable {

	private Long coIncidSitCargo;
	private IncidenciaSituacionDTO incidenciaSituacionDTO;
	private MunicipioDTO municipioDTO;
	private SituacionCargoDTO situacionCargoDTOOrigen;
	private ModeloVersionDTO modeloVersionDTO;
	private IncidenciaCargoDTO incidenciaCargoDTO;
	private SituacionCargoDTO situacionCargoDTODestino;
	private String coSituacionCargoOrigen;
	private String coSituacionCargoDestino;
	private String coIncidenciaCargo;
	private String tipo;
	private ProcesoDTO procesoDTO;
	private boolean boSeleccionable;
	private boolean boEconomica;
	private boolean boActualizaUltimaInsit;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private Set<IncidSitCargoPermisoDTO> incidSitCargoPermisoDTOs = new HashSet<IncidSitCargoPermisoDTO>(
			0);
	
	private String rowid;

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public IncidSitCargoDTO() {
	}

	public IncidSitCargoDTO(MunicipioDTO municipioDTO,
			SituacionCargoDTO situacionCargoDTOOrigen,
			ModeloVersionDTO modeloVersionDTO,
			IncidenciaCargoDTO incidenciaCargoDTO,
			SituacionCargoDTO situacionCargoDTODestino,
			boolean boSeleccionable, boolean boEconomica,
			boolean boActualizaUltimaInsit) {
		this.municipioDTO = municipioDTO;
		this.situacionCargoDTOOrigen = situacionCargoDTOOrigen;
		this.modeloVersionDTO = modeloVersionDTO;
		this.incidenciaCargoDTO = incidenciaCargoDTO;
		this.situacionCargoDTODestino = situacionCargoDTODestino;
		this.boSeleccionable = boSeleccionable;
		this.boEconomica = boEconomica;
		this.boActualizaUltimaInsit = boActualizaUltimaInsit;
	}

	public IncidSitCargoDTO(IncidenciaSituacionDTO incidenciaSituacionDTO,
			MunicipioDTO municipioDTO,
			SituacionCargoDTO situacionCargoDTOOrigen,
			ModeloVersionDTO modeloVersionDTO,
			IncidenciaCargoDTO incidenciaCargoDTO,
			SituacionCargoDTO situacionCargoDTODestino,
			ProcesoDTO procesoDTO, boolean boSeleccionable,
			boolean boEconomica, boolean boActualizaUltimaInsit,
			String coUsuarioActualizacion, Date fhActualizacion,
			Set<IncidSitCargoPermisoDTO> incidSitCargoPermisoDTOs) {
		this.incidenciaSituacionDTO = incidenciaSituacionDTO;
		this.municipioDTO = municipioDTO;
		this.situacionCargoDTOOrigen = situacionCargoDTOOrigen;
		this.modeloVersionDTO = modeloVersionDTO;
		this.incidenciaCargoDTO = incidenciaCargoDTO;
		this.situacionCargoDTODestino = situacionCargoDTODestino;
		this.procesoDTO = procesoDTO;
		this.boSeleccionable = boSeleccionable;
		this.boEconomica = boEconomica;
		this.boActualizaUltimaInsit = boActualizaUltimaInsit;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.incidSitCargoPermisoDTOs = incidSitCargoPermisoDTOs;
	}

	public Long getCoIncidSitCargo() {
		return this.coIncidSitCargo;
	}

	public void setCoIncidSitCargo(Long coIncidSitCargo) {
		this.coIncidSitCargo = coIncidSitCargo;
	}

	public IncidenciaSituacionDTO getIncidenciaSituacionDTO() {
		return this.incidenciaSituacionDTO;
	}

	public void setIncidenciaSituacionDTO(
			IncidenciaSituacionDTO incidenciaSituacionDTO) {
		this.incidenciaSituacionDTO = incidenciaSituacionDTO;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public SituacionCargoDTO getSituacionCargoDTOOrigen() {
		return this.situacionCargoDTOOrigen;
	}

	public void setSituacionCargoDTOOrigen(
			SituacionCargoDTO situacionCargoDTOOrigen) {
		this.situacionCargoDTOOrigen = situacionCargoDTOOrigen;
	}

	public ModeloVersionDTO getModeloVersionDTO() {
		return this.modeloVersionDTO;
	}

	public void setModeloVersionDTO(ModeloVersionDTO modeloVersionDTO) {
		this.modeloVersionDTO = modeloVersionDTO;
	}

	public IncidenciaCargoDTO getIncidenciaCargoDTO() {
		return this.incidenciaCargoDTO;
	}

	public void setIncidenciaCargoDTO(IncidenciaCargoDTO incidenciaCargoDTO) {
		this.incidenciaCargoDTO = incidenciaCargoDTO;
	}

	public SituacionCargoDTO getSituacionCargoDTODestino() {
		return this.situacionCargoDTODestino;
	}

	public void setSituacionCargoDTODestino(
			SituacionCargoDTO situacionCargoDTODestino) {
		this.situacionCargoDTODestino = situacionCargoDTODestino;
	}

	public ProcesoDTO getProcesoDTO() {
		return this.procesoDTO;
	}

	public void setProcesoDTO(ProcesoDTO procesoDTO) {
		this.procesoDTO = procesoDTO;
	}

	public boolean isBoSeleccionable() {
		return this.boSeleccionable;
	}

	public void setBoSeleccionable(boolean boSeleccionable) {
		this.boSeleccionable = boSeleccionable;
	}

	public boolean isBoEconomica() {
		return this.boEconomica;
	}

	public void setBoEconomica(boolean boEconomica) {
		this.boEconomica = boEconomica;
	}

	public boolean isBoActualizaUltimaInsit() {
		return this.boActualizaUltimaInsit;
	}

	public void setBoActualizaUltimaInsit(boolean boActualizaUltimaInsit) {
		this.boActualizaUltimaInsit = boActualizaUltimaInsit;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public Set<IncidSitCargoPermisoDTO> getIncidSitCargoPermisoDTOs() {
		return this.incidSitCargoPermisoDTOs;
	}

	public void setIncidSitCargoPermisoDTOs(
			Set<IncidSitCargoPermisoDTO> incidSitCargoPermisoDTOs) {
		this.incidSitCargoPermisoDTOs = incidSitCargoPermisoDTOs;
	}

	public String getCoSituacionCargoOrigen() {
		return coSituacionCargoOrigen;
	}

	public void setCoSituacionCargoOrigen(String coSituacionCargoOrigen) {
		this.coSituacionCargoOrigen = coSituacionCargoOrigen;
	}

	public String getCoSituacionCargoDestino() {
		return coSituacionCargoDestino;
	}

	public void setCoSituacionCargoDestino(String coSituacionCargoDestino) {
		this.coSituacionCargoDestino = coSituacionCargoDestino;
	}

	public String getCoIncidenciaCargo() {
		return coIncidenciaCargo;
	}

	public void setCoIncidenciaCargo(String coIncidenciaCargo) {
		this.coIncidenciaCargo = coIncidenciaCargo;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	

}
