package es.dipucadiz.etir.comun.dto;

// Generated 09-mar-2010 14:09:36 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * InformeDTO generated by hbm2java
 */
public class InformeDTO implements java.io.Serializable {

	private Long coInforme;
	private EjecucionDTO ejecucionDTO;
	private String rutaPdf;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Long coPlantilla;
	private String coAcmUsuario;
	private String rowid;

	public InformeDTO() {
	}

	public InformeDTO(EjecucionDTO ejecucionDTO, String rutaPdf,
			Date fhActualizacion, String coUsuarioActualizacion,
			Long coPlantilla) {
		this.ejecucionDTO = ejecucionDTO;
		this.rutaPdf = rutaPdf;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.coPlantilla = coPlantilla;
	}

	public Long getCoInforme() {
		return this.coInforme;
	}

	public void setCoInforme(Long coInforme) {
		this.coInforme = coInforme;
	}

	public EjecucionDTO getEjecucionDTO() {
		return this.ejecucionDTO;
	}

	public void setEjecucionDTO(EjecucionDTO ejecucionDTO) {
		this.ejecucionDTO = ejecucionDTO;
	}

	public String getRutaPdf() {
		return this.rutaPdf;
	}

	public void setRutaPdf(String rutaPdf) {
		this.rutaPdf = rutaPdf;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public Long getCoPlantilla() {
		return this.coPlantilla;
	}

	public void setCoPlantilla(Long coPlantilla) {
		this.coPlantilla = coPlantilla;
	}
	
	public String getCoAcmUsuario() {
		return this.coAcmUsuario;
	}

	public void setCoAcmUsuario(String coAcmUsuario) {
		this.coAcmUsuario = coAcmUsuario;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
