package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * DatosDTO generated by hbm2java
 */
public class JuntaEnvioDTO implements java.io.Serializable {
	private static final long serialVersionUID = 7542759756151182982L;
	
	private JuntaEnvioDTOId id;
	private String nombre;
	private Date fxDesde;
	private Date fxHasta;
	private Date fxEnvio;
	private BigDecimal imIngresoAplicadoDeuda;
	private BigDecimal imInteresesCobrados;
	private BigDecimal imIngresadoEnte;
	private Long nuRegistrosTipo1;
	private Long nuRegistrosTipo2;
	private Long nuRegistrosTipo3;
	private Long nuRegistrosFichero;
	private BigDecimal imCosteServicio;
	private String coEstado;
	private String coResultado;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	
	public JuntaEnvioDTO() {
		
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFxDesde() {
		return fxDesde;
	}

	public void setFxDesde(Date fxDesde) {
		this.fxDesde = fxDesde;
	}

	public Date getFxHasta() {
		return fxHasta;
	}

	public void setFxHasta(Date fxHasta) {
		this.fxHasta = fxHasta;
	}

	public Date getFxEnvio() {
		return fxEnvio;
	}

	public void setFxEnvio(Date fxEnvio) {
		this.fxEnvio = fxEnvio;
	}

	public BigDecimal getImIngresoAplicadoDeuda() {
		return imIngresoAplicadoDeuda;
	}

	public void setImIngresoAplicadoDeuda(BigDecimal imIngresoAplicadoDeuda) {
		this.imIngresoAplicadoDeuda = imIngresoAplicadoDeuda;
	}

	public BigDecimal getImInteresesCobrados() {
		return imInteresesCobrados;
	}

	public void setImInteresesCobrados(BigDecimal imInteresesCobrados) {
		this.imInteresesCobrados = imInteresesCobrados;
	}

	public BigDecimal getImIngresadoEnte() {
		return imIngresadoEnte;
	}

	public void setImIngresadoEnte(BigDecimal imIngresadoEnte) {
		this.imIngresadoEnte = imIngresadoEnte;
	}

	public Long getNuRegistrosTipo1() {
		return nuRegistrosTipo1;
	}

	public void setNuRegistrosTipo1(Long nuRegistrosTipo1) {
		this.nuRegistrosTipo1 = nuRegistrosTipo1;
	}

	public Long getNuRegistrosTipo2() {
		return nuRegistrosTipo2;
	}

	public void setNuRegistrosTipo2(Long nuRegistrosTipo2) {
		this.nuRegistrosTipo2 = nuRegistrosTipo2;
	}

	public Long getNuRegistrosTipo3() {
		return nuRegistrosTipo3;
	}

	public void setNuRegistrosTipo3(Long nuRegistrosTipo3) {
		this.nuRegistrosTipo3 = nuRegistrosTipo3;
	}

	public Long getNuRegistrosFichero() {
		return nuRegistrosFichero;
	}

	public void setNuRegistrosFichero(Long nuRegistrosFichero) {
		this.nuRegistrosFichero = nuRegistrosFichero;
	}

	public BigDecimal getImCosteServicio() {
		return imCosteServicio;
	}

	public void setImCosteServicio(BigDecimal imCosteServicio) {
		this.imCosteServicio = imCosteServicio;
	}

	public String getCoEstado() {
		return coEstado;
	}

	public void setCoEstado(String coEstado) {
		this.coEstado = coEstado;
	}

	public String getCoResultado() {
		return coResultado;
	}

	public void setCoResultado(String coResultado) {
		this.coResultado = coResultado;
	}

	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public JuntaEnvioDTOId getId() {
		return id;
	}

	public void setId(JuntaEnvioDTOId id) {
		this.id = id;
	}

} 
