package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * DatosDTO generated by hbm2java
 */
public class JuntaEnvioLiquidacionExcluidoDTO implements java.io.Serializable {
	private static final long serialVersionUID = 7542759756151182982L;
	
	private Long coJuntaEnvioLiqExcluido;
	private Long nuEnvio;
	private String coDelegacion;	
	private DocumentoDTO documentoDTO;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private String observaciones;
	


	public JuntaEnvioLiquidacionExcluidoDTO() {
		
	}

	public Long getCoJuntaEnvioLiqExcluido() {
		return coJuntaEnvioLiqExcluido;
	}

	public void setCoJuntaEnvioLiqExcluido(Long coJuntaEnvioLiqExcluido) {
		this.coJuntaEnvioLiqExcluido = coJuntaEnvioLiqExcluido;
	}

	public Long getNuEnvio() {
		return nuEnvio;
	}

	public void setNuEnvio(Long nuEnvio) {
		this.nuEnvio = nuEnvio;
	}

	public String getCoDelegacion() {
		return coDelegacion;
	}

	public void setCoDelegacion(String coDelegacion) {
		this.coDelegacion = coDelegacion;
	}

	public DocumentoDTO getDocumentoDTO() {
		return documentoDTO;
	}

	public void setDocumentoDTO(DocumentoDTO documentoDTO) {
		this.documentoDTO = documentoDTO;
	}

	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}
	public String getObservaciones() {
		return observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}
	
} 
