package es.dipucadiz.etir.comun.dto;

// Generated 04-nov-2010 8:41:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ModoCobroDTO generated by hbm2java
 */
public class ModoCobroDTO implements java.io.Serializable {

	private String coModoCobro;
	private String nombre;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private Set<IncidenciaSituacionDTO> incidenciaSituacionDTOs = new HashSet<IncidenciaSituacionDTO>(
			0);
	private Set<DocumentoLiquidacionDTO> documentoLiquidacionDTOs = new HashSet<DocumentoLiquidacionDTO>(
			0);
	private String rowid;

	public String getCodigoDescripcion(){
		return coModoCobro + " - " + nombre;
	}
	
	public ModoCobroDTO() {
	}

	public ModoCobroDTO(String coModoCobro) {
		this.coModoCobro = coModoCobro;
	}

	public ModoCobroDTO(String coModoCobro, String nombre,
			String coUsuarioActualizacion, Date fhActualizacion,
			Set<IncidenciaSituacionDTO> incidenciaSituacionDTOs,
			Set<DocumentoLiquidacionDTO> documentoLiquidacionDTOs) {
		this.coModoCobro = coModoCobro;
		this.nombre = nombre;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.incidenciaSituacionDTOs = incidenciaSituacionDTOs;
		this.documentoLiquidacionDTOs = documentoLiquidacionDTOs;
	}

	public String getCoModoCobro() {
		return this.coModoCobro;
	}

	public void setCoModoCobro(String coModoCobro) {
		this.coModoCobro = coModoCobro;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}
	
	public Set<IncidenciaSituacionDTO> getIncidenciaSituacionDTOs() {
		return this.incidenciaSituacionDTOs;
	}

	public void setIncidenciaSituacionDTOs(
			Set<IncidenciaSituacionDTO> incidenciaSituacionDTOs) {
		this.incidenciaSituacionDTOs = incidenciaSituacionDTOs;
	}

	public Set<DocumentoLiquidacionDTO> getDocumentoLiquidacionDTOs() {
		return this.documentoLiquidacionDTOs;
	}

	public void setDocumentoLiquidacionDTOs(
			Set<DocumentoLiquidacionDTO> documentoLiquidacionDTOs) {
		this.documentoLiquidacionDTOs = documentoLiquidacionDTOs;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
