package es.dipucadiz.etir.comun.dto;

// Generated 16-mar-2011 9:09:55 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * MovimientoContableDTO generated by hbm2java
 */
public class MovimientoContableDTO implements java.io.Serializable {

	private Long coMovimientoContable;
	private DiputacionCuentaDTO diputacionCuentaDTO;
	private DocumentoDTO documentoDTO;
	private MovimientoContableDTO movimientoContableDTO;
	private boolean boHaber;
	private boolean boAplicado;
	private BigDecimal importe;
	private Date fxValor;
	private Long nuIntervencion;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private Set<MovimientoContableDTO> movimientoContableDTOs = new HashSet<MovimientoContableDTO>(0);
	private Set<MovimContableClienteDTO> movimContableClienteDTOs = new HashSet<MovimContableClienteDTO>(0);
	private String rowid;
	private DocumentoSeguimientoDTO documentoSeguimientoDTO;
	private DepositoDTO depositoDTO;	
	private String conceptoComplementario; 
	
	public MovimientoContableDTO() {
	}

	public MovimientoContableDTO(boolean boHaber) {
		this.boHaber = boHaber;
	}

	public MovimientoContableDTO(DiputacionCuentaDTO diputacionCuentaDTO,
			DocumentoDTO documentoDTO,
			MovimientoContableDTO movimientoContableDTO, boolean boHaber,
			BigDecimal importe, Date fxValor, Long nuIntervencion,
			String coUsuarioActualizacion, Date fhActualizacion,
			Set<MovimientoContableDTO> movimientoContableDTOs,
			Set<MovimContableClienteDTO> movimContableClienteDTOs) {
		this.diputacionCuentaDTO = diputacionCuentaDTO;
		this.documentoDTO = documentoDTO;
		this.movimientoContableDTO = movimientoContableDTO;
		this.boHaber = boHaber;
		this.importe = importe;
		this.fxValor = fxValor;
		this.nuIntervencion = nuIntervencion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.movimientoContableDTOs = movimientoContableDTOs;
		this.movimContableClienteDTOs = movimContableClienteDTOs;
	}

	public Long getCoMovimientoContable() {
		return this.coMovimientoContable;
	}

	public void setCoMovimientoContable(Long coMovimientoContable) {
		this.coMovimientoContable = coMovimientoContable;
	}

	public DiputacionCuentaDTO getDiputacionCuentaDTO() {
		return this.diputacionCuentaDTO;
	}

	public void setDiputacionCuentaDTO(DiputacionCuentaDTO diputacionCuentaDTO) {
		this.diputacionCuentaDTO = diputacionCuentaDTO;
	}

	public DocumentoDTO getDocumentoDTO() {
		return this.documentoDTO;
	}

	public void setDocumentoDTO(DocumentoDTO documentoDTO) {
		this.documentoDTO = documentoDTO;
	}

	public MovimientoContableDTO getMovimientoContableDTO() {
		return this.movimientoContableDTO;
	}

	public void setMovimientoContableDTO(
			MovimientoContableDTO movimientoContableDTO) {
		this.movimientoContableDTO = movimientoContableDTO;
	}

	public boolean isBoHaber() {
		return this.boHaber;
	}

	public void setBoHaber(boolean boHaber) {
		this.boHaber = boHaber;
	}

	public boolean isBoAplicado() {
		return this.boAplicado;
	}

	public void setBoAplicado(boolean boAplicado) {
		this.boAplicado = boAplicado;
	}

	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	public Date getFxValor() {
		return this.fxValor;
	}

	public void setFxValor(Date fxValor) {
		this.fxValor = fxValor;
	}

	public Long getNuIntervencion() {
		return this.nuIntervencion;
	}

	public void setNuIntervencion(Long nuIntervencion) {
		this.nuIntervencion = nuIntervencion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public Set<MovimientoContableDTO> getMovimientoContableDTOs() {
		return this.movimientoContableDTOs;
	}

	public void setMovimientoContableDTOs(
			Set<MovimientoContableDTO> movimientoContableDTOs) {
		this.movimientoContableDTOs = movimientoContableDTOs;
	}

	public Set<MovimContableClienteDTO> getMovimContableClienteDTOs() {
		return this.movimContableClienteDTOs;
	}

	public void setMovimContableClienteDTOs(
			Set<MovimContableClienteDTO> movimContableClienteDTOs) {
		this.movimContableClienteDTOs = movimContableClienteDTOs;
	}

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public DocumentoSeguimientoDTO getDocumentoSeguimientoDTO() {
		return documentoSeguimientoDTO;
	}

	public void setDocumentoSeguimientoDTO(
			DocumentoSeguimientoDTO documentoSeguimientoDTO) {
		this.documentoSeguimientoDTO = documentoSeguimientoDTO;
	}

	public DepositoDTO getDepositoDTO() {
		return depositoDTO;
	}

	public void setDepositoDTO(DepositoDTO depositoDTO) {
		this.depositoDTO = depositoDTO;
	}

	public String getConceptoComplementario() {
		return conceptoComplementario;
	}

	public void setConceptoComplementario(String conceptoComplementario) {
		this.conceptoComplementario = conceptoComplementario;
	}



}
