package es.dipucadiz.etir.comun.dto;

// Generated 16-mar-2011 9:09:55 by Hibernate Tools 3.2.4.GA

/**
 * MovimContableClienteDTOId generated by hbm2java
 */
public class MovimContableClienteDTOId implements java.io.Serializable {

	private long coMovimientoContable;
	private long coCliente;

	public MovimContableClienteDTOId() {
	}

	public MovimContableClienteDTOId(long coMovimientoContable, long coCliente) {
		this.coMovimientoContable = coMovimientoContable;
		this.coCliente = coCliente;
	}

	public long getCoMovimientoContable() {
		return this.coMovimientoContable;
	}

	public void setCoMovimientoContable(long coMovimientoContable) {
		this.coMovimientoContable = coMovimientoContable;
	}

	public long getCoCliente() {
		return this.coCliente;
	}

	public void setCoCliente(long coCliente) {
		this.coCliente = coCliente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MovimContableClienteDTOId))
			return false;
		MovimContableClienteDTOId castOther = (MovimContableClienteDTOId) other;

		return (this.getCoMovimientoContable() == castOther
				.getCoMovimientoContable())
				&& (this.getCoCliente() == castOther.getCoCliente());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCoMovimientoContable();
		result = 37 * result + (int) this.getCoCliente();
		return result;
	}

}
