package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * MunicipioSinonimoDTO generated by hbm2java
 */
public class MunicipioSinonimoDTO implements java.io.Serializable {

	private MunicipioSinonimoDTOId id;
	private MunicipioDTO municipioDTO;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public MunicipioSinonimoDTO() {
	}

	public MunicipioSinonimoDTO(MunicipioSinonimoDTOId id,
			MunicipioDTO municipioDTO) {
		this.id = id;
		this.municipioDTO = municipioDTO;
	}

	public MunicipioSinonimoDTO(MunicipioSinonimoDTOId id,
			MunicipioDTO municipioDTO, Date fhActualizacion,
			String coUsuarioActualizacion) {
		this.id = id;
		this.municipioDTO = municipioDTO;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public MunicipioSinonimoDTOId getId() {
		return this.id;
	}

	public void setId(MunicipioSinonimoDTOId id) {
		this.id = id;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
