package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * MunicipioDTOId generated by hbm2java
 */
public class MunicipioDTOId implements java.io.Serializable {

	private String coProvincia;
	private String coMunicipio;

	public MunicipioDTOId() {
	}

	public MunicipioDTOId(String coProvincia, String coMunicipio) {
		this.coProvincia = coProvincia;
		this.coMunicipio = coMunicipio;
	}

	public String getCoProvincia() {
		return this.coProvincia;
	}

	public void setCoProvincia(String coProvincia) {
		this.coProvincia = coProvincia;
	}

	public String getCoMunicipio() {
		return this.coMunicipio;
	}

	public void setCoMunicipio(String coMunicipio) {
		this.coMunicipio = coMunicipio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MunicipioDTOId))
			return false;
		MunicipioDTOId castOther = (MunicipioDTOId) other;

		return ((this.getCoProvincia() == castOther.getCoProvincia()) || (this
				.getCoProvincia() != null
				&& castOther.getCoProvincia() != null && this.getCoProvincia()
				.equals(castOther.getCoProvincia())))
				&& ((this.getCoMunicipio() == castOther.getCoMunicipio()) || (this
						.getCoMunicipio() != null
						&& castOther.getCoMunicipio() != null && this
						.getCoMunicipio().equals(castOther.getCoMunicipio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCoProvincia() == null ? 0 : this.getCoProvincia()
						.hashCode());
		result = 37
				* result
				+ (getCoMunicipio() == null ? 0 : this.getCoMunicipio()
						.hashCode());
		return result;
	}

}
