package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * OtrDTO generated by hbm2java
 */
public class OtrDTO implements java.io.Serializable {

	private String coOtr;
	private String CodigoOtr;
	private ClienteDTO clienteDTO;
	private String nombre;
	private String tipo;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private Set<CargoSubcargoDTO> cargoSubcargoDTOs = new HashSet<CargoSubcargoDTO>(
			0);
	private Set<ConveniosConceptoDTO> conveniosConceptoDTOs = new HashSet<ConveniosConceptoDTO>(
			0);
	private Set<FraccionamientoCondsDTO> fraccionamientoCondsDTOs = new HashSet<FraccionamientoCondsDTO>(
			0);
	
	private String rowid;
	
	public String getCodigoDescripcion(){
		return coOtr + " - " + nombre;
	}

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public OtrDTO() {
	}

	public OtrDTO(String coOtr, String nombre, String tipo) {
		this.coOtr = coOtr;
		this.nombre = nombre;
		this.tipo = tipo;
		
	}

	public OtrDTO(String coOtr, ClienteDTO clienteDTO, String nombre,
			String tipo, String coUsuarioActualizacion, Date fhActualizacion,
			Set<PppCondsDTO> pppCondsDTOs,
			Set<CargoSubcargoDTO> cargoSubcargoDTOs,
			Set<ConveniosConceptoDTO> conveniosConceptoDTOs,
			Set<FraccionamientoCondsDTO> fraccionamientoCondsDTOs) {
		this.coOtr = coOtr;
		this.clienteDTO = clienteDTO;
		this.nombre = nombre;
		this.tipo = tipo;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.cargoSubcargoDTOs = cargoSubcargoDTOs;
		this.conveniosConceptoDTOs = conveniosConceptoDTOs;
		this.fraccionamientoCondsDTOs = fraccionamientoCondsDTOs;
	}

	public String getCoOtr() {
		return this.coOtr;
	}

	public void setCoOtr(String coOtr) {
		this.coOtr = coOtr;
	}
	
	public String getCodigoOtr() {
		return this.CodigoOtr;
	}

	public void getCodigoOtr(String CodigoOtr) {
		this.CodigoOtr = CodigoOtr;
	}

	public ClienteDTO getClienteDTO() {
		return this.clienteDTO;
	}

	public void setClienteDTO(ClienteDTO clienteDTO) {
		this.clienteDTO = clienteDTO;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public Set<CargoSubcargoDTO> getCargoSubcargoDTOs() {
		return this.cargoSubcargoDTOs;
	}

	public void setCargoSubcargoDTOs(Set<CargoSubcargoDTO> cargoSubcargoDTOs) {
		this.cargoSubcargoDTOs = cargoSubcargoDTOs;
	}

	public Set<ConveniosConceptoDTO> getConveniosConceptoDTOs() {
		return this.conveniosConceptoDTOs;
	}

	public void setConveniosConceptoDTOs(
			Set<ConveniosConceptoDTO> conveniosConceptoDTOs) {
		this.conveniosConceptoDTOs = conveniosConceptoDTOs;
	}

	public Set<FraccionamientoCondsDTO> getFraccionamientoCondsDTOs() {
		return this.fraccionamientoCondsDTOs;
	}

	public void setFraccionamientoCondsDTOs(
			Set<FraccionamientoCondsDTO> fraccionamientoCondsDTOs) {
		this.fraccionamientoCondsDTOs = fraccionamientoCondsDTOs;
	}

}
