package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ParametroMunicipioValorDTO generated by hbm2java
 */
public class ParametroMunicipioValorDTO implements java.io.Serializable, Comparable<ParametroMunicipioValorDTO> {
	private static final long serialVersionUID = -6304881001680216492L;

	private ParametroMunicipioValorDTOId id;
	private ParametroMunicipioDTO parametroMunicipioDTO;
	private String valorHasta;
	private String tipoResultado;
	private String valorResultado;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public ParametroMunicipioValorDTO() {
	}

	public ParametroMunicipioValorDTO(ParametroMunicipioValorDTOId id,
			ParametroMunicipioDTO parametroMunicipioDTO) {
		this.id = id;
		this.parametroMunicipioDTO = parametroMunicipioDTO;
	}

	public ParametroMunicipioValorDTO(ParametroMunicipioValorDTOId id,
			ParametroMunicipioDTO parametroMunicipioDTO, String valorHasta,
			String tipoResultado, String valorResultado, Date fhActualizacion,
			String coUsuarioActualizacion) {
		this.id = id;
		this.parametroMunicipioDTO = parametroMunicipioDTO;
		this.valorHasta = valorHasta;
		this.tipoResultado = tipoResultado;
		this.valorResultado = valorResultado;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public ParametroMunicipioValorDTOId getId() {
		return this.id;
	}

	public void setId(ParametroMunicipioValorDTOId id) {
		this.id = id;
	}

	public ParametroMunicipioDTO getParametroMunicipioDTO() {
		return this.parametroMunicipioDTO;
	}

	public void setParametroMunicipioDTO(
			ParametroMunicipioDTO parametroMunicipioDTO) {
		this.parametroMunicipioDTO = parametroMunicipioDTO;
	}

	public String getValorHasta() {
		return this.valorHasta;
	}

	public void setValorHasta(String valorHasta) {
		this.valorHasta = valorHasta;
	}

	public String getTipoResultado() {
		return this.tipoResultado;
	}

	public void setTipoResultado(String tipoResultado) {
		this.tipoResultado = tipoResultado;
	}

	public String getValorResultado() {
		return this.valorResultado;
	}

	public void setValorResultado(String valorResultado) {
		this.valorResultado = valorResultado;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((tipoResultado == null) ? 0 : tipoResultado.hashCode());
		result = prime * result
				+ ((valorHasta == null) ? 0 : valorHasta.hashCode());
		result = prime * result
				+ ((valorResultado == null) ? 0 : valorResultado.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ParametroMunicipioValorDTO other = (ParametroMunicipioValorDTO) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (tipoResultado == null) {
			if (other.tipoResultado != null)
				return false;
		} else if (!tipoResultado.equals(other.tipoResultado))
			return false;
		if (valorHasta == null) {
			if (other.valorHasta != null)
				return false;
		} else if (!valorHasta.equals(other.valorHasta))
			return false;
		if (valorResultado == null) {
			if (other.valorResultado != null)
				return false;
		} else if (!valorResultado.equals(other.valorResultado))
			return false;
		return true;
	}

	public int compareTo(ParametroMunicipioValorDTO otro) {
		int result;
		try {
			// Comparar numericamente.
			double valThis = Double.parseDouble(this.getId().getValorDesde().replace(',', '.')); 
			double valOtro = Double.parseDouble(otro.getId().getValorDesde().replace(',', '.'));
			if (valThis > valOtro) result = 1;
			else if (valThis < valOtro) result = -1;
			else result = 0;
		} catch (NumberFormatException e) {
			// Comparar alfanumericamente.
			result = this.id.getValorDesde().compareTo(otro.getId().getValorDesde());			
		}
		return result;
	}
}
