package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * ParametroMunicipioValorDTOId generated by hbm2java
 */
public class ParametroMunicipioValorDTOId implements java.io.Serializable {

	private long coParametroMunicipio;
	private String valorDesde;

	public ParametroMunicipioValorDTOId() {
	}

	public ParametroMunicipioValorDTOId(long coParametroMunicipio,
			String valorDesde) {
		this.coParametroMunicipio = coParametroMunicipio;
		this.valorDesde = valorDesde;
	}

	public long getCoParametroMunicipio() {
		return this.coParametroMunicipio;
	}

	public void setCoParametroMunicipio(long coParametroMunicipio) {
		this.coParametroMunicipio = coParametroMunicipio;
	}

	public String getValorDesde() {
		return this.valorDesde;
	}

	public void setValorDesde(String valorDesde) {
		this.valorDesde = valorDesde;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParametroMunicipioValorDTOId))
			return false;
		ParametroMunicipioValorDTOId castOther = (ParametroMunicipioValorDTOId) other;

		return (this.getCoParametroMunicipio() == castOther
				.getCoParametroMunicipio())
				&& (this.getValorDesde() == castOther.getValorDesde());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCoParametroMunicipio();
		result = 37 * result + (getValorDesde() == null ? 0 : this.getValorDesde().hashCode());
		return result;
	}

}
