package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ParametroDTO generated by hbm2java
 */
public class ParametroDTO implements java.io.Serializable {

	private String coParametro;
	private String nombre;
	private String descripcion;
	private String formato;
	private BigDecimal longitud;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<ParametroMunicipioDTO> parametroMunicipioDTOsForCoParametro = new HashSet<ParametroMunicipioDTO>(
			0);
	private Set<ParametroMunicipioDTO> parametroMunicipioDTOsForCoParametroRango = new HashSet<ParametroMunicipioDTO>(
			0);
	private String rowid;

	public ParametroDTO() {
	}

	public ParametroDTO(String coParametro, String nombre) {
		this.coParametro = coParametro;
		this.nombre = nombre;
	}

	public ParametroDTO(String coParametro, String nombre, String descripcion,
			String formato, BigDecimal longitud, Date fhActualizacion,
			String coUsuarioActualizacion,
			Set<ParametroMunicipioDTO> parametroMunicipioDTOsForCoParametro,
			Set<ParametroMunicipioDTO> parametroMunicipioDTOsForCoParametroRango) {
		this.coParametro = coParametro;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.formato = formato;
		this.longitud = longitud;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.parametroMunicipioDTOsForCoParametro = parametroMunicipioDTOsForCoParametro;
		this.parametroMunicipioDTOsForCoParametroRango = parametroMunicipioDTOsForCoParametroRango;
	}

	public String getCoParametro() {
		return this.coParametro;
	}

	public void setCoParametro(String coParametro) {
		this.coParametro = coParametro;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getFormato() {
		return this.formato;
	}

	public void setFormato(String formato) {
		this.formato = formato;
	}

	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<ParametroMunicipioDTO> getParametroMunicipioDTOsForCoParametro() {
		return this.parametroMunicipioDTOsForCoParametro;
	}

	public void setParametroMunicipioDTOsForCoParametro(
			Set<ParametroMunicipioDTO> parametroMunicipioDTOsForCoParametro) {
		this.parametroMunicipioDTOsForCoParametro = parametroMunicipioDTOsForCoParametro;
	}

	public Set<ParametroMunicipioDTO> getParametroMunicipioDTOsForCoParametroRango() {
		return this.parametroMunicipioDTOsForCoParametroRango;
	}

	public void setParametroMunicipioDTOsForCoParametroRango(
			Set<ParametroMunicipioDTO> parametroMunicipioDTOsForCoParametroRango) {
		this.parametroMunicipioDTOsForCoParametroRango = parametroMunicipioDTOsForCoParametroRango;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((coParametro == null) ? 0 : coParametro.hashCode());
		result = prime * result
				+ ((descripcion == null) ? 0 : descripcion.hashCode());
		result = prime * result + ((formato == null) ? 0 : formato.hashCode());
		result = prime * result
				+ ((longitud == null) ? 0 : longitud.hashCode());
		result = prime * result + ((nombre == null) ? 0 : nombre.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ParametroDTO other = (ParametroDTO) obj;
		if (coParametro == null) {
			if (other.coParametro != null)
				return false;
		} else if (!coParametro.equals(other.coParametro))
			return false;
		if (descripcion == null) {
			if (other.descripcion != null)
				return false;
		} else if (!descripcion.equals(other.descripcion))
			return false;
		if (formato == null) {
			if (other.formato != null)
				return false;
		} else if (!formato.equals(other.formato))
			return false;
		if (longitud == null) {
			if (other.longitud != null)
				return false;
		} else if (!longitud.equals(other.longitud))
			return false;
		if (nombre == null) {
			if (other.nombre != null)
				return false;
		} else if (!nombre.equals(other.nombre))
			return false;
		return true;
	}

	public String getCodigoDescripcion() {
		return coParametro + " - " + nombre;
	}
	

}
