package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * PeriodoVoluntariaDTO generated by hbm2java
 */
public class PeriodoVoluntariaDTO implements java.io.Serializable {

	private Long coPeriodoVoluntaria;
	private ConveniosConceptoDTO conveniosConceptoDTO;
	private String periodo;
	private Date fxIniVoluntaria;
	private Date fxFinVoluntaria;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	
	private String rowid;

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public PeriodoVoluntariaDTO() {
	}

	public PeriodoVoluntariaDTO(String periodo, Date fxIniVoluntaria,
			Date fxFinVoluntaria) {
		this.periodo = periodo;
		this.fxIniVoluntaria = fxIniVoluntaria;
		this.fxFinVoluntaria = fxFinVoluntaria;
	}

	public PeriodoVoluntariaDTO(ConveniosConceptoDTO conveniosConceptoDTO,
			String periodo, Date fxIniVoluntaria, Date fxFinVoluntaria,
			String coUsuarioActualizacion, Date fhActualizacion) {
		this.conveniosConceptoDTO = conveniosConceptoDTO;
		this.periodo = periodo;
		this.fxIniVoluntaria = fxIniVoluntaria;
		this.fxFinVoluntaria = fxFinVoluntaria;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
	}

	public Long getCoPeriodoVoluntaria() {
		return this.coPeriodoVoluntaria;
	}

	public void setCoPeriodoVoluntaria(Long coPeriodoVoluntaria) {
		this.coPeriodoVoluntaria = coPeriodoVoluntaria;
	}

	public ConveniosConceptoDTO getConveniosConceptoDTO() {
		return this.conveniosConceptoDTO;
	}

	public void setConveniosConceptoDTO(
			ConveniosConceptoDTO conveniosConceptoDTO) {
		this.conveniosConceptoDTO = conveniosConceptoDTO;
	}

	public String getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(String periodo) {
		this.periodo = periodo;
	}

	public Date getFxIniVoluntaria() {
		return this.fxIniVoluntaria;
	}

	public void setFxIniVoluntaria(Date fxIniVoluntaria) {
		this.fxIniVoluntaria = fxIniVoluntaria;
	}

	public Date getFxFinVoluntaria() {
		return this.fxFinVoluntaria;
	}

	public void setFxFinVoluntaria(Date fxFinVoluntaria) {
		this.fxFinVoluntaria = fxFinVoluntaria;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

}
