package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * PlantillaModeloDTO generated by hbm2java
 */
public class PlantillaModeloDTO implements java.io.Serializable, Comparable<PlantillaModeloDTO> {

	private PlantillaModeloDTOId id;
	private PlantillaDTO plantillaDTO;
	private ModeloVersionDTO modeloVersionDTO;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public PlantillaModeloDTO() {
	}

	public PlantillaModeloDTO(PlantillaModeloDTOId id,
			PlantillaDTO plantillaDTO, ModeloVersionDTO modeloVersionDTO) {
		this.id = id;
		this.plantillaDTO = plantillaDTO;
		this.modeloVersionDTO = modeloVersionDTO;
	}

	public PlantillaModeloDTO(PlantillaModeloDTOId id,
			PlantillaDTO plantillaDTO, ModeloVersionDTO modeloVersionDTO,
			Date fhActualizacion, String coUsuarioActualizacion) {
		this.id = id;
		this.plantillaDTO = plantillaDTO;
		this.modeloVersionDTO = modeloVersionDTO;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public PlantillaModeloDTOId getId() {
		return this.id;
	}

	public void setId(PlantillaModeloDTOId id) {
		this.id = id;
	}

	public PlantillaDTO getPlantillaDTO() {
		return this.plantillaDTO;
	}

	public void setPlantillaDTO(PlantillaDTO plantillaDTO) {
		this.plantillaDTO = plantillaDTO;
	}

	public ModeloVersionDTO getModeloVersionDTO() {
		return this.modeloVersionDTO;
	}

	public void setModeloVersionDTO(ModeloVersionDTO modeloVersionDTO) {
		this.modeloVersionDTO = modeloVersionDTO;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public int compareTo(PlantillaModeloDTO plantillaModeloDTO) {
		int resultado = this.getId().getCoModelo().compareTo(plantillaModeloDTO.getId().getCoModelo());
		if (resultado == 0) {
			resultado = this.getId().getCoVersion().compareTo(plantillaModeloDTO.getId().getCoVersion());
		}
		return resultado;
	}

}
