package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * PlantillaFirmaDTOId generated by hbm2java
 */
public class PlantillaFirmaDTOId implements java.io.Serializable {

	private long coPlantilla;
	private String coUnidadAdministrativa;
	private short ordenFirma;
	private Date fxDesde;

	public PlantillaFirmaDTOId() {
	}

	public PlantillaFirmaDTOId(long coPlantilla, String coUnidadAdministrativa,
			short ordenFirma, Date fxDesde) {
		this.coPlantilla = coPlantilla;
		this.coUnidadAdministrativa = coUnidadAdministrativa;
		this.ordenFirma = ordenFirma;
		this.fxDesde = fxDesde;
	}

	public long getCoPlantilla() {
		return this.coPlantilla;
	}

	public void setCoPlantilla(long coPlantilla) {
		this.coPlantilla = coPlantilla;
	}

	public String getCoUnidadAdministrativa() {
		return this.coUnidadAdministrativa;
	}

	public void setCoUnidadAdministrativa(String coUnidadAdministrativa) {
		this.coUnidadAdministrativa = coUnidadAdministrativa;
	}

	public short getOrdenFirma() {
		return this.ordenFirma;
	}

	public void setOrdenFirma(short ordenFirma) {
		this.ordenFirma = ordenFirma;
	}

	public Date getFxDesde() {
		return this.fxDesde;
	}

	public void setFxDesde(Date fxDesde) {
		this.fxDesde = fxDesde;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlantillaFirmaDTOId))
			return false;
		PlantillaFirmaDTOId castOther = (PlantillaFirmaDTOId) other;

		return (this.getCoPlantilla() == castOther.getCoPlantilla())
				&& ((this.getCoUnidadAdministrativa() == castOther
						.getCoUnidadAdministrativa()) || (this
						.getCoUnidadAdministrativa() != null
						&& castOther.getCoUnidadAdministrativa() != null && this
						.getCoUnidadAdministrativa().equals(
								castOther.getCoUnidadAdministrativa())))
				&& (this.getOrdenFirma() == castOther.getOrdenFirma())
				&& ((this.getFxDesde() == castOther.getFxDesde()) || (this
						.getFxDesde() != null
						&& castOther.getFxDesde() != null && this.getFxDesde()
						.equals(castOther.getFxDesde())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCoPlantilla();
		result = 37
				* result
				+ (getCoUnidadAdministrativa() == null ? 0 : this
						.getCoUnidadAdministrativa().hashCode());
		result = 37 * result + this.getOrdenFirma();
		result = 37 * result
				+ (getFxDesde() == null ? 0 : this.getFxDesde().hashCode());
		return result;
	}

}
