package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * PlantillaTablaDTO generated by hbm2java
 */
public class PlantillaTablaDTO implements java.io.Serializable {

	private PlantillaTablaDTOId id;
	private PlantillaDTO plantillaDTO;
	private Short numLineas;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<PlantillaEtiquetaDTO> plantillaEtiquetaDTOs = new HashSet<PlantillaEtiquetaDTO>(
			0);
	private String rowid;

	public PlantillaTablaDTO() {
	}

	public PlantillaTablaDTO(PlantillaTablaDTOId id, PlantillaDTO plantillaDTO) {
		this.id = id;
		this.plantillaDTO = plantillaDTO;
	}

	public PlantillaTablaDTO(PlantillaTablaDTOId id, PlantillaDTO plantillaDTO,
			Short numLineas, Date fhActualizacion,
			String coUsuarioActualizacion,
			Set<PlantillaEtiquetaDTO> plantillaEtiquetaDTOs) {
		this.id = id;
		this.plantillaDTO = plantillaDTO;
		this.numLineas = numLineas;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.plantillaEtiquetaDTOs = plantillaEtiquetaDTOs;
	}

	public PlantillaTablaDTOId getId() {
		return this.id;
	}

	public void setId(PlantillaTablaDTOId id) {
		this.id = id;
	}

	public PlantillaDTO getPlantillaDTO() {
		return this.plantillaDTO;
	}

	public void setPlantillaDTO(PlantillaDTO plantillaDTO) {
		this.plantillaDTO = plantillaDTO;
	}

	public Short getNumLineas() {
		return this.numLineas;
	}

	public void setNumLineas(Short numLineas) {
		this.numLineas = numLineas;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<PlantillaEtiquetaDTO> getPlantillaEtiquetaDTOs() {
		return this.plantillaEtiquetaDTOs;
	}

	public void setPlantillaEtiquetaDTOs(
			Set<PlantillaEtiquetaDTO> plantillaEtiquetaDTOs) {
		this.plantillaEtiquetaDTOs = plantillaEtiquetaDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
