package es.dipucadiz.etir.comun.dto;

// Generated 11-feb-2010 12:29:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * PlantillaImgCondCampoDTO generated by hbm2java
 */
public class PlantillaImgCondCampoDTO implements java.io.Serializable {

	private PlantillaImgCondCampoDTOId id;
	private PlantillaImgCondicionalDTO plantillaImgCondicionalDTO;
	private String tipo;
	private String valor;
	private String valorAdicional;
	private String modeloAdicional;
	private String versionAdicional;
	private Short posInicio;
	private Short posFin;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public PlantillaImgCondCampoDTO() {
	}

	public PlantillaImgCondCampoDTO(PlantillaImgCondCampoDTOId id,
			PlantillaImgCondicionalDTO plantillaImgCondicionalDTO,
			String tipo, String valor) {
		this.id = id;
		this.plantillaImgCondicionalDTO = plantillaImgCondicionalDTO;
		this.tipo = tipo;
		this.valor = valor;
	}

	public PlantillaImgCondCampoDTO(PlantillaImgCondCampoDTOId id,
			PlantillaImgCondicionalDTO plantillaImgCondicionalDTO,
			long coPlantillaImgCondicional, String tipo, String valor,
			String valorAdicional, String modeloAdicional,
			String versionAdicional, Short posInicio, Short posFin,
			Date fhActualizacion, String coUsuarioActualizacion) {
		this.id = id;
		this.plantillaImgCondicionalDTO = plantillaImgCondicionalDTO;
		this.tipo = tipo;
		this.valor = valor;
		this.valorAdicional = valorAdicional;
		this.modeloAdicional = modeloAdicional;
		this.versionAdicional = versionAdicional;
		this.posInicio = posInicio;
		this.posFin = posFin;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public PlantillaImgCondCampoDTOId getId() {
		return this.id;
	}

	public void setId(PlantillaImgCondCampoDTOId id) {
		this.id = id;
	}

	public PlantillaImgCondicionalDTO getPlantillaImgCondicionalDTO() {
		return this.plantillaImgCondicionalDTO;
	}

	public void setPlantillaImgCondicionalDTO(
			PlantillaImgCondicionalDTO plantillaImgCondicionalDTO) {
		this.plantillaImgCondicionalDTO = plantillaImgCondicionalDTO;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public String getValorAdicional() {
		return this.valorAdicional;
	}

	public void setValorAdicional(String valorAdicional) {
		this.valorAdicional = valorAdicional;
	}

	public String getModeloAdicional() {
		return this.modeloAdicional;
	}

	public void setModeloAdicional(String modeloAdicional) {
		this.modeloAdicional = modeloAdicional;
	}

	public String getVersionAdicional() {
		return this.versionAdicional;
	}

	public void setVersionAdicional(String versionAdicional) {
		this.versionAdicional = versionAdicional;
	}

	public Short getPosInicio() {
		return this.posInicio;
	}

	public void setPosInicio(Short posInicio) {
		this.posInicio = posInicio;
	}

	public Short getPosFin() {
		return this.posFin;
	}

	public void setPosFin(Short posFin) {
		this.posFin = posFin;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
