package es.dipucadiz.etir.comun.dto;

// Generated 11-feb-2010 12:29:03 by Hibernate Tools 3.2.4.GA

/**
 * PlantillaImgCondicionalDTOId generated by hbm2java
 */
public class PlantillaImgCondicionalDTOId implements java.io.Serializable {

	private long coPlantillaImagen;
	private short ordenImgCondicional;

	public PlantillaImgCondicionalDTOId() {
	}

	public PlantillaImgCondicionalDTOId(long coPlantillaImagen,
			short ordenImgCondicional) {
		this.coPlantillaImagen = coPlantillaImagen;
		this.ordenImgCondicional = ordenImgCondicional;
	}

	public long getCoPlantillaImagen() {
		return this.coPlantillaImagen;
	}

	public void setCoPlantillaImagen(long coPlantillaImagen) {
		this.coPlantillaImagen = coPlantillaImagen;
	}

	public short getOrdenImgCondicional() {
		return this.ordenImgCondicional;
	}

	public void setOrdenImgCondicional(short ordenImgCondicional) {
		this.ordenImgCondicional = ordenImgCondicional;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlantillaImgCondicionalDTOId))
			return false;
		PlantillaImgCondicionalDTOId castOther = (PlantillaImgCondicionalDTOId) other;

		return (this.getCoPlantillaImagen() == castOther.getCoPlantillaImagen())
				&& (this.getOrdenImgCondicional() == castOther
						.getOrdenImgCondicional());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCoPlantillaImagen();
		result = 37 * result + this.getOrdenImgCondicional();
		return result;
	}

}
