package es.dipucadiz.etir.comun.dto;

// Generated 07-jul-2010 10:24:49 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * PlanificacionArgumentoDTO generated by hbm2java
 */
public class PlanificacionArgumentoDTO implements java.io.Serializable {

	private Long coPlanificacionArgumento;
	private PlanificacionDTO planificacionDTO;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String valor;
	private Short nuProcesoParametro;

	public PlanificacionArgumentoDTO() {
	}

	public PlanificacionArgumentoDTO(PlanificacionDTO planificacionDTO,
			Date fhActualizacion, String coUsuarioActualizacion, String valor,
			Short nuProcesoParametro) {
		this.planificacionDTO = planificacionDTO;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.valor = valor;
		this.nuProcesoParametro = nuProcesoParametro;
	}

	public Long getCoPlanificacionArgumento() {
		return this.coPlanificacionArgumento;
	}

	public void setCoPlanificacionArgumento(Long coPlanificacionArgumento) {
		this.coPlanificacionArgumento = coPlanificacionArgumento;
	}

	public PlanificacionDTO getPlanificacionDTO() {
		return this.planificacionDTO;
	}

	public void setPlanificacionDTO(PlanificacionDTO planificacionDTO) {
		this.planificacionDTO = planificacionDTO;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public Short getNuProcesoParametro() {
		return this.nuProcesoParametro;
	}

	public void setNuProcesoParametro(Short nuProcesoParametro) {
		this.nuProcesoParametro = nuProcesoParametro;
	}

}
