package es.dipucadiz.etir.comun.dto;

// Generated 11-feb-2010 12:29:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * PlantillaImagenDTO generated by hbm2java
 */
public class PlantillaImagenDTO implements java.io.Serializable {

	private Long coPlantillaImagen;
	private PlantillaDTO plantillaDTO;
	private UnidadAdministrativaDTO unidadAdministrativaDTO;
	private Short ordenImagen;
	private Date fxDesde;
	private Date fxHasta;
	private String ruta;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<PlantillaImgCondicionalDTO> plantillaImgCondicionalDTOs = new HashSet<PlantillaImgCondicionalDTO>(
			0);
	private String rowid;

	public PlantillaImagenDTO() {
	}

	public PlantillaImagenDTO(PlantillaDTO plantillaDTO,
			UnidadAdministrativaDTO unidadAdministrativaDTO, Short ordenImagen,
			Date fxDesde, Date fxHasta, String ruta, Date fhActualizacion,
			String coUsuarioActualizacion,
			Set<PlantillaImgCondicionalDTO> plantillaImgCondicionalDTOs) {
		this.plantillaDTO = plantillaDTO;
		this.unidadAdministrativaDTO = unidadAdministrativaDTO;
		this.ordenImagen = ordenImagen;
		this.fxDesde = fxDesde;
		this.fxHasta = fxHasta;
		this.ruta = ruta;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.plantillaImgCondicionalDTOs = plantillaImgCondicionalDTOs;
	}

	public Long getCoPlantillaImagen() {
		return this.coPlantillaImagen;
	}

	public void setCoPlantillaImagen(Long coPlantillaImagen) {
		this.coPlantillaImagen = coPlantillaImagen;
	}

	public PlantillaDTO getPlantillaDTO() {
		return this.plantillaDTO;
	}

	public void setPlantillaDTO(PlantillaDTO plantillaDTO) {
		this.plantillaDTO = plantillaDTO;
	}

	public UnidadAdministrativaDTO getUnidadAdministrativaDTO() {
		return this.unidadAdministrativaDTO;
	}

	public void setUnidadAdministrativaDTO(
			UnidadAdministrativaDTO unidadAdministrativaDTO) {
		this.unidadAdministrativaDTO = unidadAdministrativaDTO;
	}

	public Short getOrdenImagen() {
		return this.ordenImagen;
	}

	public void setOrdenImagen(Short ordenImagen) {
		this.ordenImagen = ordenImagen;
	}

	public Date getFxDesde() {
		return this.fxDesde;
	}

	public void setFxDesde(Date fxDesde) {
		this.fxDesde = fxDesde;
	}

	public Date getFxHasta() {
		return this.fxHasta;
	}

	public void setFxHasta(Date fxHasta) {
		this.fxHasta = fxHasta;
	}

	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<PlantillaImgCondicionalDTO> getPlantillaImgCondicionalDTOs() {
		return this.plantillaImgCondicionalDTOs;
	}

	public void setPlantillaImgCondicionalDTOs(
			Set<PlantillaImgCondicionalDTO> plantillaImgCondicionalDTOs) {
		this.plantillaImgCondicionalDTOs = plantillaImgCondicionalDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
