package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * PlantillaFirmaDTO generated by hbm2java
 */
public class PlantillaFirmaDTO implements java.io.Serializable {

	private PlantillaFirmaDTOId id;
	private PlantillaDTO plantillaDTO;
	private UnidadAdministrativaDTO unidadAdministrativaDTO;
	private Date fxHasta;
	private String ruta;
	private String cargo;
	private String firmante;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public PlantillaFirmaDTO() {
	}

	public PlantillaFirmaDTO(PlantillaFirmaDTOId id, PlantillaDTO plantillaDTO,
			UnidadAdministrativaDTO unidadAdministrativaDTO) {
		this.id = id;
		this.plantillaDTO = plantillaDTO;
		this.unidadAdministrativaDTO = unidadAdministrativaDTO;
	}

	public PlantillaFirmaDTO(PlantillaFirmaDTOId id, PlantillaDTO plantillaDTO,
			UnidadAdministrativaDTO unidadAdministrativaDTO, Date fxHasta,
			String ruta, String cargo, String firmante, Date fhActualizacion,
			String coUsuarioActualizacion) {
		this.id = id;
		this.plantillaDTO = plantillaDTO;
		this.unidadAdministrativaDTO = unidadAdministrativaDTO;
		this.fxHasta = fxHasta;
		this.ruta = ruta;
		this.cargo = cargo;
		this.firmante = firmante;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public PlantillaFirmaDTOId getId() {
		return this.id;
	}

	public void setId(PlantillaFirmaDTOId id) {
		this.id = id;
	}

	public PlantillaDTO getPlantillaDTO() {
		return this.plantillaDTO;
	}

	public void setPlantillaDTO(PlantillaDTO plantillaDTO) {
		this.plantillaDTO = plantillaDTO;
	}

	public UnidadAdministrativaDTO getUnidadAdministrativaDTO() {
		return this.unidadAdministrativaDTO;
	}

	public void setUnidadAdministrativaDTO(
			UnidadAdministrativaDTO unidadAdministrativaDTO) {
		this.unidadAdministrativaDTO = unidadAdministrativaDTO;
	}

	public Date getFxHasta() {
		return this.fxHasta;
	}

	public void setFxHasta(Date fxHasta) {
		this.fxHasta = fxHasta;
	}

	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public String getFirmante() {
		return this.firmante;
	}

	public void setFirmante(String firmante) {
		this.firmante = firmante;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
