package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * PppCondsPlazosDTO generated by hbm2java
 */
public class PppCondsPlazosDTO implements java.io.Serializable, Comparable {

	private Long coPppCondsPlazos;
	private PppCondsDTO pppCondsDTO;
	private Short nuPlazos;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private Set<PppCondsPlazosFxsDTO> pppCondsPlazosFxsDTOs = new HashSet<PppCondsPlazosFxsDTO>(
			0);
	
	private String rowid;

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public PppCondsPlazosDTO() {
	}

	public PppCondsPlazosDTO(PppCondsDTO pppCondsDTO) {
		this.pppCondsDTO = pppCondsDTO;
	}

	public PppCondsPlazosDTO(PppCondsDTO pppCondsDTO, Short nuPlazos,
			String coUsuarioActualizacion, Date fhActualizacion,
			Set<PppCondsPlazosFxsDTO> pppCondsPlazosFxsDTOs) {
		this.pppCondsDTO = pppCondsDTO;
		this.nuPlazos = nuPlazos;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.pppCondsPlazosFxsDTOs = pppCondsPlazosFxsDTOs;
	}

	public Long getCoPppCondsPlazos() {
		return this.coPppCondsPlazos;
	}

	public void setCoPppCondsPlazos(Long coPppCondsPlazos) {
		this.coPppCondsPlazos = coPppCondsPlazos;
	}

	public PppCondsDTO getPppCondsDTO() {
		return this.pppCondsDTO;
	}

	public void setPppCondsDTO(PppCondsDTO pppCondsDTO) {
		this.pppCondsDTO = pppCondsDTO;
	}

	public Short getNuPlazos() {
		return this.nuPlazos;
	}

	public void setNuPlazos(Short nuPlazos) {
		this.nuPlazos = nuPlazos;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public Set<PppCondsPlazosFxsDTO> getPppCondsPlazosFxsDTOs() {
		return this.pppCondsPlazosFxsDTOs;
	}

	public void setPppCondsPlazosFxsDTOs(
			Set<PppCondsPlazosFxsDTO> pppCondsPlazosFxsDTOs) {
		this.pppCondsPlazosFxsDTOs = pppCondsPlazosFxsDTOs;
	}

	public int compareTo(Object o) {
		int res=0;
		try{
			res= nuPlazos.compareTo(((PppCondsPlazosDTO)o).getNuPlazos());
		}catch(Exception e){
			
		}
		return res;
	}

}
