package es.dipucadiz.etir.comun.dto;

// Generated 11-nov-2010 11:56:35 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * PppDTO generated by hbm2java
 */
public class PppDTO implements java.io.Serializable {

	private Long coPpp;
	private ClienteDTO clienteDTOByCoClienteConyuge;
	private DocumentoDTO documentoDTO;
	private DomiciliacionDTO domiciliacionDTO;
	private ClienteDTO clienteDTOByCoCliente;
	private BigDecimal importe;
	private Short nuPlazos;
	private Date fxIni;
	private Date fxFin;
	private Date fxSolicitud;
	private Date fxConcesion;
	private String coUsuarioActualizacion;
	private Date fhActualizacion;
	private String coSituacionCargo;
	private Short ano;
	private Short anoInicio;
	private Integer nuPpp;
	private BigDecimal importeEjercicioAnterior;
	private BigDecimal importeEstimado;
	private BigDecimal saldoEjercicioAnterior;
	private BigDecimal importeCobrado;
	private BigDecimal importeSaldado;
	private boolean boHaLlegadoTodo;
	private Set<PppSeguimientoDTO> pppSeguimientoDTOs = new HashSet<PppSeguimientoDTO>(
			0);
	private Set<DocumentoLiquidacionDTO> documentoLiquidacionDTOs = new HashSet<DocumentoLiquidacionDTO>(
			0);
	private Set<PppEstimacionDTO> pppEstimacionDTOs = new HashSet<PppEstimacionDTO>(
			0);
	private Set<PppPlazoDTO> pppPlazoDTOs = new HashSet<PppPlazoDTO>(0);
	
	private String rowid;

	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public PppDTO() {
	}

	public PppDTO(ClienteDTO clienteDTOByCoClienteConyuge,
			DocumentoDTO documentoDTO, DomiciliacionDTO domiciliacionDTO,
			ClienteDTO clienteDTOByCoCliente, BigDecimal importe,
			Short nuPlazos, Date fxIni, Date fxFin, Date fxSolicitud,
			Date fxConcesion, String coUsuarioActualizacion,
			Date fhActualizacion, String coSituacionCargo, Short ano,
			Short anoInicio, Integer nuPpp,
			Set<DocumentoLiquidacionDTO> documentoLiquidacionDTOs,
			Set<PppEstimacionDTO> pppEstimacionDTOs,
			Set<PppPlazoDTO> pppPlazoDTOs) {
		this.clienteDTOByCoClienteConyuge = clienteDTOByCoClienteConyuge;
		this.documentoDTO = documentoDTO;
		this.domiciliacionDTO = domiciliacionDTO;
		this.clienteDTOByCoCliente = clienteDTOByCoCliente;
		this.importe = importe;
		this.nuPlazos = nuPlazos;
		this.fxIni = fxIni;
		this.fxFin = fxFin;
		this.fxSolicitud = fxSolicitud;
		this.fxConcesion = fxConcesion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.fhActualizacion = fhActualizacion;
		this.coSituacionCargo = coSituacionCargo;
		this.ano = ano;
		this.anoInicio = anoInicio;
		this.nuPpp = nuPpp;
		this.documentoLiquidacionDTOs = documentoLiquidacionDTOs;
		this.pppEstimacionDTOs = pppEstimacionDTOs;
		this.pppPlazoDTOs = pppPlazoDTOs;
	}

	public Long getCoPpp() {
		return this.coPpp;
	}

	public void setCoPpp(Long coPpp) {
		this.coPpp = coPpp;
	}

	public ClienteDTO getClienteDTOByCoClienteConyuge() {
		return this.clienteDTOByCoClienteConyuge;
	}

	public void setClienteDTOByCoClienteConyuge(
			ClienteDTO clienteDTOByCoClienteConyuge) {
		this.clienteDTOByCoClienteConyuge = clienteDTOByCoClienteConyuge;
	}

	public DocumentoDTO getDocumentoDTO() {
		return this.documentoDTO;
	}

	public void setDocumentoDTO(DocumentoDTO documentoDTO) {
		this.documentoDTO = documentoDTO;
	}

	public DomiciliacionDTO getDomiciliacionDTO() {
		return this.domiciliacionDTO;
	}

	public void setDomiciliacionDTO(DomiciliacionDTO domiciliacionDTO) {
		this.domiciliacionDTO = domiciliacionDTO;
	}

	public ClienteDTO getClienteDTOByCoCliente() {
		return this.clienteDTOByCoCliente;
	}

	public void setClienteDTOByCoCliente(ClienteDTO clienteDTOByCoCliente) {
		this.clienteDTOByCoCliente = clienteDTOByCoCliente;
	}

	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	public Short getNuPlazos() {
		return this.nuPlazos;
	}

	public void setNuPlazos(Short nuPlazos) {
		this.nuPlazos = nuPlazos;
	}

	public Date getFxIni() {
		return this.fxIni;
	}

	public void setFxIni(Date fxIni) {
		this.fxIni = fxIni;
	}

	public Date getFxFin() {
		return this.fxFin;
	}

	public void setFxFin(Date fxFin) {
		this.fxFin = fxFin;
	}

	public Date getFxSolicitud() {
		return this.fxSolicitud;
	}

	public void setFxSolicitud(Date fxSolicitud) {
		this.fxSolicitud = fxSolicitud;
	}

	public Date getFxConcesion() {
		return this.fxConcesion;
	}

	public void setFxConcesion(Date fxConcesion) {
		this.fxConcesion = fxConcesion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoSituacionCargo() {
		return this.coSituacionCargo;
	}

	public void setCoSituacionCargo(String coSituacionCargo) {
		this.coSituacionCargo = coSituacionCargo;
	}

	public Short getAno() {
		return this.ano;
	}

	public void setAno(Short ano) {
		this.ano = ano;
	}

	public Short getAnoInicio() {
		return this.anoInicio;
	}

	public void setAnoInicio(Short anoInicio) {
		this.anoInicio = anoInicio;
	}

	public Integer getNuPpp() {
		return this.nuPpp;
	}

	public void setNuPpp(Integer nuPpp) {
		this.nuPpp = nuPpp;
	}
	
	public BigDecimal getImporteEjercicioAnterior() {
		return this.importeEjercicioAnterior;
	}

	public void setImporteEjercicioAnterior(BigDecimal importeEjercicioAnterior) {
		this.importeEjercicioAnterior = importeEjercicioAnterior;
	}

	public BigDecimal getImporteEstimado() {
		return this.importeEstimado;
	}

	public void setImporteEstimado(BigDecimal importeEstimado) {
		this.importeEstimado = importeEstimado;
	}

	public BigDecimal getSaldoEjercicioAnterior() {
		return this.saldoEjercicioAnterior;
	}

	public void setSaldoEjercicioAnterior(BigDecimal saldoEjercicioAnterior) {
		this.saldoEjercicioAnterior = saldoEjercicioAnterior;
	}

	public BigDecimal getImporteCobrado() {
		return this.importeCobrado;
	}

	public void setImporteCobrado(BigDecimal importeCobrado) {
		this.importeCobrado = importeCobrado;
	}

	public BigDecimal getImporteSaldado() {
		return this.importeSaldado;
	}

	public void setImporteSaldado(BigDecimal importeSaldado) {
		this.importeSaldado = importeSaldado;
	}

	public boolean isBoHaLlegadoTodo() {
		return this.boHaLlegadoTodo;
	}

	public void setBoHaLlegadoTodo(boolean boHaLlegadoTodo) {
		this.boHaLlegadoTodo = boHaLlegadoTodo;
	}

	public Set<PppSeguimientoDTO> getPppSeguimientoDTOs() {
		return this.pppSeguimientoDTOs;
	}

	public void setPppSeguimientoDTOs(Set<PppSeguimientoDTO> pppSeguimientoDTOs) {
		this.pppSeguimientoDTOs = pppSeguimientoDTOs;
	}

	public Set<DocumentoLiquidacionDTO> getDocumentoLiquidacionDTOs() {
		return this.documentoLiquidacionDTOs;
	}

	public void setDocumentoLiquidacionDTOs(
			Set<DocumentoLiquidacionDTO> documentoLiquidacionDTOs) {
		this.documentoLiquidacionDTOs = documentoLiquidacionDTOs;
	}

	public Set<PppEstimacionDTO> getPppEstimacionDTOs() {
		return this.pppEstimacionDTOs;
	}

	public void setPppEstimacionDTOs(Set<PppEstimacionDTO> pppEstimacionDTOs) {
		this.pppEstimacionDTOs = pppEstimacionDTOs;
	}

	public Set<PppPlazoDTO> getPppPlazoDTOs() {
		return this.pppPlazoDTOs;
	}

	public void setPppPlazoDTOs(Set<PppPlazoDTO> pppPlazoDTOs) {
		this.pppPlazoDTOs = pppPlazoDTOs;
	}

}
