package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ProcesoParametroDTO generated by hbm2java
 */
public class ProcesoParametroDTO implements java.io.Serializable {

	private ProcesoParametroDTOId id;
	private ProcesoDTO procesoDTO;
	private String nombre;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public ProcesoParametroDTO() {
	}

	public ProcesoParametroDTO(ProcesoParametroDTOId id, ProcesoDTO procesoDTO,
			String nombre) {
		this.id = id;
		this.procesoDTO = procesoDTO;
		this.nombre = nombre;
	}

	public ProcesoParametroDTO(ProcesoParametroDTOId id, ProcesoDTO procesoDTO,
			String nombre, Date fhActualizacion, String coUsuarioActualizacion) {
		this.id = id;
		this.procesoDTO = procesoDTO;
		this.nombre = nombre;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public ProcesoParametroDTOId getId() {
		return this.id;
	}

	public void setId(ProcesoParametroDTOId id) {
		this.id = id;
	}

	public ProcesoDTO getProcesoDTO() {
		return this.procesoDTO;
	}

	public void setProcesoDTO(ProcesoDTO procesoDTO) {
		this.procesoDTO = procesoDTO;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
