package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ProvinciaSinonimoDTO generated by hbm2java
 */
public class ProvinciaSinonimoDTO implements java.io.Serializable {

	private ProvinciaSinonimoDTOId id;
	private ProvinciaDTO provinciaDTO;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public ProvinciaSinonimoDTO() {
	}

	public ProvinciaSinonimoDTO(ProvinciaSinonimoDTOId id,
			ProvinciaDTO provinciaDTO) {
		this.id = id;
		this.provinciaDTO = provinciaDTO;
	}

	public ProvinciaSinonimoDTO(ProvinciaSinonimoDTOId id,
			ProvinciaDTO provinciaDTO, Date fhActualizacion,
			String coUsuarioActualizacion) {
		this.id = id;
		this.provinciaDTO = provinciaDTO;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public ProvinciaSinonimoDTOId getId() {
		return this.id;
	}

	public void setId(ProvinciaSinonimoDTOId id) {
		this.id = id;
	}

	public ProvinciaDTO getProvinciaDTO() {
		return this.provinciaDTO;
	}

	public void setProvinciaDTO(ProvinciaDTO provinciaDTO) {
		this.provinciaDTO = provinciaDTO;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
