package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * DocumentoDTOId generated by hbm2java
 */
public class RegistroMunicipioDTOId implements java.io.Serializable {

	private Long coRegistro;
	private String coProvincia;
	private String coMunicipio;

	public RegistroMunicipioDTOId() {
	}
	
	

	public RegistroMunicipioDTOId(Long coRegistro, String coProvincia, String coMunicipio) {
		super();
		this.coRegistro = coRegistro;
		this.coProvincia = coProvincia;
		this.coMunicipio = coMunicipio;
	}



	public Long getCoRegistro() {
		return coRegistro;
	}

	public void setCoRegistro(Long coRegistro) {
		this.coRegistro = coRegistro;
	}

	public String getCoProvincia() {
		return coProvincia;
	}

	public void setCoProvincia(String coProvincia) {
		this.coProvincia = coProvincia;
	}

	public String getCoMunicipio() {
		return coMunicipio;
	}

	public void setCoMunicipio(String coMunicipio) {
		this.coMunicipio = coMunicipio;
	}


	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegistroMunicipioDTOId))
			return false;
		RegistroMunicipioDTOId castOther = (RegistroMunicipioDTOId) other;

		return (this.getCoProvincia()== castOther.getCoProvincia() && this.getCoMunicipio().equals(castOther.getCoMunicipio())&& this.getCoProvincia().equals(castOther.getCoProvincia()));
	}

	public int hashCode() {
		int result = 47;

		result = 127
				* result
				+ (getCoRegistro() == null ? 0 : this.getCoRegistro().hashCode());
		return result;
	}
	
}
