package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ProvinciaDTO generated by hbm2java
 */
public class RegistroMunicipioDTO implements java.io.Serializable  {

	private RegistroMunicipioDTOId id;
	 
	
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	 
	private String rowid;

	
	
	public RegistroMunicipioDTO() {
		super();
	}



	 


	public RegistroMunicipioDTO(RegistroMunicipioDTOId id,
			Date fhActualizacion, String coUsuarioActualizacion, String rowid) {
		super();
		this.id = id;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.rowid = rowid;
	}






	public RegistroMunicipioDTOId getId() {
		return id;
	}






	public void setId(RegistroMunicipioDTOId id) {
		this.id = id;
	}






	public Date getFhActualizacion() {
		return fhActualizacion;
	}



	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}



	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}



	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}



	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}
	

	 
	
	 
	 
	}


