package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * RemesaCargoCanalResDTO generated by hbm2java
 */
public class RemesaCargoCanalResDTO implements java.io.Serializable {
	private static final long serialVersionUID = -3180317549647412965L;
	
	private Long coRemesaCargoCanalRes;
	private RemesaDTO remesaDTO;
	private OtrDTO otrDTO;
	private CargoDTO cargoDTO;
	private String canalNotificacion;
	private String coResultado;
	private Long nuCodbar;	
	private MunicipioDTO municipioNotificacionDTO;
	private BigDecimal imNotificado;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;	
	private String rowid;

	public RemesaCargoCanalResDTO() {
	}

	public RemesaCargoCanalResDTO(RemesaDTO remesaDTO, OtrDTO otrDTO, CargoDTO cargoDTO, String canalNotificacion,
	String coResultado, Long nuCodbar, BigDecimal imNotificado, Date fhActualizacion, String coUsuarioActualizacion) {
		this.remesaDTO = remesaDTO;
		this.otrDTO = otrDTO;
		this.cargoDTO = cargoDTO;
		this.canalNotificacion = canalNotificacion;
		this.coResultado = coResultado;
		this.nuCodbar = nuCodbar;	
		this.imNotificado = imNotificado;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Long getCoRemesaCargoCanalRes() {
		return coRemesaCargoCanalRes;
	}

	public void setCoRemesaCargoCanalRes(Long coRemesaCargoCanalRes) {
		this.coRemesaCargoCanalRes = coRemesaCargoCanalRes;
	}

	public RemesaDTO getRemesaDTO() {
		return remesaDTO;
	}

	public void setRemesaDTO(RemesaDTO remesaDTO) {
		this.remesaDTO = remesaDTO;
	}

	public OtrDTO getOtrDTO() {
		return otrDTO;
	}

	public void setOtrDTO(OtrDTO otrDTO) {
		this.otrDTO = otrDTO;
	}

	public CargoDTO getCargoDTO() {
		return cargoDTO;
	}

	public void setCargoDTO(CargoDTO cargoDTO) {
		this.cargoDTO = cargoDTO;
	}

	public String getCanalNotificacion() {
		return canalNotificacion;
	}

	public void setCanalNotificacion(String canalNotificacion) {
		this.canalNotificacion = canalNotificacion;
	}

	public String getCoResultado() {
		return coResultado;
	}

	public void setCoResultado(String coResultado) {
		this.coResultado = coResultado;
	}

	public Long getNuCodbar() {
		return nuCodbar;
	}

	public void setNuCodbar(Long nuCodbar) {
		this.nuCodbar = nuCodbar;
	}

	public Date getFhActualizacion() {
		return fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	public void setMunicipioNotificacionDTO(MunicipioDTO municipioNotificacionDTO) {
		this.municipioNotificacionDTO = municipioNotificacionDTO;
	}

	public MunicipioDTO getMunicipioNotificacionDTO() {
		return municipioNotificacionDTO;
	}

	public void setImNotificado(BigDecimal imNotificado) {
		this.imNotificado = imNotificado;
	}

	public BigDecimal getImNotificado() {
		return imNotificado;
	}
	
}
