package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * RemesaDTO generated by hbm2java
 */
public class RemesaUniAdmDTO implements java.io.Serializable {
	private static final long serialVersionUID = -3180317549647412965L;
	
	private Long coRemesaUniAdm;
	private RemesaDTO remesaDTO;
	private UnidadAdministrativaDTO unidadAdministrativaDTO;	
	private String estado;
	private BigDecimal imNotificado;
	private Long notificaciones; 
	private Date fhActualizacion;
	private String coUsuarioActualizacion;	
	private String rowid;

	public RemesaUniAdmDTO() {
	}

	public RemesaUniAdmDTO(RemesaDTO remesaDTO, UnidadAdministrativaDTO unidadAdministrativaDTO, String estado, 
	 BigDecimal imNotificado, Long notificaciones, Date fhActualizacion, String coUsuarioActualizacion) {
		this.remesaDTO = remesaDTO;
		this.unidadAdministrativaDTO = unidadAdministrativaDTO;
		this.estado = estado;		
		this.imNotificado = imNotificado;
		this.notificaciones = notificaciones;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;				
	}

	public Long getCoRemesaUniAdm() {
		return coRemesaUniAdm;
	}

	public void setCoRemesaUniAdm(Long coRemesaUniAdm) {
		this.coRemesaUniAdm = coRemesaUniAdm;
	}
	
	public UnidadAdministrativaDTO getUnidadAdministrativaDTO() {
		return unidadAdministrativaDTO;
	}

	public void setUnidadAdministrativaDTO(
			UnidadAdministrativaDTO unidadAdministrativaDTO) {
		this.unidadAdministrativaDTO = unidadAdministrativaDTO;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public BigDecimal getImNotificado() {
		return imNotificado;
	}

	public void setImNotificado(BigDecimal imNotificado) {
		this.imNotificado = imNotificado;
	}

	public Long getNotificaciones() {
		return notificaciones;
	}

	public void setNotificaciones(Long notificaciones) {
		this.notificaciones = notificaciones;
	}

	public Date getFhActualizacion() {
		return fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	public RemesaDTO getRemesaDTO() {
		return remesaDTO;
	}

	public void setRemesaDTO(RemesaDTO remesaDTO) {
		this.remesaDTO = remesaDTO;
	}

	
}
