package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * RevisionCatastralDTO generated by hbm2java
 */
public class RevisionCatastralDTO implements java.io.Serializable {

	private Long coRevisionCatastral;
	private MunicipioDTO municipioDTO;
	private ConceptoDTO conceptoDTO;
	private Short ejercicioIni;
	private Short ejercicioFin;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<BonificacionArt74DTO> bonificacionArt74DTOs = new HashSet<BonificacionArt74DTO>(
			0);
	private String rowid;

	public RevisionCatastralDTO() {
	}

	public RevisionCatastralDTO(MunicipioDTO municipioDTO,
			ConceptoDTO conceptoDTO) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
	}

	public RevisionCatastralDTO(MunicipioDTO municipioDTO,
			ConceptoDTO conceptoDTO, Short ejercicioIni, Short ejercicioFin,
			Date fhActualizacion, String coUsuarioActualizacion,
			Set<BonificacionArt74DTO> bonificacionArt74DTOs) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.ejercicioIni = ejercicioIni;
		this.ejercicioFin = ejercicioFin;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.bonificacionArt74DTOs = bonificacionArt74DTOs;
	}

	public Long getCoRevisionCatastral() {
		return this.coRevisionCatastral;
	}

	public void setCoRevisionCatastral(Long coRevisionCatastral) {
		this.coRevisionCatastral = coRevisionCatastral;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public ConceptoDTO getConceptoDTO() {
		return this.conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public Short getEjercicioIni() {
		return this.ejercicioIni;
	}

	public void setEjercicioIni(Short ejercicioIni) {
		this.ejercicioIni = ejercicioIni;
	}

	public Short getEjercicioFin() {
		return this.ejercicioFin;
	}

	public void setEjercicioFin(Short ejercicioFin) {
		this.ejercicioFin = ejercicioFin;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<BonificacionArt74DTO> getBonificacionArt74DTOs() {
		return this.bonificacionArt74DTOs;
	}

	public void setBonificacionArt74DTOs(
			Set<BonificacionArt74DTO> bonificacionArt74DTOs) {
		this.bonificacionArt74DTOs = bonificacionArt74DTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
