package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * SigreSubconceptoDTO generated by hbm2java
 */
public class SigreSubconceptoDTO implements java.io.Serializable {

	private Long coSigreSubconcepto;
	private MunicipioDTO municipioDTO;
	private CasillaModeloDTO casillaModeloDTO;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String coTasa;
	private Short nuSubconcepto;
	private String descripcion;
	private boolean boSumando;
	private boolean boApremiable;
	private String rowid;

	public SigreSubconceptoDTO() {
	}

	public SigreSubconceptoDTO(CasillaModeloDTO casillaModeloDTO) {
		this.casillaModeloDTO = casillaModeloDTO;
	}

	public SigreSubconceptoDTO(MunicipioDTO municipioDTO,
			CasillaModeloDTO casillaModeloDTO, Date fhActualizacion,
			String coUsuarioActualizacion, String coTasa, Short nuSubconcepto) {
		this.municipioDTO = municipioDTO;
		this.casillaModeloDTO = casillaModeloDTO;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.coTasa = coTasa;
		this.nuSubconcepto = nuSubconcepto;
	}

	public Long getCoSigreSubconcepto() {
		return this.coSigreSubconcepto;
	}

	public void setCoSigreSubconcepto(Long coSigreSubconcepto) {
		this.coSigreSubconcepto = coSigreSubconcepto;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public CasillaModeloDTO getCasillaModeloDTO() {
		return this.casillaModeloDTO;
	}

	public void setCasillaModeloDTO(CasillaModeloDTO casillaModeloDTO) {
		this.casillaModeloDTO = casillaModeloDTO;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public String getCoTasa() {
		return this.coTasa;
	}

	public void setCoTasa(String coTasa) {
		this.coTasa = coTasa;
	}

	public Short getNuSubconcepto() {
		return this.nuSubconcepto;
	}

	public void setNuSubconcepto(Short nuSubconcepto) {
		this.nuSubconcepto = nuSubconcepto;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isBoSumando() {
		return boSumando;
	}

	public void setBoSumando(boolean boSumando) {
		this.boSumando = boSumando;
	}

	public boolean isBoApremiable() {
		return boApremiable;
	}

	public void setBoApremiable(boolean boApremiable) {
		this.boApremiable = boApremiable;
	}

}
