package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

/**
 * SigrePeriodoDTOId generated by hbm2java
 */
public class SigrePeriodoDTOId implements java.io.Serializable {

	private String coProvincia;
	private String coMunicipio;
	private String sigrePeriodo;

	public SigrePeriodoDTOId() {
	}

	public SigrePeriodoDTOId(String coProvincia, String coMunicipio,
			String sigrePeriodo) {
		this.coProvincia = coProvincia;
		this.coMunicipio = coMunicipio;
		this.sigrePeriodo = sigrePeriodo;
	}

	public String getCoProvincia() {
		return this.coProvincia;
	}

	public void setCoProvincia(String coProvincia) {
		this.coProvincia = coProvincia;
	}

	public String getCoMunicipio() {
		return this.coMunicipio;
	}

	public void setCoMunicipio(String coMunicipio) {
		this.coMunicipio = coMunicipio;
	}

	public String getSigrePeriodo() {
		return this.sigrePeriodo;
	}

	public void setSigrePeriodo(String sigrePeriodo) {
		this.sigrePeriodo = sigrePeriodo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SigrePeriodoDTOId))
			return false;
		SigrePeriodoDTOId castOther = (SigrePeriodoDTOId) other;

		return ((this.getCoProvincia() == castOther.getCoProvincia()) || (this
				.getCoProvincia() != null
				&& castOther.getCoProvincia() != null && this.getCoProvincia()
				.equals(castOther.getCoProvincia())))
				&& ((this.getCoMunicipio() == castOther.getCoMunicipio()) || (this
						.getCoMunicipio() != null
						&& castOther.getCoMunicipio() != null && this
						.getCoMunicipio().equals(castOther.getCoMunicipio())))
				&& (this.getSigrePeriodo() == castOther.getSigrePeriodo());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCoProvincia() == null ? 0 : this.getCoProvincia()
						.hashCode());
		result = 37
				* result
				+ (getCoMunicipio() == null ? 0 : this.getCoMunicipio()
						.hashCode());
		result = 37 * result + this.getSigrePeriodo().hashCode();
		return result;
	}

}
