package es.dipucadiz.etir.comun.dto;

// Generated 15-nov-2010 8:36:49 by Hibernate Tools 3.2.4.GA

/**
 * SituacionCargoDTOId generated by hbm2java
 */
public class SituacionCargoDTOId implements java.io.Serializable {

	private String coSituacionCargo;
	private String tipo;

	public SituacionCargoDTOId() {
	}

	public SituacionCargoDTOId(String coSituacionCargo, String tipo) {
		this.coSituacionCargo = coSituacionCargo;
		this.tipo = tipo;
	}

	public String getCoSituacionCargo() {
		return this.coSituacionCargo;
	}

	public void setCoSituacionCargo(String coSituacionCargo) {
		this.coSituacionCargo = coSituacionCargo;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SituacionCargoDTOId))
			return false;
		SituacionCargoDTOId castOther = (SituacionCargoDTOId) other;

		return ((this.getCoSituacionCargo() == castOther.getCoSituacionCargo()) || (this
				.getCoSituacionCargo() != null
				&& castOther.getCoSituacionCargo() != null && this
				.getCoSituacionCargo().equals(castOther.getCoSituacionCargo())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null
						&& castOther.getTipo() != null && this.getTipo()
						.equals(castOther.getTipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCoSituacionCargo() == null ? 0 : this
						.getCoSituacionCargo().hashCode());
		result = 37 * result
				+ (getTipo() == null ? 0 : this.getTipo().hashCode());
		return result;
	}

}
