package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * SituacionDTO generated by hbm2java
 */
public class SituacionDTO implements java.io.Serializable {

	private String coSituacion;
	private String nombre;
	private String descripcion;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<DocumentoSeguimientoDTO> documentoSeguimientoDTOsForCoSituacionOrigen = new HashSet<DocumentoSeguimientoDTO>(
			0);
	private Set<IncidenciaSituacionDTO> incidenciaSituacionDTOsForCoSituacionOrigen = new HashSet<IncidenciaSituacionDTO>(
			0);
	private Set<IncidenciaSituacionDTO> incidenciaSituacionDTOsForCoSituacionDestino = new HashSet<IncidenciaSituacionDTO>(
			0);
	private Set<DocumentoSeguimientoDTO> documentoSeguimientoDTOsForCoSituacionDestino = new HashSet<DocumentoSeguimientoDTO>(
			0);
	private Set<DocumentoDTO> documentoDTOs = new HashSet<DocumentoDTO>(0);

	private String rowid;

	public SituacionDTO() {
	}

	public SituacionDTO(String coSituacion) {
		this.coSituacion = coSituacion;
	}

	public SituacionDTO(
			String coSituacion,
			String nombre,
			String descripcion,
			Date fhActualizacion,
			String coUsuarioActualizacion,
			Set<DocumentoSeguimientoDTO> documentoSeguimientoDTOsForCoSituacionOrigen,
			Set<IncidenciaSituacionDTO> incidenciaSituacionDTOsForCoSituacionOrigen,
			Set<IncidenciaSituacionDTO> incidenciaSituacionDTOsForCoSituacionDestino,
			Set<DocumentoSeguimientoDTO> documentoSeguimientoDTOsForCoSituacionDestino,
			Set<DocumentoDTO> documentoDTOs) {
		this.coSituacion = coSituacion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.documentoSeguimientoDTOsForCoSituacionOrigen = documentoSeguimientoDTOsForCoSituacionOrigen;
		this.incidenciaSituacionDTOsForCoSituacionOrigen = incidenciaSituacionDTOsForCoSituacionOrigen;
		this.incidenciaSituacionDTOsForCoSituacionDestino = incidenciaSituacionDTOsForCoSituacionDestino;
		this.documentoSeguimientoDTOsForCoSituacionDestino = documentoSeguimientoDTOsForCoSituacionDestino;
		this.documentoDTOs = documentoDTOs;
	}
	
	public String getCodigoDescripcion() {
		return this.coSituacion + " - " + this.nombre;
	}

	public String getCoSituacion() {
		return this.coSituacion;
	}

	public void setCoSituacion(String coSituacion) {
		this.coSituacion = coSituacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<DocumentoSeguimientoDTO> getDocumentoSeguimientoDTOsForCoSituacionOrigen() {
		return this.documentoSeguimientoDTOsForCoSituacionOrigen;
	}

	public void setDocumentoSeguimientoDTOsForCoSituacionOrigen(
			Set<DocumentoSeguimientoDTO> documentoSeguimientoDTOsForCoSituacionOrigen) {
		this.documentoSeguimientoDTOsForCoSituacionOrigen = documentoSeguimientoDTOsForCoSituacionOrigen;
	}

	public Set<IncidenciaSituacionDTO> getIncidenciaSituacionDTOsForCoSituacionOrigen() {
		return this.incidenciaSituacionDTOsForCoSituacionOrigen;
	}

	public void setIncidenciaSituacionDTOsForCoSituacionOrigen(
			Set<IncidenciaSituacionDTO> incidenciaSituacionDTOsForCoSituacionOrigen) {
		this.incidenciaSituacionDTOsForCoSituacionOrigen = incidenciaSituacionDTOsForCoSituacionOrigen;
	}

	public Set<IncidenciaSituacionDTO> getIncidenciaSituacionDTOsForCoSituacionDestino() {
		return this.incidenciaSituacionDTOsForCoSituacionDestino;
	}

	public void setIncidenciaSituacionDTOsForCoSituacionDestino(
			Set<IncidenciaSituacionDTO> incidenciaSituacionDTOsForCoSituacionDestino) {
		this.incidenciaSituacionDTOsForCoSituacionDestino = incidenciaSituacionDTOsForCoSituacionDestino;
	}

	public Set<DocumentoSeguimientoDTO> getDocumentoSeguimientoDTOsForCoSituacionDestino() {
		return this.documentoSeguimientoDTOsForCoSituacionDestino;
	}

	public void setDocumentoSeguimientoDTOsForCoSituacionDestino(
			Set<DocumentoSeguimientoDTO> documentoSeguimientoDTOsForCoSituacionDestino) {
		this.documentoSeguimientoDTOsForCoSituacionDestino = documentoSeguimientoDTOsForCoSituacionDestino;
	}

	public Set<DocumentoDTO> getDocumentoDTOs() {
		return this.documentoDTOs;
	}

	public void setDocumentoDTOs(Set<DocumentoDTO> documentoDTOs) {
		this.documentoDTOs = documentoDTOs;
	}

	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
