package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * TablaGtElementoDTO generated by hbm2java
 */
public class TablaGtElementoDTO implements java.io.Serializable {

	private Long coTablaGtElemento;
	private TablaGtColumnaDTO tablaGtColumnaDTO;
	private int fila;
	private String valor;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public TablaGtElementoDTO() {
	}

	public TablaGtElementoDTO(TablaGtColumnaDTO tablaGtColumnaDTO, int fila) {
		this.tablaGtColumnaDTO = tablaGtColumnaDTO;
		this.fila = fila;
	}

	public TablaGtElementoDTO(TablaGtColumnaDTO tablaGtColumnaDTO, int fila,
			String valor, Date fhActualizacion, String coUsuarioActualizacion) {
		this.tablaGtColumnaDTO = tablaGtColumnaDTO;
		this.fila = fila;
		this.valor = valor;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Long getCoTablaGtElemento() {
		return this.coTablaGtElemento;
	}

	public void setCoTablaGtElemento(Long coTablaGtElemento) {
		this.coTablaGtElemento = coTablaGtElemento;
	}

	public TablaGtColumnaDTO getTablaGtColumnaDTO() {
		return this.tablaGtColumnaDTO;
	}

	public void setTablaGtColumnaDTO(TablaGtColumnaDTO tablaGtColumnaDTO) {
		this.tablaGtColumnaDTO = tablaGtColumnaDTO;
	}

	public int getFila() {
		return this.fila;
	}

	public void setFila(int fila) {
		this.fila = fila;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
