package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * TablaGtUsuarioDTO generated by hbm2java
 */
public class TablaGtUsuarioDTO implements java.io.Serializable {
	private static final long serialVersionUID = 1962723647146053260L;
	
	private Long coTablaGtUsuario;
	private AcmUsuarioDTO acmUsuarioDTO;
	private TablaGtDTO tablaGtDTO;
	private String modoAcceso;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public TablaGtUsuarioDTO() {
	}

	public TablaGtUsuarioDTO(AcmUsuarioDTO acmUsuarioDTO, TablaGtDTO tablaGtDTO) {
		this.acmUsuarioDTO = acmUsuarioDTO;
		this.tablaGtDTO = tablaGtDTO;
	}

	public TablaGtUsuarioDTO(AcmUsuarioDTO acmUsuarioDTO,
			TablaGtDTO tablaGtDTO, Date fhActualizacion,
			String coUsuarioActualizacion) {
		this.acmUsuarioDTO = acmUsuarioDTO;
		this.tablaGtDTO = tablaGtDTO;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Long getCoTablaGtUsuario() {
		return this.coTablaGtUsuario;
	}

	public void setCoTablaGtUsuario(Long coTablaGtUsuario) {
		this.coTablaGtUsuario = coTablaGtUsuario;
	}

	public AcmUsuarioDTO getAcmUsuarioDTO() {
		return this.acmUsuarioDTO;
	}

	public void setAcmUsuarioDTO(AcmUsuarioDTO acmUsuarioDTO) {
		this.acmUsuarioDTO = acmUsuarioDTO;
	}

	public TablaGtDTO getTablaGtDTO() {
		return this.tablaGtDTO;
	}

	public void setTablaGtDTO(TablaGtDTO tablaGtDTO) {
		this.tablaGtDTO = tablaGtDTO;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public String getModoAcceso() {
		return modoAcceso;
	}

	public void setModoAcceso(String modoAcceso) {
		this.modoAcceso = modoAcceso;
	}

}
