package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * TablaGtColumnaDTO generated by hbm2java
 */
public class TablaGtColumnaDTO implements java.io.Serializable {

	private TablaGtColumnaDTOId id;
	private TablaGtDTO tablaGtDTOByCoTablaGt;
	private TablaGtDTO tablaGtDTOByCoTablaValidacion;
	private String nombre;
	private String formato;
	private BigDecimal longitud;
	private Boolean boObligatorio;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Byte posInicioValidacion;
	private Byte numCaracteresValidacion;
	private Set<TablaGtElementoDTO> tablaGtElementoDTOs = new HashSet<TablaGtElementoDTO>(
			0);
	private String rowid;

	public TablaGtColumnaDTO() {
	}

	public TablaGtColumnaDTO(TablaGtColumnaDTOId id,
			TablaGtDTO tablaGtDTOByCoTablaGt, String nombre) {
		this.id = id;
		this.tablaGtDTOByCoTablaGt = tablaGtDTOByCoTablaGt;
		this.nombre = nombre;
	}

	public TablaGtColumnaDTO(TablaGtColumnaDTOId id,
			TablaGtDTO tablaGtDTOByCoTablaGt,
			TablaGtDTO tablaGtDTOByCoTablaValidacion, String nombre,
			String formato, BigDecimal longitud, Boolean boObligatorio,
			Date fhActualizacion, String coUsuarioActualizacion,
			Byte posInicioValidacion, Byte numCaracteresValidacion,
			Set<TablaGtElementoDTO> tablaGtElementoDTOs) {
		this.id = id;
		this.tablaGtDTOByCoTablaGt = tablaGtDTOByCoTablaGt;
		this.tablaGtDTOByCoTablaValidacion = tablaGtDTOByCoTablaValidacion;
		this.nombre = nombre;
		this.formato = formato;
		this.longitud = longitud;
		this.boObligatorio = boObligatorio;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.posInicioValidacion = posInicioValidacion;
		this.numCaracteresValidacion = numCaracteresValidacion;
		this.tablaGtElementoDTOs = tablaGtElementoDTOs;
	}

	public TablaGtColumnaDTOId getId() {
		return this.id;
	}

	public void setId(TablaGtColumnaDTOId id) {
		this.id = id;
	}

	public TablaGtDTO getTablaGtDTOByCoTablaGt() {
		return this.tablaGtDTOByCoTablaGt;
	}

	public void setTablaGtDTOByCoTablaGt(TablaGtDTO tablaGtDTOByCoTablaGt) {
		this.tablaGtDTOByCoTablaGt = tablaGtDTOByCoTablaGt;
	}

	public TablaGtDTO getTablaGtDTOByCoTablaValidacion() {
		return this.tablaGtDTOByCoTablaValidacion;
	}

	public void setTablaGtDTOByCoTablaValidacion(
			TablaGtDTO tablaGtDTOByCoTablaValidacion) {
		this.tablaGtDTOByCoTablaValidacion = tablaGtDTOByCoTablaValidacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getFormato() {
		return this.formato;
	}

	public void setFormato(String formato) {
		this.formato = formato;
	}

	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	public Boolean getBoObligatorio() {
		return this.boObligatorio;
	}

	public void setBoObligatorio(Boolean boObligatorio) {
		this.boObligatorio = boObligatorio;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Byte getPosInicioValidacion() {
		return this.posInicioValidacion;
	}

	public void setPosInicioValidacion(Byte posInicioValidacion) {
		this.posInicioValidacion = posInicioValidacion;
	}

	public Byte getNumCaracteresValidacion() {
		return this.numCaracteresValidacion;
	}

	public void setNumCaracteresValidacion(Byte numCaracteresValidacion) {
		this.numCaracteresValidacion = numCaracteresValidacion;
	}

	public Set<TablaGtElementoDTO> getTablaGtElementoDTOs() {
		return this.tablaGtElementoDTOs;
	}

	public void setTablaGtElementoDTOs(
			Set<TablaGtElementoDTO> tablaGtElementoDTOs) {
		this.tablaGtElementoDTOs = tablaGtElementoDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
