package es.dipucadiz.etir.comun.dto;
// Generated 07-abr-2010 9:08:07 by Hibernate Tools 3.2.4.GA


import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * TramiteTransicionDTO generated by hbm2java
 */
public class TramiteTransicionDTO  implements java.io.Serializable, Comparable<TramiteTransicionDTO> {


     private TramiteTransicionDTOId id;
     private TramiteDTO tramiteDTOByCoTramiteDestino;
     private TramiteDTO tramiteDTOByCoTramiteOrigen;
     private Date fhActualizacion;
     private String coUsuarioActualizacion;
     private Short orden;
     private String rowid;

    public TramiteTransicionDTO() {
    }

    public TramiteTransicionDTO(TramiteTransicionDTOId id) {
        this.id = id;
    }
    
    public TramiteTransicionDTO(TramiteTransicionDTOId id, TramiteDTO tramiteDTOByCoTramiteDestino, TramiteDTO tramiteDTOByCoTramiteOrigen) {
        this.id = id;
        this.tramiteDTOByCoTramiteDestino = tramiteDTOByCoTramiteDestino;
        this.tramiteDTOByCoTramiteOrigen = tramiteDTOByCoTramiteOrigen;
    }
    public TramiteTransicionDTO(TramiteTransicionDTOId id, TramiteDTO tramiteDTOByCoTramiteDestino, TramiteDTO tramiteDTOByCoTramiteOrigen, Date fhActualizacion, String coUsuarioActualizacion, Short orden) {
       this.id = id;
       this.tramiteDTOByCoTramiteDestino = tramiteDTOByCoTramiteDestino;
       this.tramiteDTOByCoTramiteOrigen = tramiteDTOByCoTramiteOrigen;
       this.fhActualizacion = fhActualizacion;
       this.coUsuarioActualizacion = coUsuarioActualizacion;
       this.orden = orden;
    }
   
    public TramiteTransicionDTOId getId() {
        return this.id;
    }
    
    public void setId(TramiteTransicionDTOId id) {
        this.id = id;
    }
    public TramiteDTO getTramiteDTOByCoTramiteDestino() {
        return this.tramiteDTOByCoTramiteDestino;
    }
    
    public void setTramiteDTOByCoTramiteDestino(TramiteDTO tramiteDTOByCoTramiteDestino) {
        this.tramiteDTOByCoTramiteDestino = tramiteDTOByCoTramiteDestino;
    }
    public TramiteDTO getTramiteDTOByCoTramiteOrigen() {
        return this.tramiteDTOByCoTramiteOrigen;
    }
    
    public void setTramiteDTOByCoTramiteOrigen(TramiteDTO tramiteDTOByCoTramiteOrigen) {
        this.tramiteDTOByCoTramiteOrigen = tramiteDTOByCoTramiteOrigen;
    }
    public Date getFhActualizacion() {
        return this.fhActualizacion;
    }
    
    public void setFhActualizacion(Date fhActualizacion) {
        this.fhActualizacion = fhActualizacion;
    }
    public String getCoUsuarioActualizacion() {
        return this.coUsuarioActualizacion;
    }
    
    public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
        this.coUsuarioActualizacion = coUsuarioActualizacion;
    }
    
    public Short getOrden() {
        return this.orden;
    }
    
    public void setOrden(Short orden) {
        this.orden = orden;
    }
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}


	public int compareTo(TramiteTransicionDTO tramiteTransicionDTO) {
		int resultado;
		if (tramiteTransicionDTO.getOrden() > this.getOrden()) {
			resultado = 1;
		} else {
			resultado = 0;
		}
		return resultado;
	}




}


