package es.dipucadiz.etir.comun.dto;
// Generated 07-abr-2010 9:08:07 by Hibernate Tools 3.2.4.GA



/**
 * TramitePlantillaDTOId generated by hbm2java
 */
public class TramitePlantillaDTOId  implements java.io.Serializable {


     private long coTramite;
     private long coPlantilla;

    public TramitePlantillaDTOId() {
    }

    public TramitePlantillaDTOId(long coTramite, long coPlantilla) {
       this.coTramite = coTramite;
       this.coPlantilla = coPlantilla;
    }
   
    public long getCoTramite() {
        return this.coTramite;
    }
    
    public void setCoTramite(long coTramite) {
        this.coTramite = coTramite;
    }
    public long getCoPlantilla() {
        return this.coPlantilla;
    }
    
    public void setCoPlantilla(long coPlantilla) {
        this.coPlantilla = coPlantilla;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TramitePlantillaDTOId) ) return false;
		 TramitePlantillaDTOId castOther = ( TramitePlantillaDTOId ) other; 
         
		 return (this.getCoTramite()==castOther.getCoTramite())
		     && (this.getCoPlantilla()==castOther.getCoPlantilla());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCoTramite();
         result = 37 * result + (int) this.getCoPlantilla();
         return result;
   }   


}


