package es.dipucadiz.etir.comun.dto;
// Generated 07-abr-2010 9:08:07 by Hibernate Tools 3.2.4.GA


import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * TramiteCircDependienteDTO generated by hbm2java
 */
public class TramiteCircDependienteDTO  implements java.io.Serializable {


     private TramiteCircDependienteDTOId id;
     private TramiteDTO tramiteDTO;
     private TramiteCircDerivadoDTO tramiteCircDerivadoDTO;
     private Date fhActualizacion;
     private String coUsuarioActualizacion;
     private String rowid;

    public TramiteCircDependienteDTO() {
    }

	
    public TramiteCircDependienteDTO(TramiteCircDependienteDTOId id, TramiteDTO tramiteDTO, TramiteCircDerivadoDTO tramiteCircDerivadoDTO) {
        this.id = id;
        this.tramiteDTO = tramiteDTO;
        this.tramiteCircDerivadoDTO = tramiteCircDerivadoDTO;
    }
    public TramiteCircDependienteDTO(TramiteCircDependienteDTOId id, TramiteDTO tramiteDTO, TramiteCircDerivadoDTO tramiteCircDerivadoDTO, Date fhActualizacion, String coUsuarioActualizacion) {
       this.id = id;
       this.tramiteDTO = tramiteDTO;
       this.tramiteCircDerivadoDTO = tramiteCircDerivadoDTO;
       this.fhActualizacion = fhActualizacion;
       this.coUsuarioActualizacion = coUsuarioActualizacion;
    }
   
    public TramiteCircDependienteDTOId getId() {
        return this.id;
    }
    
    public void setId(TramiteCircDependienteDTOId id) {
        this.id = id;
    }
    public TramiteDTO getTramiteDTO() {
        return this.tramiteDTO;
    }
    
    public void setTramiteDTO(TramiteDTO tramiteDTO) {
        this.tramiteDTO = tramiteDTO;
    }
    public TramiteCircDerivadoDTO getTramiteCircDerivadoDTO() {
        return this.tramiteCircDerivadoDTO;
    }
    
    public void setTramiteCircDerivadoDTO(TramiteCircDerivadoDTO tramiteCircDerivadoDTO) {
        this.tramiteCircDerivadoDTO = tramiteCircDerivadoDTO;
    }
    public Date getFhActualizacion() {
        return this.fhActualizacion;
    }
    
    public void setFhActualizacion(Date fhActualizacion) {
        this.fhActualizacion = fhActualizacion;
    }
    public String getCoUsuarioActualizacion() {
        return this.coUsuarioActualizacion;
    }
    
    public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
        this.coUsuarioActualizacion = coUsuarioActualizacion;
    }
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}




}


