package es.dipucadiz.etir.comun.dto;
// Generated 07-abr-2010 9:08:07 by Hibernate Tools 3.2.4.GA



/**
 * TramiteCondicionDTOId generated by hbm2java
 */
public class TramiteCondicionDTOId  implements java.io.Serializable {


     private long coTramite;
     private short orden;

    public TramiteCondicionDTOId() {
    }

    public TramiteCondicionDTOId(long coTramite, short orden) {
       this.coTramite = coTramite;
       this.orden = orden;
    }
   
    public long getCoTramite() {
        return this.coTramite;
    }
    
    public void setCoTramite(long coTramite) {
        this.coTramite = coTramite;
    }
    public short getOrden() {
        return this.orden;
    }
    
    public void setOrden(short orden) {
        this.orden = orden;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TramiteCondicionDTOId) ) return false;
		 TramiteCondicionDTOId castOther = ( TramiteCondicionDTOId ) other; 
         
		 return (this.getCoTramite()==castOther.getCoTramite())
 && (this.getOrden()==castOther.getOrden());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCoTramite();
         result = 37 * result + this.getOrden();
         return result;
   }   


}


