package es.dipucadiz.etir.comun.dto;
// Generated 07-abr-2010 9:08:07 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;
import es.dipucadiz.etir.sb06.utilidades.TramitadorConstants;

/**
 * TramiteDTO generated by hbm2java
 */
public class TramiteDTO implements java.io.Serializable {

	private static final long serialVersionUID = 7068187438881902056L;

	private Long coTramite;
	private IncidenciaSituacionDTO incidenciaSituacionDTO;
	private ProcesoDTO procesoDTO;
	private CircuitoRutaDTO circuitoRutaDTO;
	private String etiqueta;
	private String pregunta;
	private String nombre;
	private String tipoTramite;
	private String tipo;
	private String tipoEjecucion;
	private String tipoCaptura;
	private Boolean boSello;
	private Boolean boObservaciones;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Boolean boActuacionUsuario;
	private Boolean boDocumentoIndividual;
	private Boolean boAsociarDocumento;
	private Boolean boAdjuntarDocumentacion;
	private Set<TramiteTransicionDTO> tramiteTransicionDTOsForCoTramiteDestino = new HashSet<TramiteTransicionDTO>(0);
	private Set<TramiteTransicionDTO> tramiteTransicionDTOsForCoTramiteOrigen = new HashSet<TramiteTransicionDTO>(0);
	private Set<TramitePlantillaDTO> tramitePlantillaDTOs = new HashSet<TramitePlantillaDTO>(0);
	private Set<TramiteCircDependienteDTO> tramiteCircDependienteDTOs = new HashSet<TramiteCircDependienteDTO>(0);
	private Set<TramiteCircDerivadoDTO> tramiteCircDerivadoDTOs = new HashSet<TramiteCircDerivadoDTO>(0);
	private Set<ExpedienteDTO> expedienteDTOs = new HashSet<ExpedienteDTO>(0);
	private Set<TramiteUnidadAdminDTO> tramiteUnidadAdminDTOs = new HashSet<TramiteUnidadAdminDTO>(0);
	private Set<TramiteCondicionDTO> tramiteCondicionDTOs = new HashSet<TramiteCondicionDTO>(0);
	private String rowid;
	private Short dias;
	private Short hora;
	private TramiteDTO tramiteRemitenteDTO;
	private String tipoRemitente;
	private ProcesoDTO procesoInterrupcionDTO;

	public TramiteDTO() {}

	public TramiteDTO(	IncidenciaSituacionDTO incidenciaSituacionDTO, ProcesoDTO procesoDTO, CircuitoRutaDTO circuitoRutaDTO, String etiqueta, String nombre, String tipoTramite, String tipo,
						String tipoEjecucion, String tipoCaptura, Boolean boSello, Boolean boObservaciones, Date fhActualizacion, String coUsuarioActualizacion, Boolean boActuacionUsuario,
						Boolean boDocumentoIndividual, Set<TramiteTransicionDTO> tramiteTransicionDTOsForCoTramiteDestino, Set<TramiteTransicionDTO> tramiteTransicionDTOsForCoTramiteOrigen,
						Set<TramitePlantillaDTO> tramitePlantillaDTOs, Set<TramiteCircDependienteDTO> tramiteCircDependienteDTOs, Set<TramiteCircDerivadoDTO> tramiteCircDerivadoDTOs,
						Set<ExpedienteDTO> expedienteDTOs, Set<TramiteUnidadAdminDTO> tramiteUnidadAdminDTOs, Set<TramiteCondicionDTO> tramiteCondicionDTOs) {
		this.incidenciaSituacionDTO = incidenciaSituacionDTO;
		this.procesoDTO = procesoDTO;
		this.circuitoRutaDTO = circuitoRutaDTO;
		this.etiqueta = etiqueta;
		this.nombre = nombre;
		this.tipoTramite = tipoTramite;
		this.tipo = tipo;
		this.tipoEjecucion = tipoEjecucion;
		this.tipoCaptura = tipoCaptura;
		this.boSello = boSello;
		this.boObservaciones = boObservaciones;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.boActuacionUsuario = boActuacionUsuario;
		this.boDocumentoIndividual = boDocumentoIndividual;
		this.tramiteTransicionDTOsForCoTramiteDestino = tramiteTransicionDTOsForCoTramiteDestino;
		this.tramiteTransicionDTOsForCoTramiteOrigen = tramiteTransicionDTOsForCoTramiteOrigen;
		this.tramitePlantillaDTOs = tramitePlantillaDTOs;
		this.tramiteCircDependienteDTOs = tramiteCircDependienteDTOs;
		this.tramiteCircDerivadoDTOs = tramiteCircDerivadoDTOs;
		this.expedienteDTOs = expedienteDTOs;
		this.tramiteUnidadAdminDTOs = tramiteUnidadAdminDTOs;
		this.tramiteCondicionDTOs = tramiteCondicionDTOs;
	}

	public String getCodigoDescripcion() {
		if (!Utilidades.isEmpty(this.nombre)) return this.etiqueta + " - " + this.nombre;
		return this.etiqueta;
	}

	public String getCodigoDescripcionEspecial() {
		if (TramitadorConstants.TRAMITE_TIPO_PREGUNTA.equals(tipoTramite) && Utilidades.isNotEmpty(this.pregunta)) {
			return this.etiqueta + " - " + this.pregunta;
		} else {
			return getCodigoDescripcion();
		}
	}

	public Long getCoTramite() {
		return this.coTramite;
	}

	public void setCoTramite(Long coTramite) {
		this.coTramite = coTramite;
	}

	public IncidenciaSituacionDTO getIncidenciaSituacionDTO() {
		return this.incidenciaSituacionDTO;
	}

	public void setIncidenciaSituacionDTO(IncidenciaSituacionDTO incidenciaSituacionDTO) {
		this.incidenciaSituacionDTO = incidenciaSituacionDTO;
	}

	public ProcesoDTO getProcesoDTO() {
		return this.procesoDTO;
	}

	public void setProcesoDTO(ProcesoDTO procesoDTO) {
		this.procesoDTO = procesoDTO;
	}

	public CircuitoRutaDTO getCircuitoRutaDTO() {
		return this.circuitoRutaDTO;
	}

	public void setCircuitoRutaDTO(CircuitoRutaDTO circuitoRutaDTO) {
		this.circuitoRutaDTO = circuitoRutaDTO;
	}

	public String getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(String etiqueta) {
		this.etiqueta = etiqueta;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipoTramite() {
		return this.tipoTramite;
	}

	public void setTipoTramite(String tipoTramite) {
		this.tipoTramite = tipoTramite;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getTipoEjecucion() {
		return this.tipoEjecucion;
	}

	public void setTipoEjecucion(String tipoEjecucion) {
		this.tipoEjecucion = tipoEjecucion;
	}

	public String getTipoCaptura() {
		return this.tipoCaptura;
	}

	public void setTipoCaptura(String tipoCaptura) {
		this.tipoCaptura = tipoCaptura;
	}

	public Boolean getBoSello() {
		return this.boSello;
	}

	public void setBoSello(Boolean boSello) {
		this.boSello = boSello;
	}

	public Boolean getBoObservaciones() {
		return this.boObservaciones;
	}

	public void setBoObservaciones(Boolean boObservaciones) {
		this.boObservaciones = boObservaciones;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Boolean getBoActuacionUsuario() {
		return this.boActuacionUsuario;
	}

	public void setBoActuacionUsuario(Boolean boActuacionUsuario) {
		this.boActuacionUsuario = boActuacionUsuario;
	}

	//    public Boolean getBoCaptura() {
	//        return this.boCaptura;
	//    }
	//    
	//    public void setBoCaptura(Boolean boCaptura) {
	//        this.boCaptura = boCaptura;
	//    }
	public void setPregunta(String pregunta) {
		this.pregunta = pregunta;
	}

	public String getPregunta() {
		return pregunta;
	}

	public Boolean getBoDocumentoIndividual() {
		return this.boDocumentoIndividual;
	}

	public void setBoDocumentoIndividual(Boolean boDocumentoIndividual) {
		this.boDocumentoIndividual = boDocumentoIndividual;
	}

	public Set<TramiteTransicionDTO> getTramiteTransicionDTOsForCoTramiteDestino() {
		return this.tramiteTransicionDTOsForCoTramiteDestino;
	}

	public void setTramiteTransicionDTOsForCoTramiteDestino(Set<TramiteTransicionDTO> tramiteTransicionDTOsForCoTramiteDestino) {
		this.tramiteTransicionDTOsForCoTramiteDestino = tramiteTransicionDTOsForCoTramiteDestino;
	}

	public Set<TramiteTransicionDTO> getTramiteTransicionDTOsForCoTramiteOrigen() {
		return this.tramiteTransicionDTOsForCoTramiteOrigen;
	}

	public void setTramiteTransicionDTOsForCoTramiteOrigen(Set<TramiteTransicionDTO> tramiteTransicionDTOsForCoTramiteOrigen) {
		this.tramiteTransicionDTOsForCoTramiteOrigen = tramiteTransicionDTOsForCoTramiteOrigen;
	}

	public Set<TramitePlantillaDTO> getTramitePlantillaDTOs() {
		return this.tramitePlantillaDTOs;
	}

	public void setTramitePlantillaDTOs(Set<TramitePlantillaDTO> tramitePlantillaDTOs) {
		this.tramitePlantillaDTOs = tramitePlantillaDTOs;
	}

	public Set<TramiteCircDependienteDTO> getTramiteCircDependienteDTOs() {
		return this.tramiteCircDependienteDTOs;
	}

	public void setTramiteCircDependienteDTOs(Set<TramiteCircDependienteDTO> tramiteCircDependienteDTOs) {
		this.tramiteCircDependienteDTOs = tramiteCircDependienteDTOs;
	}

	public Set<TramiteCircDerivadoDTO> getTramiteCircDerivadoDTOs() {
		return this.tramiteCircDerivadoDTOs;
	}

	public void setTramiteCircDerivadoDTOs(Set<TramiteCircDerivadoDTO> tramiteCircDerivadoDTOs) {
		this.tramiteCircDerivadoDTOs = tramiteCircDerivadoDTOs;
	}

	public Set<ExpedienteDTO> getExpedienteDTOs() {
		return this.expedienteDTOs;
	}

	public void setExpedienteDTOs(Set<ExpedienteDTO> expedienteDTOs) {
		this.expedienteDTOs = expedienteDTOs;
	}

	public Set<TramiteUnidadAdminDTO> getTramiteUnidadAdminDTOs() {
		return this.tramiteUnidadAdminDTOs;
	}

	public void setTramiteUnidadAdminDTOs(Set<TramiteUnidadAdminDTO> tramiteUnidadAdminDTOs) {
		this.tramiteUnidadAdminDTOs = tramiteUnidadAdminDTOs;
	}

	public Set<TramiteCondicionDTO> getTramiteCondicionDTOs() {
		return this.tramiteCondicionDTOs;
	}

	public void setTramiteCondicionDTOs(Set<TramiteCondicionDTO> tramiteCondicionDTOs) {
		this.tramiteCondicionDTOs = tramiteCondicionDTOs;
	}

	public String getRowid() {
		return rowid;
	}

	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

	public Boolean getBoAsociarDocumento() {
		return boAsociarDocumento;
	}

	public void setBoAsociarDocumento(Boolean boAsociarDocumento) {
		this.boAsociarDocumento = boAsociarDocumento;
	}

	public Boolean getBoAdjuntarDocumentacion() {
		return boAdjuntarDocumentacion;
	}

	public void setBoAdjuntarDocumentacion(Boolean boAdjuntarDocumentacion) {
		this.boAdjuntarDocumentacion = boAdjuntarDocumentacion;
	}

	public Short getDias() {
		return dias;
	}

	public void setDias(Short dias) {
		this.dias = dias;
	}

	public Short getHora() {
		return hora;
	}

	public void setHora(Short hora) {
		this.hora = hora;
	}

	public TramiteDTO getTramiteRemitenteDTO() {
		return tramiteRemitenteDTO;
	}

	public void setTramiteRemitenteDTO(TramiteDTO tramiteRemitenteDTO) {
		this.tramiteRemitenteDTO = tramiteRemitenteDTO;
	}

	public String getTipoRemitente() {
		return tipoRemitente;
	}

	public void setTipoRemitente(String tipoRemitente) {
		this.tipoRemitente = tipoRemitente;
	}

	public ProcesoDTO getProcesoInterrupcionDTO() {
		return procesoInterrupcionDTO;
	}

	public void setProcesoInterrupcionDTO(ProcesoDTO procesoInterrupcionDTO) {
		this.procesoInterrupcionDTO = procesoInterrupcionDTO;
	}

}
