package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ValidacionArgumentoDTO generated by hbm2java
 */
public class ValidacionArgumentoDTO implements java.io.Serializable {

	private ValidacionArgumentoDTOId id;
	private FuncionArgumentoDTO funcionArgumentoDTO;
	private ValidacionDTO validacionDTO;
	private String tipo;
	private String valor;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private String rowid;

	public ValidacionArgumentoDTO() {
	}

	public ValidacionArgumentoDTO(ValidacionArgumentoDTOId id,
			FuncionArgumentoDTO funcionArgumentoDTO, ValidacionDTO validacionDTO) {
		this.id = id;
		this.funcionArgumentoDTO = funcionArgumentoDTO;
		this.validacionDTO = validacionDTO;
	}

	public ValidacionArgumentoDTO(ValidacionArgumentoDTOId id,
			FuncionArgumentoDTO funcionArgumentoDTO,
			ValidacionDTO validacionDTO, String tipo, String valor,
			Date fhActualizacion, String coUsuarioActualizacion) {
		this.id = id;
		this.funcionArgumentoDTO = funcionArgumentoDTO;
		this.validacionDTO = validacionDTO;
		this.tipo = tipo;
		this.valor = valor;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public ValidacionArgumentoDTOId getId() {
		return this.id;
	}

	public void setId(ValidacionArgumentoDTOId id) {
		this.id = id;
	}

	public FuncionArgumentoDTO getFuncionArgumentoDTO() {
		return this.funcionArgumentoDTO;
	}

	public void setFuncionArgumentoDTO(FuncionArgumentoDTO funcionArgumentoDTO) {
		this.funcionArgumentoDTO = funcionArgumentoDTO;
	}

	public ValidacionDTO getValidacionDTO() {
		return this.validacionDTO;
	}

	public void setValidacionDTO(ValidacionDTO validacionDTO) {
		this.validacionDTO = validacionDTO;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
