package es.dipucadiz.etir.comun.dto;

// Generated 02-feb-2010 13:28:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import es.dipucadiz.etir.comun.utilidades.Utilidades;

/**
 * ValidacionDTO generated by hbm2java
 */
public class ValidacionDTO implements java.io.Serializable {

	private Long coValidacion;
	private MunicipioDTO municipioDTO;
	private MensajeErrorDTO mensajeErrorDTO;
	private ConceptoDTO conceptoDTO;
	private FuncionDTO funcionDTO;
	private CasillaModeloDTO casillaModeloDTO;
	private short orden;
	private String nombre;
	private String descripcion;
	private String tipo;
	private Boolean boActiva;
	private Date fhActualizacion;
	private String coUsuarioActualizacion;
	private Set<ValidacionArgumentoDTO> validacionArgumentoDTOs = new HashSet<ValidacionArgumentoDTO>(
			0);
	private String rowid;

	public ValidacionDTO() {
	}

	public ValidacionDTO(MunicipioDTO municipioDTO, ConceptoDTO conceptoDTO,
			FuncionDTO funcionDTO, CasillaModeloDTO casillaModeloDTO,
			short orden) {
		this.municipioDTO = municipioDTO;
		this.conceptoDTO = conceptoDTO;
		this.funcionDTO = funcionDTO;
		this.casillaModeloDTO = casillaModeloDTO;
		this.orden = orden;
	}

	public ValidacionDTO(MunicipioDTO municipioDTO,
			MensajeErrorDTO mensajeErrorDTO, ConceptoDTO conceptoDTO,
			FuncionDTO funcionDTO, CasillaModeloDTO casillaModeloDTO,
			short orden, String nombre, String descripcion, String tipo,
			Boolean boActiva, Date fhActualizacion,
			String coUsuarioActualizacion,
			Set<ValidacionArgumentoDTO> validacionArgumentoDTOs) {
		this.municipioDTO = municipioDTO;
		this.mensajeErrorDTO = mensajeErrorDTO;
		this.conceptoDTO = conceptoDTO;
		this.funcionDTO = funcionDTO;
		this.casillaModeloDTO = casillaModeloDTO;
		this.orden = orden;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.boActiva = boActiva;
		this.fhActualizacion = fhActualizacion;
		this.coUsuarioActualizacion = coUsuarioActualizacion;
		this.validacionArgumentoDTOs = validacionArgumentoDTOs;
	}

	public Long getCoValidacion() {
		return this.coValidacion;
	}

	public void setCoValidacion(Long coValidacion) {
		this.coValidacion = coValidacion;
	}

	public MunicipioDTO getMunicipioDTO() {
		return this.municipioDTO;
	}

	public void setMunicipioDTO(MunicipioDTO municipioDTO) {
		this.municipioDTO = municipioDTO;
	}

	public MensajeErrorDTO getMensajeErrorDTO() {
		return this.mensajeErrorDTO;
	}

	public void setMensajeErrorDTO(MensajeErrorDTO mensajeErrorDTO) {
		this.mensajeErrorDTO = mensajeErrorDTO;
	}

	public ConceptoDTO getConceptoDTO() {
		return this.conceptoDTO;
	}

	public void setConceptoDTO(ConceptoDTO conceptoDTO) {
		this.conceptoDTO = conceptoDTO;
	}

	public FuncionDTO getFuncionDTO() {
		return this.funcionDTO;
	}

	public void setFuncionDTO(FuncionDTO funcionDTO) {
		this.funcionDTO = funcionDTO;
	}

	public CasillaModeloDTO getCasillaModeloDTO() {
		return this.casillaModeloDTO;
	}

	public void setCasillaModeloDTO(CasillaModeloDTO casillaModeloDTO) {
		this.casillaModeloDTO = casillaModeloDTO;
	}

	public short getOrden() {
		return this.orden;
	}

	public void setOrden(short orden) {
		this.orden = orden;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Boolean getBoActiva() {
		return this.boActiva;
	}

	public void setBoActiva(Boolean boActiva) {
		this.boActiva = boActiva;
	}

	public Date getFhActualizacion() {
		return this.fhActualizacion;
	}

	public void setFhActualizacion(Date fhActualizacion) {
		this.fhActualizacion = fhActualizacion;
	}

	public String getCoUsuarioActualizacion() {
		return this.coUsuarioActualizacion;
	}

	public void setCoUsuarioActualizacion(String coUsuarioActualizacion) {
		this.coUsuarioActualizacion = coUsuarioActualizacion;
	}

	public Set<ValidacionArgumentoDTO> getValidacionArgumentoDTOs() {
		return this.validacionArgumentoDTOs;
	}

	public void setValidacionArgumentoDTOs(
			Set<ValidacionArgumentoDTO> validacionArgumentoDTOs) {
		this.validacionArgumentoDTOs = validacionArgumentoDTOs;
	}
	
	public String getRowid() {
		return rowid;
	}
	
	public void setRowid(String rowid) {
		this.rowid = Utilidades.codificarRowidFormatoSeguro(rowid);
	}

}
